;; Cymbal calibration basis / reduced dispersive plate, identified from Donit's cymbal recordings.
;; Six frequency regions, each with three paths and an orthogonal junction.
;; Eight resolved resonances carry the bell/foot modes; dense plate modes live
;; in the delay network. No PCM, recorded phase or sampled envelope is used.
;; Rebuild and validation: tools/pm-cymbals/README.md.
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))
(param character @group voicing @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)
(param size @group body @default 1 @min 0.5 @max 2 @mod true @mod-mode additive)
(param decay @group body @default 1 @min 0.2 @max 3 @mod true @mod-mode additive)
(param damping @group body @default 1 @min 0.25 @max 3 @mod true @mod-mode additive)
(param hardness @group stick @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)
(param bell @group body @default 1 @min 0 @max 2 @mod true @mod-mode additive)
(param wash @group body @default 1 @min 0 @max 2 @mod true @mod-mode additive)
(param touch @group contact @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param color @group output @default 0 @min -1 @max 1 @mod true @mod-mode additive)
(param width @group output @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param gain @group output @default 1 @min 0 @max 2 @mod true @mod-mode additive)
(param tracking @group tuning @default 0 @min 0 @max 1)
(param r0 @group fit @default 3 @min 0.03 @max 120)
(param r1 @group fit @default 3 @min 0.03 @max 120)
(param r2 @group fit @default 3 @min 0.03 @max 120)
(param r3 @group fit @default 3 @min 0.03 @max 120)
(param r4 @group fit @default 3 @min 0.03 @max 120)
(param r5 @group fit @default 3 @min 0.03 @max 120)
(param contact_s @group fit @default 0.002 @min 0.0001 @max 0.025)
(param direct @group fit @default 0.3 @min 0 @max 1)
(param hz0 @group fit @default 300 @min 50 @max 20000)
(param rate0 @group fit @default 3 @min 0.03 @max 120)
(param hz1 @group fit @default 600 @min 50 @max 20000)
(param rate1 @group fit @default 3 @min 0.03 @max 120)
(param hz2 @group fit @default 900 @min 50 @max 20000)
(param rate2 @group fit @default 3 @min 0.03 @max 120)
(param hz3 @group fit @default 1200 @min 50 @max 20000)
(param rate3 @group fit @default 3 @min 0.03 @max 120)
(param hz4 @group fit @default 1500 @min 50 @max 20000)
(param rate4 @group fit @default 3 @min 0.03 @max 120)
(param hz5 @group fit @default 1800 @min 50 @max 20000)
(param rate5 @group fit @default 3 @min 0.03 @max 120)
(param hz6 @group fit @default 2100 @min 50 @max 20000)
(param rate6 @group fit @default 3 @min 0.03 @max 120)
(param hz7 @group fit @default 2400 @min 50 @max 20000)
(param rate7 @group fit @default 3 @min 0.03 @max 120)
(param openness @group contact @default 0 @min 0 @max 1 @mod true @mod-mode additive)


(defmacro cymbal-smooth (target ms)
  (make-history previous)
  (make-history ready)
  (def pole (exp (/ -1 (* 0.001 ms samplerate))))
  (def value (gswitch (read-history ready) (mix target (read-history previous) pole) target))
  (write-history previous value)
  (write-history ready 1)
  value)
(defmacro cymbal-pole (input pole)
  (make-history previous)
  (def value (mix input (read-history previous) pole))
  (write-history previous value)
  value)
(make-history last_gate)
(def held (gt gate 0.5))
(def onset (max (gt trigger 0.5) (* held (lte (read-history last_gate) 0.5))))
(write-history last_gate held)
(def tick (max onset (eq (accum 1 0 0 16) 0)))
(def strength (latch (clip velocity 0 1) onset))
(def scale (latch (cymbal-smooth (/ (clip (mod size) 0.5 2)
  (pow (/ (clip pitch 65.406391 1046.50226) 261.625565) (clip tracking 0 1))) 12) tick))
(def decay_v (latch (cymbal-smooth (clip (mod decay) 0.2 3) 8) tick))
(def damping_v (latch (cymbal-smooth (clip (mod damping) 0.25 3) 8) tick))
(def touch_v (cymbal-smooth (clip (mod touch) 0 1) 2))
(def base_rate0 r0)
(def base_rate1 r1)
(def base_rate2 r2)
(def base_rate3 r3)
(def base_rate4 r4)
(def base_rate5 r5)
(def base_contact_s contact_s)
(def base_direct direct)
(def openness_v (latch (cymbal-smooth (clip (mod openness) 0 1) 2) tick))

;; Openness is a live loss condition, not an output envelope. Closed-hat
;; coefficients include contact losses; touch adds a choke to every wave path
;; and resolved resonance. Gate-off deliberately leaves percussion ringing.
(def contact_loss (* 180 touch_v touch_v))

;; Finite stick contact: resolved modes receive the compression impulse;
;; unresolved modes receive the compact, stochastic rough-contact force.
;; Randomness exists only while the stick contacts the metal; all subsequent
;; sound is the free response of the passive body.
(def hardness_v (latch (clip (mod hardness) 0 1) tick))
(def contact_s (latch (* base_contact_s (pow 2 (* 2 (- 0.5 hardness_v)))) tick))
(def age (accum (/ 1 samplerate) onset 0 100000))
(def pulse_phase (clip (/ age contact_s) 0 1))
(def friction (* (noise) (sin (* pi pulse_phase)) (lt age contact_s)))
(def force_pole (exp (/ -1 (* samplerate 0.000025 (pow 2 (* 3 (- 0.5 hardness_v)))))))
(def force (cymbal-pole (cymbal-pole
  (* strength friction 0.23) force_pole) force_pole))
(def point_force (cymbal-pole (cymbal-pole (* onset strength) force_pole) force_pole))
(def region_rate0 (+ (/ (* base_rate0 (pow damping_v 0)) decay_v) contact_loss))
;; Region 0, path 0: lossless fractional propagation.
(make-history outgoing0)
(def path_samples0 (max 8 (* 109 scale (/ samplerate 48000))))
(def integer_delay0 (- (floor path_samples0) 2))
(def fractional0 (+ 1 (- path_samples0 (floor path_samples0))))
(def allpass_a0 (/ (- 1 fractional0) (+ 1 fractional0)))
(def incoming0 (delay (read-history outgoing0) integer_delay0))
(make-history ap_x0)
(make-history ap_y0)
(def arrival0 (- (+ (* allpass_a0 incoming0) (read-history ap_x0)) (* allpass_a0 (read-history ap_y0))))
(write-history ap_x0 incoming0)
(write-history ap_y0 arrival0)
(def path_seconds0 (/ path_samples0 samplerate))
(def damped0 (* (exp (* (- region_rate0) path_seconds0)) arrival0))
;; Region 0, path 1: lossless fractional propagation.
(make-history outgoing1)
(def path_samples1 (max 8 (* 461 scale (/ samplerate 48000))))
(def integer_delay1 (- (floor path_samples1) 2))
(def fractional1 (+ 1 (- path_samples1 (floor path_samples1))))
(def allpass_a1 (/ (- 1 fractional1) (+ 1 fractional1)))
(def incoming1 (delay (read-history outgoing1) integer_delay1))
(make-history ap_x1)
(make-history ap_y1)
(def arrival1 (- (+ (* allpass_a1 incoming1) (read-history ap_x1)) (* allpass_a1 (read-history ap_y1))))
(write-history ap_x1 incoming1)
(write-history ap_y1 arrival1)
(def path_seconds1 (/ path_samples1 samplerate))
(def damped1 (* (exp (* (- region_rate0) path_seconds1)) arrival1))
;; Region 0, path 2: lossless fractional propagation.
(make-history outgoing2)
(def path_samples2 (max 8 (* 1797 scale (/ samplerate 48000))))
(def integer_delay2 (- (floor path_samples2) 2))
(def fractional2 (+ 1 (- path_samples2 (floor path_samples2))))
(def allpass_a2 (/ (- 1 fractional2) (+ 1 fractional2)))
(def incoming2 (delay (read-history outgoing2) integer_delay2))
(make-history ap_x2)
(make-history ap_y2)
(def arrival2 (- (+ (* allpass_a2 incoming2) (read-history ap_x2)) (* allpass_a2 (read-history ap_y2))))
(write-history ap_x2 incoming2)
(write-history ap_y2 arrival2)
(def path_seconds2 (/ path_samples2 samplerate))
(def damped2 (* (exp (* (- region_rate0) path_seconds2)) arrival2))
(def region_rate1 (+ (/ (* base_rate1 (pow damping_v 0.2)) decay_v) contact_loss))
;; Region 1, path 0: lossless fractional propagation.
(make-history outgoing3)
(def path_samples3 (max 8 (* 130 scale (/ samplerate 48000))))
(def integer_delay3 (- (floor path_samples3) 2))
(def fractional3 (+ 1 (- path_samples3 (floor path_samples3))))
(def allpass_a3 (/ (- 1 fractional3) (+ 1 fractional3)))
(def incoming3 (delay (read-history outgoing3) integer_delay3))
(make-history ap_x3)
(make-history ap_y3)
(def arrival3 (- (+ (* allpass_a3 incoming3) (read-history ap_x3)) (* allpass_a3 (read-history ap_y3))))
(write-history ap_x3 incoming3)
(write-history ap_y3 arrival3)
(def path_seconds3 (/ path_samples3 samplerate))
(def damped3 (* (exp (* (- region_rate1) path_seconds3)) arrival3))
;; Region 1, path 1: lossless fractional propagation.
(make-history outgoing4)
(def path_samples4 (max 8 (* 549 scale (/ samplerate 48000))))
(def integer_delay4 (- (floor path_samples4) 2))
(def fractional4 (+ 1 (- path_samples4 (floor path_samples4))))
(def allpass_a4 (/ (- 1 fractional4) (+ 1 fractional4)))
(def incoming4 (delay (read-history outgoing4) integer_delay4))
(make-history ap_x4)
(make-history ap_y4)
(def arrival4 (- (+ (* allpass_a4 incoming4) (read-history ap_x4)) (* allpass_a4 (read-history ap_y4))))
(write-history ap_x4 incoming4)
(write-history ap_y4 arrival4)
(def path_seconds4 (/ path_samples4 samplerate))
(def damped4 (* (exp (* (- region_rate1) path_seconds4)) arrival4))
;; Region 1, path 2: lossless fractional propagation.
(make-history outgoing5)
(def path_samples5 (max 8 (* 2141 scale (/ samplerate 48000))))
(def integer_delay5 (- (floor path_samples5) 2))
(def fractional5 (+ 1 (- path_samples5 (floor path_samples5))))
(def allpass_a5 (/ (- 1 fractional5) (+ 1 fractional5)))
(def incoming5 (delay (read-history outgoing5) integer_delay5))
(make-history ap_x5)
(make-history ap_y5)
(def arrival5 (- (+ (* allpass_a5 incoming5) (read-history ap_x5)) (* allpass_a5 (read-history ap_y5))))
(write-history ap_x5 incoming5)
(write-history ap_y5 arrival5)
(def path_seconds5 (/ path_samples5 samplerate))
(def damped5 (* (exp (* (- region_rate1) path_seconds5)) arrival5))
(def region_rate2 (+ (/ (* base_rate2 (pow damping_v 0.4)) decay_v) contact_loss))
;; Region 2, path 0: lossless fractional propagation.
(make-history outgoing6)
(def path_samples6 (max 8 (* 153 scale (/ samplerate 48000))))
(def integer_delay6 (- (floor path_samples6) 2))
(def fractional6 (+ 1 (- path_samples6 (floor path_samples6))))
(def allpass_a6 (/ (- 1 fractional6) (+ 1 fractional6)))
(def incoming6 (delay (read-history outgoing6) integer_delay6))
(make-history ap_x6)
(make-history ap_y6)
(def arrival6 (- (+ (* allpass_a6 incoming6) (read-history ap_x6)) (* allpass_a6 (read-history ap_y6))))
(write-history ap_x6 incoming6)
(write-history ap_y6 arrival6)
(def path_seconds6 (/ path_samples6 samplerate))
(def damped6 (* (exp (* (- region_rate2) path_seconds6)) arrival6))
;; Region 2, path 1: lossless fractional propagation.
(make-history outgoing7)
(def path_samples7 (max 8 (* 650 scale (/ samplerate 48000))))
(def integer_delay7 (- (floor path_samples7) 2))
(def fractional7 (+ 1 (- path_samples7 (floor path_samples7))))
(def allpass_a7 (/ (- 1 fractional7) (+ 1 fractional7)))
(def incoming7 (delay (read-history outgoing7) integer_delay7))
(make-history ap_x7)
(make-history ap_y7)
(def arrival7 (- (+ (* allpass_a7 incoming7) (read-history ap_x7)) (* allpass_a7 (read-history ap_y7))))
(write-history ap_x7 incoming7)
(write-history ap_y7 arrival7)
(def path_seconds7 (/ path_samples7 samplerate))
(def damped7 (* (exp (* (- region_rate2) path_seconds7)) arrival7))
;; Region 2, path 2: lossless fractional propagation.
(make-history outgoing8)
(def path_samples8 (max 8 (* 2535 scale (/ samplerate 48000))))
(def integer_delay8 (- (floor path_samples8) 2))
(def fractional8 (+ 1 (- path_samples8 (floor path_samples8))))
(def allpass_a8 (/ (- 1 fractional8) (+ 1 fractional8)))
(def incoming8 (delay (read-history outgoing8) integer_delay8))
(make-history ap_x8)
(make-history ap_y8)
(def arrival8 (- (+ (* allpass_a8 incoming8) (read-history ap_x8)) (* allpass_a8 (read-history ap_y8))))
(write-history ap_x8 incoming8)
(write-history ap_y8 arrival8)
(def path_seconds8 (/ path_samples8 samplerate))
(def damped8 (* (exp (* (- region_rate2) path_seconds8)) arrival8))
(def region_rate3 (+ (/ (* base_rate3 (pow damping_v 0.6)) decay_v) contact_loss))
;; Region 3, path 0: lossless fractional propagation.
(make-history outgoing9)
(def path_samples9 (max 8 (* 177 scale (/ samplerate 48000))))
(def integer_delay9 (- (floor path_samples9) 2))
(def fractional9 (+ 1 (- path_samples9 (floor path_samples9))))
(def allpass_a9 (/ (- 1 fractional9) (+ 1 fractional9)))
(def incoming9 (delay (read-history outgoing9) integer_delay9))
(make-history ap_x9)
(make-history ap_y9)
(def arrival9 (- (+ (* allpass_a9 incoming9) (read-history ap_x9)) (* allpass_a9 (read-history ap_y9))))
(write-history ap_x9 incoming9)
(write-history ap_y9 arrival9)
(def path_seconds9 (/ path_samples9 samplerate))
(def damped9 (* (exp (* (- region_rate3) path_seconds9)) arrival9))
;; Region 3, path 1: lossless fractional propagation.
(make-history outgoing10)
(def path_samples10 (max 8 (* 751 scale (/ samplerate 48000))))
(def integer_delay10 (- (floor path_samples10) 2))
(def fractional10 (+ 1 (- path_samples10 (floor path_samples10))))
(def allpass_a10 (/ (- 1 fractional10) (+ 1 fractional10)))
(def incoming10 (delay (read-history outgoing10) integer_delay10))
(make-history ap_x10)
(make-history ap_y10)
(def arrival10 (- (+ (* allpass_a10 incoming10) (read-history ap_x10)) (* allpass_a10 (read-history ap_y10))))
(write-history ap_x10 incoming10)
(write-history ap_y10 arrival10)
(def path_seconds10 (/ path_samples10 samplerate))
(def damped10 (* (exp (* (- region_rate3) path_seconds10)) arrival10))
;; Region 3, path 2: lossless fractional propagation.
(make-history outgoing11)
(def path_samples11 (max 8 (* 2929 scale (/ samplerate 48000))))
(def integer_delay11 (- (floor path_samples11) 2))
(def fractional11 (+ 1 (- path_samples11 (floor path_samples11))))
(def allpass_a11 (/ (- 1 fractional11) (+ 1 fractional11)))
(def incoming11 (delay (read-history outgoing11) integer_delay11))
(make-history ap_x11)
(make-history ap_y11)
(def arrival11 (- (+ (* allpass_a11 incoming11) (read-history ap_x11)) (* allpass_a11 (read-history ap_y11))))
(write-history ap_x11 incoming11)
(write-history ap_y11 arrival11)
(def path_seconds11 (/ path_samples11 samplerate))
(def damped11 (* (exp (* (- region_rate3) path_seconds11)) arrival11))
(def region_rate4 (+ (/ (* base_rate4 (pow damping_v 0.8)) decay_v) contact_loss))
;; Region 4, path 0: lossless fractional propagation.
(make-history outgoing12)
(def path_samples12 (max 8 (* 204 scale (/ samplerate 48000))))
(def integer_delay12 (- (floor path_samples12) 2))
(def fractional12 (+ 1 (- path_samples12 (floor path_samples12))))
(def allpass_a12 (/ (- 1 fractional12) (+ 1 fractional12)))
(def incoming12 (delay (read-history outgoing12) integer_delay12))
(make-history ap_x12)
(make-history ap_y12)
(def arrival12 (- (+ (* allpass_a12 incoming12) (read-history ap_x12)) (* allpass_a12 (read-history ap_y12))))
(write-history ap_x12 incoming12)
(write-history ap_y12 arrival12)
(def path_seconds12 (/ path_samples12 samplerate))
(def damped12 (* (exp (* (- region_rate4) path_seconds12)) arrival12))
;; Region 4, path 1: lossless fractional propagation.
(make-history outgoing13)
(def path_samples13 (max 8 (* 864 scale (/ samplerate 48000))))
(def integer_delay13 (- (floor path_samples13) 2))
(def fractional13 (+ 1 (- path_samples13 (floor path_samples13))))
(def allpass_a13 (/ (- 1 fractional13) (+ 1 fractional13)))
(def incoming13 (delay (read-history outgoing13) integer_delay13))
(make-history ap_x13)
(make-history ap_y13)
(def arrival13 (- (+ (* allpass_a13 incoming13) (read-history ap_x13)) (* allpass_a13 (read-history ap_y13))))
(write-history ap_x13 incoming13)
(write-history ap_y13 arrival13)
(def path_seconds13 (/ path_samples13 samplerate))
(def damped13 (* (exp (* (- region_rate4) path_seconds13)) arrival13))
;; Region 4, path 2: lossless fractional propagation.
(make-history outgoing14)
(def path_samples14 (max 8 (* 3372 scale (/ samplerate 48000))))
(def integer_delay14 (- (floor path_samples14) 2))
(def fractional14 (+ 1 (- path_samples14 (floor path_samples14))))
(def allpass_a14 (/ (- 1 fractional14) (+ 1 fractional14)))
(def incoming14 (delay (read-history outgoing14) integer_delay14))
(make-history ap_x14)
(make-history ap_y14)
(def arrival14 (- (+ (* allpass_a14 incoming14) (read-history ap_x14)) (* allpass_a14 (read-history ap_y14))))
(write-history ap_x14 incoming14)
(write-history ap_y14 arrival14)
(def path_seconds14 (/ path_samples14 samplerate))
(def damped14 (* (exp (* (- region_rate4) path_seconds14)) arrival14))
(def region_rate5 (+ (/ (* base_rate5 (pow damping_v 1)) decay_v) contact_loss))
;; Region 5, path 0: lossless fractional propagation.
(make-history outgoing15)
(def path_samples15 (max 8 (* 234 scale (/ samplerate 48000))))
(def integer_delay15 (- (floor path_samples15) 2))
(def fractional15 (+ 1 (- path_samples15 (floor path_samples15))))
(def allpass_a15 (/ (- 1 fractional15) (+ 1 fractional15)))
(def incoming15 (delay (read-history outgoing15) integer_delay15))
(make-history ap_x15)
(make-history ap_y15)
(def arrival15 (- (+ (* allpass_a15 incoming15) (read-history ap_x15)) (* allpass_a15 (read-history ap_y15))))
(write-history ap_x15 incoming15)
(write-history ap_y15 arrival15)
(def path_seconds15 (/ path_samples15 samplerate))
(def damped15 (* (exp (* (- region_rate5) path_seconds15)) arrival15))
;; Region 5, path 1: lossless fractional propagation.
(make-history outgoing16)
(def path_samples16 (max 8 (* 991 scale (/ samplerate 48000))))
(def integer_delay16 (- (floor path_samples16) 2))
(def fractional16 (+ 1 (- path_samples16 (floor path_samples16))))
(def allpass_a16 (/ (- 1 fractional16) (+ 1 fractional16)))
(def incoming16 (delay (read-history outgoing16) integer_delay16))
(make-history ap_x16)
(make-history ap_y16)
(def arrival16 (- (+ (* allpass_a16 incoming16) (read-history ap_x16)) (* allpass_a16 (read-history ap_y16))))
(write-history ap_x16 incoming16)
(write-history ap_y16 arrival16)
(def path_seconds16 (/ path_samples16 samplerate))
(def damped16 (* (exp (* (- region_rate5) path_seconds16)) arrival16))
;; Region 5, path 2: lossless fractional propagation.
(make-history outgoing17)
(def path_samples17 (max 8 (* 3864 scale (/ samplerate 48000))))
(def integer_delay17 (- (floor path_samples17) 2))
(def fractional17 (+ 1 (- path_samples17 (floor path_samples17))))
(def allpass_a17 (/ (- 1 fractional17) (+ 1 fractional17)))
(def incoming17 (delay (read-history outgoing17) integer_delay17))
(make-history ap_x17)
(make-history ap_y17)
(def arrival17 (- (+ (* allpass_a17 incoming17) (read-history ap_x17)) (* allpass_a17 (read-history ap_y17))))
(write-history ap_x17 incoming17)
(write-history ap_y17 arrival17)
(def path_seconds17 (/ path_samples17 samplerate))
(def damped17 (* (exp (* (- region_rate5) path_seconds17)) arrival17))
;; Reduced relative shell motion and a unilateral contact junction.
;; q/v use energy-normalized spring coordinates. The free rotation contracts;
;; projection only removes potential energy. On impact the two-port scattering
;; has eigenvalues 1 and -restitution, so it cannot create stored energy.
;; A normalized projection couples this one contact to all six wave regions.
(make-history shell_q)
(make-history shell_v)
(def shell_angle (/ (* twopi 195) (* samplerate scale)))
(def shell_radius (exp (/ (- (+ 2 (* 12 (- 1 openness_v)))) samplerate)))
(def shell_c (* shell_radius (cos shell_angle)))
(def shell_s (* shell_radius (sin shell_angle)))
(def shell_free_q (+ (* shell_c (read-history shell_q)) (* shell_s (read-history shell_v))))
(def shell_free_v (+ (- (* shell_c (read-history shell_v)) (* shell_s (read-history shell_q))) (* onset strength 0.05)))
(def shell_gap (* 0.08 openness_v openness_v))
(def incoming_contact (* 0.408248290463863 (+ damped0 damped3 damped6 damped9 damped12 damped15)))
(def shell_impact (* (gt shell_free_q shell_gap) (gt shell_free_v incoming_contact)))
(def restitution (+ 0.2 (* openness_v 0.65)))
(def collision_a (* 0.5 (- 1 restitution)))
(def collision_b (* 0.5 (+ 1 restitution)))
(def outgoing_contact (+ (* collision_a incoming_contact) (* collision_b shell_free_v)))
(def collision_velocity (+ (* collision_b incoming_contact) (* collision_a shell_free_v)))
(def contact_delta (* shell_impact (- outgoing_contact incoming_contact) 0.408248290463863))
(write-history shell_q (min shell_free_q shell_gap))
(write-history shell_v (gswitch shell_impact collision_velocity shell_free_v))

;; Unresolved microscopic contacts randomize reflection phase while preserving
;; wave energy. Noise controls an orthogonal matrix; it is never added to the
;; ringing signal. A physical-rate pole bounds the contact correlation time.
(def contact_memory (cymbal-pole shell_impact (exp (/ -1 (* samplerate 0.0007)))))
(def contact_fraction (max (pow (- 1 openness_v) 8) contact_memory))
(def roughness_pole (exp (/ (* -1 twopi 4800) samplerate)))
(def roughness (cymbal-pole (- (* 2 (noise)) 1) roughness_pole))
;; Bipolar uniform noise has variance 1/3; normalize the filtered variance.
(def roughness_scale (sqrt (/ (* 3 (+ 1 roughness_pole)) (- 1 roughness_pole))))
(def scatter_u (+ 1 (* 0.8 contact_fraction roughness roughness_scale)))
(def scatter_norm (/ 2 (+ 2 (* scatter_u scatter_u))))

(def scattered0 (+ damped0 contact_delta))
(def scattered1 damped1)
(def scattered2 damped2)
(def junction0 (* scatter_norm (+ scattered0 (* scatter_u scattered1) scattered2)))
(write-history outgoing0 (+ (- junction0 scattered0) (* force 0.57735026919)))
(write-history outgoing1 (+ (- (* scatter_u junction0) scattered1) (* force -0.57735026919)))
(write-history outgoing2 (+ (- junction0 scattered2) (* force 0.57735026919)))
(def plate0 (+ (* force base_direct) (* scattered0 0.485823499594) (* scattered1 -0.147516199622) (* scattered2 -0.268275790313)))
(def scattered3 (+ damped3 contact_delta))
(def scattered4 damped4)
(def scattered5 damped5)
(def junction1 (* scatter_norm (+ scattered3 (* scatter_u scattered4) scattered5)))
(write-history outgoing3 (+ (- junction1 scattered3) (* force 0.57735026919)))
(write-history outgoing4 (+ (- (* scatter_u junction1) scattered4) (* force -0.57735026919)))
(write-history outgoing5 (+ (- junction1 scattered5) (* force 0.57735026919)))
(def plate1 (+ (* force base_direct) (* scattered3 0.485823499594) (* scattered4 -0.147516199622) (* scattered5 -0.268275790313)))
(def scattered6 (+ damped6 contact_delta))
(def scattered7 damped7)
(def scattered8 damped8)
(def junction2 (* scatter_norm (+ scattered6 (* scatter_u scattered7) scattered8)))
(write-history outgoing6 (+ (- junction2 scattered6) (* force 0.57735026919)))
(write-history outgoing7 (+ (- (* scatter_u junction2) scattered7) (* force -0.57735026919)))
(write-history outgoing8 (+ (- junction2 scattered8) (* force 0.57735026919)))
(def plate2 (+ (* force base_direct) (* scattered6 0.485823499594) (* scattered7 -0.147516199622) (* scattered8 -0.268275790313)))
(def scattered9 (+ damped9 contact_delta))
(def scattered10 damped10)
(def scattered11 damped11)
(def junction3 (* scatter_norm (+ scattered9 (* scatter_u scattered10) scattered11)))
(write-history outgoing9 (+ (- junction3 scattered9) (* force 0.57735026919)))
(write-history outgoing10 (+ (- (* scatter_u junction3) scattered10) (* force -0.57735026919)))
(write-history outgoing11 (+ (- junction3 scattered11) (* force 0.57735026919)))
(def plate3 (+ (* force base_direct) (* scattered9 0.485823499594) (* scattered10 -0.147516199622) (* scattered11 -0.268275790313)))
(def scattered12 (+ damped12 contact_delta))
(def scattered13 damped13)
(def scattered14 damped14)
(def junction4 (* scatter_norm (+ scattered12 (* scatter_u scattered13) scattered14)))
(write-history outgoing12 (+ (- junction4 scattered12) (* force 0.57735026919)))
(write-history outgoing13 (+ (- (* scatter_u junction4) scattered13) (* force -0.57735026919)))
(write-history outgoing14 (+ (- junction4 scattered14) (* force 0.57735026919)))
(def plate4 (+ (* force base_direct) (* scattered12 0.485823499594) (* scattered13 -0.147516199622) (* scattered14 -0.268275790313)))
(def scattered15 (+ damped15 contact_delta))
(def scattered16 damped16)
(def scattered17 damped17)
(def junction5 (* scatter_norm (+ scattered15 (* scatter_u scattered16) scattered17)))
(write-history outgoing15 (+ (- junction5 scattered15) (* force 0.57735026919)))
(write-history outgoing16 (+ (- (* scatter_u junction5) scattered16) (* force -0.57735026919)))
(write-history outgoing17 (+ (- junction5 scattered17) (* force 0.57735026919)))
(def plate5 (+ (* force base_direct) (* scattered15 0.485823499594) (* scattered16 -0.147516199622) (* scattered17 -0.268275790313)))
(def band0 (svf plate0 (min (/ 100 scale) (* samplerate 0.43)) 3.2 1))
(def band1 (svf plate0 (min (/ 135.944938584 scale) (* samplerate 0.43)) 3.2 1))
(def band2 (svf plate0 (min (/ 184.810263266 scale) (* samplerate 0.43)) 3.2 1))
(def band3 (svf plate1 (min (/ 251.240198894 scale) (* samplerate 0.43)) 3.2 1))
(def band4 (svf plate1 (min (/ 341.548334086 scale) (* samplerate 0.43)) 3.2 1))
(def band5 (svf plate1 (min (/ 464.317673008 scale) (* samplerate 0.43)) 3.2 1))
(def band6 (svf plate2 (min (/ 631.216375405 scale) (* samplerate 0.43)) 3.2 1))
(def band7 (svf plate2 (min (/ 858.106713878 scale) (* samplerate 0.43)) 3.2 1))
(def band8 (svf plate2 (min (/ 1166.55264517 scale) (* samplerate 0.43)) 3.2 1))
(def band9 (svf plate3 (min (/ 1585.86927702 scale) (* samplerate 0.43)) 3.2 1))
(def band10 (svf plate3 (min (/ 2155.90901467 scale) (* samplerate 0.43)) 3.2 1))
(def band11 (svf plate3 (min (/ 2930.84918593 scale) (* samplerate 0.43)) 3.2 1))
(def band12 (svf plate4 (min (/ 3984.3411258 scale) (* samplerate 0.43)) 3.2 1))
(def band13 (svf plate4 (min (/ 5416.51009645 scale) (* samplerate 0.43)) 3.2 1))
(def band14 (svf plate4 (min (/ 7363.47132402 scale) (* samplerate 0.43)) 3.2 1))
(def band15 (svf plate5 (min (/ 10010.2665691 scale) (* samplerate 0.43)) 3.2 1))
(def band16 (svf plate5 (min (/ 13608.4507395 scale) (* samplerate 0.43)) 3.2 1))
(def band17 (svf plate5 (min (/ 18500 scale) (* samplerate 0.43)) 3.2 1))
(def omega0 (* twopi (/ (min (/ hz0 scale) (* samplerate 0.47)) samplerate)))
(def radius0 (exp (/ (- (+ (/ rate0 decay_v) contact_loss)) samplerate)))
(make-history mx0)
(make-history my0)
(def mc0 (* radius0 (cos omega0)))
(def ms0 (* radius0 (sin omega0)))
(def mp0 (exp (/ -1 (* samplerate 0.000025))))
(def mi0 (/ (+ (* (- 1 mp0) (- 1 mp0)) (* 2 mp0 (- 1 (cos omega0)))) (* (- 1 mp0) (- 1 mp0))))
(def mr0 (+ (- (* mc0 (read-history mx0)) (* ms0 (read-history my0))) (* point_force mi0)))
(def resolved0 (+ (* ms0 (read-history mx0)) (* mc0 (read-history my0))))
(write-history mx0 mr0)
(write-history my0 resolved0)
(def omega1 (* twopi (/ (min (/ hz1 scale) (* samplerate 0.47)) samplerate)))
(def radius1 (exp (/ (- (+ (/ rate1 decay_v) contact_loss)) samplerate)))
(make-history mx1)
(make-history my1)
(def mc1 (* radius1 (cos omega1)))
(def ms1 (* radius1 (sin omega1)))
(def mp1 (exp (/ -1 (* samplerate 0.000025))))
(def mi1 (/ (+ (* (- 1 mp1) (- 1 mp1)) (* 2 mp1 (- 1 (cos omega1)))) (* (- 1 mp1) (- 1 mp1))))
(def mr1 (+ (- (* mc1 (read-history mx1)) (* ms1 (read-history my1))) (* point_force mi1)))
(def resolved1 (+ (* ms1 (read-history mx1)) (* mc1 (read-history my1))))
(write-history mx1 mr1)
(write-history my1 resolved1)
(def omega2 (* twopi (/ (min (/ hz2 scale) (* samplerate 0.47)) samplerate)))
(def radius2 (exp (/ (- (+ (/ rate2 decay_v) contact_loss)) samplerate)))
(make-history mx2)
(make-history my2)
(def mc2 (* radius2 (cos omega2)))
(def ms2 (* radius2 (sin omega2)))
(def mp2 (exp (/ -1 (* samplerate 0.000025))))
(def mi2 (/ (+ (* (- 1 mp2) (- 1 mp2)) (* 2 mp2 (- 1 (cos omega2)))) (* (- 1 mp2) (- 1 mp2))))
(def mr2 (+ (- (* mc2 (read-history mx2)) (* ms2 (read-history my2))) (* point_force mi2)))
(def resolved2 (+ (* ms2 (read-history mx2)) (* mc2 (read-history my2))))
(write-history mx2 mr2)
(write-history my2 resolved2)
(def omega3 (* twopi (/ (min (/ hz3 scale) (* samplerate 0.47)) samplerate)))
(def radius3 (exp (/ (- (+ (/ rate3 decay_v) contact_loss)) samplerate)))
(make-history mx3)
(make-history my3)
(def mc3 (* radius3 (cos omega3)))
(def ms3 (* radius3 (sin omega3)))
(def mp3 (exp (/ -1 (* samplerate 0.000025))))
(def mi3 (/ (+ (* (- 1 mp3) (- 1 mp3)) (* 2 mp3 (- 1 (cos omega3)))) (* (- 1 mp3) (- 1 mp3))))
(def mr3 (+ (- (* mc3 (read-history mx3)) (* ms3 (read-history my3))) (* point_force mi3)))
(def resolved3 (+ (* ms3 (read-history mx3)) (* mc3 (read-history my3))))
(write-history mx3 mr3)
(write-history my3 resolved3)
(def omega4 (* twopi (/ (min (/ hz4 scale) (* samplerate 0.47)) samplerate)))
(def radius4 (exp (/ (- (+ (/ rate4 decay_v) contact_loss)) samplerate)))
(make-history mx4)
(make-history my4)
(def mc4 (* radius4 (cos omega4)))
(def ms4 (* radius4 (sin omega4)))
(def mp4 (exp (/ -1 (* samplerate 0.000025))))
(def mi4 (/ (+ (* (- 1 mp4) (- 1 mp4)) (* 2 mp4 (- 1 (cos omega4)))) (* (- 1 mp4) (- 1 mp4))))
(def mr4 (+ (- (* mc4 (read-history mx4)) (* ms4 (read-history my4))) (* point_force mi4)))
(def resolved4 (+ (* ms4 (read-history mx4)) (* mc4 (read-history my4))))
(write-history mx4 mr4)
(write-history my4 resolved4)
(def omega5 (* twopi (/ (min (/ hz5 scale) (* samplerate 0.47)) samplerate)))
(def radius5 (exp (/ (- (+ (/ rate5 decay_v) contact_loss)) samplerate)))
(make-history mx5)
(make-history my5)
(def mc5 (* radius5 (cos omega5)))
(def ms5 (* radius5 (sin omega5)))
(def mp5 (exp (/ -1 (* samplerate 0.000025))))
(def mi5 (/ (+ (* (- 1 mp5) (- 1 mp5)) (* 2 mp5 (- 1 (cos omega5)))) (* (- 1 mp5) (- 1 mp5))))
(def mr5 (+ (- (* mc5 (read-history mx5)) (* ms5 (read-history my5))) (* point_force mi5)))
(def resolved5 (+ (* ms5 (read-history mx5)) (* mc5 (read-history my5))))
(write-history mx5 mr5)
(write-history my5 resolved5)
(def omega6 (* twopi (/ (min (/ hz6 scale) (* samplerate 0.47)) samplerate)))
(def radius6 (exp (/ (- (+ (/ rate6 decay_v) contact_loss)) samplerate)))
(make-history mx6)
(make-history my6)
(def mc6 (* radius6 (cos omega6)))
(def ms6 (* radius6 (sin omega6)))
(def mp6 (exp (/ -1 (* samplerate 0.000025))))
(def mi6 (/ (+ (* (- 1 mp6) (- 1 mp6)) (* 2 mp6 (- 1 (cos omega6)))) (* (- 1 mp6) (- 1 mp6))))
(def mr6 (+ (- (* mc6 (read-history mx6)) (* ms6 (read-history my6))) (* point_force mi6)))
(def resolved6 (+ (* ms6 (read-history mx6)) (* mc6 (read-history my6))))
(write-history mx6 mr6)
(write-history my6 resolved6)
(def omega7 (* twopi (/ (min (/ hz7 scale) (* samplerate 0.47)) samplerate)))
(def radius7 (exp (/ (- (+ (/ rate7 decay_v) contact_loss)) samplerate)))
(make-history mx7)
(make-history my7)
(def mc7 (* radius7 (cos omega7)))
(def ms7 (* radius7 (sin omega7)))
(def mp7 (exp (/ -1 (* samplerate 0.000025))))
(def mi7 (/ (+ (* (- 1 mp7) (- 1 mp7)) (* 2 mp7 (- 1 (cos omega7)))) (* (- 1 mp7) (- 1 mp7))))
(def mr7 (+ (- (* mc7 (read-history mx7)) (* ms7 (read-history my7))) (* point_force mi7)))
(def resolved7 (+ (* ms7 (read-history mx7)) (* mc7 (read-history my7))))
(write-history mx7 mr7)
(write-history my7 resolved7)
(out band0 1 @name band0)
(out band1 2 @name band1)
(out band2 3 @name band2)
(out band3 4 @name band3)
(out band4 5 @name band4)
(out band5 6 @name band5)
(out band6 7 @name band6)
(out band7 8 @name band7)
(out band8 9 @name band8)
(out band9 10 @name band9)
(out band10 11 @name band10)
(out band11 12 @name band11)
(out band12 13 @name band12)
(out band13 14 @name band13)
(out band14 15 @name band14)
(out band15 16 @name band15)
(out band16 17 @name band16)
(out band17 18 @name band17)
(out resolved0 19 @name mode0)
(out resolved1 20 @name mode1)
(out resolved2 21 @name mode2)
(out resolved3 22 @name mode3)
(out resolved4 23 @name mode4)
(out resolved5 24 @name mode5)
(out resolved6 25 @name mode6)
(out resolved7 26 @name mode7)
