; Delay / attack / (gated peak) / decay / end, plus exact note-off hold.
; A trigger begins a new contour; reset selects zero or the current value.
; No release timeout: the downstream amp envelope owns voice termination.
(defmacro digi-fm-envelope (gate trigger delay-ms attack-ms decay-ms end-level gated reset hold)
  (make-history value-h)
  (make-history stage-h)
  (make-history progress-h)
  (make-history start-h)
  (make-history gate-h)
  (make-history held-h)
  (def old (read-history value-h))
  (def trig (gt trigger 0.5))
  (def on (gt gate 0.5))
  (def off (* (gt (read-history gate-h) 0.5) (eq on 0)))
  (def held (gswitch trig 0 (max (read-history held-h) (* off (gt hold 0.5)))))
  (def stage (gswitch trig (gswitch (gt delay-ms 0) 1 2) (read-history stage-h)))
  (def progress (gswitch trig 0 (read-history progress-h)))
  (def start (gswitch trig (gswitch (gt reset 0.5) 0 old) (read-history start-h)))
  (def duration (selector (max 1 (min 3 stage)) delay-ms attack-ms decay-ms))
  (def next-progress (min 1 (+ progress (/ 1000 (* samplerate (max duration .001))))))
  (def waiting (* (eq stage 3) (gt gated 0.5) on))
  (def p (gswitch waiting 0 next-progress))
  (def candidate (gswitch (eq stage 1) start
    (gswitch (eq stage 2) (+ start (* (- 1 start) p))
      (gswitch (eq stage 3) (+ 1 (* (- end-level 1) p)) end-level))))
  (def finished (gte p 1))
  (def next-stage (gswitch (* finished (lt stage 4)) (+ stage 1) stage))
  (def frozen (gt held 0.5))
  (def value (gswitch frozen old (gswitch (eq stage 0) 0 candidate)))
  (write-history value-h value)
  (write-history stage-h (gswitch frozen (read-history stage-h) next-stage))
  (write-history progress-h (gswitch frozen progress (gswitch finished 0 p)))
  (write-history start-h start)
  (write-history held-h held)
  (write-history gate-h on)
  value)
