#[cfg(target_os = "macos")]
use super::text_metrics::measured_text_width;
use super::metrics::{
    CODE_NODE_FONT_SIZE, CODE_NODE_HEIGHT, CODE_NODE_MIN_WIDTH, NODE_FONT_SIZE, NODE_HEIGHT,
    NODE_MIN_WIDTH, PORT_EDGE_PADDING_CELLS, PORT_MIN_CENTER_SPACING_CELLS,
};
use super::model::{ArgValue, NodeKind, PatchNode};

const MISSING_INPUT_SENTINEL: &str = "__patcher_missing_input__";

pub(super) fn preview(text: &str, max_chars: usize) -> String {
    let mut out = String::new();
    for (idx, ch) in text.chars().enumerate() {
        if idx >= max_chars {
            out.push_str("...");
            break;
        }
        out.push(ch);
    }
    out
}

pub(super) fn node_display_label(node: &PatchNode) -> String {
    let base = match node.kind {
        NodeKind::Out if node.label.contains("@modulator") => return node.label.clone(),
        NodeKind::Builtin | NodeKind::MacroInstance | NodeKind::Out | NodeKind::Constant => {
            node.op.as_str()
        }
        NodeKind::In => return node.label.clone(),
        _ => node.label.as_str(),
    };
    let mut label = base.to_string();
    for idx in node_display_input_slots(node) {
        if let Some(inline) = node.inline_inputs.get(idx).and_then(|input| input.as_ref()) {
            label.push(' ');
            label.push_str(&inline.label());
            continue;
        }
        match &node.args[idx] {
            ArgValue::Literal(value) if value == MISSING_INPUT_SENTINEL => {
                label.push_str(" ?");
            }
            ArgValue::Literal(value) if value != "<expr>" => {
                label.push(' ');
                label.push_str(value);
            }
            ArgValue::SymbolRef(_) | ArgValue::ConnectedExpr => {
                label.push_str(" ?");
            }
            _ => {}
        }
    }
    label
}

pub(super) fn node_display_input_slots(node: &PatchNode) -> Vec<usize> {
    let display_start = if matches!(
        node.args.first(),
        Some(ArgValue::SymbolRef(_) | ArgValue::ConnectedExpr)
    ) || matches!(
        node.args.first(),
        Some(ArgValue::Literal(value)) if value == MISSING_INPUT_SENTINEL
    ) {
        1
    } else {
        0
    };
    let last_displayed = node
        .args
        .iter()
        .enumerate()
        .skip(display_start)
        .filter_map(|(idx, arg)| match arg {
            _ if node
                .inline_inputs
                .get(idx)
                .and_then(|input| input.as_ref())
                .is_some() =>
            {
                Some(idx)
            }
            ArgValue::Literal(value) if value != "<expr>" && value != MISSING_INPUT_SENTINEL => {
                Some(idx)
            }
            _ => None,
        })
        .last();
    let Some(last_displayed) = last_displayed else {
        return Vec::new();
    };
    node.args
        .iter()
        .enumerate()
        .take(last_displayed + 1)
        .skip(display_start)
        .filter_map(|(idx, arg)| {
            if node
                .inline_inputs
                .get(idx)
                .and_then(|input| input.as_ref())
                .is_some()
            {
                return Some(idx);
            }
            match arg {
                ArgValue::Literal(value) if value == MISSING_INPUT_SENTINEL => Some(idx),
                ArgValue::Literal(value) if value != "<expr>" => Some(idx),
                ArgValue::SymbolRef(_) | ArgValue::ConnectedExpr => Some(idx),
                _ => None,
            }
        })
        .collect()
}

pub(super) fn node_size(node: &PatchNode) -> (f32, f32) {
    node_size_for_ports(node, 0, node.outputs.len())
}

pub(super) fn node_font_size(node: &PatchNode) -> f32 {
    if node.kind == NodeKind::CodeIsland {
        CODE_NODE_FONT_SIZE
    } else {
        NODE_FONT_SIZE
    }
}

pub(super) fn node_autogenerated_size_for_ports(
    node: &PatchNode,
    input_slot_count: usize,
    output_count: usize,
) -> (f32, f32) {
    let horizontal_padding = if node.kind == NodeKind::CodeIsland {
        2.0
    } else {
        2.65
    };
    let label = node_display_label(node);
    let font_size = node_font_size(node);
    #[cfg(target_os = "macos")]
    let label_width = measured_text_width(&label, font_size)
        .unwrap_or_else(|| estimated_label_width_cells(&label, font_size));
    // The terminal renderer places patcher label characters directly in its
    // fixed cell grid, so this is exact in that backend rather than a font
    // width estimate.
    #[cfg(not(target_os = "macos"))]
    let label_width = label.chars().count() as f32;
    let text_width = label_width + horizontal_padding;
    if node.kind == NodeKind::CodeIsland {
        (
            text_width
                .max(CODE_NODE_MIN_WIDTH)
                .min(34.0)
                .max(port_width(input_slot_count.max(output_count))),
            CODE_NODE_HEIGHT,
        )
    } else {
        (
            text_width
                .max(NODE_MIN_WIDTH)
                .min(96.0)
                .max(port_width(input_slot_count.max(output_count))),
            NODE_HEIGHT,
        )
    }
}

/// Approximate width of `label` in layout cells for the passes that run before
/// any glyph advance has been measured.
///
/// The auto layout runs while a patch is projected, which happens *before* the
/// measure pass caches that patch's label advances (and the projected patch is
/// then cached, so the cold-cache widths are the ones the layout keeps). Falling
/// back to a zero-width label collapsed every node to `NODE_MIN_WIDTH`, so the
/// layout packed nodes far tighter than they render and they visibly overlapped.
#[cfg(target_os = "macos")]
pub(super) fn estimated_label_width_cells(label: &str, font_size: f32) -> f32 {
    let chars = label.chars().count() as f32;
    // Average glyph advance of the patcher font, in pixels.
    let char_px = font_size * 0.55;
    match crate::layout::current_layout_cell_dims() {
        // cell_w == 1.0 means the pass carries no pixel geometry (terminal
        // backend), where one character occupies exactly one cell.
        Some((cell_w, _)) if cell_w > 1.0 => chars * char_px / cell_w,
        _ => chars,
    }
}

pub(super) fn node_size_for_ports(
    node: &PatchNode,
    input_slot_count: usize,
    output_count: usize,
) -> (f32, f32) {
    let (autogenerated_width, height) =
        node_autogenerated_size_for_ports(node, input_slot_count, output_count);
    let width = node
        .width
        .filter(|width| width.is_finite())
        .map(|width| width.max(autogenerated_width))
        .unwrap_or(autogenerated_width);
    (width, height)
}

fn port_width(port_count: usize) -> f32 {
    if port_count == 0 {
        0.0
    } else {
        PORT_EDGE_PADDING_CELLS * 2.0
            + PORT_MIN_CENTER_SPACING_CELLS * port_count.saturating_sub(1) as f32
    }
}
