//! Deterministic dsp.lisp generator: patch model -> complete source text.
//!
//! This replaces the surgical write-back path (docs/patch-vs-code-editor-spec.md
//! §4). The generator's input is the patch model alone — node ids, ops, args,
//! labels, connections — never prior source text or `NodeSource` positions
//! (§4.1a). Every node's identity is emitted as its binding name so a reload
//! recovers identity purely from names; nodes whose model id is not a valid
//! binding symbol are renamed deterministically and the rename is reported so
//! the layout sidecar can follow.

use std::collections::{BTreeMap, HashMap, HashSet};

use crate::parser::{ASTParser, Expression, Parser, format_expression};

use super::model::{
    ArgValue, ConnectionKind, MacroOrigin, NodeKind, Patch, PatchConnection, PatchNode,
    PatcherIntent, hidden_inline_node_ids, orphaned_inline_mod_node_ids,
};
use super::project::{dgenlisp_constant_names, dgenlisp_operator_names};

const MISSING_INPUT_SENTINEL: &str = "__patcher_missing_input__";

pub(super) const GENERATED_HEADER: &str =
    ";; generated by the patch editor — edit via the patcher or eject to code";

#[derive(Debug, Clone)]
pub(super) struct GeneratedPatchSource {
    pub(super) source: String,
    /// `(view_key, model node id) -> emitted binding name` for nodes whose
    /// canonical emitted identity differs from the model id. Shape matches the
    /// map consumed by `sidecar::emitted_layout_json_with_node_map`.
    pub(super) renamed_node_ids: HashMap<(String, String), String>,
}

pub(super) fn generate_patch_source(
    patch: &Patch,
    intent: PatcherIntent,
) -> Result<GeneratedPatchSource, String> {
    let mut renames = HashMap::new();
    let mut sections: Vec<String> = Vec::new();
    sections.push(GENERATED_HEADER.to_string());

    let library_imports = used_library_macro_names(patch);
    if !library_imports.is_empty() {
        sections.push(
            library_imports
                .iter()
                .map(|name| format!("(use-defmacro {name})"))
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }

    let mut local_macros = patch
        .macros
        .iter()
        .filter(|macro_patch| matches!(macro_patch.origin, MacroOrigin::Local))
        .collect::<Vec<_>>();
    local_macros.sort_by(|a, b| a.name.cmp(&b.name));
    for macro_patch in local_macros {
        let scope = ScopeEmitter::new(
            &macro_patch.patch,
            format!("macro:{}", macro_patch.name),
            intent,
            true,
        )?;
        let emitted = scope.emit(&mut renames)?;
        let mut lines = Vec::new();
        lines.push(format!(
            "(defmacro {} ({})",
            macro_patch.name,
            emitted.macro_params.join(" ")
        ));
        for line in &emitted.body_lines {
            if line.is_empty() {
                lines.push(String::new());
            } else {
                lines.push(format!("  {line}"));
            }
        }
        match &emitted.macro_return {
            Some(return_expr) => lines.push(format!("  {return_expr})")),
            None => {
                let last = lines.pop().unwrap_or_default();
                lines.push(format!("{last})"));
            }
        }
        sections.push(lines.join("\n"));
    }

    let scope = ScopeEmitter::new(patch, "root".to_string(), intent, false)?;
    let emitted = scope.emit(&mut renames)?;
    if !patch.host_modulators.is_empty() {
        let mut host_modulators = patch.host_modulators.clone();
        host_modulators.sort_by_key(|input| (input.slot, input.channel));
        sections.push(
            host_modulators
                .iter()
                .map(|input| {
                    format!(
                        "(def {name} (in {channel} @name {name} @modulator {slot}))",
                        name = input.name,
                        channel = input.channel,
                        slot = input.slot
                    )
                })
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }
    for group in emitted.root_groups {
        if !group.is_empty() {
            sections.push(group.join("\n"));
        }
    }

    Ok(GeneratedPatchSource {
        source: format!("{}\n", sections.join("\n\n")),
        renamed_node_ids: renames,
    })
}

fn used_library_macro_names(patch: &Patch) -> Vec<String> {
    let library_names = patch
        .macros
        .iter()
        .filter(|macro_patch| matches!(macro_patch.origin, MacroOrigin::Library { .. }))
        .map(|macro_patch| macro_patch.name.as_str())
        .collect::<HashSet<_>>();
    if library_names.is_empty() {
        return Vec::new();
    }
    let mut used = std::collections::BTreeSet::new();
    let mut scan = |scope: &Patch| {
        for node in &scope.nodes {
            if node.kind == NodeKind::MacroInstance && library_names.contains(node.op.as_str()) {
                used.insert(node.op.clone());
            }
        }
    };
    scan(patch);
    for macro_patch in &patch.macros {
        if matches!(macro_patch.origin, MacroOrigin::Local) {
            scan(&macro_patch.patch);
        }
    }
    used.into_iter().collect()
}

#[derive(Debug, Default)]
struct EmittedScope {
    /// Root scope: line groups (params, ins, defs, write-histories, outs)
    /// separated by blank lines at the section level.
    root_groups: Vec<Vec<String>>,
    /// Macro scope body (defs + write-histories), without the return line.
    body_lines: Vec<String>,
    macro_params: Vec<String>,
    macro_return: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum NodeRole {
    /// `(def name (param ...))`
    Param,
    /// `(def name (in ...))`
    Input,
    /// Macro parameter — implicit in the defmacro parameter list.
    MacroParam,
    /// `(make-history name)`
    History,
    /// `(def name value)` / `(def (a b) (macro ...))`
    Value,
    /// Emitted inline in the consumer argument: `(mod gain)`.
    InlineMod,
    /// `(out ...)` root form or macro return position.
    Out,
    /// Skipped entirely (macro-definition placeholder nodes).
    Skip,
}

struct ScopeEmitter<'a> {
    patch: &'a Patch,
    view_key: String,
    is_macro: bool,
    roles: HashMap<&'a str, NodeRole>,
    /// Dead-code omission (docs/patch-vs-code-editor-spec.md §4): value nodes
    /// that do not reach any `out` node AND whose call would be incomplete
    /// (missing required inputs, empty/unknown op, unfilled macro arity) are
    /// left out of the generated source entirely. They keep existing in the
    /// interaction state and the layout sidecar, matching the pre-regeneration
    /// system where uncommitted incomplete nodes never entered the source.
    /// Dead nodes whose calls ARE complete are still emitted as harmless
    /// unused defs so they survive a save + reload.
    omitted: HashSet<String>,
    nodes: HashMap<&'a str, &'a PatchNode>,
    /// (to_node, to_input) -> connection, deterministic pick.
    inbound: BTreeMap<(&'a str, usize), &'a PatchConnection>,
    /// binding (or reference) name per node id.
    names: HashMap<String, String>,
    /// destructured output names for multi-output value nodes.
    output_names: HashMap<String, Vec<String>>,
    used_names: HashSet<String>,
    /// Occurrence counter for inline-emitted `mod` nodes (canonical ids).
    inline_mod_counter: usize,
    /// Extra `(def name literal)` lines hoisted ahead of the consumer so the
    /// projector re-reads the literal as the same standalone constant node.
    hoisted_lines: Vec<String>,
}

impl<'a> ScopeEmitter<'a> {
    fn new(
        patch: &'a Patch,
        view_key: String,
        _intent: PatcherIntent,
        is_macro: bool,
    ) -> Result<Self, String> {
        let hidden = hidden_inline_node_ids(patch);
        let mut roles = HashMap::new();
        let mut nodes = HashMap::new();
        for node in &patch.nodes {
            nodes.insert(node.id.as_str(), node);
            let role = match node.kind {
                NodeKind::CodeIsland => {
                    return Err(format!(
                        "patch contains a code island node ('{}') and cannot be regenerated",
                        node.label
                    ));
                }
                NodeKind::MacroDefinition => NodeRole::Skip,
                NodeKind::Param => NodeRole::Param,
                NodeKind::In if is_macro => NodeRole::MacroParam,
                NodeKind::In => NodeRole::Input,
                NodeKind::History => NodeRole::History,
                NodeKind::Out => NodeRole::Out,
                NodeKind::Constant | NodeKind::Builtin | NodeKind::MacroInstance => {
                    if hidden.contains(&node.id) {
                        NodeRole::InlineMod
                    } else {
                        NodeRole::Value
                    }
                }
            };
            roles.insert(node.id.as_str(), role);
        }
        let mut inbound: BTreeMap<(&str, usize), &PatchConnection> = BTreeMap::new();
        let mut sorted_connections = patch.connections.iter().collect::<Vec<_>>();
        sorted_connections.sort_by_key(|connection| {
            (
                connection.to_node.as_str(),
                connection.to_input,
                connection.from_node.as_str(),
                connection.from_output,
            )
        });
        for connection in sorted_connections {
            inbound
                .entry((connection.to_node.as_str(), connection.to_input))
                .or_insert(connection);
        }
        let omitted = omitted_dead_node_ids(patch, &roles, &inbound);
        let mut emitter = Self {
            patch,
            view_key,
            is_macro,
            roles,
            omitted,
            nodes,
            inbound,
            names: HashMap::new(),
            output_names: HashMap::new(),
            used_names: HashSet::new(),
            inline_mod_counter: 0,
            hoisted_lines: Vec::new(),
        };
        emitter.allocate_names();
        Ok(emitter)
    }

    fn allocate_names(&mut self) {
        for reserved in [
            "def",
            "defmacro",
            "param",
            "in",
            "out",
            "make-history",
            "write-history",
            "read-history",
            "use-defmacro",
            "tuple",
            "mod",
            MISSING_INPUT_SENTINEL,
        ] {
            self.used_names.insert(reserved.to_string());
        }
        for constant in dgenlisp_constant_names() {
            self.used_names.insert(constant.clone());
        }
        // Bindings must never shadow operator names: op-derived names for
        // interaction-created nodes (`binding_base_for_node`) would otherwise
        // emit forms like `(def cos (cos x))`, making later references to the
        // binding ambiguous with the operator.
        for operator in dgenlisp_operator_names() {
            self.used_names.insert(operator.clone());
        }
        for macro_patch in &self.patch.macros {
            self.used_names.insert(macro_patch.name.clone());
        }
        for input in &self.patch.host_modulators {
            self.used_names.insert(input.name.clone());
        }

        // Macro parameters first: their names are fixed by the parameter list.
        if self.is_macro {
            for node in self.nodes_in_role_order(NodeRole::MacroParam) {
                let name = macro_param_name(node);
                let name = self.claim_unique(&name);
                self.names.insert(node.id.clone(), name);
            }
        }
        for role in [
            NodeRole::Param,
            NodeRole::Input,
            NodeRole::History,
            NodeRole::Value,
        ] {
            for node in self.nodes_in_role_order(role) {
                if node.outputs.len() > 1 {
                    let mut names = Vec::new();
                    for output in &node.outputs {
                        names.push(self.claim_unique(&sanitize_binding(output)));
                    }
                    self.names.insert(node.id.clone(), names.join("_"));
                    self.output_names.insert(node.id.clone(), names);
                } else {
                    let base = binding_base_for_node(node);
                    let name = self.claim_unique(&base);
                    self.names.insert(node.id.clone(), name);
                }
            }
        }
        for node in self.nodes_in_role_order(NodeRole::Out) {
            let name = self.claim_unique(&out_binding_base(node));
            self.names.insert(node.id.clone(), name);
        }
    }

    fn nodes_in_role_order(&self, role: NodeRole) -> Vec<&'a PatchNode> {
        let mut nodes = self
            .patch
            .nodes
            .iter()
            .filter(|node| self.roles.get(node.id.as_str()) == Some(&role))
            .filter(|node| !self.omitted.contains(node.id.as_str()))
            .collect::<Vec<_>>();
        match role {
            NodeRole::MacroParam | NodeRole::Input | NodeRole::Out => {
                nodes.sort_by(|a, b| {
                    (node_channel(a), a.id.as_str()).cmp(&(node_channel(b), b.id.as_str()))
                });
            }
            _ => nodes.sort_by(|a, b| a.id.cmp(&b.id)),
        }
        nodes
    }

    fn claim_unique(&mut self, base: &str) -> String {
        if self.used_names.insert(base.to_string()) {
            return base.to_string();
        }
        let mut idx = 2usize;
        loop {
            let candidate = format!("{base}-{idx}");
            if self.used_names.insert(candidate.clone()) {
                return candidate;
            }
            idx += 1;
        }
    }

    fn emit(mut self, renames: &mut HashMap<(String, String), String>) -> Result<EmittedScope, String> {
        let params = self.emit_role_lines(NodeRole::Param)?;
        let inputs = self.emit_role_lines(NodeRole::Input)?;
        let ordered_values = self.topological_value_order();
        let mut defs = Vec::new();
        for node_id in &ordered_values {
            let node = self.nodes[node_id.as_str()];
            let line = self.emit_value_def(node)?;
            defs.append(&mut self.hoisted_lines);
            defs.push(line);
        }
        let writes = self.emit_write_history_lines();
        let mut scope = EmittedScope::default();
        if self.is_macro {
            scope.macro_params = self.macro_param_list();
            let mut body = Vec::new();
            body.extend(params);
            body.extend(inputs.clone());
            body.extend(defs);
            body.extend(writes);
            scope.macro_return = self.emit_macro_return()?;
            scope.body_lines = body;
        } else {
            let outs = self.emit_root_out_lines()?;
            scope.root_groups = vec![params, inputs, defs, writes, outs];
        }
        self.record_renames(renames);
        Ok(scope)
    }

    fn record_renames(&self, renames: &mut HashMap<(String, String), String>) {
        for (node_id, name) in &self.names {
            if node_id != name {
                renames.insert((self.view_key.clone(), node_id.clone()), name.clone());
            }
        }
    }

    fn emit_role_lines(&mut self, role: NodeRole) -> Result<Vec<String>, String> {
        let mut lines = Vec::new();
        for node in self.nodes_in_role_order(role) {
            let binding = self.names[&node.id].clone();
            let line = match role {
                NodeRole::Param => {
                    let param_name = node.param.as_ref().map(|param| param.name.clone());
                    let label = if node.label.trim().starts_with("param") {
                        node.label.trim().to_string()
                    } else {
                        format!(
                            "param {}",
                            param_name.clone().unwrap_or_else(|| binding.clone())
                        )
                    };
                    // `(mod name)` only resolves against top-level `param`
                    // forms, so params whose identity matches the param name
                    // are emitted bare; def-wrapping is kept only for params
                    // bound under a different name.
                    if param_name.as_deref() == Some(binding.as_str()) {
                        format!("({label})")
                    } else {
                        format!("(def {binding} ({label}))")
                    }
                }
                NodeRole::Input => {
                    let label = if node.label.trim().starts_with("in") {
                        node.label.trim().to_string()
                    } else {
                        format!("in {}", node_channel(node))
                    };
                    format!("(def {binding} ({label}))")
                }
                NodeRole::History => format!("(make-history {binding})"),
                _ => continue,
            };
            lines.push(line);
        }
        Ok(lines)
    }

    /// Histories, then values, ordered so every referenced binding is defined
    /// before use. Kahn's algorithm with a deterministic (role rank, binding
    /// name) tiebreak; feedback (write-history) edges are excluded so history
    /// loops don't cycle. Genuine forward cycles fall back to name order.
    fn topological_value_order(&self) -> Vec<String> {
        let mut candidates: Vec<&PatchNode> = Vec::new();
        for role in [NodeRole::History, NodeRole::Value] {
            candidates.extend(self.nodes_in_role_order(role));
        }
        let candidate_ids = candidates
            .iter()
            .map(|node| node.id.as_str())
            .collect::<HashSet<_>>();
        let mut deps: HashMap<&str, HashSet<&str>> = HashMap::new();
        let mut dependents: HashMap<&str, Vec<&str>> = HashMap::new();
        for node in &candidates {
            let mut node_deps = HashSet::new();
            self.collect_value_deps(node, &mut node_deps);
            node_deps.retain(|dep| candidate_ids.contains(dep) && *dep != node.id.as_str());
            for dep in &node_deps {
                dependents.entry(dep).or_default().push(node.id.as_str());
            }
            deps.insert(node.id.as_str(), node_deps);
        }
        let sort_key = |node_id: &str| {
            let role_rank = match self.roles.get(node_id) {
                Some(NodeRole::History) => 0usize,
                _ => 1usize,
            };
            (role_rank, self.names[node_id].clone(), node_id.to_string())
        };
        let mut ready = deps
            .iter()
            .filter(|(_, node_deps)| node_deps.is_empty())
            .map(|(node_id, _)| sort_key(node_id))
            .collect::<std::collections::BTreeSet<_>>();
        let mut remaining = deps;
        let mut ordered = Vec::new();
        while ordered.len() < candidates.len() {
            let next = ready.iter().next().cloned().or_else(|| {
                // cycle fallback: emit the smallest-keyed remaining node
                remaining
                    .iter()
                    .filter(|(_, node_deps)| !node_deps.is_empty())
                    .map(|(node_id, _)| sort_key(node_id))
                    .min()
            });
            let Some(next) = next else { break };
            ready.remove(&next);
            let node_id = next.2.clone();
            remaining.remove(node_id.as_str());
            for dependent in dependents.remove(node_id.as_str()).unwrap_or_default() {
                if let Some(node_deps) = remaining.get_mut(dependent) {
                    node_deps.remove(node_id.as_str());
                    if node_deps.is_empty() {
                        ready.insert(sort_key(dependent));
                    }
                }
            }
            ordered.push(node_id);
        }
        ordered
    }

    /// Emission dependencies of a node: sources of its inbound forward
    /// connections, looking through inline-emitted `mod` nodes.
    fn collect_value_deps(&self, node: &PatchNode, deps: &mut HashSet<&'a str>) {
        for ((to_node, _), connection) in self
            .inbound
            .range((node.id.as_str(), 0)..=(node.id.as_str(), usize::MAX))
        {
            debug_assert_eq!(*to_node, node.id.as_str());
            if connection.kind == ConnectionKind::Feedback {
                continue;
            }
            let Some(from) = self.nodes.get(connection.from_node.as_str()) else {
                continue;
            };
            if self.roles.get(from.id.as_str()) == Some(&NodeRole::InlineMod) {
                deps.insert(from.id.as_str());
                self.collect_value_deps(from, deps);
                // the inline node itself is not emitted; depend on its inputs
                let mut inline_deps = HashSet::new();
                self.collect_value_deps(from, &mut inline_deps);
                deps.remove(from.id.as_str());
                deps.extend(inline_deps);
            } else {
                deps.insert(from.id.as_str());
            }
        }
        // Bare symbol arguments (e.g. a created node typed as `mix phase 0.25`)
        // reference other bindings by name; the referenced def must precede us.
        for arg in &node.args {
            let ArgValue::Literal(value) = arg else {
                continue;
            };
            if let Some(referenced) = self
                .patch
                .nodes
                .iter()
                .find(|candidate| self.names.get(&candidate.id) == Some(value))
            {
                deps.insert(referenced.id.as_str());
            }
        }
    }

    fn emit_value_def(&mut self, node: &'a PatchNode) -> Result<String, String> {
        if self.roles.get(node.id.as_str()) == Some(&NodeRole::History) {
            return Ok(format!("(make-history {})", self.names[&node.id]));
        }
        let binding = self.names[&node.id].clone();
        let value = match node.kind {
            NodeKind::Constant => node.op.clone(),
            _ => self.emit_call_expr(node)?,
        };
        if let Some(output_names) = self.output_names.get(&node.id).cloned() {
            Ok(format!("(def ({}) {value})", output_names.join(" ")))
        } else {
            Ok(format!("(def {binding} {value})"))
        }
    }

    fn emit_call_expr(&mut self, node: &'a PatchNode) -> Result<String, String> {
        let mut parts = vec![node.op.clone()];
        let last_needed = self.last_needed_arg_index(node);
        // Macro calls have a fixed arity: a live instance with unfilled
        // trailing parameters must emit missing-input sentinels (a genuinely
        // broken patch surfaces a diagnostic) rather than silently emitting a
        // shorter call. Builtins keep the trailing-slot trim.
        let emit_count = if node.kind == NodeKind::MacroInstance {
            self.patch
                .macros
                .iter()
                .find(|macro_patch| macro_patch.name == node.op)
                .map(|macro_patch| macro_patch.params.len())
                .filter(|arity| *arity > 0)
                .unwrap_or_else(|| last_needed.map_or(0, |last| last + 1))
        } else {
            last_needed.map_or(0, |last| last + 1)
        };
        for idx in 0..emit_count {
            let connection = self.inbound.get(&(node.id.as_str(), idx)).copied();
            if let Some(connection) = connection {
                let reference = self.reference_expr(connection)?;
                parts.push(reference);
                continue;
            }
            match node.args.get(idx) {
                Some(ArgValue::Literal(value)) => {
                    if self.literal_needs_hoisting(node, idx, value) {
                        let hoisted = self.claim_unique(&sanitize_binding(value));
                        self.hoisted_lines.push(format!("(def {hoisted} {value})"));
                        parts.push(hoisted);
                    } else {
                        parts.push(value.clone());
                    }
                }
                // A SymbolRef without a live connection means the cable was
                // deleted; the slot is open again.
                Some(ArgValue::SymbolRef(_)) | Some(ArgValue::ConnectedExpr) | None => {
                    parts.push(MISSING_INPUT_SENTINEL.to_string());
                }
            }
        }
        Ok(format!("({})", parts.join(" ")))
    }

    /// The last argument slot that must be written out: trailing unfilled
    /// slots are dropped entirely; missing-input sentinels are only emitted
    /// for gaps in front of a filled slot.
    fn last_needed_arg_index(&self, node: &PatchNode) -> Option<usize> {
        let mut last: Option<usize> = None;
        for idx in 0..node.args.len() {
            let filled = self.inbound.contains_key(&(node.id.as_str(), idx))
                || matches!(node.args.get(idx), Some(ArgValue::Literal(_)));
            if filled {
                last = Some(idx);
            }
        }
        last
    }

    /// A numeric/constant literal followed by a connected slot would be pulled
    /// out into a standalone constant node by the projector; hoist it into an
    /// explicit `def` so reparsing reproduces the emitted structure.
    fn literal_needs_hoisting(&self, node: &PatchNode, idx: usize, value: &str) -> bool {
        let is_constant_literal =
            value.parse::<f64>().is_ok() || dgenlisp_constant_names().contains(value);
        if !is_constant_literal {
            return false;
        }
        (idx + 1..node.args.len())
            .any(|later| self.inbound.contains_key(&(node.id.as_str(), later)))
    }

    fn reference_expr(&mut self, connection: &'a PatchConnection) -> Result<String, String> {
        let Some(from) = self.nodes.get(connection.from_node.as_str()).copied() else {
            return Ok(MISSING_INPUT_SENTINEL.to_string());
        };
        match self.roles.get(from.id.as_str()) {
            Some(NodeRole::History) => Ok(format!("(read-history {})", self.names[&from.id])),
            Some(NodeRole::InlineMod) => {
                let inner = match self.inbound.get(&(from.id.as_str(), 0)).copied() {
                    Some(inner_connection) => self.reference_expr(inner_connection)?,
                    None => MISSING_INPUT_SENTINEL.to_string(),
                };
                // Canonical identity of inline-emitted nodes is positional
                // (`mod#N` in projection encounter order).
                let canonical = format!("mod#{}", self.inline_mod_counter);
                self.inline_mod_counter += 1;
                self.names.insert(from.id.clone(), canonical);
                Ok(format!("({} {inner})", from.op))
            }
            _ => {
                if let Some(output_names) = self.output_names.get(&from.id) {
                    output_names
                        .get(connection.from_output)
                        .cloned()
                        .ok_or_else(|| {
                            format!(
                                "connection references missing output {} of node '{}'",
                                connection.from_output, from.id
                            )
                        })
                } else {
                    Ok(self
                        .names
                        .get(&from.id)
                        .cloned()
                        .unwrap_or_else(|| MISSING_INPUT_SENTINEL.to_string()))
                }
            }
        }
    }

    fn emit_write_history_lines(&mut self) -> Vec<String> {
        let mut writes = Vec::new();
        let mut connections = self.patch.connections.iter().collect::<Vec<_>>();
        connections.sort_by_key(|connection| {
            (
                connection.to_node.clone(),
                connection.from_node.clone(),
                connection.from_output,
            )
        });
        for connection in connections {
            if self.roles.get(connection.to_node.as_str()) != Some(&NodeRole::History) {
                continue;
            }
            // A write fed by an omitted dead node has no emitted source binding.
            if self.omitted.contains(&connection.from_node) {
                continue;
            }
            let history = self.names[&connection.to_node].clone();
            let reference = match self.nodes.get(connection.from_node.as_str()) {
                Some(_) => self
                    .reference_expr_for_write(connection)
                    .unwrap_or_else(|_| MISSING_INPUT_SENTINEL.to_string()),
                None => MISSING_INPUT_SENTINEL.to_string(),
            };
            writes.push(format!("(write-history {history} {reference})"));
        }
        writes
    }

    fn reference_expr_for_write(&mut self, connection: &'a PatchConnection) -> Result<String, String> {
        self.reference_expr(connection)
    }

    fn macro_param_list(&self) -> Vec<String> {
        let param_nodes = self.nodes_in_role_order(NodeRole::MacroParam);
        let mut by_channel: BTreeMap<usize, String> = BTreeMap::new();
        let mut max_channel = 0usize;
        for node in param_nodes {
            let channel = node_channel(node).max(1);
            max_channel = max_channel.max(channel);
            by_channel
                .entry(channel)
                .or_insert_with(|| self.names[&node.id].clone());
        }
        (1..=max_channel)
            .map(|channel| {
                by_channel
                    .get(&channel)
                    .cloned()
                    .unwrap_or_else(|| format!("input{channel}"))
            })
            .collect()
    }

    fn emit_macro_return(&mut self) -> Result<Option<String>, String> {
        let outs = self.nodes_in_role_order(NodeRole::Out);
        if outs.is_empty() {
            return Ok(None);
        }
        let mut by_channel: BTreeMap<usize, &PatchNode> = BTreeMap::new();
        let mut max_channel = 1usize;
        for out in outs {
            let channel = node_channel(out).max(1);
            max_channel = max_channel.max(channel);
            by_channel.entry(channel).or_insert(out);
        }
        let mut values = Vec::new();
        for channel in 1..=max_channel {
            let value = match by_channel.get(&channel) {
                Some(out) => match self.inbound.get(&(out.id.as_str(), 0)).copied() {
                    Some(connection) => self.reference_expr(connection)?,
                    None => MISSING_INPUT_SENTINEL.to_string(),
                },
                None => MISSING_INPUT_SENTINEL.to_string(),
            };
            values.push(value);
        }
        // Canonical macro out ids are `out`, `out2`, ... by channel.
        for (channel, out) in &by_channel {
            let canonical = if *channel == 1 {
                "out".to_string()
            } else {
                format!("out{channel}")
            };
            self.names.insert(out.id.clone(), canonical);
        }
        if values.len() == 1 {
            Ok(Some(values.remove(0)))
        } else {
            Ok(Some(format!("(tuple {})", values.join(" "))))
        }
    }

    fn emit_root_out_lines(&mut self) -> Result<Vec<String>, String> {
        let mut lines = Vec::new();
        for out in self.nodes_in_role_order(NodeRole::Out) {
            let name = self.names[&out.id].clone();
            let channel = node_channel(out).max(1);
            let value = match self.inbound.get(&(out.id.as_str(), 0)).copied() {
                Some(connection) => self.reference_expr(connection)?,
                None => MISSING_INPUT_SENTINEL.to_string(),
            };
            let modulator = out_modulator_attr(out);
            let modulator_attr = modulator
                .map(|slot| format!(" @modulator {slot}"))
                .unwrap_or_default();
            lines.push(format!(
                "(out {value} {channel}{modulator_attr} @name {name})"
            ));
        }
        Ok(lines)
    }
}

fn macro_param_name(node: &PatchNode) -> String {
    if let Some(name) = label_attribute(&node.label, "@name") {
        return sanitize_binding(&name);
    }
    if let Some(output) = node.outputs.first().filter(|name| !name.is_empty()) {
        return sanitize_binding(output);
    }
    format!("input{}", node_channel(node).max(1))
}

/// Channel of an `in`/`out` node: the first numeric literal argument, falling
/// back to the label, then 1.
fn node_channel(node: &PatchNode) -> usize {
    let from_args = node.args.iter().find_map(|arg| match arg {
        ArgValue::Literal(value) => value.parse::<f64>().ok().map(|value| value as usize),
        _ => None,
    });
    if let Some(channel) = from_args {
        return channel;
    }
    label_positional_numbers(&node.label)
        .first()
        .copied()
        .unwrap_or(1)
}

fn out_binding_base(node: &PatchNode) -> String {
    if let Some(name) = label_attribute(&node.label, "@name") {
        return sanitize_binding(&name);
    }
    let label = node.label.trim();
    let is_plain_name =
        !label.is_empty() && label != "out" && !label.starts_with("out ") && !label.contains(' ');
    if is_plain_name {
        return sanitize_binding(label);
    }
    // Interaction-created outs must not leak their `created-N` interaction id
    // into a persistent `@name` (see `binding_base_for_node`).
    if is_interaction_created_id(&node.id) {
        return "audio".to_string();
    }
    // The editable display label omits `@name`, so a dragged/edited out keeps
    // its identity through the node id (which the parser derived from @name).
    sanitize_binding(&node.id)
}

/// True for node ids minted by the interaction layer (`allocate_created_node`).
/// These are session-scoped identities and must never become binding names in
/// generated source: a reload would parse them back as node ids, and the next
/// session's `created-N` counter would collide with them, visually splicing
/// existing cables into freshly created nodes and corrupting regeneration.
fn is_interaction_created_id(id: &str) -> bool {
    id.strip_prefix("created-")
        .is_some_and(|digits| !digits.is_empty() && digits.chars().all(|ch| ch.is_ascii_digit()))
}

/// Binding base for a single-output node: source-derived ids keep their name;
/// interaction-created ids get a deterministic, op-derived name instead.
fn binding_base_for_node(node: &PatchNode) -> String {
    if !is_interaction_created_id(&node.id) {
        return sanitize_binding(&node.id);
    }
    match node.kind {
        NodeKind::Param => node
            .param
            .as_ref()
            .map(|param| sanitize_binding(&param.name))
            .filter(|name| !name.is_empty())
            .unwrap_or_else(|| "param-value".to_string()),
        NodeKind::In => label_attribute(&node.label, "@name")
            .map(|name| sanitize_binding(&name))
            .unwrap_or_else(|| format!("in{}", node_channel(node))),
        NodeKind::Constant => "value".to_string(),
        _ => {
            if node.op.trim().is_empty() {
                "node".to_string()
            } else {
                sanitize_binding(&node.op)
            }
        }
    }
}

/// Dead-code omission set: value-role nodes that (a) cannot reach any `out`
/// node through the connection graph and (b) would emit an incomplete call —
/// empty/unknown op, a missing-input gap, or an unfilled macro arity — plus,
/// transitively, dead value nodes that reference an omitted node. Dead nodes
/// with complete calls are kept (emitted as unused defs) so they survive
/// save + reload; live nodes are never omitted, so genuinely broken live
/// patches still surface the missing-input sentinel / compile diagnostics.
///
/// The "keep complete dead nodes" rule applies to user-authored nodes only:
/// projector-synthesized `param~` accessors that lost their consumer are
/// dropped outright (§4.2b) so deleting `(* a gain~)` never leaves a
/// standalone `(def mod0 (mod gain))` behind.
fn omitted_dead_node_ids(
    patch: &Patch,
    roles: &HashMap<&str, NodeRole>,
    inbound: &BTreeMap<(&str, usize), &PatchConnection>,
) -> HashSet<String> {
    let live = live_node_ids(patch, roles);
    let orphaned_inline_mods = orphaned_inline_mod_node_ids(patch);
    let mut omitted: HashSet<String> = patch
        .nodes
        .iter()
        .filter(|node| roles.get(node.id.as_str()) == Some(&NodeRole::Value))
        .filter(|node| !live.contains(node.id.as_str()))
        .filter(|node| {
            orphaned_inline_mods.contains(&node.id) || node_call_is_incomplete(patch, inbound, node)
        })
        .map(|node| node.id.clone())
        .collect();
    // Propagate: a dead node whose input references an omitted node cannot be
    // emitted either (its reference would have no binding).
    loop {
        let mut grew = false;
        for node in &patch.nodes {
            if roles.get(node.id.as_str()) != Some(&NodeRole::Value)
                || live.contains(node.id.as_str())
                || omitted.contains(node.id.as_str())
            {
                continue;
            }
            let references_omitted = inbound
                .range((node.id.as_str(), 0)..=(node.id.as_str(), usize::MAX))
                .any(|(_, connection)| omitted.contains(&connection.from_node));
            if references_omitted {
                omitted.insert(node.id.clone());
                grew = true;
            }
        }
        if !grew {
            break;
        }
    }
    omitted
}

/// Node ids from which some `out` node is reachable (reverse reachability over
/// all connections, feedback included so history writers stay live when the
/// history is read on a live path).
fn live_node_ids(patch: &Patch, roles: &HashMap<&str, NodeRole>) -> HashSet<String> {
    let mut feeds: HashMap<&str, Vec<&str>> = HashMap::new();
    for connection in &patch.connections {
        feeds
            .entry(connection.to_node.as_str())
            .or_default()
            .push(connection.from_node.as_str());
    }
    let mut live: HashSet<String> = HashSet::new();
    let mut stack: Vec<&str> = patch
        .nodes
        .iter()
        .filter(|node| roles.get(node.id.as_str()) == Some(&NodeRole::Out))
        .map(|node| node.id.as_str())
        .collect();
    while let Some(node_id) = stack.pop() {
        if !live.insert(node_id.to_string()) {
            continue;
        }
        if let Some(sources) = feeds.get(node_id) {
            for source in sources {
                if !live.contains(*source) {
                    stack.push(source);
                }
            }
        }
    }
    live
}

/// Would emitting this node's call produce an incomplete form? Mirrors
/// `emit_call_expr`: an empty or diagnosed (unknown) op, a gap in front of a
/// filled slot (missing-input sentinel), or — for macro instances, whose
/// arity is fixed — any unfilled parameter slot.
fn node_call_is_incomplete(
    patch: &Patch,
    inbound: &BTreeMap<(&str, usize), &PatchConnection>,
    node: &PatchNode,
) -> bool {
    if node.op.trim().is_empty() || node.diagnostic.is_some() {
        return true;
    }
    let slot_filled = |idx: usize| {
        inbound.contains_key(&(node.id.as_str(), idx))
            || matches!(node.args.get(idx), Some(ArgValue::Literal(_)))
    };
    if node.kind == NodeKind::MacroInstance {
        let arity = patch
            .macros
            .iter()
            .find(|macro_patch| macro_patch.name == node.op)
            .map(|macro_patch| macro_patch.params.len())
            .unwrap_or(node.args.len());
        return (0..arity).any(|idx| !slot_filled(idx));
    }
    let mut last_filled: Option<usize> = None;
    for idx in 0..node.args.len() {
        if slot_filled(idx) {
            last_filled = Some(idx);
        }
    }
    let Some(last_filled) = last_filled else {
        return false;
    };
    (0..last_filled).any(|idx| !slot_filled(idx))
}

fn out_modulator_attr(node: &PatchNode) -> Option<usize> {
    label_attribute(&node.label, "@modulator")
        .and_then(|value| value.parse::<f64>().ok())
        .map(|value| value as usize)
}

fn label_items(label: &str) -> Option<Vec<Expression>> {
    let source = format!("({})", label.trim());
    let tokens = Parser::new(source).parse().ok()?;
    let exprs = ASTParser::new(tokens).parse().ok()?;
    match exprs.into_iter().next() {
        Some(Expression::List(items)) => Some(items),
        _ => None,
    }
}

fn label_attribute(label: &str, attribute: &str) -> Option<String> {
    let items = label_items(label)?;
    items.windows(2).find_map(|pair| match (&pair[0], &pair[1]) {
        (Expression::Symbol(key), value) if key == attribute => Some(match value {
            Expression::Number(number) if *number == number.trunc() && number.abs() < 1e15 => {
                format!("{number:.0}")
            }
            other => format_expression(other),
        }),
        _ => None,
    })
}

fn label_positional_numbers(label: &str) -> Vec<usize> {
    let Some(items) = label_items(label) else {
        return Vec::new();
    };
    let mut numbers = Vec::new();
    let mut idx = 1;
    while idx < items.len() {
        if matches!(&items[idx], Expression::Symbol(symbol) if symbol.starts_with('@')) {
            idx += 2;
            continue;
        }
        if let Expression::Number(number) = &items[idx] {
            numbers.push(*number as usize);
        }
        idx += 1;
    }
    numbers
}

fn op_word(op: &str) -> Option<&'static str> {
    match op {
        "+" => Some("add"),
        "-" => Some("sub"),
        "*" => Some("mul"),
        "/" => Some("div"),
        "%" => Some("rem"),
        "<" => Some("lt"),
        ">" => Some("gt"),
        "<=" => Some("lte"),
        ">=" => Some("gte"),
        "=" | "==" => Some("eq"),
        "!=" => Some("neq"),
        _ => None,
    }
}

/// Deterministically map a model node id to a valid, compilable binding
/// symbol. Idempotent for names that are already valid.
pub(super) fn sanitize_binding(raw: &str) -> String {
    let mut segments = Vec::new();
    for segment in raw.split(['#', '~']) {
        if segment.is_empty() {
            continue;
        }
        let word = match op_word(segment) {
            Some(word) => word.to_string(),
            None => segment
                .chars()
                .map(|ch| {
                    if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                        ch
                    } else {
                        '-'
                    }
                })
                .collect::<String>(),
        };
        let word = word.trim_matches('-').to_string();
        if !word.is_empty() {
            segments.push(word);
        }
    }
    let mut joined = segments.join("-");
    while joined.contains("--") {
        joined = joined.replace("--", "-");
    }
    let joined = joined.trim_matches('-').to_string();
    let mut name = if joined.is_empty() {
        "node".to_string()
    } else {
        joined
    };
    if !name
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic())
    {
        name = format!("n{name}");
    }
    name
}
