//! Deterministic dsp.lisp generator: patch model -> complete source text.
//!
//! This replaces the surgical write-back path (docs/patch-vs-code-editor-spec.md
//! §4). The generator's input is the patch model alone — node ids, ops, args,
//! labels, connections — never prior source text or `NodeSource` positions
//! (§4.1a). Every node's identity is emitted as its binding name so a reload
//! recovers identity purely from names; nodes whose model id is not a valid
//! binding symbol are renamed deterministically and the rename is reported so
//! the layout sidecar can follow.

use std::collections::{BTreeMap, HashMap, HashSet};

use crate::parser::{ASTParser, Expression, Parser, format_expression};

use super::lisp::{
    attribute_span_len, attribute_value_items, is_attribute_key, label_attributes_suffix,
    normalize_editor_node_text, replace_label_attribute,
};
use super::model::{
    ArgValue, ConnectionKind, HostModulatorInput, MacroOrigin, NodeKind, Patch, PatchConnection,
    PatchNode, PatcherIntent, hidden_inline_node_ids, is_param_options_connection,
    options_connection_is_valid, orphaned_inline_mod_node_ids,
};
use super::project::{
    dgenlisp_constant_names, dgenlisp_operator_names, dgenlisp_preamble_macro_arities,
};

const MISSING_INPUT_SENTINEL: &str = "__patcher_missing_input__";

pub(super) const GENERATED_HEADER: &str =
    ";; generated by the patch editor — edit via the patcher or eject to code";

#[derive(Debug, Clone)]
pub(super) struct GeneratedPatchSource {
    pub(super) source: String,
    /// `(view_key, model node id) -> emitted binding name` for nodes whose
    /// canonical emitted identity differs from the model id. Shape matches the
    /// map consumed by `sidecar::emitted_layout_json_with_node_map`.
    pub(super) renamed_node_ids: HashMap<(String, String), String>,
}

pub(super) fn generate_patch_source(
    patch: &Patch,
    intent: PatcherIntent,
) -> Result<GeneratedPatchSource, String> {
    let mut renames = HashMap::new();
    let mut sections: Vec<String> = Vec::new();
    sections.push(GENERATED_HEADER.to_string());

    let library_imports = used_library_macro_names(patch);
    if !library_imports.is_empty() {
        sections.push(
            library_imports
                .iter()
                .map(|name| format!("(use-defmacro {name})"))
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }

    // Ahead of the macro sections: the effect compiler hoists a defmacro's
    // internal `param` forms to just above the defmacro, and every `@mod` param
    // must land after the `@modulator` inputs it reads.
    let host_modulators = host_modulator_inputs(patch, intent);
    if !host_modulators.is_empty() {
        sections.push(
            host_modulators
                .iter()
                .map(|input| {
                    format!(
                        "(def {name} (in {channel} @name {name} @modulator {slot}))",
                        name = input.name,
                        channel = input.channel,
                        slot = input.slot
                    )
                })
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }

    let mut local_macros = patch
        .macros
        .iter()
        .filter(|macro_patch| matches!(macro_patch.origin, MacroOrigin::Local))
        .collect::<Vec<_>>();
    local_macros.sort_by(|a, b| a.name.cmp(&b.name));
    for macro_patch in local_macros {
        let scope = ScopeEmitter::new(
            &macro_patch.patch,
            format!("macro:{}", macro_patch.name),
            intent,
            true,
        )?;
        let emitted = scope.emit(&mut renames)?;
        let mut lines = Vec::new();
        lines.push(format!(
            "(defmacro {} ({})",
            macro_patch.name,
            emitted.macro_params.join(" ")
        ));
        for line in &emitted.body_lines {
            if line.is_empty() {
                lines.push(String::new());
            } else {
                lines.push(format!("  {line}"));
            }
        }
        match &emitted.macro_return {
            Some(return_expr) => lines.push(format!("  {return_expr})")),
            None => {
                let last = lines.pop().unwrap_or_default();
                lines.push(format!("{last})"));
            }
        }
        sections.push(lines.join("\n"));
    }

    let scope = ScopeEmitter::new(patch, "root".to_string(), intent, false)?;
    let emitted = scope.emit(&mut renames)?;
    for group in emitted.root_groups {
        if !group.is_empty() {
            sections.push(group.join("\n"));
        }
    }

    Ok(GeneratedPatchSource {
        source: format!("{}\n", sections.join("\n\n")),
        renamed_node_ids: renames,
    })
}

/// The `@modulator` inputs the emitted source declares.
///
/// A modulatable param is inert without them — the compiler has nothing to feed
/// `(mod name)` and `dsp_validate` rejects the file — so when the patch carries
/// no host modulator defs of its own (a hand-built patch, or any effect: only
/// `INSTRUMENT_TEMPLATE` ships them) the four configurable slots are
/// materialized as soon as anything in the patch is modulatable. Channels sit
/// past the fixed host inputs: 1-5 for an instrument, 1-2 (L/R) for an effect.
fn host_modulator_inputs(patch: &Patch, intent: PatcherIntent) -> Vec<HostModulatorInput> {
    if !patch.host_modulators.is_empty() {
        let mut declared = patch.host_modulators.clone();
        declared.sort_by_key(|input| (input.slot, input.channel));
        return declared;
    }
    if !patch_has_modulatable_param(patch) {
        return Vec::new();
    }
    let first_channel = match intent {
        PatcherIntent::Instrument => 6,
        PatcherIntent::Effect => 3,
    };
    (1..=4)
        .map(|slot| HostModulatorInput {
            name: format!("mod{slot}"),
            channel: first_channel + slot - 1,
            slot,
        })
        .collect()
}

/// Root scope or any macro body — a defmacro-internal `@mod` param needs the
/// modulator inputs just as much as a top-level one.
fn patch_has_modulatable_param(patch: &Patch) -> bool {
    let scope_is_modulatable = |scope: &Patch| {
        scope
            .nodes
            .iter()
            .any(|node| node.param.as_ref().is_some_and(|param| param.modulatable))
    };
    scope_is_modulatable(patch)
        || patch
            .macros
            .iter()
            .any(|macro_patch| scope_is_modulatable(&macro_patch.patch))
}

/// Modulation is inferred from graph use (`infer_modulatable_params` in
/// state.rs), so the `param` form the patch was authored with usually says
/// nothing about it. Fill in what the compiler needs, leaving anything the user
/// wrote alone: an authored `@mod-mode` survives, and additive is the default
/// only because it is what nearly every patch wants.
fn augment_param_label_with_mod(label: String, modulatable: bool) -> String {
    if !modulatable {
        return label;
    }
    let mut label = label;
    if label_attribute(&label, "@mod").is_none() {
        label.push_str(" @mod true");
    }
    if label_attribute(&label, "@mod-mode").is_none() {
        label.push_str(" @mod-mode additive");
    }
    label
}

fn used_library_macro_names(patch: &Patch) -> Vec<String> {
    let library_names = patch
        .macros
        .iter()
        .filter(|macro_patch| matches!(macro_patch.origin, MacroOrigin::Library { .. }))
        .map(|macro_patch| macro_patch.name.as_str())
        .collect::<HashSet<_>>();
    // Imports the source declared that the model could not resolve to a
    // library macro (see `Patch::imports`): a call to one of these projects as
    // an unknown-operator `Builtin`, so it is matched by op name alone.
    let unresolved_imports = patch
        .imports
        .iter()
        .filter(|import| {
            !patch
                .macros
                .iter()
                .any(|macro_patch| &&macro_patch.name == import)
        })
        .map(String::as_str)
        .collect::<HashSet<_>>();
    if library_names.is_empty() && unresolved_imports.is_empty() {
        return Vec::new();
    }
    let mut used = std::collections::BTreeSet::new();
    let mut scan = |scope: &Patch| {
        for node in &scope.nodes {
            let is_library_instance =
                node.kind == NodeKind::MacroInstance && library_names.contains(node.op.as_str());
            if is_library_instance || unresolved_imports.contains(node.op.as_str()) {
                used.insert(node.op.clone());
            }
        }
    };
    scan(patch);
    for macro_patch in &patch.macros {
        if matches!(macro_patch.origin, MacroOrigin::Local) {
            scan(&macro_patch.patch);
        }
    }
    used.into_iter().collect()
}

#[derive(Debug, Default)]
struct EmittedScope {
    /// Root scope: line groups (params, ins, defs, write-histories, outs)
    /// separated by blank lines at the section level.
    root_groups: Vec<Vec<String>>,
    /// Macro scope body (defs + write-histories), without the return line.
    body_lines: Vec<String>,
    macro_params: Vec<String>,
    macro_return: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum NodeRole {
    /// `(def name (param ...))`
    Param,
    /// `(def name (in ...))`
    Input,
    /// Macro parameter — implicit in the defmacro parameter list.
    MacroParam,
    /// `(make-history name)`
    History,
    /// `(def name value)` / `(def (a b) (macro ...))`
    Value,
    /// Emitted inline in the consumer argument: `(mod gain)`.
    InlineMod,
    /// `(out ...)` root form or macro return position.
    Out,
    /// Skipped entirely (macro-definition placeholder nodes).
    Skip,
}

struct ScopeEmitter<'a> {
    patch: &'a Patch,
    view_key: String,
    is_macro: bool,
    roles: HashMap<&'a str, NodeRole>,
    /// Dead-code omission (docs/patch-vs-code-editor-spec.md §4): value nodes
    /// that do not reach any `out` node AND whose call would be incomplete
    /// (missing required inputs, empty/unknown op, unfilled macro arity) are
    /// left out of the generated source entirely. They keep existing in the
    /// interaction state and the layout sidecar, matching the pre-regeneration
    /// system where uncommitted incomplete nodes never entered the source.
    /// Dead nodes whose calls ARE complete are still emitted as harmless
    /// unused defs so they survive a save + reload.
    omitted: HashSet<String>,
    nodes: HashMap<&'a str, &'a PatchNode>,
    /// (to_node, to_input) -> every connection landing on that inlet, in a
    /// deterministic order.
    ///
    /// An inlet may take more than one cable (Max/gen~ summing inlets): the
    /// slot then emits `(+ a b …)`. Every dgenlisp inlet is a float or a
    /// tensor and both sum, so this is allowed on every inlet rather than
    /// opted into per operator. Slots holding an inline literal or an inline
    /// `param~` draw no port at all (geometry.rs `patch_input_indices`), so a
    /// summed slot is always made of cables only.
    inbound: BTreeMap<(&'a str, usize), Vec<&'a PatchConnection>>,
    /// The one tensor binding cable supplying each param's `@options` attribute.
    param_options: HashMap<&'a str, &'a PatchConnection>,
    /// binding (or reference) name per node id.
    names: HashMap<String, String>,
    /// destructured output names for multi-output value nodes.
    output_names: HashMap<String, Vec<String>>,
    used_names: HashSet<String>,
    /// Occurrence counter for inline-emitted `mod` nodes (canonical ids).
    inline_mod_counter: usize,
    /// Extra `(def name literal)` lines hoisted ahead of the consumer so the
    /// projector re-reads the literal as the same standalone constant node.
    hoisted_lines: Vec<String>,
}

impl<'a> ScopeEmitter<'a> {
    fn new(
        patch: &'a Patch,
        view_key: String,
        _intent: PatcherIntent,
        is_macro: bool,
    ) -> Result<Self, String> {
        let hidden = hidden_inline_node_ids(patch);
        let mut roles = HashMap::new();
        let mut nodes = HashMap::new();
        for node in &patch.nodes {
            nodes.insert(node.id.as_str(), node);
            let role = match node.kind {
                NodeKind::CodeIsland => {
                    return Err(format!(
                        "patch contains a code island node ('{}') and cannot be regenerated",
                        node.label
                    ));
                }
                NodeKind::MacroDefinition => NodeRole::Skip,
                NodeKind::Param => NodeRole::Param,
                NodeKind::In if is_macro => NodeRole::MacroParam,
                NodeKind::In => NodeRole::Input,
                NodeKind::History => NodeRole::History,
                NodeKind::Out => NodeRole::Out,
                NodeKind::Constant | NodeKind::Builtin | NodeKind::MacroInstance => {
                    if hidden.contains(&node.id) {
                        NodeRole::InlineMod
                    } else {
                        NodeRole::Value
                    }
                }
            };
            roles.insert(node.id.as_str(), role);
        }
        let mut inbound: BTreeMap<(&str, usize), Vec<&PatchConnection>> = BTreeMap::new();
        let mut sorted_connections = patch.connections.iter().collect::<Vec<_>>();
        // Summed inlets emit their terms in this order, so it decides the
        // generated text: sorting by endpoint (never by the patch's connection
        // order, which drag order perturbs) keeps saves byte-stable.
        sorted_connections.sort_by_key(|connection| {
            (
                connection.to_node.as_str(),
                connection.to_input,
                connection.from_node.as_str(),
                connection.from_output,
            )
        });
        let mut param_options = HashMap::new();
        for connection in sorted_connections {
            if is_param_options_connection(patch, connection) {
                if !options_connection_is_valid(patch, connection) {
                    return Err(format!(
                        "param options cable must originate from tensor outlet 0: '{}:{}' -> '{}'",
                        connection.from_node, connection.from_output, connection.to_node
                    ));
                }
                if param_options
                    .insert(connection.to_node.as_str(), connection)
                    .is_some()
                {
                    return Err(format!(
                        "param '{}' has more than one options cable",
                        connection.to_node
                    ));
                }
                continue;
            }
            inbound
                .entry((connection.to_node.as_str(), connection.to_input))
                .or_default()
                .push(connection);
        }
        let omitted = omitted_dead_node_ids(patch, &roles, &inbound);
        let mut emitter = Self {
            patch,
            view_key,
            is_macro,
            roles,
            omitted,
            nodes,
            inbound,
            param_options,
            names: HashMap::new(),
            output_names: HashMap::new(),
            used_names: HashSet::new(),
            inline_mod_counter: 0,
            hoisted_lines: Vec::new(),
        };
        emitter.allocate_names();
        Ok(emitter)
    }

    fn allocate_names(&mut self) {
        for reserved in [
            "def",
            "defmacro",
            "param",
            "in",
            "out",
            "make-history",
            "write-history",
            "read-history",
            "use-defmacro",
            "tuple",
            "mod",
            MISSING_INPUT_SENTINEL,
        ] {
            self.used_names.insert(reserved.to_string());
        }
        for constant in dgenlisp_constant_names() {
            self.used_names.insert(constant.clone());
        }
        // Bindings must never shadow operator names: op-derived names for
        // interaction-created nodes (`binding_base_for_node`) would otherwise
        // emit forms like `(def cos (cos x))`, making later references to the
        // binding ambiguous with the operator.
        for operator in dgenlisp_operator_names() {
            self.used_names.insert(operator.clone());
        }
        for macro_patch in &self.patch.macros {
            self.used_names.insert(macro_patch.name.clone());
        }
        for input in &self.patch.host_modulators {
            self.used_names.insert(input.name.clone());
        }

        // Macro parameters first: their names are fixed by the parameter list.
        if self.is_macro {
            for node in self.nodes_in_role_order(NodeRole::MacroParam) {
                let name = macro_param_name(node);
                let name = self.claim_unique(&name);
                self.names.insert(node.id.clone(), name);
            }
        }
        for role in [
            NodeRole::Param,
            NodeRole::Input,
            NodeRole::History,
            NodeRole::Value,
        ] {
            for node in self.nodes_in_role_order(role) {
                if node.outputs.len() > 1 {
                    let mut names = Vec::new();
                    for output in &node.outputs {
                        names.push(self.claim_unique(&sanitize_binding(output)));
                    }
                    self.names.insert(node.id.clone(), names.join("_"));
                    self.output_names.insert(node.id.clone(), names);
                } else {
                    let base = binding_base_for_node(node);
                    let name = self.claim_unique(&base);
                    self.names.insert(node.id.clone(), name);
                }
            }
        }
        for node in self.nodes_in_role_order(NodeRole::Out) {
            let name = self.claim_unique(&out_binding_base(node));
            self.names.insert(node.id.clone(), name);
        }
    }

    fn nodes_in_role_order(&self, role: NodeRole) -> Vec<&'a PatchNode> {
        let mut nodes = self
            .patch
            .nodes
            .iter()
            .filter(|node| self.roles.get(node.id.as_str()) == Some(&role))
            .filter(|node| !self.omitted.contains(node.id.as_str()))
            .collect::<Vec<_>>();
        match role {
            NodeRole::MacroParam | NodeRole::Input | NodeRole::Out => {
                nodes.sort_by(|a, b| {
                    (node_channel(a), a.id.as_str()).cmp(&(node_channel(b), b.id.as_str()))
                });
            }
            _ => nodes.sort_by(|a, b| a.id.cmp(&b.id)),
        }
        nodes
    }

    fn claim_unique(&mut self, base: &str) -> String {
        if self.used_names.insert(base.to_string()) {
            return base.to_string();
        }
        let mut idx = 2usize;
        loop {
            let candidate = format!("{base}-{idx}");
            if self.used_names.insert(candidate.clone()) {
                return candidate;
            }
            idx += 1;
        }
    }

    fn emit(
        mut self,
        renames: &mut HashMap<(String, String), String>,
    ) -> Result<EmittedScope, String> {
        let ordered_values = self.topological_value_order();
        let option_source_ids = self
            .param_options
            .values()
            .map(|connection| connection.from_node.as_str())
            .collect::<HashSet<_>>();
        // Binding-valued attributes are resolved while the param is compiled,
        // so their tensor defs must precede the param declaration even when the
        // options cable is the tensor's only fan-out.
        let mut option_defs = Vec::new();
        for node_id in ordered_values
            .iter()
            .filter(|node_id| option_source_ids.contains(node_id.as_str()))
        {
            let node = self.nodes[node_id.as_str()];
            let line = self.emit_value_def(node)?;
            option_defs.append(&mut self.hoisted_lines);
            option_defs.push(line);
        }
        let params = self.emit_role_lines(NodeRole::Param)?;
        let inputs = self.emit_role_lines(NodeRole::Input)?;
        let mut defs = Vec::new();
        for node_id in ordered_values
            .iter()
            .filter(|node_id| !option_source_ids.contains(node_id.as_str()))
        {
            let node = self.nodes[node_id.as_str()];
            let line = self.emit_value_def(node)?;
            defs.append(&mut self.hoisted_lines);
            defs.push(line);
        }
        let writes = self.emit_write_history_lines();
        let mut scope = EmittedScope::default();
        if self.is_macro {
            scope.macro_params = self.macro_param_list();
            let mut body = Vec::new();
            body.extend(option_defs);
            body.extend(params);
            body.extend(inputs.clone());
            body.extend(defs);
            body.extend(writes);
            scope.macro_return = self.emit_macro_return()?;
            scope.body_lines = body;
        } else {
            let outs = self.emit_root_out_lines()?;
            scope.root_groups = vec![option_defs, params, inputs, defs, writes, outs];
        }
        self.record_renames(renames);
        Ok(scope)
    }

    fn record_renames(&self, renames: &mut HashMap<(String, String), String>) {
        for (node_id, name) in &self.names {
            if node_id != name {
                renames.insert((self.view_key.clone(), node_id.clone()), name.clone());
            }
        }
    }

    fn emit_role_lines(&mut self, role: NodeRole) -> Result<Vec<String>, String> {
        let mut lines = Vec::new();
        for node in self.nodes_in_role_order(role) {
            let binding = self.names[&node.id].clone();
            let line = match role {
                NodeRole::Param => {
                    let param_name = node.param.as_ref().map(|param| param.name.clone());
                    let label = if node.label.trim().starts_with("param") {
                        node.label.trim().to_string()
                    } else {
                        format!(
                            "param {}",
                            param_name.clone().unwrap_or_else(|| binding.clone())
                        )
                    };
                    let label = augment_param_label_with_mod(
                        label,
                        node.param.as_ref().is_some_and(|param| param.modulatable),
                    );
                    let options = self.param_options.get(node.id.as_str()).copied();
                    let label = if let Some(connection) = options {
                        let binding = self.reference_expr(connection)?;
                        replace_label_attribute(&label, "@options", Some(&binding))?
                    } else if node
                        .param
                        .as_ref()
                        .is_some_and(|param| param.options_tensor.is_some())
                    {
                        replace_label_attribute(&label, "@options", None)?
                    } else {
                        label
                    };
                    // `(mod name)` only resolves against top-level `param`
                    // forms, so params whose identity matches the param name
                    // are emitted bare; def-wrapping is kept only for params
                    // bound under a different name.
                    if param_name.as_deref() == Some(binding.as_str()) {
                        format!("({label})")
                    } else {
                        format!("(def {binding} ({label}))")
                    }
                }
                NodeRole::Input => {
                    let label = if node.label.trim().starts_with("in") {
                        node.label.trim().to_string()
                    } else {
                        format!("in {}", node_channel(node))
                    };
                    format!("(def {binding} ({label}))")
                }
                // `(make-history h @shape [2 2])` is a tensor history; the
                // label is the attribute carrier (see lisp.rs node_label).
                NodeRole::History => format!(
                    "(make-history {binding}{})",
                    label_attributes_suffix(&node.label)
                ),
                _ => continue,
            };
            lines.push(line);
        }
        Ok(lines)
    }

    /// Histories, then values, ordered so every referenced binding is defined
    /// before use. Kahn's algorithm with a deterministic (role rank, binding
    /// name) tiebreak; feedback (write-history) edges are excluded so history
    /// loops don't cycle. Genuine forward cycles fall back to name order.
    fn topological_value_order(&self) -> Vec<String> {
        let mut candidates: Vec<&PatchNode> = Vec::new();
        for role in [NodeRole::History, NodeRole::Value] {
            candidates.extend(self.nodes_in_role_order(role));
        }
        let candidate_ids = candidates
            .iter()
            .map(|node| node.id.as_str())
            .collect::<HashSet<_>>();
        let mut deps: HashMap<&str, HashSet<&str>> = HashMap::new();
        let mut dependents: HashMap<&str, Vec<&str>> = HashMap::new();
        for node in &candidates {
            let mut node_deps = HashSet::new();
            self.collect_value_deps(node, &mut node_deps);
            node_deps.retain(|dep| candidate_ids.contains(dep) && *dep != node.id.as_str());
            for dep in &node_deps {
                dependents.entry(dep).or_default().push(node.id.as_str());
            }
            deps.insert(node.id.as_str(), node_deps);
        }
        let sort_key = |node_id: &str| {
            let role_rank = match self.roles.get(node_id) {
                Some(NodeRole::History) => 0usize,
                _ => 1usize,
            };
            (role_rank, self.names[node_id].clone(), node_id.to_string())
        };
        let mut ready = deps
            .iter()
            .filter(|(_, node_deps)| node_deps.is_empty())
            .map(|(node_id, _)| sort_key(node_id))
            .collect::<std::collections::BTreeSet<_>>();
        let mut remaining = deps;
        let mut ordered = Vec::new();
        while ordered.len() < candidates.len() {
            let next = ready.iter().next().cloned().or_else(|| {
                // cycle fallback: emit the smallest-keyed remaining node
                remaining
                    .iter()
                    .filter(|(_, node_deps)| !node_deps.is_empty())
                    .map(|(node_id, _)| sort_key(node_id))
                    .min()
            });
            let Some(next) = next else { break };
            ready.remove(&next);
            let node_id = next.2.clone();
            remaining.remove(node_id.as_str());
            for dependent in dependents.remove(node_id.as_str()).unwrap_or_default() {
                if let Some(node_deps) = remaining.get_mut(dependent) {
                    node_deps.remove(node_id.as_str());
                    if node_deps.is_empty() {
                        ready.insert(sort_key(dependent));
                    }
                }
            }
            ordered.push(node_id);
        }
        ordered
    }

    /// Emission dependencies of a node: sources of its inbound forward
    /// connections, looking through inline-emitted `mod` nodes.
    fn collect_value_deps(&self, node: &PatchNode, deps: &mut HashSet<&'a str>) {
        // Every cable on a slot is a dependency, not just the first: a summed
        // inlet's terms all have to be bound before the consumer is emitted.
        for ((to_node, _), connections) in self
            .inbound
            .range((node.id.as_str(), 0)..=(node.id.as_str(), usize::MAX))
        {
            debug_assert_eq!(*to_node, node.id.as_str());
            for connection in connections {
                if connection.kind == ConnectionKind::Feedback {
                    continue;
                }
                let Some(from) = self.nodes.get(connection.from_node.as_str()) else {
                    continue;
                };
                if self.roles.get(from.id.as_str()) == Some(&NodeRole::InlineMod) {
                    deps.insert(from.id.as_str());
                    self.collect_value_deps(from, deps);
                    // the inline node itself is not emitted; depend on its inputs
                    let mut inline_deps = HashSet::new();
                    self.collect_value_deps(from, &mut inline_deps);
                    deps.remove(from.id.as_str());
                    deps.extend(inline_deps);
                } else {
                    deps.insert(from.id.as_str());
                }
            }
        }
        // Bare symbol arguments (e.g. a created node typed as `mix phase 0.25`)
        // reference other bindings by name; the referenced def must precede us.
        for arg in &node.args {
            let ArgValue::Literal(value) = arg else {
                continue;
            };
            if let Some(referenced) = self
                .patch
                .nodes
                .iter()
                .find(|candidate| self.names.get(&candidate.id) == Some(value))
            {
                deps.insert(referenced.id.as_str());
            }
        }
    }

    fn emit_value_def(&mut self, node: &'a PatchNode) -> Result<String, String> {
        if self.roles.get(node.id.as_str()) == Some(&NodeRole::History) {
            return Ok(format!(
                "(make-history {}{})",
                self.names[&node.id],
                label_attributes_suffix(&node.label)
            ));
        }
        let binding = self.names[&node.id].clone();
        let value = match node.kind {
            NodeKind::Constant => node.op.clone(),
            _ => self.emit_call_expr(node)?,
        };
        if let Some(output_names) = self.output_names.get(&node.id).cloned() {
            Ok(format!("(def ({}) {value})", output_names.join(" ")))
        } else {
            Ok(format!("(def {binding} {value})"))
        }
    }

    fn emit_call_expr(&mut self, node: &'a PatchNode) -> Result<String, String> {
        let mut parts = vec![node.op.clone()];
        let last_needed = self.last_needed_arg_index(node);
        // Macro calls (patch-local/library instances and preamble defmacros
        // like `svf`) have a fixed arity: a live instance with unfilled
        // trailing parameters must emit missing-input sentinels (a genuinely
        // broken patch surfaces a diagnostic) rather than silently emitting a
        // shorter call. Builtins keep the trailing-slot trim.
        let trimmed_count = last_needed.map_or(0, |last| last + 1);
        let emit_count = fixed_macro_arity(self.patch, node)
            .filter(|arity| *arity > 0)
            .map_or(trimmed_count, |arity| arity.max(trimmed_count));
        for idx in 0..emit_count {
            if let Some(value) = self.slot_value_expr(node.id.as_str(), idx)? {
                parts.push(value);
                continue;
            }
            match node.args.get(idx) {
                Some(ArgValue::Literal(value)) => {
                    if self.literal_needs_hoisting(node, idx, value) {
                        let hoisted = self.claim_unique(&sanitize_binding(value));
                        self.hoisted_lines.push(format!("(def {hoisted} {value})"));
                        parts.push(hoisted);
                    } else {
                        parts.push(value.clone());
                    }
                }
                // A SymbolRef without a live connection means the cable was
                // deleted; the slot is open again.
                Some(ArgValue::SymbolRef(_)) | Some(ArgValue::ConnectedExpr) | None => {
                    parts.push(MISSING_INPUT_SENTINEL.to_string());
                }
            }
        }
        Ok(format!(
            "({}{})",
            parts.join(" "),
            label_attributes_suffix(&node.label)
        ))
    }

    /// The last argument slot that must be written out: trailing unfilled
    /// slots are dropped entirely; missing-input sentinels are only emitted
    /// for gaps in front of a filled slot.
    fn last_needed_arg_index(&self, node: &PatchNode) -> Option<usize> {
        let mut last: Option<usize> = None;
        for idx in 0..node.args.len() {
            let filled = self.inbound.contains_key(&(node.id.as_str(), idx))
                || matches!(node.args.get(idx), Some(ArgValue::Literal(_)));
            if filled {
                last = Some(idx);
            }
        }
        last
    }

    /// A numeric/constant literal followed by a connected slot would be pulled
    /// out into a standalone constant node by the projector; hoist it into an
    /// explicit `def` so reparsing reproduces the emitted structure.
    fn literal_needs_hoisting(&self, node: &PatchNode, idx: usize, value: &str) -> bool {
        let is_constant_literal =
            value.parse::<f64>().is_ok() || dgenlisp_constant_names().contains(value);
        if !is_constant_literal {
            return false;
        }
        (idx + 1..node.args.len())
            .any(|later| self.inbound.contains_key(&(node.id.as_str(), later)))
    }

    /// Every cable landing on one inlet, in emission order.
    fn slot_connections(&self, node_id: &'a str, idx: usize) -> Vec<&'a PatchConnection> {
        self.inbound
            .get(&(node_id, idx))
            .cloned()
            .unwrap_or_default()
    }

    /// The single cable on an inlet that cannot meaningfully sum — the
    /// synthesized `(mod p)` accessor's own input, which is always exactly one
    /// edge from a param node.
    fn slot_primary(&self, node_id: &'a str, idx: usize) -> Option<&'a PatchConnection> {
        self.inbound
            .get(&(node_id, idx))
            .and_then(|connections| connections.first().copied())
    }

    /// The expression feeding one inlet: the reference itself for a single
    /// cable, `(+ …)` for several. `None` when nothing is cabled.
    fn slot_value_expr(&mut self, node_id: &'a str, idx: usize) -> Result<Option<String>, String> {
        let connections = self.slot_connections(node_id, idx);
        let mut terms = Vec::with_capacity(connections.len());
        for connection in connections {
            terms.push(self.reference_expr(connection)?);
        }
        Ok(match terms.len() {
            0 => None,
            1 => Some(terms.remove(0)),
            _ => Some(format!("(+ {})", terms.join(" "))),
        })
    }

    /// The declared param name of `node_id`, if it is a param node.
    fn param_name_for(&self, node_id: &str) -> Option<String> {
        self.nodes
            .get(node_id)
            .and_then(|node| node.param.as_ref())
            .map(|param| param.name.clone())
    }

    fn reference_expr(&mut self, connection: &'a PatchConnection) -> Result<String, String> {
        let Some(from) = self.nodes.get(connection.from_node.as_str()).copied() else {
            return Ok(MISSING_INPUT_SENTINEL.to_string());
        };
        match self.roles.get(from.id.as_str()) {
            Some(NodeRole::History) => Ok(format!("(read-history {})", self.names[&from.id])),
            Some(NodeRole::InlineMod) => {
                let inner = match self.slot_primary(from.id.as_str(), 0) {
                    // `(mod X)` resolves only against a top-level `(param X …)`
                    // form, so it must name the PARAM — not the binding. A param
                    // bound under a different name (`(def value (param embouchure
                    // …))`, which the emitter keeps def-wrapped) is referenced as
                    // `value` everywhere else but modulated as `(mod embouchure)`;
                    // emitting the binding produced "'value' does not reference a
                    // parameter" at compile time.
                    Some(inner_connection) if from.op == "mod" => {
                        match self.param_name_for(&inner_connection.from_node) {
                            Some(param_name) => param_name,
                            None => self.reference_expr(inner_connection)?,
                        }
                    }
                    Some(inner_connection) => self.reference_expr(inner_connection)?,
                    None => MISSING_INPUT_SENTINEL.to_string(),
                };
                // Canonical identity of inline-emitted nodes is positional
                // (`mod#N` in projection encounter order).
                let canonical = format!("mod#{}", self.inline_mod_counter);
                self.inline_mod_counter += 1;
                self.names.insert(from.id.clone(), canonical);
                Ok(format!("({} {inner})", from.op))
            }
            _ => {
                if let Some(output_names) = self.output_names.get(&from.id) {
                    output_names
                        .get(connection.from_output)
                        .cloned()
                        .ok_or_else(|| {
                            format!(
                                "connection references missing output {} of node '{}'",
                                connection.from_output, from.id
                            )
                        })
                } else {
                    Ok(self
                        .names
                        .get(&from.id)
                        .cloned()
                        .unwrap_or_else(|| MISSING_INPUT_SENTINEL.to_string()))
                }
            }
        }
    }

    fn emit_write_history_lines(&mut self) -> Vec<String> {
        let mut writes = Vec::new();
        let mut connections = self.patch.connections.iter().collect::<Vec<_>>();
        connections.sort_by_key(|connection| {
            (
                connection.to_node.clone(),
                connection.from_node.clone(),
                connection.from_output,
            )
        });
        // A history inlet sums its cables like any other, so the writes are
        // grouped per history node and emitted as one summed `write-history`
        // rather than as competing writes that overwrite each other.
        let mut grouped: Vec<(String, Vec<String>)> = Vec::new();
        for connection in connections {
            if self.roles.get(connection.to_node.as_str()) != Some(&NodeRole::History) {
                continue;
            }
            // A write fed by an omitted dead node has no emitted source binding.
            if self.omitted.contains(&connection.from_node) {
                continue;
            }
            let reference = match self.nodes.get(connection.from_node.as_str()) {
                Some(_) => self
                    .reference_expr_for_write(connection)
                    .unwrap_or_else(|_| MISSING_INPUT_SENTINEL.to_string()),
                None => MISSING_INPUT_SENTINEL.to_string(),
            };
            match grouped
                .iter_mut()
                .find(|(node_id, _)| node_id == &connection.to_node)
            {
                Some((_, terms)) => terms.push(reference),
                None => grouped.push((connection.to_node.clone(), vec![reference])),
            }
        }
        for (node_id, mut terms) in grouped {
            let history = self.names[&node_id].clone();
            let value = match terms.len() {
                0 => MISSING_INPUT_SENTINEL.to_string(),
                1 => terms.remove(0),
                _ => format!("(+ {})", terms.join(" ")),
            };
            writes.push(format!("(write-history {history} {value})"));
        }
        writes
    }

    fn reference_expr_for_write(
        &mut self,
        connection: &'a PatchConnection,
    ) -> Result<String, String> {
        self.reference_expr(connection)
    }

    fn macro_param_list(&self) -> Vec<String> {
        let param_nodes = self.nodes_in_role_order(NodeRole::MacroParam);
        let mut by_channel: BTreeMap<usize, String> = BTreeMap::new();
        let mut max_channel = 0usize;
        for node in param_nodes {
            let channel = node_channel(node).max(1);
            max_channel = max_channel.max(channel);
            by_channel
                .entry(channel)
                .or_insert_with(|| self.names[&node.id].clone());
        }
        (1..=max_channel)
            .map(|channel| {
                by_channel
                    .get(&channel)
                    .cloned()
                    .unwrap_or_else(|| format!("input{channel}"))
            })
            .collect()
    }

    fn emit_macro_return(&mut self) -> Result<Option<String>, String> {
        let outs = self.nodes_in_role_order(NodeRole::Out);
        if outs.is_empty() {
            return Ok(None);
        }
        let mut by_channel: BTreeMap<usize, &PatchNode> = BTreeMap::new();
        let mut max_channel = 1usize;
        for out in outs {
            let channel = node_channel(out).max(1);
            max_channel = max_channel.max(channel);
            by_channel.entry(channel).or_insert(out);
        }
        let mut values = Vec::new();
        for channel in 1..=max_channel {
            let value = match by_channel.get(&channel) {
                Some(out) => self
                    .slot_value_expr(out.id.as_str(), 0)?
                    .unwrap_or_else(|| MISSING_INPUT_SENTINEL.to_string()),
                None => MISSING_INPUT_SENTINEL.to_string(),
            };
            values.push(value);
        }
        // Canonical macro out ids are `out`, `out2`, ... by channel.
        for (channel, out) in &by_channel {
            let canonical = if *channel == 1 {
                "out".to_string()
            } else {
                format!("out{channel}")
            };
            self.names.insert(out.id.clone(), canonical);
        }
        if values.len() == 1 {
            Ok(Some(values.remove(0)))
        } else {
            Ok(Some(format!("(tuple {})", values.join(" "))))
        }
    }

    fn emit_root_out_lines(&mut self) -> Result<Vec<String>, String> {
        let mut lines = Vec::new();
        for out in self.nodes_in_role_order(NodeRole::Out) {
            let name = self.names[&out.id].clone();
            let channel = node_channel(out).max(1);
            let value = self
                .slot_value_expr(out.id.as_str(), 0)?
                .unwrap_or_else(|| MISSING_INPUT_SENTINEL.to_string());
            let modulator = out_modulator_attr(out);
            let modulator_attr = modulator
                .map(|slot| format!(" @modulator {slot}"))
                .unwrap_or_default();
            lines.push(format!(
                "(out {value} {channel}{modulator_attr} @name {name})"
            ));
        }
        Ok(lines)
    }
}

fn macro_param_name(node: &PatchNode) -> String {
    if let Some(name) = label_attribute(&node.label, "@name") {
        return sanitize_binding(&name);
    }
    if let Some(output) = node.outputs.first().filter(|name| !name.is_empty()) {
        return sanitize_binding(output);
    }
    format!("input{}", node_channel(node).max(1))
}

/// Channel of an `in`/`out` node: the first numeric literal argument, falling
/// back to the label, then 1.
fn node_channel(node: &PatchNode) -> usize {
    let from_args = node.args.iter().find_map(|arg| match arg {
        ArgValue::Literal(value) => value.parse::<f64>().ok().map(|value| value as usize),
        _ => None,
    });
    if let Some(channel) = from_args {
        return channel;
    }
    label_positional_numbers(&node.label)
        .first()
        .copied()
        .unwrap_or(1)
}

fn out_binding_base(node: &PatchNode) -> String {
    if let Some(name) = label_attribute(&node.label, "@name") {
        return sanitize_binding(&name);
    }
    let label = node.label.trim();
    let is_plain_name =
        !label.is_empty() && label != "out" && !label.starts_with("out ") && !label.contains(' ');
    if is_plain_name {
        return sanitize_binding(label);
    }
    // Interaction-created outs must not leak their `created-N` interaction id
    // into a persistent `@name` (see `binding_base_for_node`).
    if is_interaction_created_id(&node.id) {
        return "audio".to_string();
    }
    // The editable display label omits `@name`, so a dragged/edited out keeps
    // its identity through the node id (which the parser derived from @name).
    sanitize_binding(&node.id)
}

/// True for node ids minted by the interaction layer (`allocate_created_node`).
/// These are session-scoped identities and must never become binding names in
/// generated source: a reload would parse them back as node ids, and the next
/// session's `created-N` counter would collide with them, visually splicing
/// existing cables into freshly created nodes and corrupting regeneration.
fn is_interaction_created_id(id: &str) -> bool {
    id.strip_prefix("created-")
        .is_some_and(|digits| !digits.is_empty() && digits.chars().all(|ch| ch.is_ascii_digit()))
}

/// Binding base for a single-output node: source-derived ids keep their name;
/// interaction-created ids get a deterministic, op-derived name instead.
fn binding_base_for_node(node: &PatchNode) -> String {
    // A modulatable param has to be emitted as a BARE top-level `(param X …)`,
    // because `(mod X)` resolves only against that form — a def-wrapped
    // `(def value (param embouchure …))` is invisible to it. So its binding
    // must be the param name itself; `emit_role_lines` then drops the wrapper.
    // Params are named first, so they win the name before anything else can
    // claim it. The rename is invisible to the editor: the graph payload keys
    // nodes by model id, and the source is only a build artifact.
    //
    // A grouped param's canonical identity carries the group dot
    // (`fm.harmonicity`), which is exactly the spelling the accessor and every
    // other reference emit — so the dot survives sanitizing here. Folding it to
    // `fm-harmonicity` made the binding stop matching the declared name, the
    // wrapper stayed, and `(mod fm.harmonicity)` lost its declaration.
    if node.kind == NodeKind::Param
        && let Some(param) = node.param.as_ref()
        && param.modulatable
    {
        let name = sanitize_param_identity_binding(&param.name);
        if !name.is_empty() {
            return name;
        }
    }
    if !is_interaction_created_id(&node.id) {
        return sanitize_binding(&node.id);
    }
    match node.kind {
        NodeKind::Param => node
            .param
            .as_ref()
            .map(|param| sanitize_binding(&param.name))
            .filter(|name| !name.is_empty())
            .unwrap_or_else(|| "param-value".to_string()),
        NodeKind::In => label_attribute(&node.label, "@name")
            .map(|name| sanitize_binding(&name))
            .unwrap_or_else(|| format!("in{}", node_channel(node))),
        NodeKind::Constant => "value".to_string(),
        _ => {
            if node.op.trim().is_empty() {
                "node".to_string()
            } else {
                sanitize_binding(&node.op)
            }
        }
    }
}

/// Dead-code omission set: value-role nodes that (a) cannot reach any `out`
/// node through the connection graph and (b) would emit an incomplete call —
/// empty/unknown op, a missing-input gap, or an unfilled macro arity — plus,
/// transitively, dead value nodes that reference an omitted node. Dead nodes
/// with complete calls are kept (emitted as unused defs) so they survive
/// save + reload; live nodes are never omitted, so genuinely broken live
/// patches still surface the missing-input sentinel / compile diagnostics.
///
/// The "keep complete dead nodes" rule applies to user-authored nodes only:
/// projector-synthesized `param~` accessors that lost their consumer are
/// dropped outright (§4.2b) so deleting `(* a gain~)` never leaves a
/// standalone `(def mod0 (mod gain))` behind.
fn omitted_dead_node_ids(
    patch: &Patch,
    roles: &HashMap<&str, NodeRole>,
    inbound: &BTreeMap<(&str, usize), Vec<&PatchConnection>>,
) -> HashSet<String> {
    let live = live_node_ids(patch, roles);
    let orphaned_inline_mods = orphaned_inline_mod_node_ids(patch);
    let mut omitted: HashSet<String> = patch
        .nodes
        .iter()
        .filter(|node| roles.get(node.id.as_str()) == Some(&NodeRole::Value))
        .filter(|node| !live.contains(node.id.as_str()))
        .filter(|node| {
            orphaned_inline_mods.contains(&node.id) || node_call_is_incomplete(patch, inbound, node)
        })
        .map(|node| node.id.clone())
        .collect();
    // Propagate: a dead node whose input references an omitted node cannot be
    // emitted either (its reference would have no binding).
    loop {
        let mut grew = false;
        for node in &patch.nodes {
            if roles.get(node.id.as_str()) != Some(&NodeRole::Value)
                || live.contains(node.id.as_str())
                || omitted.contains(node.id.as_str())
            {
                continue;
            }
            // Any omitted term poisons the whole slot: a summed inlet whose
            // `(+ …)` names a binding that was never emitted is just as broken.
            let references_omitted = inbound
                .range((node.id.as_str(), 0)..=(node.id.as_str(), usize::MAX))
                .flat_map(|(_, connections)| connections)
                .any(|connection| omitted.contains(&connection.from_node));
            if references_omitted {
                omitted.insert(node.id.clone());
                grew = true;
            }
        }
        if !grew {
            break;
        }
    }
    omitted
}

/// Node ids from which some `out` node is reachable (reverse reachability over
/// all connections, feedback included so history writers stay live when the
/// history is read on a live path).
fn live_node_ids(patch: &Patch, roles: &HashMap<&str, NodeRole>) -> HashSet<String> {
    let mut feeds: HashMap<&str, Vec<&str>> = HashMap::new();
    for connection in &patch.connections {
        feeds
            .entry(connection.to_node.as_str())
            .or_default()
            .push(connection.from_node.as_str());
    }
    let mut live: HashSet<String> = HashSet::new();
    let mut stack: Vec<&str> = patch
        .nodes
        .iter()
        .filter(|node| roles.get(node.id.as_str()) == Some(&NodeRole::Out))
        .map(|node| node.id.as_str())
        .collect();
    while let Some(node_id) = stack.pop() {
        if !live.insert(node_id.to_string()) {
            continue;
        }
        if let Some(sources) = feeds.get(node_id) {
            for source in sources {
                if !live.contains(*source) {
                    stack.push(source);
                }
            }
        }
    }
    live
}

/// Would emitting this node's call produce an incomplete form? Mirrors
/// `emit_call_expr`: an empty or diagnosed (unknown) op, a gap in front of a
/// filled slot (missing-input sentinel), or — for macro instances, whose
/// arity is fixed — any unfilled parameter slot.
/// Fixed parameter count for nodes that expand as a *macro*, whose call must
/// carry every argument: patch-local / library macro instances (arity from the
/// macro's own parameter list) and dgenlisp preamble defmacros such as `svf`
/// (arity from the bundled operator manifest — the same data that draws the
/// node's inlets). `None` for builtin operators, which tolerate trailing-slot
/// trimming.
fn fixed_macro_arity(patch: &Patch, node: &PatchNode) -> Option<usize> {
    if node.kind == NodeKind::MacroInstance {
        return Some(
            patch
                .macros
                .iter()
                .find(|macro_patch| macro_patch.name == node.op)
                .map(|macro_patch| macro_patch.params.len())
                .unwrap_or(node.args.len()),
        );
    }
    dgenlisp_preamble_macro_arities()
        .get(node.op.trim())
        .copied()
}

fn node_call_is_incomplete(
    patch: &Patch,
    inbound: &BTreeMap<(&str, usize), Vec<&PatchConnection>>,
    node: &PatchNode,
) -> bool {
    if node.op.trim().is_empty() || node.diagnostic.is_some() {
        return true;
    }
    let slot_filled = |idx: usize| {
        inbound.contains_key(&(node.id.as_str(), idx))
            || matches!(node.args.get(idx), Some(ArgValue::Literal(_)))
    };
    if let Some(arity) = fixed_macro_arity(patch, node) {
        return (0..arity).any(|idx| !slot_filled(idx));
    }
    let mut last_filled: Option<usize> = None;
    for idx in 0..node.args.len() {
        if slot_filled(idx) {
            last_filled = Some(idx);
        }
    }
    let Some(last_filled) = last_filled else {
        return false;
    };
    (0..last_filled).any(|idx| !slot_filled(idx))
}

fn out_modulator_attr(node: &PatchNode) -> Option<usize> {
    label_attribute(&node.label, "@modulator")
        .and_then(|value| value.parse::<f64>().ok())
        .map(|value| value as usize)
}

fn label_items(label: &str) -> Option<Vec<Expression>> {
    let source = format!("({})", normalize_editor_node_text(label.trim()));
    let tokens = Parser::new(source).parse().ok()?;
    let exprs = ASTParser::new(tokens).parse().ok()?;
    match exprs.into_iter().next() {
        Some(Expression::List(items)) => Some(items),
        _ => None,
    }
}

pub(super) fn label_attribute(label: &str, attribute: &str) -> Option<String> {
    let items = label_items(label)?;
    let values = attribute_value_items(&items, attribute)?;
    Some(
        values
            .iter()
            .map(|value| match value {
                Expression::Number(number) if *number == number.trunc() && number.abs() < 1e15 => {
                    format!("{number:.0}")
                }
                other => format_expression(other),
            })
            .collect::<Vec<_>>()
            .join(" "),
    )
}

fn label_positional_numbers(label: &str) -> Vec<usize> {
    let Some(items) = label_items(label) else {
        return Vec::new();
    };
    let mut numbers = Vec::new();
    let mut idx = 1;
    while idx < items.len() {
        if is_attribute_key(&items[idx]) {
            idx += attribute_span_len(&items, idx);
            continue;
        }
        if let Expression::Number(number) = &items[idx] {
            numbers.push(*number as usize);
        }
        idx += 1;
    }
    numbers
}

fn op_word(op: &str) -> Option<&'static str> {
    match op {
        "+" => Some("add"),
        "-" => Some("sub"),
        "*" => Some("mul"),
        "/" => Some("div"),
        "%" => Some("rem"),
        "<" => Some("lt"),
        ">" => Some("gt"),
        "<=" => Some("lte"),
        ">=" => Some("gte"),
        "=" | "==" => Some("eq"),
        "!=" => Some("neq"),
        _ => None,
    }
}

/// `sanitize_binding` for a param's canonical identity, which is `group.name`
/// since eseq-gg6e. The group separator is the one `.` a binding may keep: it
/// is part of the identity the DGenLisp param namespace resolves, not a
/// character to fold away. Each side is sanitized on its own.
fn sanitize_param_identity_binding(raw: &str) -> String {
    let sanitized = raw
        .split('.')
        .map(sanitize_binding)
        .filter(|segment| !segment.is_empty())
        .collect::<Vec<_>>();
    sanitized.join(".")
}

/// Deterministically map a model node id to a valid, compilable binding
/// symbol. Idempotent for names that are already valid.
pub(super) fn sanitize_binding(raw: &str) -> String {
    let mut segments = Vec::new();
    for segment in raw.split(['#', '~']) {
        if segment.is_empty() {
            continue;
        }
        let word = match op_word(segment) {
            Some(word) => word.to_string(),
            None => segment
                .chars()
                .map(|ch| {
                    if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                        ch
                    } else {
                        '-'
                    }
                })
                .collect::<String>(),
        };
        let word = word.trim_matches('-').to_string();
        if !word.is_empty() {
            segments.push(word);
        }
    }
    let mut joined = segments.join("-");
    while joined.contains("--") {
        joined = joined.replace("--", "-");
    }
    let joined = joined.trim_matches('-').to_string();
    let mut name = if joined.is_empty() {
        "node".to_string()
    } else {
        joined
    };
    if !name
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic())
    {
        name = format!("n{name}");
    }
    name
}
