use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::display::{node_autogenerated_size_for_ports, node_size};
use super::geometry::{patch_input_indices, patch_input_slot_counts, patch_output_counts};
use super::model::{CableSegmentInfo, Patch, PatchNode};
use super::state::{
    PatcherInteractionState, patch_with_created_macros, patch_with_interaction_state,
    source_connection_id,
};

const SIDECAR_VERSION: u32 = 1;
const NODE_PADDING: f32 = 1.0;

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
struct LayoutSidecar {
    version: u32,
    #[serde(default)]
    root: ScopeLayout,
    #[serde(default)]
    macros: BTreeMap<String, ScopeLayout>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
struct ScopeLayout {
    #[serde(default)]
    nodes: BTreeMap<String, NodePosition>,
    #[serde(default)]
    cables: BTreeMap<String, CableLayout>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
struct NodePosition {
    x: f32,
    y: f32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    width: Option<f32>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
struct CableLayout {
    segmented: bool,
    y: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SidecarStatus {
    Missing,
    Present,
}

pub(super) fn sidecar_path_for_source(source_path: &Path) -> PathBuf {
    if source_path.file_name().and_then(|name| name.to_str()) == Some("dsp.lisp") {
        source_path.with_file_name("dsp.layout.json")
    } else {
        let stem = source_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or("dsp");
        source_path.with_file_name(format!("{stem}.layout.json"))
    }
}

pub(super) fn apply_or_materialize(source_path: &Path, patch: &mut Patch) -> Result<(), String> {
    match load_sidecar(source_path) {
        Ok((SidecarStatus::Present, sidecar)) => {
            apply_sidecar(patch, &sidecar);
            save_patch_layout(source_path, patch)
        }
        Ok((SidecarStatus::Missing, _)) => save_patch_layout(source_path, patch),
        Err(error) => {
            eprintln!(
                "failed to load patcher layout sidecar for '{}': {error}",
                source_path.display()
            );
            save_patch_layout(source_path, patch)
        }
    }
}

pub(super) fn apply_or_materialize_excluding_macro_scopes(
    source_path: &Path,
    patch: &mut Patch,
    excluded_macros: &HashSet<String>,
) -> Result<(), String> {
    match load_sidecar(source_path) {
        Ok((SidecarStatus::Present, mut sidecar)) => {
            sidecar
                .macros
                .retain(|macro_name, _| !excluded_macros.contains(macro_name));
            apply_sidecar(patch, &sidecar);
            save_patch_layout(source_path, patch)
        }
        Ok((SidecarStatus::Missing, _)) => save_patch_layout(source_path, patch),
        Err(error) => {
            eprintln!(
                "failed to load patcher layout sidecar for '{}': {error}",
                source_path.display()
            );
            save_patch_layout(source_path, patch)
        }
    }
}

pub(super) fn save_current_layout(
    source_path: &Path,
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Result<(), String> {
    let patch = root_patch_with_interaction(root_patch, interaction_state);
    save_patch_layout(source_path, &patch)
}

pub(super) fn current_layout_json(
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Result<String, String> {
    let patch = root_patch_with_interaction(root_patch, interaction_state);
    serde_json::to_string_pretty(&sidecar_from_patch(&patch))
        .map(|json| format!("{json}\n"))
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))
}

pub(super) fn emitted_layout_json_with_node_map(
    emitted_patch: &mut Patch,
    previous_root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
    node_id_map: &HashMap<(String, String), String>,
) -> Result<String, String> {
    let visible = root_patch_with_interaction(previous_root_patch, interaction_state);
    overlay_visible_layout(emitted_patch, &visible, node_id_map);
    serde_json::to_string_pretty(&sidecar_from_patch(emitted_patch))
        .map(|json| format!("{json}\n"))
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))
}

#[cfg(any(test, feature = "patcher-test-support"))]
pub(super) fn load_apply_for_test(source_path: &Path, patch: &mut Patch) -> Result<(), String> {
    apply_or_materialize(source_path, patch)
}

fn load_sidecar(source_path: &Path) -> Result<(SidecarStatus, LayoutSidecar), String> {
    let path = sidecar_path_for_source(source_path);
    if !path.exists() {
        return Ok((SidecarStatus::Missing, LayoutSidecar::default()));
    }
    let source = fs::read_to_string(&path)
        .map_err(|error| format!("failed to read '{}': {error}", path.display()))?;
    let sidecar: LayoutSidecar = serde_json::from_str(&source)
        .map_err(|error| format!("failed to parse '{}': {error}", path.display()))?;
    if sidecar.version != SIDECAR_VERSION {
        return Err(format!(
            "unsupported layout sidecar version {} in '{}'",
            sidecar.version,
            path.display()
        ));
    }
    Ok((SidecarStatus::Present, sidecar))
}

fn save_patch_layout(source_path: &Path, patch: &Patch) -> Result<(), String> {
    let sidecar = sidecar_from_patch(patch);
    write_sidecar(source_path, &sidecar)
}

fn write_sidecar(source_path: &Path, sidecar: &LayoutSidecar) -> Result<(), String> {
    let path = sidecar_path_for_source(source_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create '{}': {error}", parent.display()))?;
    }
    let json = serde_json::to_string_pretty(sidecar)
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))?;
    let tmp_path = path.with_file_name(format!(
        ".{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("dsp.layout.json")
    ));
    fs::write(&tmp_path, format!("{json}\n"))
        .map_err(|error| format!("failed to write '{}': {error}", tmp_path.display()))?;
    fs::rename(&tmp_path, &path).map_err(|error| {
        let _ = fs::remove_file(&tmp_path);
        format!("failed to replace '{}': {error}", path.display())
    })
}

fn apply_sidecar(patch: &mut Patch, sidecar: &LayoutSidecar) {
    apply_scope_layout(patch, &sidecar.root);
    for macro_patch in &mut patch.macros {
        if let Some(scope) = sidecar.macros.get(&macro_patch.name) {
            apply_scope_layout(&mut macro_patch.patch, scope);
        }
    }
}

fn apply_scope_layout(patch: &mut Patch, scope: &ScopeLayout) {
    let mut fixed = HashSet::new();
    for node in &mut patch.nodes {
        if let Some(position) = scope
            .nodes
            .get(&node.id)
            .filter(|position| position.x.is_finite() && position.y.is_finite())
        {
            node.position = (position.x, position.y);
            node.width = position.width.filter(|width| width.is_finite());
            fixed.insert(node.id.clone());
        }
    }
    place_unmatched_nodes(patch, &fixed);

    let connection_endpoint_new = patch
        .connections
        .iter()
        .map(|connection| {
            (
                source_connection_id(connection),
                !fixed.contains(&connection.from_node) || !fixed.contains(&connection.to_node),
            )
        })
        .collect::<HashMap<_, _>>();
    for connection in &mut patch.connections {
        let id = source_connection_id(connection);
        if let Some(cable) = scope.cables.get(&id).filter(|cable| cable.y.is_finite()) {
            connection.segment = cable.segmented.then_some(CableSegmentInfo {
                is_segmented: true,
                segment_row: cable.y,
            });
        } else if !connection_endpoint_new.get(&id).copied().unwrap_or(false) {
            connection.segment = None;
        }
    }
}

fn place_unmatched_nodes(patch: &mut Patch, fixed: &HashSet<String>) {
    let mut occupied = patch
        .nodes
        .iter()
        .filter(|node| fixed.contains(&node.id))
        .map(node_rect)
        .collect::<Vec<_>>();
    for node in &mut patch.nodes {
        if fixed.contains(&node.id) {
            continue;
        }
        let (_, height) = node_size(node);
        while occupied
            .iter()
            .any(|rect| rects_overlap(node_rect(node), *rect))
        {
            node.position.1 += height + NODE_PADDING;
        }
        occupied.push(node_rect(node));
    }
}

fn sidecar_from_patch(patch: &Patch) -> LayoutSidecar {
    let mut macros = BTreeMap::new();
    for macro_patch in &patch.macros {
        macros.insert(
            macro_patch.name.clone(),
            scope_layout_from_patch(&macro_patch.patch),
        );
    }
    LayoutSidecar {
        version: SIDECAR_VERSION,
        root: scope_layout_from_patch(patch),
        macros,
    }
}

fn scope_layout_from_patch(patch: &Patch) -> ScopeLayout {
    let input_indices = patch_input_indices(patch);
    let input_slot_counts = patch_input_slot_counts(patch, &input_indices);
    let output_counts = patch_output_counts(patch);
    let nodes = patch
        .nodes
        .iter()
        .filter(|node| node.position.0.is_finite() && node.position.1.is_finite())
        .map(|node| {
            let (autogenerated_width, _) = node_autogenerated_size_for_ports(
                node,
                input_slot_counts.get(&node.id).copied().unwrap_or(0),
                output_counts.get(&node.id).copied().unwrap_or(0),
            );
            (
                node.id.clone(),
                NodePosition {
                    x: node.position.0,
                    y: node.position.1,
                    width: node
                        .width
                        .filter(|width| width.is_finite() && *width > autogenerated_width),
                },
            )
        })
        .collect();
    let cables = patch
        .connections
        .iter()
        .filter_map(|connection| {
            let segment = connection.segment?;
            (segment.is_segmented && segment.segment_row.is_finite()).then(|| {
                (
                    source_connection_id(connection),
                    CableLayout {
                        segmented: true,
                        y: segment.segment_row,
                    },
                )
            })
        })
        .collect();
    ScopeLayout { nodes, cables }
}

fn root_patch_with_interaction(
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Patch {
    let mut root = patch_with_interaction_state(root_patch.clone(), interaction_state, "root");
    let with_created_macros = patch_with_created_macros(root_patch.clone(), interaction_state);
    root.macros = with_created_macros
        .macros
        .into_iter()
        .map(|macro_patch| {
            let view_key = format!("macro:{}", macro_patch.name);
            let mut patch =
                patch_with_interaction_state(macro_patch.patch, interaction_state, &view_key);
            patch.macros = root.macros.clone();
            super::model::MacroPatch {
                name: macro_patch.name,
                params: macro_patch.params,
                outputs: macro_patch.outputs,
                patch,
            }
        })
        .collect();
    root
}

fn overlay_visible_layout(
    emitted: &mut Patch,
    visible: &Patch,
    node_id_map: &HashMap<(String, String), String>,
) {
    overlay_scope_visible_layout(emitted, visible, "root", node_id_map);
    let visible_macros = visible
        .macros
        .iter()
        .map(|macro_patch| (macro_patch.name.as_str(), &macro_patch.patch))
        .collect::<HashMap<_, _>>();
    for macro_patch in &mut emitted.macros {
        if let Some(visible_patch) = visible_macros.get(macro_patch.name.as_str()) {
            let view_key = format!("macro:{}", macro_patch.name);
            overlay_scope_visible_layout(
                &mut macro_patch.patch,
                visible_patch,
                &view_key,
                node_id_map,
            );
        }
    }
}

fn overlay_scope_visible_layout(
    emitted: &mut Patch,
    visible: &Patch,
    view_key: &str,
    node_id_map: &HashMap<(String, String), String>,
) {
    let live_node_ids = emitted
        .nodes
        .iter()
        .map(|node| node.id.clone())
        .collect::<HashSet<_>>();
    let layouts = visible
        .nodes
        .iter()
        .filter_map(|node| {
            let emitted_id = mapped_node_id(view_key, &node.id, node_id_map);
            live_node_ids
                .contains(emitted_id.as_str())
                .then_some((emitted_id, (node.position, node.width)))
        })
        .collect::<HashMap<_, _>>();
    for node in &mut emitted.nodes {
        if let Some((position, width)) = layouts.get(&node.id) {
            node.position = *position;
            node.width = *width;
        }
    }

    let visible_segments = visible
        .connections
        .iter()
        .filter_map(|connection| {
            let from_node = mapped_node_id(view_key, &connection.from_node, node_id_map);
            let to_node = mapped_node_id(view_key, &connection.to_node, node_id_map);
            if !live_node_ids.contains(&from_node) || !live_node_ids.contains(&to_node) {
                return None;
            }
            let mut mapped = connection.clone();
            mapped.from_node = from_node;
            mapped.to_node = to_node;
            Some((source_connection_id(&mapped), connection.segment))
        })
        .collect::<HashMap<_, _>>();
    for connection in &mut emitted.connections {
        let id = source_connection_id(connection);
        if let Some(segment) = visible_segments.get(&id) {
            connection.segment = *segment;
        }
    }
}

fn mapped_node_id(
    view_key: &str,
    node_id: &str,
    node_id_map: &HashMap<(String, String), String>,
) -> String {
    node_id_map
        .get(&(view_key.to_string(), node_id.to_string()))
        .cloned()
        .unwrap_or_else(|| node_id.to_string())
}

fn node_rect(node: &PatchNode) -> (f32, f32, f32, f32) {
    let (width, height) = node_size(node);
    (
        node.position.0,
        node.position.1,
        node.position.0 + width + NODE_PADDING,
        node.position.1 + height + NODE_PADDING,
    )
}

fn rects_overlap(a: (f32, f32, f32, f32), b: (f32, f32, f32, f32)) -> bool {
    a.0 < b.2 && a.2 > b.0 && a.1 < b.3 && a.3 > b.1
}
