use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::display::{node_autogenerated_size_for_ports, node_display_input_slots, node_size};
use super::geometry::{patch_input_indices, patch_input_slot_counts, patch_output_counts};
use super::lisp::parse_editor_node_text;
use super::model::{
    CableSegmentInfo, InputPresentation, MacroOrigin, Patch, PatchNode,
    connection_touches_hidden_inline_node, hidden_inline_node_ids, refresh_patch_inline_inputs,
};
use super::state::{
    PatcherInteractionState, PatcherNodeOrigin, active_patcher_view_key, patch_with_created_macros,
    patch_with_interaction_state, source_connection_id,
};

const SIDECAR_VERSION: u32 = 2;
/// Version-1 sidecars predate the `authored` flag. They were auto-materialized
/// on patcher open, so their presence does not mean the item was patch-authored;
/// they load fine but never count as authored.
const SIDECAR_MIN_SUPPORTED_VERSION: u32 = 1;
const NODE_PADDING: f32 = 1.0;

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
struct LayoutSidecar {
    version: u32,
    /// True when this layout was produced by a patch-editor save. Only
    /// authored sidecars route the item back into the patch editor.
    #[serde(default)]
    authored: bool,
    #[serde(default)]
    root: ScopeLayout,
    #[serde(default)]
    macros: BTreeMap<String, ScopeLayout>,
}

fn sidecar_version_supported(version: u32) -> bool {
    (SIDECAR_MIN_SUPPORTED_VERSION..=SIDECAR_VERSION).contains(&version)
}

/// Whether the layout sidecar next to `source_path` marks the item as
/// patch-authored (version >= 2 with `authored: true`).
pub(super) fn sidecar_is_authored(source_path: &Path) -> bool {
    let path = sidecar_path_for_source(source_path);
    let Ok(source) = fs::read_to_string(&path) else {
        return false;
    };
    let Ok(sidecar) = serde_json::from_str::<LayoutSidecar>(&source) else {
        return false;
    };
    sidecar.version >= 2 && sidecar.authored
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
struct ScopeLayout {
    #[serde(default)]
    nodes: BTreeMap<String, NodePosition>,
    #[serde(default)]
    cables: BTreeMap<String, CableLayout>,
    #[serde(
        default,
        rename = "inputPresentation",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    input_presentation: BTreeMap<String, InputPresentation>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
struct NodePosition {
    x: f32,
    y: f32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    width: Option<f32>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
struct CableLayout {
    segmented: bool,
    y: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SidecarStatus {
    Missing,
    Present,
}

pub(super) fn sidecar_path_for_source(source_path: &Path) -> PathBuf {
    if source_path.file_name().and_then(|name| name.to_str()) == Some("dsp.lisp") {
        source_path.with_file_name("dsp.layout.json")
    } else {
        let stem = source_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or("dsp");
        source_path.with_file_name(format!("{stem}.layout.json"))
    }
}

pub(super) fn apply_or_materialize(source_path: &Path, patch: &mut Patch) -> Result<(), String> {
    // Opening a patch never writes the sidecar; layout is materialized
    // in-memory only and persisted on explicit save. (A write here used to
    // stamp every opened item as "has layout", polluting the patch-vs-code
    // editor decision — see docs/patch-vs-code-editor-spec.md §3.5.)
    match load_sidecar(source_path) {
        Ok((SidecarStatus::Present, sidecar)) => {
            apply_sidecar(patch, &sidecar, false);
            Ok(())
        }
        Ok((SidecarStatus::Missing, _)) => {
            log_layout_auto_materialize(source_path, "missing-sidecar", patch);
            Ok(())
        }
        Err(error) => {
            eprintln!(
                "failed to load patcher layout sidecar for '{}': {error}",
                source_path.display()
            );
            log_layout_auto_materialize(source_path, "invalid-sidecar", patch);
            Ok(())
        }
    }
}

pub(super) fn apply_or_materialize_excluding_macro_scopes(
    source_path: &Path,
    patch: &mut Patch,
    excluded_macros: &HashSet<String>,
) -> Result<(), String> {
    // Unlike plain opens, this runs as part of an agentic macro edit that has
    // already rewritten dsp.lisp on disk, so persisting the rebuilt layout here
    // is an edit-flow write, not an open-time materialization: without it a
    // stale sidecar scope would poison every later load of the edited macro.
    match load_sidecar(source_path) {
        Ok((SidecarStatus::Present, mut sidecar)) => {
            sidecar
                .macros
                .retain(|macro_name, _| !excluded_macros.contains(macro_name));
            apply_sidecar(patch, &sidecar, false);
            save_patch_layout(source_path, patch, "rematerialize-excluded-macro-scopes")
        }
        Ok((SidecarStatus::Missing, _)) => {
            log_layout_auto_materialize(source_path, "missing-sidecar-excluding-macros", patch);
            save_patch_layout(
                source_path,
                patch,
                "materialize-missing-sidecar-excluding-macros",
            )
        }
        Err(error) => {
            eprintln!(
                "failed to load patcher layout sidecar for '{}': {error}",
                source_path.display()
            );
            log_layout_auto_materialize(source_path, "invalid-sidecar-excluding-macros", patch);
            save_patch_layout(
                source_path,
                patch,
                "materialize-invalid-sidecar-excluding-macros",
            )
        }
    }
}

pub(super) fn apply_layout_file(layout_path: &Path, patch: &mut Patch) -> Result<(), String> {
    if !layout_path.exists() {
        return Ok(());
    }
    let source = fs::read_to_string(layout_path)
        .map_err(|error| format!("failed to read '{}': {error}", layout_path.display()))?;
    apply_layout_json(&source, &layout_path.display().to_string(), patch)
}

pub(super) fn apply_layout_json(
    source: &str,
    source_label: &str,
    patch: &mut Patch,
) -> Result<(), String> {
    let sidecar: LayoutSidecar = serde_json::from_str(&source)
        .map_err(|error| format!("failed to parse '{source_label}': {error}"))?;
    if !sidecar_version_supported(sidecar.version) {
        return Err(format!(
            "unsupported layout sidecar version {} in '{}'",
            sidecar.version, source_label
        ));
    }
    apply_sidecar(patch, &sidecar, false);
    Ok(())
}

pub(super) fn save_current_layout(
    source_path: &Path,
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Result<(), String> {
    let patch = root_patch_with_interaction(root_patch, interaction_state);
    save_patch_layout(source_path, &patch, "explicit-layout-save")
}

pub(super) fn current_layout_json(
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Result<String, String> {
    let patch = root_patch_with_interaction(root_patch, interaction_state);
    serde_json::to_string_pretty(&sidecar_from_patch(&patch))
        .map(|json| format!("{json}\n"))
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))
}

pub(super) fn emitted_layout_json_with_node_map(
    emitted_patch: &mut Patch,
    previous_root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
    node_id_map: &HashMap<(String, String), String>,
) -> Result<String, String> {
    let visible = root_patch_with_interaction(previous_root_patch, interaction_state);
    overlay_visible_layout(
        emitted_patch,
        previous_root_patch,
        &visible,
        interaction_state,
        node_id_map,
    );
    serde_json::to_string_pretty(&sidecar_from_patch(emitted_patch))
        .map(|json| format!("{json}\n"))
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))
}

#[cfg(any(test, feature = "patcher-test-support"))]
pub(super) fn load_apply_for_test(source_path: &Path, patch: &mut Patch) -> Result<(), String> {
    apply_or_materialize(source_path, patch)
}

fn load_sidecar(source_path: &Path) -> Result<(SidecarStatus, LayoutSidecar), String> {
    let path = sidecar_path_for_source(source_path);
    if !path.exists() {
        return Ok((SidecarStatus::Missing, LayoutSidecar::default()));
    }
    let source = fs::read_to_string(&path)
        .map_err(|error| format!("failed to read '{}': {error}", path.display()))?;
    let sidecar: LayoutSidecar = serde_json::from_str(&source)
        .map_err(|error| format!("failed to parse '{}': {error}", path.display()))?;
    if !sidecar_version_supported(sidecar.version) {
        return Err(format!(
            "unsupported layout sidecar version {} in '{}'",
            sidecar.version,
            path.display()
        ));
    }
    Ok((SidecarStatus::Present, sidecar))
}

fn save_patch_layout(source_path: &Path, patch: &Patch, reason: &str) -> Result<(), String> {
    log_layout_write(source_path, reason, patch);
    let sidecar = sidecar_from_patch(patch);
    write_sidecar(source_path, &sidecar)
}

fn log_layout_auto_materialize(source_path: &Path, reason: &str, patch: &Patch) {
    let (node_count, macro_count) = patch_layout_counts(patch);
    eprintln!(
        "[patcher layout auto-materialize] reason={reason} path={} sidecar={} nodes={} macros={}",
        source_path.display(),
        sidecar_path_for_source(source_path).display(),
        node_count,
        macro_count
    );
}

fn log_layout_write(source_path: &Path, reason: &str, patch: &Patch) {
    let (node_count, macro_count) = patch_layout_counts(patch);
    eprintln!(
        "[patcher layout write] reason={reason} path={} sidecar={} nodes={} macros={}",
        source_path.display(),
        sidecar_path_for_source(source_path).display(),
        node_count,
        macro_count
    );
}

fn patch_layout_counts(patch: &Patch) -> (usize, usize) {
    let node_count = patch.nodes.len()
        + patch
            .macros
            .iter()
            .map(|macro_patch| macro_patch.patch.nodes.len())
            .sum::<usize>();
    (node_count, patch.macros.len())
}

fn write_sidecar(source_path: &Path, sidecar: &LayoutSidecar) -> Result<(), String> {
    let path = sidecar_path_for_source(source_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create '{}': {error}", parent.display()))?;
    }
    let json = serde_json::to_string_pretty(sidecar)
        .map_err(|error| format!("failed to serialize layout sidecar: {error}"))?;
    let tmp_path = path.with_file_name(format!(
        ".{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("dsp.layout.json")
    ));
    fs::write(&tmp_path, format!("{json}\n"))
        .map_err(|error| format!("failed to write '{}': {error}", tmp_path.display()))?;
    fs::rename(&tmp_path, &path).map_err(|error| {
        let _ = fs::remove_file(&tmp_path);
        format!("failed to replace '{}': {error}", path.display())
    })
}

fn apply_sidecar(patch: &mut Patch, sidecar: &LayoutSidecar, place_unmatched: bool) {
    apply_scope_layout(patch, &sidecar.root, place_unmatched);
    for macro_patch in &mut patch.macros {
        if let Some(scope) = sidecar.macros.get(&macro_patch.name) {
            apply_scope_layout(&mut macro_patch.patch, scope, place_unmatched);
        }
    }
}

fn apply_scope_layout(patch: &mut Patch, scope: &ScopeLayout, place_unmatched: bool) {
    for connection in &mut patch.connections {
        let key = destination_input_key(&connection.to_node, connection.to_input);
        if let Some(presentation) = scope.input_presentation.get(&key).copied() {
            connection.presentation = presentation;
            connection.presentation_override = Some(presentation);
        }
    }
    refresh_patch_inline_inputs(patch);

    let mut fixed = HashSet::new();
    for node in &mut patch.nodes {
        if let Some(position) = scope
            .nodes
            .get(&node.id)
            .filter(|position| position.x.is_finite() && position.y.is_finite())
        {
            node.position = (position.x, position.y);
            node.width = position.width.filter(|width| width.is_finite());
            fixed.insert(node.id.clone());
        }
    }
    if place_unmatched {
        place_unmatched_nodes(patch, &fixed, "apply-sidecar-place-unmatched");
    }

    let connection_endpoint_new = patch
        .connections
        .iter()
        .map(|connection| {
            (
                source_connection_id(connection),
                !fixed.contains(&connection.from_node) || !fixed.contains(&connection.to_node),
            )
        })
        .collect::<HashMap<_, _>>();
    for connection in &mut patch.connections {
        let id = source_connection_id(connection);
        if let Some(cable) = scope.cables.get(&id).filter(|cable| cable.y.is_finite()) {
            connection.segment = cable.segmented.then_some(CableSegmentInfo {
                is_segmented: true,
                segment_row: cable.y,
            });
        } else if !connection_endpoint_new.get(&id).copied().unwrap_or(false) {
            connection.segment = None;
        }
    }
}

fn place_unmatched_nodes(patch: &mut Patch, fixed: &HashSet<String>, reason: &str) {
    let hidden_node_ids = hidden_inline_node_ids(patch);
    let mut occupied = patch
        .nodes
        .iter()
        .filter(|node| fixed.contains(&node.id) && !hidden_node_ids.contains(&node.id))
        .map(node_rect)
        .collect::<Vec<_>>();
    for node in &mut patch.nodes {
        if fixed.contains(&node.id) || hidden_node_ids.contains(&node.id) {
            continue;
        }
        let (_, height) = node_size(node);
        let original_position = node.position;
        while occupied
            .iter()
            .any(|rect| rects_overlap(node_rect(node), *rect))
        {
            node.position.1 += height + NODE_PADDING;
        }
        if node.position != original_position {
            eprintln!(
                "[patcher layout auto-place] reason={reason} node={} old=({:.3},{:.3}) new=({:.3},{:.3}) fixed_nodes={}",
                node.id,
                original_position.0,
                original_position.1,
                node.position.0,
                node.position.1,
                fixed.len()
            );
        }
        occupied.push(node_rect(node));
    }
}

fn sidecar_from_patch(patch: &Patch) -> LayoutSidecar {
    let mut macros = BTreeMap::new();
    for macro_patch in &patch.macros {
        if matches!(macro_patch.origin, MacroOrigin::Library { .. }) {
            continue;
        }
        macros.insert(
            macro_patch.name.clone(),
            scope_layout_from_patch(&macro_patch.patch),
        );
    }
    LayoutSidecar {
        version: SIDECAR_VERSION,
        // Sidecars are only serialized from live patch-editor state, so any
        // written layout marks the item as patch-authored.
        authored: true,
        root: scope_layout_from_patch(patch),
        macros,
    }
}

fn scope_layout_from_patch(patch: &Patch) -> ScopeLayout {
    let input_indices = patch_input_indices(patch);
    let input_slot_counts = patch_input_slot_counts(patch, &input_indices);
    let output_counts = patch_output_counts(patch);
    let hidden_node_ids = hidden_inline_node_ids(patch);
    let nodes = patch
        .nodes
        .iter()
        .filter(|node| !hidden_node_ids.contains(&node.id))
        .filter(|node| node.position.0.is_finite() && node.position.1.is_finite())
        .map(|node| {
            let (autogenerated_width, _) = node_autogenerated_size_for_ports(
                node,
                input_slot_counts.get(&node.id).copied().unwrap_or(0),
                output_counts.get(&node.id).copied().unwrap_or(0),
            );
            (
                node.id.clone(),
                NodePosition {
                    x: node.position.0,
                    y: node.position.1,
                    width: node
                        .width
                        .filter(|width| width.is_finite() && *width > autogenerated_width),
                },
            )
        })
        .collect();
    let cables = patch
        .connections
        .iter()
        .filter(|connection| !connection_touches_hidden_inline_node(connection, &hidden_node_ids))
        .filter_map(|connection| {
            let segment = connection.segment?;
            (segment.is_segmented && segment.segment_row.is_finite()).then(|| {
                (
                    source_connection_id(connection),
                    CableLayout {
                        segmented: true,
                        y: segment.segment_row,
                    },
                )
            })
        })
        .collect();
    let input_presentation = patch
        .connections
        .iter()
        .filter_map(|connection| {
            connection.presentation_override.map(|presentation| {
                (
                    destination_input_key(&connection.to_node, connection.to_input),
                    presentation,
                )
            })
        })
        .collect();
    ScopeLayout {
        nodes,
        cables,
        input_presentation,
    }
}

fn root_patch_with_interaction(
    root_patch: &Patch,
    interaction_state: &PatcherInteractionState,
) -> Patch {
    let mut root = patch_with_interaction_state(root_patch.clone(), interaction_state, "root");
    let with_created_macros = patch_with_created_macros(root_patch.clone(), interaction_state);
    root.macros = with_created_macros
        .macros
        .into_iter()
        .map(|macro_patch| {
            let view_key = format!("macro:{}", macro_patch.name);
            let mut patch =
                patch_with_interaction_state(macro_patch.patch, interaction_state, &view_key);
            patch.macros = root.macros.clone();
            super::model::MacroPatch {
                name: macro_patch.name,
                params: macro_patch.params,
                outputs: macro_patch.outputs,
                patch,
                origin: macro_patch.origin,
            }
        })
        .collect();
    root
}

fn overlay_visible_layout(
    emitted: &mut Patch,
    original: &Patch,
    visible: &Patch,
    interaction_state: &PatcherInteractionState,
    node_id_map: &HashMap<(String, String), String>,
) {
    overlay_scope_visible_layout(
        emitted,
        original,
        visible,
        "root",
        interaction_state,
        node_id_map,
    );
    let original_macros = original
        .macros
        .iter()
        .map(|macro_patch| (macro_patch.name.as_str(), &macro_patch.patch))
        .collect::<HashMap<_, _>>();
    let visible_macros = visible
        .macros
        .iter()
        .map(|macro_patch| (macro_patch.name.as_str(), &macro_patch.patch))
        .collect::<HashMap<_, _>>();
    for macro_patch in &mut emitted.macros {
        if let (Some(original_patch), Some(visible_patch)) = (
            original_macros.get(macro_patch.name.as_str()),
            visible_macros.get(macro_patch.name.as_str()),
        ) {
            let view_key = format!("macro:{}", macro_patch.name);
            overlay_scope_visible_layout(
                &mut macro_patch.patch,
                original_patch,
                visible_patch,
                &view_key,
                interaction_state,
                node_id_map,
            );
        }
    }
}

fn overlay_scope_visible_layout(
    emitted: &mut Patch,
    original: &Patch,
    visible: &Patch,
    view_key: &str,
    interaction_state: &PatcherInteractionState,
    node_id_map: &HashMap<(String, String), String>,
) {
    let live_node_ids = emitted
        .nodes
        .iter()
        .map(|node| node.id.clone())
        .collect::<HashSet<_>>();
    let layouts = visible
        .nodes
        .iter()
        .filter_map(|node| {
            let emitted_id = mapped_node_id(view_key, &node.id, node_id_map);
            live_node_ids
                .contains(emitted_id.as_str())
                .then_some((emitted_id, (node.position, node.width)))
        })
        .collect::<HashMap<_, _>>();
    for node in &mut emitted.nodes {
        if let Some((position, width)) = layouts.get(&node.id) {
            node.position = *position;
            node.width = *width;
        }
    }

    let visible_segments = visible
        .connections
        .iter()
        .filter_map(|connection| {
            let from_node = mapped_node_id(view_key, &connection.from_node, node_id_map);
            let to_node = mapped_node_id(view_key, &connection.to_node, node_id_map);
            if !live_node_ids.contains(&from_node) || !live_node_ids.contains(&to_node) {
                return None;
            }
            let mut mapped = connection.clone();
            mapped.from_node = from_node;
            mapped.to_node = to_node;
            Some((source_connection_id(&mapped), connection.segment))
        })
        .collect::<HashMap<_, _>>();
    for connection in &mut emitted.connections {
        let id = source_connection_id(connection);
        if let Some(segment) = visible_segments.get(&id) {
            connection.segment = *segment;
        }
    }
    let visible_presentations = visible
        .connections
        .iter()
        .filter_map(|connection| {
            let to_node = mapped_node_id(view_key, &connection.to_node, node_id_map);
            live_node_ids.contains(&to_node).then_some((
                destination_input_key(&to_node, connection.to_input),
                connection.presentation_override,
            ))
        })
        .collect::<HashMap<_, _>>();
    for connection in &mut emitted.connections {
        let key = destination_input_key(&connection.to_node, connection.to_input);
        if let Some(presentation) = visible_presentations.get(&key).and_then(|p| *p) {
            connection.presentation = presentation;
            connection.presentation_override = Some(presentation);
        }
    }
    apply_editor_text_presentation_overrides(
        emitted,
        original,
        view_key,
        interaction_state,
        node_id_map,
        &live_node_ids,
    );
    refresh_patch_inline_inputs(emitted);
}

fn apply_editor_text_presentation_overrides(
    emitted: &mut Patch,
    original: &Patch,
    view_key: &str,
    interaction_state: &PatcherInteractionState,
    node_id_map: &HashMap<(String, String), String>,
    live_node_ids: &HashSet<String>,
) {
    for edit in interaction_state
        .edit_state
        .nodes
        .values()
        .filter(|edit| edit.view_key == view_key)
    {
        let original_node_id = match &edit.origin {
            PatcherNodeOrigin::Source { source_node_id } => source_node_id.as_str(),
            PatcherNodeOrigin::Created { .. } => edit.id.as_str(),
        };
        apply_editor_text_presentation_override(
            emitted,
            original,
            view_key,
            &edit.id,
            original_node_id,
            &edit.text,
            node_id_map,
            live_node_ids,
        );
    }

    let active_view_key = active_patcher_view_key(interaction_state);
    if active_view_key == view_key
        && let Some(edit) = interaction_state.text_edit.as_ref()
    {
        apply_editor_text_presentation_override(
            emitted,
            original,
            view_key,
            &edit.node_id,
            &edit.node_id,
            &edit.text,
            node_id_map,
            live_node_ids,
        );
    }
}

fn apply_editor_text_presentation_override(
    emitted: &mut Patch,
    original: &Patch,
    view_key: &str,
    visible_node_id: &str,
    original_node_id: &str,
    text: &str,
    node_id_map: &HashMap<(String, String), String>,
    live_node_ids: &HashSet<String>,
) {
    let emitted_node_id = mapped_node_id(view_key, visible_node_id, node_id_map);
    if !live_node_ids.contains(&emitted_node_id) {
        return;
    }
    let Ok((_op, tokens)) = parse_editor_node_text(text.trim()) else {
        return;
    };
    if tokens.is_empty() {
        return;
    }

    let original_node = original
        .nodes
        .iter()
        .find(|node| node.id == original_node_id);
    let input_slots = original_node
        .and_then(|node| editor_display_input_slots(node, tokens.len()))
        .unwrap_or_else(|| fallback_editor_input_slots(tokens.len()));

    for (token, input_index) in tokens.iter().zip(input_slots) {
        let Some(presentation) = input_presentation_for_editor_token(token) else {
            continue;
        };
        if let Some(connection) = emitted.connections.iter_mut().find(|connection| {
            connection.to_node == emitted_node_id && connection.to_input == input_index
        }) {
            connection.presentation = presentation;
            connection.presentation_override = Some(presentation);
        }
    }
}

fn editor_display_input_slots(node: &PatchNode, token_count: usize) -> Option<Vec<usize>> {
    let slots = node_display_input_slots(node);
    (slots.len() == token_count).then_some(slots)
}

fn fallback_editor_input_slots(token_count: usize) -> Vec<usize> {
    (1..=token_count).collect()
}

fn input_presentation_for_editor_token(token: &str) -> Option<InputPresentation> {
    if token.strip_suffix('~').is_some_and(is_inline_symbol_name) {
        return Some(InputPresentation::InlineModParam);
    }
    is_inline_symbol_name(token).then_some(InputPresentation::InlineRawParam)
}

fn is_inline_symbol_name(token: &str) -> bool {
    let mut chars = token.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic()
        || matches!(first, '_' | '-' | '+' | '*' | '/' | '<' | '>' | '='))
    {
        return false;
    }
    chars.all(|ch| {
        ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '+' | '*' | '/' | '<' | '>' | '=')
    })
}

fn mapped_node_id(
    view_key: &str,
    node_id: &str,
    node_id_map: &HashMap<(String, String), String>,
) -> String {
    node_id_map
        .get(&(view_key.to_string(), node_id.to_string()))
        .cloned()
        .unwrap_or_else(|| node_id.to_string())
}

fn destination_input_key(node_id: &str, input_index: usize) -> String {
    format!("{node_id}:{input_index}")
}

fn node_rect(node: &PatchNode) -> (f32, f32, f32, f32) {
    let (width, height) = node_size(node);
    (
        node.position.0,
        node.position.1,
        node.position.0 + width + NODE_PADDING,
        node.position.1 + height + NODE_PADDING,
    )
}

fn rects_overlap(a: (f32, f32, f32, f32), b: (f32, f32, f32, f32)) -> bool {
    a.0 < b.2 && a.2 > b.0 && a.1 < b.3 && a.3 > b.1
}
