; DigiClap: the classic synthesised claps — 808 (TR-808), 909 (TR-909) and
; LINN (LinnDrum-style sampled clap) — built from one burst engine: a
; retriggerable burst phasor that fires N filtered-noise bursts SPRD ms apart,
; then hands over to a closed-form exponential tail that starts on the last
; burst. Each machine shapes the noise band, the burst envelope and the tail
; differently; the shared MD-style output chain (AM, EQ, HP/LP, SRR, DIST)
; matches Digi Snare / Digi Hat.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
; milliseconds since the last trigger (saturates far past any tail)
(defmacro elapsed-ms (trig)
  (make-history n)
  (def next (gswitch (gt trig 0.5) 0.0 (min (+ (read-history n) 1.0) 100000000.0)))
  (write-history n next)
  (/ (* next 1000.0) samplerate))
; exponential tail (-60 dB at decay_ms) that starts t0 ms after the trigger
(defmacro delayed-tail (ems t0 decay_ms)
  (gswitch (lt ems t0) 0.0 (exp (/ (* -6.907755 (- ems t0)) (max 1.0 decay_ms)))))
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def a (clip amount 0 1))
  (def hz (* samplerate (pow (/ 300.0 samplerate) a)))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (def sampled (latch x tick))
  (gswitch (lt a 0.0001) x sampled))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 18000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 3)
(param ptch @default 0 @min -24 @max 24 @mod true @mod-mode additive)
(param dec @default 260 @min 20 @max 2500 @unit ms @mod true @mod-mode additive)
(param tone @default 1050 @min 300 @max 4000 @unit Hz @mod true @mod-mode additive)
(param reso @default 0.7 @min 0.5 @max 8 @mod true @mod-mode additive)
(param bursts @default 4 @min 1 @max 8)
(param sprd @default 10 @min 3 @max 30 @unit ms @mod true @mod-mode additive)
(param bdec @default 9 @min 1 @max 40 @unit ms)
(param snap @default 0.80 @min 0 @max 1 @mod true @mod-mode additive)
(param body @default 0.62 @min 0 @max 1 @mod true @mod-mode additive)
(param tlpf @default 5200 @min 400 @max 12000 @unit Hz @mod true @mod-mode additive)
(param air @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param crowd @default 0.55 @min 0 @max 1 @mod true @mod-mode additive)
(param bits @default 8 @min 4 @max 16)
(param clip @default 0.15 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.58 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 42 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 2400 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 80 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 17000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.75 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.10 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 3))
(def vel (clip velocity 0 1))
(def hum (clip humanize 0 1))
; per-hit randomness: timing spread and overall level
(def jit (latch-trig (noise) trigger))
(def jit2 (- (* 2.0 (abs jit)) 1.0))
(def hit_lvl (- 1.0 (* hum 0.18 (abs jit))))
; the band centre follows the base note (C4 = as tuned) plus PTCH
(def note_ratio (clip (/ pitch 261.6256) 0.25 4.0))
(def centre (clip (* (mod tone) note_ratio (semi (mod ptch))) 200 8000))
(def q (clip (mod reso) 0.5 8))

; burst clock: N bursts SPRD ms apart, each an exponential decay over BDEC
(def nb (clip (round bursts) 1 8))
(def sp (clip (* (mod sprd) (+ 1.0 (* hum 0.35 jit))) 3 40))
(def ems (elapsed-ms trigger))
(def bph (retrig-phasor (/ 1000.0 sp) trigger))
(make-history bprev)
(def btick (gswitch (gt trigger 0.5) 1.0 (lt bph (read-history bprev))))
(write-history bprev bph)
(def brnd (latch-trig (noise) btick))
(def blvl (- 1.0 (* hum 0.45 (abs brnd))))
(def train_len (* (- nb 1) sp))
(def in_train (lt ems (+ train_len (* sp 0.999))))
(def burst_env (* in_train blvl (exp (/ (* -6.907755 bph sp) (clip bdec 1 40)))))
(def tail_env (delayed-tail ems train_len (clip (mod dec) 20 2500)))

(def nraw (noise))
(def bp_noise (* (svf (svf nraw centre q 1) centre q 1) (/ 3.4 (pow q 0.7))))
(def bp_wide (svf nraw centre (* q 0.5) 1))
(def hp_noise (svf nraw (clip (* centre 0.5) 100 6000) 0.7 2))

; 808: sawtooth-shaped bursts through a fairly resonant band, tail through
; the same band. The burst filter rings a little, the tail is dry and short.
(def c808_burst (* bp_noise burst_env (mod snap) 2.4))
(def c808_tail (* bp_noise tail_env (mod body) 1.3))
(def c808 (md-clip (+ c808_burst c808_tail) (mod clip)))

; 909: brighter, wider band; bursts are saturated, the tail is a lowpassed
; wash whose cutoff closes as it decays (the 909 reverb section).
(def c909_burst (md-clip (* bp_wide burst_env (mod snap) 3.6) (+ 0.25 (* 0.75 (mod clip)))))
(def c909_tail_lp (clip (* (mod tlpf) (+ 0.35 (* 0.65 tail_env))) 300 12000))
(def c909_tail (* (svf (+ (* bp_wide 0.8) (* hp_noise 0.5)) c909_tail_lp 0.8 0) tail_env (mod body) 1.5))
(def c909 (+ c909_burst c909_tail))

; LINN: a sampled real clap — a dense crowd of micro-bursts instead of a
; clean flam, two resonant bands (hand cup + skin slap), companded to BITS
; and a roomy tail with AIR opening the upper band.
(def crowd_rate (+ 120 (* (mod crowd) 520)))
(def cph (retrig-phasor (* crowd_rate (+ 1 (* 0.3 jit2))) trigger))
(make-history cprev)
(def ctick (gswitch (gt trigger 0.5) 1.0 (lt cph (read-history cprev))))
(write-history cprev cph)
(def crnd (abs (latch-trig (noise) ctick)))
(def crowd_env (* (+ 0.35 (* 0.65 crnd)) (exp (* -14.0 cph))))
(def linn_shape (+ (* burst_env (- 1 (* 0.6 (mod crowd)))) (* crowd_env in_train (mod crowd) 1.1)))
(def linn_lo (* (svf (svf nraw (* centre 1.15) (+ 1.5 q) 1) (* centre 1.15) (+ 1.5 q) 1) 2.2))
(def linn_hi (svf nraw (clip (* centre 2.4) 400 12000) 2.5 1))
(def linn_burst (* (+ (* linn_lo 1.0) (* linn_hi (+ 0.25 (* 0.75 (mod air))))) linn_shape (mod snap) 2.6))
(def linn_room (* (+ (* linn_lo 0.8) (* linn_hi (mod air) 0.9)) tail_env (mod body) 1.3))
(def qbits (pow 2 (- (clip (round bits) 4 16) 1)))
(def linn_raw (md-clip (+ linn_burst linn_room) (* 0.6 (mod clip))))
(def linn (/ (floor (+ (* (clip linn_raw -1 1) qbits) 0.5)) qbits))

(def voice (selector eng c808 c909 linn))
(out (* (md-out voice) vel hit_lvl (clip (mod level) 0 1)) 1 @name audio)
