;; PM Kethuk / identified pot resonator.
;; Generated by tools/pm-gamelan/build.py; edit engine.lisp.in, then regenerate.
;; Reference coefficients only: no PCM, recorded phase, or spectral frames.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(param hardness @group mallet @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)
(param contact @group mallet @default 1 @min 0.3 @max 3 @mod true @mod-mode additive)
(param spread @group mallet @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dynamics @group mallet @default 1 @min 0 @max 1)
(param decay @group body @default 1 @min 0.15 @max 4 @mod true @mod-mode additive)
(param loss @group body @default 1 @min 0.25 @max 4 @mod true @mod-mode additive)
(param inharmonicity @group body @default 1 @min 0 @max 1.8 @mod true @mod-mode additive)
(param bloom @group body @default 1 @min 0 @max 2 @mod true @mod-mode additive)
(param color @group body @default 0 @min -1 @max 1 @mod true @mod-mode additive)
(param amount @group tuning @default 1 @min 0 @max 1 @mod true @mod-mode additive)
(param tune @group tuning @default 0 @min -100 @max 100 @unit cents @mod true @mod-mode additive)
(param touch @group damper @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param release_s @group damper @default 0.4 @min 0.02 @max 12 @unit s @mod true @mod-mode additive)
(param lift @group damper @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param width @group output @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param drive @group output @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param tone_hz @group output @default 20000 @min 1000 @max 20000 @unit Hz @mod true @mod-mode additive)
(param gain @group output @default 1 @min 0 @max 4 @mod true @mod-mode additive)

;; BEGIN GENERATED CALIBRATION
;; Latent Sonorities / memeshift, CC BY-NC 4.0; see ATTRIBUTION.md.
;; Analysis SHA256: ee6222960325ec138e5b27b2e9e8ab73da21965992fc76bd28c7ac63b9907809
(def ratio_table (tensor @shape [18] @data [
  1 4.3097438 3.52522916 6.69282169 7.86450899 4.77392383 6.83153833 8.56125332 9.01126393 1.67336879 7.26501869 7.47294774 8.26586822 6.25395662 1.73383887 8.81907218 4.69479176 7.12622046
]))
(def rate_table (tensor @shape [18] @data [
  2.31201656 6.29587934 7.47204894 20.0692486 5.82527088 4.69332998 2.51240856 3.26710884 4.99265546 0.797723863 2.14890052 2.13140098 3.05126816 2.50126607 1.04944785 3.56250485 5.23867494 2.45185149
]))
(def rise_table (tensor @shape [18] @data [
  0.00199369809 0.107395539 0.0332470726 0.721155686 0.193168257 0.050844136 0.04387159 0.190756935 0.0364563714 0.00100131497 0.0147458729 0.0283709343 0.0402242496 0.00120413364 0.555194284 0.0727975893 0.0235279777 0.108750488
]))
(def direct_table (tensor @shape [18] @data [
  0.881449121 0.337156524 5.47872858e-12 0.0539586845 0.49310218 2.42722468e-07 0.426150351 0.144646286 6.22162322e-11 0.99999704 3.90839805e-10 0.0910942469 0.259830516 0.917126454 0.551508972 0.366878949 2.01394457e-13 0.43787875
]))
(def amplitude_table (tensor @shape [3 18] @data [
  0.00530151667 0.0109204508 0.012391595 0.00966432664 0.002028317 0.00407353815 0.00140331007 0.00103937797 0.00113278939 0.000758841771 0.00101141172 0.000339445802 0.000229408917 0.000403847581 0.000194524525 0.000484549584 0.000252276157 0.000357406442
  0.0095385351 0.0256319237 0.0323167244 0.0334827059 0.0130873759 0.008449093 0.00540436616 0.00360136635 0.0048174228 0.00107348893 0.0026100002 0.00194905749 0.00165286727 0.000556315779 0.00070551676 0.000881417484 0.00166526771 0.000553665564
  0.015764678 0.0468247346 0.040466201 0.0354140568 0.0170826623 0.0163532587 0.0119560442 0.00707948681 0.00598465204 0.00185324088 0.00241712751 0.00234033462 0.00317925147 0.00242504841 0.00115715949 0.00128141267 0.000696847878 0.000965397033
]))
(def tuning_table (tensor @shape [1] @data [
  36.0306819
]))
(def mode_pan_table (tensor @shape [18] @data [
  0 0.472843206 -0.697319729 0.555520526 -0.121927366 -0.375709636 0.676000552 -0.621213901 0.240127043 0.267089484 -0.63401399 0.667914885 -0.350985309 -0.150303598 0.5726437 0.45111289 0.0289224751 -0.493765956
]))
;; END GENERATED CALIBRATION

(defmacro gamelan-smooth (target ms)
  (make-history previous)
  (make-history ready)
  (def pole (exp (/ -1 (* 0.001 ms samplerate))))
  (def value (gswitch (read-history ready) (mix target (read-history previous) pole) target))
  (write-history previous value)
  (write-history ready 1)
  value)

(defmacro gamelan-pole (signal pole)
  (make-history previous)
  (def value (mix signal (read-history previous) pole))
  (write-history previous value)
  value)

;; Coefficients latch on every strike as well as each periodic control tick.
;; A periodic-only hop would miss the beginning of an off-grid force pulse.
;; Pure coefficient calculations execute only on those events. Final audio
;; latches keep the modal recurrence running every sample.
(def control_tick (eq (accum 1 0 0 16) 0))
(defmacro gamelan-hold (value tick) (event-hold value tick))
(defmacro gamelan-audio (value tick) (latch value tick))

(defmacro gamelan-row (note)
  0)

(make-history last_gate)
(def held (gt gate 0.5))
(def onset (max (gt trigger 0.5) (* held (lte (read-history last_gate) 0.5))))
(def update_tick (max control_tick onset))
(write-history last_gate held)
(def hit_velocity (latch (clip velocity 0 1) onset))
(def strength (mix 0.6 hit_velocity (clip dynamics 0 1)))
(def velocity_row (gamelan-hold (+ (clip (/ (- strength 0.6) 0.2) 0 1) (clip (/ (- strength 0.8) 0.2) 0 1)) update_tick))
(def velocity_gain (/ hit_velocity (max 0.6 strength)))
(def key_note (+ 69 (* 12 (/ (log (/ (clip pitch 32.703196 8372.018) 440)) (log 2)))))
(def row 0)
(def row_low (floor row))
(def row_high (min 0 (+ row_low 1)))
(def row_mix (- row row_low))
;; Row coordinates are already clamped. Share integer gather indices across
;; fields instead of repeating wrapped fractional lookups inside each mode.
(def mode_indices (iota 18))
(def low_indices (+ mode_indices (* row_low 18)))
(def high_indices (+ mode_indices (* row_high 18)))
(def velocity_low (floor velocity_row))
(def velocity_high (min (- 3 1) (+ velocity_low 1)))
(def velocity_mix (- velocity_row velocity_low))
(def a00 (+ mode_indices (* (+ (* row_low 3) velocity_low) 18)))
(def a01 (+ mode_indices (* (+ (* row_low 3) velocity_high) 18)))
(def a10 (+ mode_indices (* (+ (* row_high 3) velocity_low) 18)))
(def a11 (+ mode_indices (* (+ (* row_high 3) velocity_high) 18)))
(defmacro gamelan-row-mix (table lower upper fraction)
  (mix (gather table lower) (gather table upper) fraction))

(def base_hz (* (clip pitch 32.703196 8372.018)
  (pow 2 (/ (+ (clip (mod tune) -100 100)
    (* (clip (mod amount) 0 1) (peek tuning_table (gamelan-row key_note)))) 1200))))
(def ratio ratio_table)
(def harmonic_ratio (max 1 (floor (+ ratio 0.5))))
(def live_ratio (max 0.1 (mix harmonic_ratio ratio (gamelan-hold (gamelan-smooth (clip (mod inharmonicity) 0 1.8) 8) update_tick))))
(def frequencies (* (gamelan-hold base_hz update_tick) live_ratio))
(def band (clip (/ (- (* samplerate 0.47) frequencies) (* samplerate 0.07)) 0 1))
(def amplitude (gamelan-row-mix amplitude_table a00 a01 velocity_mix))

;; A normalized two-pole contact force; measured modal residues are deconvolved
;; by its reference response. Hardness/contact alter the force, not the decay.
(def reference_pole (exp (/ -1 (* 6e-05 samplerate))))
(def contact_tau (* 6e-05 (clip (mod contact) 0.3 3)
  (pow 2 (* 3 (- 0.5 (clip (mod hardness) 0 1))))))
(def contact_pole (exp (/ -1 (* (gamelan-hold contact_tau update_tick) samplerate))))
(def force_pole (gamelan-audio contact_pole update_tick))
(def force1 (gamelan-pole (* onset velocity_gain) force_pole))
(def force (gamelan-pole force1 force_pole))
(def omega (* twopi (/ (min frequencies (* 0.48 samplerate)) samplerate)))
(def rotation_cos (cos omega))
(def rotation_sin (sin omega))
(def inverse_contact (/ (+ (* (- 1 reference_pole) (- 1 reference_pole))
  (* 2 reference_pole (- 1 rotation_cos))) (* (- 1 reference_pole) (- 1 reference_pole))))
;; A finite mallet footprint suppresses shorter spatial wavelengths. Its width
;; is a timbral control: spatial mode shapes cannot be recovered from one mic.
(def footprint (exp (* -0.8 (max 0 (- ratio 1)) (gamelan-hold (clip (mod spread) 0 1) update_tick))))
(def color_weight (pow ratio (gamelan-hold (clip (mod color) -1 1) update_tick)))
;; The force bandwidth and spectral color redistribute a finite excitation
;; budget. Squared acoustic residues are an energy proxy (modal masses are
;; unknown), not a claim to measured impact joules. Soft contacts may dissipate
;; energy; hard contacts cannot manufacture unbounded extra modal energy.
(def live_contact (/ (* (- 1 contact_pole) (- 1 contact_pole))
  (+ (* (- 1 contact_pole) (- 1 contact_pole)) (* 2 contact_pole (- 1 rotation_cos)))))
(def reference_residue (* amplitude band))
(def colored_residue (* reference_residue inverse_contact live_contact footprint color_weight))
(def reference_energy (sum (* reference_residue reference_residue)))
(def colored_energy (sum (* colored_residue colored_residue)))
(def energy_scale (min 1 (sqrt (/ reference_energy (max 0.00000000000000000001 colored_energy)))))
(def weight (gamelan-hold (* amplitude inverse_contact band footprint color_weight energy_scale) update_tick))
(def decay_scale (gamelan-hold (gamelan-smooth (clip (mod decay) 0.15 4) 8) update_tick))
(def loss_scale (pow ratio (* 0.5 (- (gamelan-hold (gamelan-smooth (clip (mod loss) 0.25 4) 8) update_tick) 1))))
(def hand_loss (* 100 (pow (gamelan-smooth (clip (mod touch) 0 1) 4) 2)))
(def release_loss (* (- 1 held) (pow (- 1 (clip (mod lift) 0 1)) 2)
  (/ 6.907755 (clip (mod release_s) 0.02 12))))
(def rate (+ (/ (* rate_table loss_scale) decay_scale)
  (* (gamelan-hold (+ hand_loss release_loss) update_tick) (sqrt ratio))))
(def rise (max 0.00005 (* rise_table
  (gamelan-hold (gamelan-smooth (clip (mod bloom) 0 2) 8) update_tick))))
(def direct direct_table)

;; A passive modal reduction followed by a radiation pole at each mode.
;; Its impulse envelope is exp(-rate*t) * (1 - (1-direct)*exp(-t/rise)).
;; This is a causal recurrence, not a recorded or scheduled amplitude envelope.
;; Both complex rotations remain contractive during pitch/damping automation.
;; Final coefficient latches cross from the event clock back to audio rate.
;; Shared sine/cosine also serve the contact response above.
(defmacro gamelan-resonator (rotation_cos rotation_sin rate rise direct weight force tick)
  (make-tensor-history bar_r @shape [18])
  (make-tensor-history bar_i @shape [18])
  (make-tensor-history radiation_r @shape [18])
  (make-tensor-history radiation_i @shape [18])
  (def x (read-tensor-history bar_r))
  (def y (read-tensor-history bar_i))
  (def xr (read-tensor-history radiation_r))
  (def yr (read-tensor-history radiation_i))
  (def radius (exp (/ (- rate) samplerate)))
  (def c (gamelan-audio (* radius rotation_cos) tick))
  (def s (gamelan-audio (* radius rotation_sin) tick))
  (def coupling (gamelan-audio (exp (/ -1 (* rise samplerate))) tick))
  (def next_r (+ (- (* c x) (* s y)) (* force (gamelan-audio weight tick))))
  (def next_i (+ (* s x) (* c y)))
  (def radiated_r (+ (* coupling (- (* c xr) (* s yr))) (* (- 1 coupling) next_r)))
  (def radiated_i (+ (* coupling (+ (* s xr) (* c yr))) (* (- 1 coupling) next_i)))
  (write-tensor-history bar_r next_r)
  (write-tensor-history bar_i next_i)
  (write-tensor-history radiation_r radiated_r)
  (write-tensor-history radiation_i radiated_i)
  (mix radiated_i next_i (gamelan-audio direct tick)))

(def modes (gamelan-resonator rotation_cos rotation_sin rate rise direct weight force update_tick))
(def stereo (gamelan-hold (gamelan-smooth (clip (mod width) 0 1) 8) update_tick))
(def left (sum (* modes (gamelan-audio (sqrt (+ 1 (* mode_pan_table stereo))) update_tick))))
(def right (sum (* modes (gamelan-audio (sqrt (- 1 (* mode_pan_table stereo))) update_tick))))

(def drive_v (gamelan-smooth (clip (mod drive) 0 1) 8))
(def cutoff (min (gamelan-smooth (clip (mod tone_hz) 1000 20000) 8) (* samplerate 0.43)))
(def output_gain (gamelan-smooth (clip (mod gain) 0 4) 8))
(defmacro gamelan-output (signal drive_v cutoff gain_v)
  (def driven (mix signal (/ (tanh (* signal (+ 1 (* drive_v 8)))) (+ 1 (* drive_v 2))) drive_v))
  (def filtered (svf driven cutoff 0.707 0))
  (* filtered gain_v))
(out (gamelan-output left drive_v cutoff output_gain) 1 @name left)
(out (gamelan-output right drive_v cutoff output_gain) 2 @name right)
