; ULTRAKICK — layered kick designer with Machinedrum DNA.
; BODY engine (SINE/FM/MODAL/FOLD, three contextual character knobs bx/by/bz)
; + always-on TRANSIENT / NOISE layers + clean post-drive SUB layer
; + PUNCH enhancer -> DRIVE -> DIRT -> HP/LP output stage.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))

(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro md-env-hold (trig hold_ms decay_ms)
  (make-history e)
  (make-history age)
  (def prev_age (read-history age))
  (def next_age (gswitch (gt trig 0.5) 0.0 (+ prev_age 1.0)))
  (def held (lt next_age (* hold_ms 0.001 samplerate)))
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (gswitch held 1.0 (* (read-history e) coef))))
  (write-history age next_age)
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro latch-trig (sig trig)
  (make-history h)
  (def old (read-history h))
  (def v (gswitch (gt trig 0.5) sig old))
  (write-history h v)
  v)

(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)

(defmacro md-ping (exc freq t60_ms trig)
  (make-history y1)
  (make-history y2)
  (def y1p (gswitch (gt trig 0.5) 0.0 (read-history y1)))
  (def y2p (gswitch (gt trig 0.5) 0.0 (read-history y2)))
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def c (* 2.0 r (cos (* twopi (/ (clip freq 8 18000) samplerate)))))
  (def y (- (+ exc (* c y1p)) (* r r y2p)))
  (write-history y2 y1p)
  (write-history y1 y)
  y)

(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (def hard (clip (* x (+ 1 (* 16 d))) -1 1))
  (def soft (tanh (* x (+ 1 (* 5 d)))))
  (+ (* soft (- 1 d)) (* hard d)))

(defmacro md-srr (x amount trig)
  (def a (clip amount 0 1))
  (def hold_hz (exp (+ (log 300.0) (* (- 1 a) (- (log 44100.0) (log 300.0))))))
  (def ph (retrig-phasor hold_hz trig))
  (make-history prev)
  (make-history held)
  (def tick (lt ph (read-history prev)))
  (def reset (gt trig 0.5))
  (def should_sample (gt (+ (gswitch reset 1.0 0.0) (gswitch tick 1.0 0.0)) 0.5))
  (def sampled (gswitch should_sample x (read-history held)))
  (write-history prev ph)
  (write-history held sampled)
  (gswitch (lt a 0.0001) x sampled))

(defmacro md-bits (x amount)
  (def bits (+ 2 (* (- 1 (clip amount 0 1)) 10)))
  (def steps (pow 2 bits))
  (/ (floor (* x steps)) steps))

(defmacro md-reset-lp (x cutoff trig)
  (make-history y)
  (def c (exp (/ (* -2.0 pi (clip cutoff 20 18000)) samplerate)))
  (def yp (gswitch (gt trig 0.5) 0.0 (read-history y)))
  (def next (+ (* (- 1.0 c) x) (* c yp)))
  (write-history y next)
  next)

(defmacro md-reset-hp (x cutoff trig)
  (- x (md-reset-lp x cutoff trig)))

(param engine @default 1 @min 1 @max 4)

(param ptch @default -26 @min -60 @max 24 @mod true @mod-mode additive)
(param dec @default 480 @min 30 @max 4000 @unit ms @mod true @mod-mode additive)
(param hold @default 10 @min 0 @max 500 @unit ms @mod true @mod-mode additive)
(param sweep @default 36 @min 0 @max 96 @mod true @mod-mode additive)
(param swpt @default 32 @min 3 @max 400 @unit ms)

(param bx @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)
(param by @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)
(param bz @default 0.15 @min 0 @max 1 @mod true @mod-mode additive)

(param ttyp @default 0 @min 0 @max 3)
(param tamt @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param ttun @default 3200 @min 200 @max 9000 @unit Hz @mod true @mod-mode additive)
(param tdec @default 6 @min 1 @max 80 @unit ms)

(param sub @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param stun @default -12 @min -24 @max 0)
(param sdec @default 700 @min 50 @max 4000 @unit ms)

(param nois @default 0.10 @min 0 @max 1 @mod true @mod-mode additive)
(param ncol @default 0.40 @min 0 @max 1 @mod true @mod-mode additive)
(param ndec @default 120 @min 5 @max 1500 @unit ms)

(param pnch @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param driv @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param dirt @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param hpf @default 20 @min 20 @max 400 @unit Hz @mod true @mod-mode additive)
(param lpf @default 16000 @min 200 @max 18000 @unit Hz @mod true @mod-mode additive)
(param humanize @default 0.15 @min 0 @max 1)
(param level @default 0.7 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def jit2 (* (latch-trig (noise) trigger) humanize))

(def dec_v (* (clip (mod dec) 30 4000) (+ 1 (* jit2 0.12))))
(def hold_v (clip (mod hold) 0 500))
(def swpt_v (clip swpt 3 400))
(def bx_v (clip (mod bx) 0 1))
(def by_v (clip (mod by) 0 1))
(def bz_v (clip (mod bz) 0 1))
(def tamt_v (clip (mod tamt) 0 1))
(def ttun_v (clip (mod ttun) 200 9000))
(def sub_v (clip (mod sub) 0 1))
(def nois_v (clip (mod nois) 0 1))
(def ncol_v (clip (mod ncol) 0 1))
(def pnch_v (clip (mod pnch) 0 1))
(def driv_v (clip (mod driv) 0 1))
(def dirt_v (clip (mod dirt) 0 1))
(def hpf_v (clip (mod hpf) 20 400))
(def lpf_v (clip (mod lpf) 200 18000))

(def base (clip (* pitch (semi (mod ptch))) 12 400))
(def amp (md-env-hold trigger hold_v dec_v))
(def p_env (md-env trigger swpt_v))
(def sigh (md-env trigger 300))
(def sweep_semi (+ (* (clip (mod sweep) 0 96) p_env (+ 0.7 (* 0.3 accent))) (* -1.5 sigh) (* jit 0.4)))
(def f0 (clip (* base (semi sweep_semi)) 8 3000))
(def body_gain (+ 0.6 (* 0.4 accent)))

; SINE body: X=HARM phase overdrive, Y=SAT tanh blend, Z=OCT octave-up blend
(def s_ph (retrig-phasor f0 trigger))
(def s_raw (sin (+ (* s_ph twopi) (* bx_v 2.6 (sin (* s_ph twopi 2))))))
(def s_oct (sin (* s_ph twopi 2)))
(def s_mix (+ (* s_raw (- 1 (* bz_v 0.5))) (* s_oct bz_v 0.6)))
(def s_sat (tanh (* s_mix (+ 1 (* by_v 5)))))
(def sine_b (* (+ (* s_mix (- 1 by_v)) (* s_sat by_v)) amp body_gain))

; FM body: X=MOD index, Y=MFRQ 25..1200 Hz exp, Z=MFB feedback (chaos allowed)
(make-history uk_fb)
(def fm_idx_env (md-env trigger (clip (* swpt_v 1.3) 4 500)))
(def fm_fb_prev (gswitch (gt trigger 0.5) 0.0 (read-history uk_fb)))
(def fm_mfrq (clip (* 25 (pow 48 by_v)) 10 2000))
(def fm_mod_ph (retrig-phasor fm_mfrq trigger))
(def fm_mod (sin (+ (* fm_mod_ph twopi) (* bz_v 8.0 fm_fb_prev))))
(write-history uk_fb (clip fm_mod -1 1))
(def fm_car_ph (retrig-phasor f0 trigger))
(def fm_b (* (sin (+ (* fm_car_ph twopi) (* fm_mod fm_idx_env bx_v 15))) amp body_gain))

; MODAL body: X=HARD mallet+mode brightness, Y=TENS tension glide, Z=DAMP
(def m_energy (md-env trigger (* dec_v 0.5)))
(def m_tens (+ 1 (* by_v 0.5 accent m_energy m_energy)))
; excitation normalized by burst length so ping ring level is independent of samplerate
(def m_norm (/ 1.0 (max 8.0 (* 0.0015 samplerate))))
(def m_mallet (* (svf (noise) (clip (+ 1500 (* bx_v 9000)) 500 12000) 1.0 0) (md-env trigger 1.5) m_norm))
(def m_p1 (md-ping m_mallet (* f0 m_tens) (* dec_v (+ 0.30 (* (- 1 bz_v) 0.90))) trigger))
(def m_p2 (md-ping m_mallet (* f0 1.50 m_tens) (* dec_v (+ 0.16 (* (- 1 bz_v) 0.50))) trigger))
(def m_p3 (md-ping m_mallet (* f0 2.20 m_tens) (* dec_v (+ 0.10 (* (- 1 bz_v) 0.35))) trigger))
(def modal_b (* (+ m_p1 (* m_p2 bx_v 0.50) (* m_p3 bx_v 0.30)) body_gain 0.55))

; FOLD body: X=FOLD amount, Y=SYM asymmetry, Z=CHEW bit crush blend
(def fo_ph (retrig-phasor f0 trigger))
(def fo_raw (sin (* fo_ph twopi)))
(def fo_g (+ 1 (* bx_v 7)))
(def fo_folded (sin (* (+ (* fo_raw fo_g) (* by_v 1.5)) pi 0.5)))
(def fo_chewed (md-bits fo_folded (* bz_v 0.85)))
(def fold_b (* (+ (* fo_folded (- 1 bz_v)) (* fo_chewed bz_v)) amp body_gain))

(def body (selector eng sine_b fm_b modal_b fold_b))

; TRANSIENT layer: TICK / KNOCK / CLICK / SNAP
(def t_env (md-env trigger (clip tdec 1 80)))
(def t_tick (* (svf (noise) (clip ttun_v 500 12000) 1.2 2) t_env 2.0))
(def t_knock (* (svf (noise) (clip ttun_v 200 3000) 2.5 1) t_env 2.2))
(def t_click_exc (* (noise) (md-env trigger 0.7)))
(def t_click (md-ping t_click_exc (clip ttun_v 200 9000) (clip (* tdec 2.5) 2 200) trigger))
(def t_blipf (clip (* ttun_v (+ 0.15 (* 0.85 (md-env trigger 4)))) 100 9000))
(def t_snap (+ (* (sin (* (retrig-phasor t_blipf trigger) twopi)) t_env 1.2) (* (svf (noise) 6000 1.2 2) (md-env trigger 2) 0.8)))
(def ttyp_i (clip (round ttyp) 0 3))
(def trans (* (selector (+ ttyp_i 1) t_tick t_knock t_click t_snap) tamt_v 1.4 accent))

; NOISE air layer
(def n_cf (clip (* 200 (pow 30 ncol_v)) 100 9000))
(def nz (* (svf (noise) n_cf 1.4 1) (md-env trigger (clip ndec 5 1500)) nois_v))

; PUNCH enhancer -> DRIVE -> DIRT
(def punch_env (md-env trigger 30))
(def pre (* (+ body trans nz) (+ 1 (* pnch_v 2.2 punch_env))))
(def driven (md-clip pre driv_v))
(def srrd (md-srr driven (* dirt_v 0.75) trigger))
(def dirted (+ (* srrd (- 1 (* dirt_v 0.5))) (* (md-bits srrd (* dirt_v 0.9)) dirt_v 0.5)))

; SUB layer: clean sine, mixed post-drive so it never smears
(def sub_f (clip (* base (semi stun)) 8 220))
(def sub_sig (* (sin (* (retrig-phasor sub_f trigger) twopi)) (md-env-hold trigger hold_v (clip sdec 50 4000)) sub_v 1.1))

; OUTPUT: 12 dB HP + 12 dB LP, level, velocity
(def summed (+ dirted sub_sig))
(def hp2 (md-reset-hp (md-reset-hp summed hpf_v trigger) hpf_v trigger))
(def lp2 (md-reset-lp (md-reset-lp hp2 lpf_v trigger) lpf_v trigger))
(out (* lp2 (clip (mod level) 0 1) vel) 1 @name audio)
