(defmacro xyz (input shape tri)
  (def phasor1 (phasor input))
  (def ramp2trig1 (ramp2trig phasor1))
  (def latch1 (latch tri ramp2trig1))
  (def triangle1 (triangle phasor1 latch1))
  (def mul1 (* triangle1 twopi))
  (def scale1 (scale triangle1 0.0 1.0 -1.0 1.0))
  (def cos1 (cos mul1))
  (def mix1 (mix scale1 cos1 shape))
  mix1)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param tri @min 0.0 @max 1.0 @mod true @mod-mode additive)
(param shape @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def modulated2 (mod tri))
(def modulated1 (mod shape))
(def xyz1 (xyz pitch modulated1 modulated2))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(out (* xyz1 env velocity (mod gain)) 1 @name audio)