(defmacro pitch-shift-hz (hz semitones)
  (def ratio (exp (/ (* (log 2.0) semitones) 12.0)))
  (* hz ratio))
(param semitone @min -12.0 @max 12.0 @default 0.0)
(use-defmacro gain2)
(make-history history1)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def mul5 (* pitch 1.25))
(def pitch-shift-hz1 (pitch-shift-hz pitch semitone))
(def phasor1 (phasor pitch-shift-hz1))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))
(param rate @min 1.0 @max 32.0 @default 4.0 @mod true @mod-mode additive)
(param smoothness @min 0.0 @max 1.0 @default 0.5 @mod true @mod-mode additive)
(param res @min 0.5 @max 9.0 @default 2.0 @mod true @mod-mode additive @group filter)
(param cutoff @min 50.0 @max 10000.0 @default 400.0 @mod true @mod-mode additive @group filter)
(def modulated1 (mod smoothness))
(def scale1 (scale modulated1 0.0 1.0 0.999 0.99999))
(param attack @group amp @env amp-env @role attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @group amp @env amp-env @role decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0.0 @max 1.0)
(param release @group amp @env amp-env @role release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def mul2 (* env (mod rate)))
(def mul3 (* clock mul2))
(def wrap1 (wrap mul3 0.0 1.0))
(def triangle1 (triangle wrap1 0.03))
(def pow1 (pow triangle1 8.0))
(def mul4 (* env pow1))
(def mix1 (mix mul4 (read-history history1) scale1))
(def triangle3 (triangle phasor1 mix1))
(def mul6 (* triangle3 twopi))
(def cos2 (cos mul6))
(def phase (phasor pitch))
(def triangle2 (triangle phase mix1))
(def mul1 (* triangle2 twopi))
(def cos1 (cos mul1))
(def mix2 (mix cos2 cos1 0.5))
(def gain21 (gain2 (* mix2 env velocity (mod gain))))
(def svf1 (svf gain21 (mod cutoff) (mod res) 0.0))
(out svf1 1 @name audio)
(write-history history1 mix1)