;; init.lisp — loaded at editor startup
;; Define commands and key bindings here.

;; Evaluate the s-expression at the cursor and show the result in the minibuffer.
;; (eval ...) is a native that schedules the string to run after this handler returns.
(def eval-sexp ()
  (let ((form (s-expression-at-cursor)))
    (if (= form "")
      (status "No s-expression at cursor")
      (let ((result (eval form)))
        (host-command "sync-current-buffer" true)
        result))))

(def eval-buffer-command ()
  (let ((result (eval (current-buffer-text))))
    (host-command "sync-current-buffer" true)
    result))

(def save-current-buffer ()
  (save-buffer))

(def compile-instrument ()
  (status "Compiling instrument...")
  (host-command "compile-instrument"
    (dict :source (current-buffer-text)
          :path (current-buffer-path))))

(def compile-effect ()
  (status "Compiling effect...")
  (host-command "compile-effect"
    (dict :source (current-buffer-text)
          :path (current-buffer-path))))

(def compile-current ()
  (status "Compiling...")
  (host-command "compile-current"
    (dict :source (current-buffer-text)
          :path (current-buffer-path))))

(def every (unit interval form)
  (host-command "register-hook"
    (dict :unit unit
          :interval interval
          :callback form)))

(def clear-hooks ()
  (host-command "clear-hooks"))

;; Switch to a buffer by name, creating it if it doesn't exist
(def switch-or-create-buffer (name)
  (let ((bufs (buffer-list))
        (exists (reduce |acc b| (if (= b name) true acc) false bufs)))
    (if exists
      (switch-to-buffer name)
      (create-buffer name))))

;; ── Theme helpers ───────────────────────────────────────────────────────────

(def light-theme ()
  ;; Adapted from folke/tokyonight.nvim's `tokyonight-day` palette.
  (set! THEME.bg "#e1e2e7")
  (set! THEME.fg "#3760bf")
  (set! THEME.fg_muted "#848cb5")
  (set! THEME.black "#dcdcde")
  (set! THEME.red "#f52a65")
  (set! THEME.green "#587539")
  (set! THEME.yellow "#8c6c3e")
  (set! THEME.blue "#2e7de9")
  (set! THEME.magenta "#9854f1")
  (set! THEME.cyan "#007197")
  (set! THEME.white "#3760bf")
  (set! THEME.bright_black "#a1a6c5")
  (set! THEME.bright_red "#c64343")
  (set! THEME.bright_yellow "#a27629")
  (set! THEME.purple "#7847bd")
  (set! THEME.cursor "#2e7de9")
  (set! THEME.syn_comment "#848cb5")
  (set! THEME.syn_string "#587539")
  (set! THEME.syn_number "#b15c00")
  (set! THEME.syn_keyword "#9854f1")
  (set! THEME.syn_builtin "#2e7de9")
  (set! THEME.syn_special "#007197")
  (set! THEME.syn_delimiter "#8990b3")
  (set! THEME.bg_region "#b6d6fd")
  (set! THEME.bg_sexp "#d7d8df")
  (set! THEME.bg_eval_flash "#c4d6b0")
  (set! THEME.bg_match_paren "#2e7de9")
  (set! THEME.fg_match_paren "#e1e2e7")
  (set! THEME.status_fg "#3760bf")
  (set! THEME.status_bg "#dcdcde")
  (set! THEME.status_edge "#c4c8da")
  (set! THEME.status_chip_bg "#d5d6db")
  (set! THEME.status_mode_bg "#cbdaf6")
  (set! THEME.status_chip_muted "#d9dadf")
  (set! THEME.status_ui_bg "#2e7de9")
  (set! THEME.status_ui_fg "#e1e2e7")
  (set! THEME.status_mix_bg "#2e7de9")
  (set! THEME.status_mix_fg "#e1e2e7")
  (set! THEME.status_dirty_bg "#b15c00")
  (set! THEME.status_dirty_fg "#f7efe4")
  (set! THEME.status_pos_bg "#d5d6db")
  (set! THEME.status_accent "#007197")
  (set! THEME.comp_selected_bg "#cbdaf6")
  (set! THEME.comp_unselected_bg "#dcdcde")
  (set! THEME.comp_fg "#3760bf")
  (set! THEME.comp_doc_bg "#d5d6db")
  (set! THEME.comp_doc_fg "#3760bf")
  (set! THEME.comp_doc_title_fg "#2e7de9")
  (set! THEME.widget_label_fg "#3760bf")
  (set! THEME.widget_slider_filled "#2e7de9")
  (set! THEME.widget_slider_track "#a8aecb")
  (set! THEME.widget_knob_filled "#9854f1")
  (set! THEME.widget_knob_track "#a8aecb")
  (set! THEME.widget_toggle_on "#2e7de9")
  (set! THEME.widget_toggle_off "#8990b3")
  (set! THEME.widget_toggle_knob_on "#ffffff")
  (set! THEME.widget_toggle_knob_off "#f1f3f7")
  (status "TokyoNight Day theme applied"))

(def tokyonight-storm-theme ()
  ;; Adapted from folke/tokyonight.nvim's `storm` palette.
  (set! THEME.bg "#24283b")
  (set! THEME.fg "#c0caf5")
  (set! THEME.fg_muted "#565f89")
  (set! THEME.black "#1f2335")
  (set! THEME.red "#f7768e")
  (set! THEME.green "#9ece6a")
  (set! THEME.yellow "#e0af68")
  (set! THEME.blue "#7aa2f7")
  (set! THEME.magenta "#bb9af7")
  (set! THEME.cyan "#7dcfff")
  (set! THEME.white "#c0caf5")
  (set! THEME.bright_black "#545c7e")
  (set! THEME.bright_red "#db4b4b")
  (set! THEME.bright_yellow "#ff9e64")
  (set! THEME.purple "#9d7cd8")
  (set! THEME.cursor "#7aa2f7")
  (set! THEME.syn_comment "#565f89")
  (set! THEME.syn_string "#9ece6a")
  (set! THEME.syn_number "#ff9e64")
  (set! THEME.syn_keyword "#bb9af7")
  (set! THEME.syn_builtin "#7aa2f7")
  (set! THEME.syn_special "#7dcfff")
  (set! THEME.syn_delimiter "#545c7e")
  (set! THEME.bg_region "#292e42")
  (set! THEME.bg_sexp "#292e42")
  (set! THEME.bg_eval_flash "#394b70")
  (set! THEME.bg_match_paren "#7aa2f7")
  (set! THEME.fg_match_paren "#1f2335")
  (set! THEME.status_fg "#c0caf5")
  (set! THEME.status_bg "#1f2335")
  (set! THEME.status_edge "#292e42")
  (set! THEME.status_chip_bg "#292e42")
  (set! THEME.status_mode_bg "#394b70")
  (set! THEME.status_chip_muted "#292e42")
  (set! THEME.status_ui_bg "#7aa2f7")
  (set! THEME.status_ui_fg "#1f2335")
  (set! THEME.status_mix_bg "#7aa2f7")
  (set! THEME.status_mix_fg "#1f2335")
  (set! THEME.status_dirty_bg "#db4b4b")
  (set! THEME.status_dirty_fg "#c0caf5")
  (set! THEME.status_pos_bg "#292e42")
  (set! THEME.status_accent "#7dcfff")
  (set! THEME.comp_selected_bg "#292e42")
  (set! THEME.comp_unselected_bg "#1f2335")
  (set! THEME.comp_fg "#c0caf5")
  (set! THEME.comp_doc_bg "#1b1e2d")
  (set! THEME.comp_doc_fg "#c0caf5")
  (set! THEME.comp_doc_title_fg "#7aa2f7")
  (set! THEME.widget_label_fg "#c0caf5")
  (set! THEME.widget_slider_filled "#7aa2f7")
  (set! THEME.widget_slider_track "#394b70")
  (set! THEME.widget_knob_filled "#bb9af7")
  (set! THEME.widget_knob_track "#545c7e")
  (set! THEME.widget_toggle_on "#7aa2f7")
  (set! THEME.widget_toggle_off "#545c7e")
  (set! THEME.widget_toggle_knob_on "#c0caf5")
  (set! THEME.widget_toggle_knob_off "#c0caf5")
  (status "TokyoNight Storm theme applied"))

(def aura-theme ()
  ;; Adapted from the Aura palette used across its editor/terminal ports.
  (set! THEME.bg "#15141b")
  (set! THEME.fg "#edecee")
  (set! THEME.fg_muted "#6d6d6d")
  (set! THEME.black "#110f18")
  (set! THEME.red "#ff6767")
  (set! THEME.green "#61ffca")
  (set! THEME.yellow "#ffca85")
  (set! THEME.blue "#82e2ff")
  (set! THEME.magenta "#f694ff")
  (set! THEME.cyan "#61ffca")
  (set! THEME.white "#edecee")
  (set! THEME.bright_black "#6d6d6d")
  (set! THEME.bright_red "#ff6767")
  (set! THEME.bright_yellow "#ffca85")
  (set! THEME.purple "#a277ff")
  (set! THEME.cursor "#a277ff")
  (set! THEME.syn_comment "#6d6d6d")
  (set! THEME.syn_string "#61ffca")
  (set! THEME.syn_number "#ffca85")
  (set! THEME.syn_keyword "#a277ff")
  (set! THEME.syn_builtin "#82e2ff")
  (set! THEME.syn_special "#f694ff")
  (set! THEME.syn_delimiter "#6d6d6d")
  (set! THEME.bg_region "#29263c")
  (set! THEME.bg_sexp "#28253c")
  (set! THEME.bg_eval_flash "#3d375e")
  (set! THEME.bg_match_paren "#a277ff")
  (set! THEME.fg_match_paren "#15141b")
  (set! THEME.status_fg "#adacae")
  (set! THEME.status_bg "#121016")
  (set! THEME.status_edge "#3b334b")
  (set! THEME.status_chip_bg "#2e2b38")
  (set! THEME.status_mode_bg "#3b334b")
  (set! THEME.status_chip_muted "#2e2b38")
  (set! THEME.status_ui_bg "#a277ff")
  (set! THEME.status_ui_fg "#15141b")
  (set! THEME.status_mix_bg "#82e2ff")
  (set! THEME.status_mix_fg "#15141b")
  (set! THEME.status_dirty_bg "#ff6767")
  (set! THEME.status_dirty_fg "#15141b")
  (set! THEME.status_pos_bg "#2e2b38")
  (set! THEME.status_accent "#61ffca")
  (set! THEME.comp_selected_bg "#2e2b38")
  (set! THEME.comp_unselected_bg "#15141b")
  (set! THEME.comp_fg "#edecee")
  (set! THEME.comp_doc_bg "#15141b")
  (set! THEME.comp_doc_fg "#cdccce")
  (set! THEME.comp_doc_title_fg "#a277ff")
  (set! THEME.widget_label_fg "#edecee")
  (set! THEME.widget_slider_filled "#a277ff")
  (set! THEME.widget_slider_track "#6d6d6d")
  (set! THEME.widget_knob_filled "#a277ff")
  (set! THEME.widget_knob_track "#6d6d6d")
  (set! THEME.widget_toggle_on "#a277ff")
  (set! THEME.widget_toggle_off "#6d6d6d")
  (set! THEME.widget_toggle_knob_on "#ffffff")
  (set! THEME.widget_toggle_knob_off "#edecee")
  (status "Aura theme applied"))

(bind-key "C-x C-e" "eval-sexp")
(bind-key "C-x C-b" "eval-buffer-command")
(bind-key "C-x C-s" "save-current-buffer")
(bind-key "C-c C-k" "compile-current")
(bind-key "C-c C-c" "compile-current")
(bind-key "C-x d" "dired-here")

;; ── Dired mode ──────────────────────────────────────────────────────────────
;; A simple file browser inspired by Emacs dired.

(def dired-current-dir "")
(def dired-entries '())

(define-mode "dired-mode" :read-only true)
(mode-bind-key "dired-mode" "g" "dired-refresh")
(mode-bind-key "dired-mode" "q" "dired-quit")
(mode-bind-key "dired-mode" "-" "dired-up")

;; Build the action callback for a directory entry
(def dired-entry-action (entry)
  (let ((name (get entry :name))
        (is-dir (get entry :directory)))
    (if is-dir
      (lambda ()
        (set! dired-current-dir (path-join dired-current-dir name))
        (dired-refresh))
      (lambda ()
        (open-file (path-join dired-current-dir name))))))

;; Build a single row widget for a dired entry
(def dired-entry-widget (entry)
  (let ((name (get entry :name))
        (is-dir (get entry :directory)))
    (if is-dir
      (h-stack :gap 1 :align :center :focusable true
        :on-enter (dired-entry-action entry)
        (label "▸" :color :yellow :width 2)
        (label (str name "/") :color :cyan))
      (h-stack :gap 1 :align :center :focusable true
        :on-enter (dired-entry-action entry)
        (label " " :width 2)
        (label name)))))

;; Refresh the *dired* buffer with a widget-based directory listing
(def dired-refresh ()
  (let ((entries (list-directory dired-current-dir))
        (dirs (filter |e| (get e :directory) entries))
        (files (filter |e| (not (get e :directory)) entries)))
    (set! dired-entries (append dirs files))
    (let ((header (label (str dired-current-dir ":")
                    :color :dim))
          (parent (h-stack :gap 1 :align :center :focusable true
                    :on-enter (lambda () (dired-up))
                    (label "▸" :color :purple :width 2)
                    (label "../" :color :purple)))
          (dir-widgets (map dired-entry-widget dirs))
          (file-widgets (map dired-entry-widget files))
          (all-widgets (cons header
                         (cons parent
                           (append dir-widgets file-widgets)))))
      (render-widget (v-stack :gap 0.125 :padding 0.5 :align :stretch all-widgets))
      (status (fmt "{} entries" (len dired-entries))))))

;; Navigate to parent directory
(def dired-up ()
  (let ((parent (path-parent dired-current-dir)))
    (if (= parent nil)
      (status "Already at root")
      (do
        (set! dired-current-dir parent)
        (dired-refresh)))))

;; Close dired and switch to previous buffer
(def dired-quit ()
  (let ((bufs (buffer-list)))
    (if (> (len bufs) 1)
      (switch-to-buffer (nth bufs 0))
      (status "No other buffer"))))

;; Entry point: open dired in current directory
(def dired-here ()
  (let ((dir (current-directory)))
    (set! dired-current-dir dir)
    (switch-or-create-buffer "*dired*")
    (set-buffer-mode "dired-mode")
    (dired-refresh)))

;; ── Buffer List mode ────────────────────────────────────────────────────────
;; Shows all open buffers and lets you switch between them.

(def buflist-source-buffer "")

(define-mode "buffer-list-mode" :read-only true)
(mode-bind-key "buffer-list-mode" "q" "buflist-quit")
(mode-bind-key "buffer-list-mode" "g" "buflist-refresh")

(def buflist-make-entry (name)
  (let ((is-current (= name buflist-source-buffer))
        (prefix (if is-current " > " "   "))
        (color (if is-current :yellow :white)))
    (label (str prefix name)
      :width 80
      :color color
      :focusable true
      :on-enter (lambda ()
                  (switch-to-buffer name)))))

(def buflist-refresh ()
  (let ((bufs (buffer-list))
        (header (label "  Buffers:"
                  :color :dim
                  :width 80))
        (entries (map buflist-make-entry bufs))
        (all-widgets (cons header entries)))
    (render-widget (v-stack all-widgets))
    (status (fmt "{} buffers" (len bufs)))))

(def buflist-quit ()
  (if (not (= buflist-source-buffer ""))
    (switch-to-buffer buflist-source-buffer)
    (let ((bufs (buffer-list)))
      (if (> (len bufs) 1)
        (switch-to-buffer (nth bufs 0))
        (status "No other buffer")))))

(def buffer-list-here ()
  (set! buflist-source-buffer (current-buffer-name))
  (switch-or-create-buffer "*buffers*")
  (set-buffer-mode "buffer-list-mode")
  (buflist-refresh))

(bind-key "C-x b" "buffer-list-here")

;; dired-open-at-cursor is no longer needed — Enter triggers :on-enter on focused widget
(bind-key "C-x v" "cycle-view-mode")
