(defmacro delay-bp-bank-8 (input delay_step base_freq freq_step q fb)
  (make-history history1)
  (make-history h1)
  (make-history h2)
  (make-history h3)
  (make-history h4)
  (make-history h5)
  (make-history h6)
  (make-history h7)
  (make-history h8)
  (def d1 (delay (+ input (* (read-history h1) fb)) (* 1.0 delay_step)))
  (def s1 (svf d1 (+ base_freq (* 1.0 freq_step)) q 1.0))
  (def w1 (write-history h1 s1))
  (def d2 (delay (+ input (* (read-history h2) fb)) (* 2.0 delay_step)))
  (def s2 (svf d2 (+ base_freq (* 2.0 freq_step)) q 1.0))
  (def w2 (write-history h2 s2))
  (def d3 (delay (+ input (* (read-history h3) fb)) (* 3.0 delay_step)))
  (def s3 (svf d3 (+ base_freq (* 3.0 freq_step)) q 1.0))
  (def w3 (write-history h3 s3))
  (def d4 (delay (+ input (* (read-history h4) fb)) (* 4.0 delay_step)))
  (def s4 (svf d4 (+ base_freq (* 4.0 freq_step)) q 1.0))
  (def w4 (write-history h4 s4))
  (def d5 (delay (+ input (* (read-history h5) fb)) (* 5.0 delay_step)))
  (def s5 (svf d5 (+ base_freq (* 5.0 freq_step)) q 1.0))
  (def w5 (write-history h5 s5))
  (def d6 (delay (+ input (* (read-history h6) fb)) (* 6.0 delay_step)))
  (def s6 (svf d6 (+ base_freq (* 6.0 freq_step)) q 1.0))
  (def w6 (write-history h6 s6))
  (def d7 (delay (+ input (* (read-history h7) fb)) (* 7.0 delay_step)))
  (def s7 (svf d7 (+ base_freq (* 7.0 freq_step)) q 1.0))
  (def w7 (write-history h7 s7))
  (def d8 (delay (+ input (* (read-history h8) fb)) (* 8.0 delay_step)))
  (def s8 (svf d8 (+ base_freq (* 8.0 freq_step)) q 1.0))
  (def w8 (write-history h8 s8))
  (* 0.125 (+ s1 s2 s3 s4 s5 s6 s7 s8)))
(defmacro frequency_shifter (input shift_freq)
  (make-history ax1)
  (make-history ay1)
  (make-history ax2)
  (make-history ay2)
  (make-history bx1)
  (make-history by1)
  (make-history bx2)
  (make-history by2)
  (def ax1_prev (read-history ax1))
  (def ay1_prev (read-history ay1))
  (def ap_a1 (+ (* 0.161758 input) ax1_prev (- (* 0.161758 ay1_prev))))
  (write-history ax1 input)
  (write-history ay1 ap_a1)
  (def ax2_prev (read-history ax2))
  (def ay2_prev (read-history ay2))
  (def I (+ (* 0.733075 ap_a1) ax2_prev (- (* 0.733075 ay2_prev))))
  (write-history ax2 ap_a1)
  (write-history ay2 I)
  (def bx1_prev (read-history bx1))
  (def by1_prev (read-history by1))
  (def ap_b1 (+ (* 0.479401 input) bx1_prev (- (* 0.479401 by1_prev))))
  (write-history bx1 input)
  (write-history by1 ap_b1)
  (def bx2_prev (read-history bx2))
  (def by2_prev (read-history by2))
  (def Q (+ (* 0.876218 ap_b1) bx2_prev (- (* 0.876218 by2_prev))))
  (write-history bx2 ap_b1)
  (write-history by2 Q)
  (def f_abs (abs shift_freq))
  (def phase (* (phasor f_abs) twopi))
  (def c (cos phase))
  (def s (sin phase))
  (- (* I c) (* (sign shift_freq) Q s)))
(defmacro fbdelay (input delaytime fb)
  (make-history history1)
  (def mul1 (* (read-history history1) fb))
  (def add1 (+ input mul1))
  (def delay1 (delay add1 delaytime))
  (write-history history1 delay1)
  delay1)
(param bankfb @min 0.0 @max 0.5)
(def value5 500.0)
(def value4 50.0)
(def value3 16.0)
(def value2 500.0)
(def value1 50.0)
(param wetmix @min 0.0 @max 1.0)
(param q @min 1.0 @max 16.0 @default 1.0)
(param fb)
(def input_l (in 1 @name Left))
(def input_r (in 2 @name Right))
(def mod1 (in 3 @name mod1 @modulator 1))
(def mod2 (in 4 @name mod2 @modulator 2))
(def mod3 (in 5 @name mod3 @modulator 3))
(def mod4 (in 6 @name mod4 @modulator 4))
(param delaywidth @min 100.0 @max 10000.0 @mod true @mod-mode additive)
(def modulated3 (mod delaywidth))
(param freqshift @min 0.0 @max 1000.0 @mod true @mod-mode additive)
(def modulated2 (mod freqshift))
(param xyz @mod true @mod-mode additive @min 50.0 @max 10000.0 @default 500.0)
(def modulated1 (mod xyz))
(def fbdelay2 (fbdelay input_l modulated1 fb))
(def frequency_shifter2 (frequency_shifter fbdelay2 modulated2))
(def delay-bp-bank-81 (delay-bp-bank-8 frequency_shifter2 modulated3 value1 value2 q bankfb))
(def fbdelay1 (fbdelay input_r modulated1 fb))
(def frequency_shifter1 (frequency_shifter fbdelay1 modulated2))
(def delay-bp-bank-82 (delay-bp-bank-8 frequency_shifter1 modulated3 value4 value5 q bankfb))
(def processed_l input_l)
(def processed_r input_r)
(out (mix input_l delay-bp-bank-81 wetmix) 1 @name Left)
(out (mix input_r delay-bp-bank-82 wetmix) 2 @name Right)