(defmacro frequency_shifter (input shift_freq)
  (make-history ax1)
  (make-history ay1)
  (make-history ax2)
  (make-history ay2)
  (make-history bx1)
  (make-history by1)
  (make-history bx2)
  (make-history by2)
  (def ax1_prev (read-history ax1))
  (def ay1_prev (read-history ay1))
  (def ap_a1 (+ (* 0.161758 input) ax1_prev (- (* 0.161758 ay1_prev))))
  (write-history ax1 input)
  (write-history ay1 ap_a1)
  (def ax2_prev (read-history ax2))
  (def ay2_prev (read-history ay2))
  (def I (+ (* 0.733075 ap_a1) ax2_prev (- (* 0.733075 ay2_prev))))
  (write-history ax2 ap_a1)
  (write-history ay2 I)
  (def bx1_prev (read-history bx1))
  (def by1_prev (read-history by1))
  (def ap_b1 (+ (* 0.479401 input) bx1_prev (- (* 0.479401 by1_prev))))
  (write-history bx1 input)
  (write-history by1 ap_b1)
  (def bx2_prev (read-history bx2))
  (def by2_prev (read-history by2))
  (def Q (+ (* 0.876218 ap_b1) bx2_prev (- (* 0.876218 by2_prev))))
  (write-history bx2 ap_b1)
  (write-history by2 Q)
  (def f_abs (abs shift_freq))
  (def phase (* (phasor f_abs) twopi))
  (def c (cos phase))
  (def s (sin phase))
  (- (* I c) (* (sign shift_freq) Q s)))
(defmacro fbdelay (input delaytime fb)
  (make-history history1)
  (def mul1 (* (read-history history1) fb))
  (def add1 (+ input mul1))
  (def delay1 (delay add1 delaytime))
  (write-history history1 delay1)
  delay1)
(param fb)
(def input_l (in 1 @name Left))
(def input_r (in 2 @name Right))
(def mod1 (in 3 @name mod1 @modulator 1))
(def mod2 (in 4 @name mod2 @modulator 2))
(def mod3 (in 5 @name mod3 @modulator 3))
(def mod4 (in 6 @name mod4 @modulator 4))
(param freqshift @min 0.0 @max 1000.0 @mod true @mod-mode additive)
(def modulated2 (mod freqshift))
(param xyz @mod true @mod-mode additive @min 50.0 @max 10000.0 @default 500.0)
(def modulated1 (mod xyz))
(def fbdelay2 (fbdelay input_l modulated1 fb))
(def frequency_shifter2 (frequency_shifter fbdelay2 modulated2))
(def fbdelay1 (fbdelay input_r modulated1 fb))
(def frequency_shifter1 (frequency_shifter fbdelay1 modulated2))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def processed_l input_l)
(def processed_r input_r)
(out (mix frequency_shifter2 processed_l mix-amt) 1 @name Left)
(out (mix frequency_shifter1 processed_r mix-amt) 2 @name Right)