(use-defmacro pitch-transpose)
(def value2 5.0)
(use-defmacro simp2)
(use-defmacro simp11)
(use-defmacro gain2)
(def value1 0.3)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def pitch-transpose1 (pitch-transpose pitch value2))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def phasor1 (phasor value1 trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))
(param depth @min 1.0 @max 16.0 @mod true @mod-mode additive @default 1.0)
(def modulated1 (mod depth))
(def simp112 (simp11 pitch-transpose1 phasor1 modulated1))
(def simp111 (simp11 pitch phasor1 modulated1))
(def mix1 (mix simp111 simp112 0.5))
(param attack @group amp @env amp-env @role attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @group amp @env amp-env @role decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0.0 @max 1.0)
(param release @group amp @env amp-env @role release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def mul1 (* mix1 velocity env (mod gain)))
(def svf1 (svf mul1 100.0 1.0 1.0))
(out svf1 1 @name audio)