(make-history history1)
(defmacro op (input) (def pow1 (pow input 2.0)) (def scale1 (scale pow1 0.0 1.0 -3.14 3.14)) (def cos1 (cos scale1)) cos1)
(def value2 0.2)
(def value1 0.1)
(def phasor2 (phasor value2))
(def phasor1 (phasor value1))
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def svf1 (svf (read-history history1) pitch 0.2 0.0))
(def phasor3 (phasor pitch))
(def triangle1 (triangle phasor3 phasor1))
(def mul1 (* triangle1 twopi))
(def add2 (+ svf1 mul1))
(def cos1 (cos add2))
(def mul2 (* cos1 phasor2))
(def mul4 (* mul2 -3.0))
(def mul3 (* mul2 2.0))
(def cos2 (cos mul4))
(def sin1 (sin mul3))
(def add1 (+ sin1 cos2))
(def mul5 (* add1 0.5))
(def op1 (op mul5))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(out (* op1 env velocity (mod gain)) 1 @name audio)
(write-history history1 mul5)