;; Dispatcher from built-in audio effect name to custom panel body.
(module eseq.effects.builtin.audio-fx)

(import eseq.effects.builtin.filter-panel :as flt)
(import eseq.effects.builtin.eq8 :as eq8)
(import eseq.effects.builtin.str8-delay :as sd)
(import eseq.effects.builtin.space-echo :as se)
(import eseq.effects.builtin.multiverb :as mv)
(import eseq.effects.builtin.dimension :as dim)
(import eseq.effects.builtin.phaser-flanger :as pf)
(import eseq.effects.builtin.roar :as roar)
(import eseq.effects.builtin.dj-mixer :as djm)
(import eseq.effects.builtin.dynamics :as dyn)
(import eseq.effects.builtin.compressor :as comp)
(import eseq.effects.builtin.multiband :as mb)
(import eseq.effects.builtin.tape :as tape)
(import eseq.effects.builtin.convolution-reverb :as cr)
(import eseq.effects.builtin.filterbank :as fb)

;; Migration alias (module spec §10). builtin-audio-fx-ui keeps its spelling —
;; the prefix is the host-facing entry-point name, and the Rust harnesses in
;; src/ui/state_values/tests.rs eval it bare (reads only, so the alias covers
;; them). The converted eseq.effects.panel-bodies imports this module instead.
;; Deleted when those tests move to the qualified spelling.
(module-compat-alias builtin-audio-fx-ui builtin-audio-fx-ui)

(def builtin-audio-fx-ui (fx)
  (if (= (get fx :name) "Filter")
    (flt/panel fx)
    (if (= (get fx :name) "EQ8")
      (eq8/eq8-ui fx)
      (if (= (get fx :name) "Str8 Delay")
        (sd/builtin-fx-str8-delay-ui fx)
        (if (= (get fx :name) "Space Echo")
          (se/panel-ui fx)
        (if (= (get fx :name) "Multiverb")
          (mv/builtin-fx-multiverb-ui fx)
        (if (= (get fx :name) "Dimension")
          (dim/builtin-fx-dimension-ui fx)
        (if (= (get fx :name) "Phaser-Flanger")
          (pf/panel-ui fx)
        (if (= (get fx :name) "Roar")
          (roar/panel fx)
        (if (= (get fx :name) "DJ Mixer")
          (djm/panel fx)
          (if (or (= (get fx :name) "444 Compressor")
                  (= (get fx :name) "Glue Compressor"))
            (dyn/dynamics-ui fx)
            (if (= (get fx :name) "Compressor")
              (comp/builtin-fx-compressor-ui fx)
              (if (= (get fx :name) "OTT")
                (mb/ott-ui fx)
              (if (= (get fx :name) "Limiter")
                (dyn/limiter-ui fx)
                (if (= (get fx :name) "Tape")
                  (tape/tape-ui fx)
                  (if (= (get fx :name) "Convolution Reverb")
                    (cr/convolution-reverb-ui fx)
                    (if (= (get fx :name) "Filterbank")
                      (fb/panel fx)
                      false)))))))))))))))))
