(defmacro pitch-glide (pitch_hz glide_ms)
  (make-history h)
  (def target (log (clip pitch_hz 1.0 22000.0)))
  (def t_ms (clip glide_ms 0.05 10000.0))
  (def coef (exp (/ -1.0 (* t_ms samplerate 0.001))))
  (def prev (read-history h))
  (def smoothed (+ (* target (- 1.0 coef)) (* prev coef)))
  (write-history h smoothed)
  (exp smoothed))
(param portamento @min 0.0 @max 1000.0 @default 0.0)
(param fm.release @min 0.0 @max 10000.0 @default 1000.0 @env fm @role release @group fm)
(param fm.sustain @min 0.0 @max 1.0 @default 0.3 @env fm @role sustain @group fm)
(param fm.decay @min 0.0 @max 10000.0 @default 2.0 @env fm @role decay @group fm)
(param fm.attack @min 0.0 @max 10000.0 @default 2.0 @env fm @role attack @group fm)
(param filter.env @group filter @min -1.0 @max 1.0 @default 0.0)
(param filter.decay @group filter @min 0.0 @max 10000.0 @unit ms @role decay @env filter-env)
(param filter.attack @group filter @min 0.0 @max 10000.0 @unit ms @role attack @env filter-env)
(param filter.release @group filter @min 0.0 @max 10000.0 @default 550.0 @env filter-env @role release)
(param filter.sustain @group filter @min 0.0 @max 1.0 @role sustain @env filter-env)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def pitch-glide1 (pitch-glide pitch portamento))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def adsr2 (adsr gate trigger fm.attack fm.decay fm.sustain fm.release))
(def adsr1 (adsr gate trigger filter.attack filter.decay filter.sustain filter.release))
(def mul1 (* adsr1 filter.env))
(def mul7 (* mul1 10000.0))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param index @min 0.0 @max 10.0 @mod true @mod-mode additive @group fm)
(param harmonicity @min 0.125 @max 16.0 @default 2.0 @mod true @mod-mode additive @group fm)
(def modulated1 (mod harmonicity))
(def mul3 (* pitch-glide1 modulated1))
(def phasor1 (phasor mul3))
(def mul6 (* phasor1 twopi))
(def cos2 (cos mul6))
(def mul4 (* cos2 (mod index)))
(def mul5 (* mul4 adsr2))
(param trishape @min 0.0 @max 1.0 @mod true @mod-mode additive @group shape)
(param hires @min 0.5 @default 2.0 @max 20.0 @mod true @mod-mode additive @group filter)
(param hicut @min 50.0 @max 10000.0 @default 50.0 @mod true @mod-mode additive @group filter)
(param res @min 0.5 @max 10.0 @default 2.0 @mod true @mod-mode additive @group filter)
(param cutoff @min 50.0 @max 10000.0 @default 50.0 @mod true @mod-mode additive @group filter)
(def add1 (+ mul7 cutoff))
(def clip1 (clip add1 10.0 10000.0))
(param attack @group amp @env amp-env @role attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @group amp @env amp-env @role decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0.0 @max 1.0)
(param release @group amp @env amp-env @role release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch-glide1))
(def triangle1 (triangle phase (mod trishape)))
(def mul2 (* triangle1 twopi))
(def add2 (+ mul5 mul2))
(def cos1 (cos add2))
(def svf1 (svf (* cos1 env velocity (mod gain)) clip1 (mod res) 0.0))
(def svf2 (svf svf1 (mod hicut) (mod hires) 1.0))
(out svf2 1 @name audio)
