; Videogame Synth - compact chiptune/game-console style instrument
; Two pulse/shape oscillators, triangle bass, stepped noise, arpeggiator,
; pitch blip envelope, vibrato/PWM, filter, drive, and bit quantization.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(defmacro chip_wave (phase freq width wave)
  (def idx (clip (round wave) 0 3))
  (def pulse (polyblep_pulse phase width freq))
  (def saw (polyblep_saw phase freq))
  (def tri (triangle phase))
  (def sine (sin (* phase twopi)))
  (selector (+ idx 1) pulse saw tri sine))

(defmacro quantize (x steps)
  (/ (round (* x steps)) steps))

(param osc1_wave @default 0 @min 0 @max 3)
(param osc1_octave @default 0 @min -2 @max 2 @unit oct)
(param osc1_semitones @default 0 @min -24 @max 24 @unit st)
(param osc1_level @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)
(param pulse_width1 @default 0.50 @min 0.05 @max 0.95 @mod true @mod-mode additive)

(param osc2_wave @default 0 @min 0 @max 3)
(param osc2_octave @default 0 @min -2 @max 2 @unit oct)
(param osc2_semitones @default 7 @min -24 @max 24 @unit st)
(param osc2_detune @default 0 @min -50 @max 50 @unit ct)
(param osc2_level @default 0.38 @min 0 @max 1 @mod true @mod-mode additive)
(param pulse_width2 @default 0.25 @min 0.05 @max 0.95 @mod true @mod-mode additive)

(param tri_octave @default -1 @min -3 @max 1 @unit oct)
(param tri_level @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param noise_level @default 0.08 @min 0 @max 1 @mod true @mod-mode additive)
(param noise_rate @default 1800 @min 40 @max 12000 @unit Hz)
(param noise_tone @default 0 @min 0 @max 2)

(param arp_pattern @default 1 @min 0 @max 4)
(param arp_steps @default 4 @min 1 @max 4)
(param arp_rate @default 12 @min 1 @max 32 @unit Hz)
(param arp_amount @default 1 @min 0 @max 1)

(param pitch_env_amt @default 5 @min -24 @max 24 @unit st)
(param pitch_decay @default 45 @min 5 @max 600 @unit ms)
(param vibrato_rate @default 6 @min 0.1 @max 18 @unit Hz)
(param vibrato_depth @default 0.04 @min 0 @max 1.5 @unit st)
(param pwm_rate @default 4 @min 0.1 @max 18 @unit Hz)
(param pwm_amount @default 0.08 @min 0 @max 0.45)

(param amp_attack @default 2 @min 1 @max 800 @unit ms)
(param amp_decay @default 90 @min 5 @max 2000 @unit ms)
(param amp_sustain @default 0.62 @min 0 @max 1)
(param amp_release @default 35 @min 5 @max 2000 @unit ms)

(param cutoff @default 6200 @min 80 @max 14000 @unit Hz @mod true @mod-mode additive)
(param resonance @default 0.72 @min 0.45 @max 4.0 @mod true @mod-mode additive)
(param filter_mode @default 0 @min 0 @max 2)
(param filter_env_amt @default 900 @min -6000 @max 6000 @unit Hz)
(param lfo_to_cutoff @default 0 @min 0 @max 3200 @unit Hz)

(param drive @default 1.25 @min 0.5 @max 6 @mod true @mod-mode additive)
(param bit_depth @default 7 @min 3 @max 14)
(param dry_chip @default 0.68 @min 0 @max 1)
(param output_gain @default 0.38 @min 0 @max 1 @mod true @mod-mode additive)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))
(def pitch_env (adsr gate trigger 1 pitch_decay 0 20))
(def lfo (sin (* (phasor vibrato_rate) twopi)))
(def pwm_lfo (sin (* (phasor pwm_rate) twopi)))

(def arp_phase (phasor arp_rate))
(def step_count (clip (round arp_steps) 1 4))
(def arp_step (clip (floor (* arp_phase step_count)) 0 3))
(def pat0 (selector (+ arp_step 1) 0 0 0 0))
(def pat1 (selector (+ arp_step 1) 0 7 12 7))
(def pat2 (selector (+ arp_step 1) 0 3 7 10))
(def pat3 (selector (+ arp_step 1) 0 4 7 11))
(def pat4 (selector (+ arp_step 1) 0 12 7 19))
(def arp_semi (selector (+ (clip (round arp_pattern) 0 4) 1) pat0 pat1 pat2 pat3 pat4))

(def pitch_semi (+ (* arp_semi arp_amount) (* pitch_env pitch_env_amt) (* lfo vibrato_depth)))
(def base_freq (* pitch (semi_ratio pitch_semi)))
(def f1 (* base_freq (semi_ratio (+ (* (clip (round osc1_octave) -2 2) 12) osc1_semitones))))
(def f2 (* base_freq (semi_ratio (+ (* (clip (round osc2_octave) -2 2) 12) osc2_semitones (/ osc2_detune 100.0)))))
(def ft (* base_freq (semi_ratio (* (clip (round tri_octave) -3 1) 12))))

(def pw1 (clip (+ (mod pulse_width1) (* pwm_lfo pwm_amount)) 0.05 0.95))
(def pw2 (clip (- (mod pulse_width2) (* pwm_lfo pwm_amount 0.65)) 0.05 0.95))
(def ph1 (phasor f1))
(def ph2 (phasor f2))
(def pht (phasor ft))
(def osc1 (chip_wave ph1 f1 pw1 osc1_wave))
(def osc2 (chip_wave ph2 f2 pw2 osc2_wave))
(def tri (triangle pht))

(def noise_phase (phasor noise_rate))
(make-history noise_phase_hist)
(def prev_noise_phase (read-history noise_phase_hist))
(def noise_tick (lt noise_phase prev_noise_phase))
(make-history noise_hist)
(def prev_noise (read-history noise_hist))
(def held_noise (gswitch noise_tick (noise) prev_noise))
(write-history noise_hist held_noise)
(write-history noise_phase_hist noise_phase)
(def bright_noise held_noise)
(def dark_noise (svf held_noise 1100 0.7 0))
(def thin_noise (svf held_noise 2600 0.8 1))
(def chip_noise (selector (+ (clip (round noise_tone) 0 2) 1) bright_noise dark_noise thin_noise))

(def raw_mix (+ (* osc1 (clip (mod osc1_level) 0 1) 0.72)
                (* osc2 (clip (mod osc2_level) 0 1) 0.62)
                (* tri (clip (mod tri_level) 0 1) 0.58)
                (* chip_noise (clip (mod noise_level) 0 1) 0.46)))

(def filter_lfo (sin (* (phasor 3.5) twopi)))
(def filt_cut (clip (+ (mod cutoff) (* amp_env filter_env_amt) (* filter_lfo lfo_to_cutoff)) 80 14000))
(def filt_q (clip (mod resonance) 0.45 4.0))
(def filt_mode (clip (round filter_mode) 0 2))
(def filtered (svf raw_mix filt_cut filt_q filt_mode))
(def chip_mix (+ (* filtered (- 1 dry_chip)) (* raw_mix dry_chip)))
(def driven (tanh (* chip_mix (clip (mod drive) 0.5 6))))
(def bit_steps (pow 2 (clip (round bit_depth) 3 14)))
(def crushed (quantize driven bit_steps))
(def vel_amp (+ 0.35 (* velocity 0.65)))

(out (* crushed amp_env vel_amp (clip (mod output_gain) 0 1)) 1 @name audio)
