;; One split velocity-wave string, excited by bow friction and/or a pluck.
;; Articulations change controls, never the resonator topology or audio source.
;; Physical assumptions and reference comparisons: tools/pm-cello/README.md.

(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro cello-smooth (target ms)
  (make-history previous)
  (make-history ready)
  (def pole (exp (/ -1 (* 0.001 ms samplerate))))
  (def value (gswitch (read-history ready) (mix target (read-history previous) pole) target))
  (write-history previous value)
  (write-history ready 1)
  value)

(defmacro cello-age (gate trigger)
  (make-history elapsed)
  (make-history last_gate)
  (make-history has_note)
  (def onset (max trigger (* (gt gate 0.5) (lte (read-history last_gate) 0.5))))
  (def armed (max onset (read-history has_note)))
  ;; An unplayed voice must not emit the beginning of a pluck during init.
  (def age (gswitch onset 0
    (gswitch armed (min 120 (+ (read-history elapsed) (/ 1 samplerate))) 120)))
  (write-history elapsed age)
  (write-history last_gate gate)
  (write-history has_note armed)
  age)

(defmacro cello-string (frequency contact speed pressure curve position pluck cutoff decay_s warp)
  (make-history bridge_h)
  (make-history neck_h)
  (make-history low_h)
  (make-history ap_x)
  (make-history ap_y)
  (make-history dc_x)
  (make-history dc_y)
  (def f (clip frequency 30 1600))
  (def period (/ samplerate f))
  (def omega (/ twopi period))
  (def pole (exp (/ (* -1 twopi cutoff) samplerate)))
  (def low_phase (/ (atan (/ (* pole (sin omega)) (- 1 (* pole (cos omega))))) omega))
  (def low_magnitude (/ (- 1 pole) (sqrt (+ 1 (* pole pole) (* -2 pole (cos omega))))))
  (def a (- warp))
  (def half_omega (* 0.5 omega))
  (def ap_phase (/ (* 2 (atan (* (/ (- 1 a) (+ 1 a))
    (/ (sin half_omega) (cos half_omega))))) omega))
  ;; Loss/dispersion live on the longer segment so the short bridge segment
  ;; remains causal even near the bridge. Both explicit histories cost a sample.
  (def bridge_length (max 1 (- (* period position) 1)))
  (def neck_length (max 1 (- (* period (- 1 position)) low_phase ap_phase 1)))
  (def bridge_wave (delay (read-history bridge_h) bridge_length))
  (def neck_wave (delay (read-history neck_h) neck_length))
  (def low (mix neck_wave (read-history low_h) pole))
  (def dispersed (+ (* a low) (read-history ap_x) (* (- a) (read-history ap_y))))
  ;; Compensate the fundamental's loss only while the termination stays passive.
  (def loss (min 0.999999 (/ (pow 0.001 (/ 1 (* decay_s f))) low_magnitude)))
  (def from_neck (* (- loss) dispersed))
  (def from_bridge (- bridge_wave))
  (def relative (- speed (+ from_bridge from_neck)))
  ;; A bounded, memoryless approximation to the solved bow scattering curve.
  (def slip (+ 0.75 (/ (abs relative) (+ 0.1 (* 0.6 pressure)))))
  (def reflection (* contact (min 0.999 (pow slip (- curve)))))
  (def drive (+ (* relative reflection) pluck))
  (def to_bridge (+ from_neck drive))
  (def to_neck (+ from_bridge drive))
  (def dc (+ (- bridge_wave (read-history dc_x))
    (* (exp (/ (* -10 twopi) samplerate)) (read-history dc_y))))
  (write-history bridge_h to_bridge)
  (write-history neck_h to_neck)
  (write-history low_h low)
  (write-history ap_x low)
  (write-history ap_y dispersed)
  (write-history dc_x bridge_wave)
  (write-history dc_y dc)
  dc)

(defmacro cello-body (signal amount size q low_hz low mid_hz mid high_hz high air_hz air)
  (def b1 (/ (svf signal (/ low_hz size) q 1) q))
  (def b2 (/ (svf signal (/ mid_hz size) q 1) q))
  (def b3 (/ (svf signal (/ high_hz size) q 1) q))
  (def b4 (/ (svf signal (/ air_hz size) q 1) q))
  (def modes (/ (+ (* b1 low) (* b2 mid) (* b3 high) (* b4 air))
    (max 0.001 (+ low mid high air))))
  (mix signal modes amount))

(param attack @group amp @env amp-env @role attack @default 3655.08123 @min 0 @max 6000 @unit ms)
(param decay @group amp @env amp-env @role decay @default 100 @min 1 @max 3000 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 1 @min 0 @max 1)
(param release @group amp @env amp-env @role release @default 122.426594 @min 1 @max 5000 @unit ms)
(param amount @group bow @default 1 @min 0 @max 1 @mod true @mod-mode additive)
(param speed @group bow @default 0.253383 @min 0 @max 0.8 @mod true @mod-mode additive)
(param pressure @group bow @default 0.837904 @min 0.02 @max 1 @mod true @mod-mode additive)
(param rosin @group bow @default 4.782031 @min 1 @max 8 @mod true @mod-mode additive)
(param noise @group bow @default 0.114822 @min 0 @max 0.3 @mod true @mod-mode additive)
(param stroke_ms @group bow @default 3329.840495 @min 0 @max 6000 @unit ms)
(param strength @group pluck @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param width_ms @group pluck @default 3 @min 0.2 @max 25 @unit ms @mod true @mod-mode additive)
(param texture @group pluck @default 0.05 @min 0 @max 1 @mod true @mod-mode additive)
(param position @group string @default 0.100276 @min 0.08 @max 0.5 @mod true @mod-mode additive)
(param damping_hz @group string @default 2768.179842 @min 500 @max 15000 @unit Hz @mod true @mod-mode additive)
(param decay_s @group string @default 3.876537 @min 0.08 @max 12 @unit s @mod true @mod-mode additive)
(param stiffness @group string @default 0 @min 0 @max 0.75 @mod true @mod-mode additive)
(param tune @group string @default 0 @min -100 @max 100 @unit cents @mod true @mod-mode additive)
(param wood @group body @default 0.900059 @min 0 @max 1 @mod true @mod-mode additive)
(param size @group body @default 1 @min 0.5 @max 2 @mod true @mod-mode additive)
(param resonance @group body @default 6.131939 @min 0.5 @max 8 @mod true @mod-mode additive)
(param low_hz @group body @default 96.909571 @min 60 @max 350 @unit Hz @mod true @mod-mode additive)
(param low @group body @default 0.734229 @min 0 @max 1 @mod true @mod-mode additive)
(param mid_hz @group body @default 220.664738 @min 120 @max 900 @unit Hz @mod true @mod-mode additive)
(param mid @group body @default 0.858874 @min 0 @max 1 @mod true @mod-mode additive)
(param high_hz @group body @default 552.169447 @min 250 @max 2500 @unit Hz @mod true @mod-mode additive)
(param high @group body @default 1 @min 0 @max 1 @mod true @mod-mode additive)
(param air_hz @group body @default 862.501904 @min 600 @max 6000 @unit Hz @mod true @mod-mode additive)
(param air @group body @default 0.958391 @min 0 @max 1 @mod true @mod-mode additive)
(param tone_hz @group body @default 13016.732571 @min 400 @max 16000 @unit Hz @mod true @mod-mode additive)
(param vib_cent @group expression @default 0 @min 0 @max 100 @unit cents @mod true @mod-mode additive)
(param vib_hz @group expression @default 5 @min 0.1 @max 12 @unit Hz @mod true @mod-mode additive)
(param vib_wait @group expression @default 300 @min 0 @max 3000 @unit ms)
(param vel_bow @group expression @default 0.3 @min 0 @max 1)
(param blend @group section @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param spread @group section @default 15 @min 0 @max 50 @unit cents @mod true @mod-mode additive)
(param lag_ms @group section @default 12 @min 0 @max 40 @unit ms @mod true @mod-mode additive)
(param width @group section @default 0.7 @min 0 @max 1 @mod true @mod-mode additive)
(param gain @default 0.895561 @min 0 @max 1 @mod true @mod-mode additive)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def age (cello-age gate trigger))
(def stroke_gate (* gate (max (lte stroke_ms 0) (lt age (* 0.001 stroke_ms)))))
(def envelope (adsr stroke_gate trigger attack decay sustain release))
(def contact_envelope (adsr stroke_gate trigger 2 1 1 release))
(def vibrato_fade (clip (/ (- age (* 0.001 vib_wait)) 0.15) 0 1))
(def vibrato (* vibrato_fade (clip (mod vib_cent) 0 100)
  (sin (* twopi (phasor (clip (mod vib_hz) 0.1 12))))))
(def frequency (* pitch (pow 2 (/ (+ vibrato (clip (mod tune) -100 100)) 1200))))
(def bow_amount (cello-smooth (clip (mod amount) 0 1) 5))
(def bow_pressure (cello-smooth (clip (mod pressure) 0.02 1) 5))
(def bow_speed (cello-smooth (clip (mod speed) 0 0.8) 8))
(def friction_curve (cello-smooth (clip (mod rosin) 1 8) 5))
(def position_value (cello-smooth (clip (mod position) 0.08 0.5) 8))
(def damping (cello-smooth (clip (mod damping_hz) 500 15000) 8))
(def lifetime (cello-smooth (clip (mod decay_s) 0.08 12) 8))
(def warp (cello-smooth (clip (mod stiffness) 0 0.75) 8))
(def texture_noise (svf (noise) 5000 0.7 0))
(def motion (* envelope bow_speed (mix 1 (clip velocity 0 1) vel_bow)
  (+ 1 (* (clip (mod noise) 0 0.3) texture_noise))))
(def pluck_time (/ age (* 0.001 (clip (mod width_ms) 0.2 25))))
(def pulse (* (lt pluck_time 1) (sin (* pi (clip pluck_time 0 1)))))
(def pluck_drive (* (clip (mod strength) 0 1) pulse
  (mix 1 texture_noise (clip (mod texture) 0 1))))
(def string_wave (cello-string frequency (* bow_amount contact_envelope) motion bow_pressure friction_curve
  position_value pluck_drive damping lifetime warp))
(def detune (cello-smooth (clip (mod spread) 0 50) 8))
(def lag_samples (* 0.001 samplerate (clip (mod lag_ms) 0 40)))
;; The section repeats this exact same physical string with detuned tuning and
;; staggered excitation. Blend=0 is the central player; no alternate engine.
(def second_string (cello-string (* frequency (pow 2 (/ (- detune) 1200)))
  (delay (* bow_amount contact_envelope) lag_samples) (delay motion lag_samples)
  bow_pressure friction_curve position_value (delay pluck_drive lag_samples) damping lifetime warp))
(def third_string (cello-string (* frequency (pow 2 (/ detune 1200)))
  (delay (* bow_amount contact_envelope) (* 2 lag_samples)) (delay motion (* 2 lag_samples))
  bow_pressure friction_curve position_value (delay pluck_drive (* 2 lag_samples)) damping lifetime warp))
(def ensemble (cello-smooth (clip (mod blend) 0 1) 8))
(def stereo (clip (mod width) 0 1))
(def left_string (mix string_wave
  (/ (+ string_wave (* second_string (+ 1 stereo)) (* third_string (- 1 stereo))) 3) ensemble))
(def right_string (mix string_wave
  (/ (+ string_wave (* second_string (- 1 stereo)) (* third_string (+ 1 stereo))) 3) ensemble))
(def left_body (cello-body left_string (clip (mod wood) 0 1) (clip (mod size) 0.5 2)
  (clip (mod resonance) 0.5 8) (clip (mod low_hz) 60 350) (clip (mod low) 0 1)
  (clip (mod mid_hz) 120 900) (clip (mod mid) 0 1)
  (clip (mod high_hz) 250 2500) (clip (mod high) 0 1)
  (clip (mod air_hz) 600 6000) (clip (mod air) 0 1)))
(def right_body (cello-body right_string (clip (mod wood) 0 1) (clip (mod size) 0.5 2)
  (clip (mod resonance) 0.5 8) (clip (mod low_hz) 60 350) (clip (mod low) 0 1)
  (clip (mod mid_hz) 120 900) (clip (mod mid) 0 1)
  (clip (mod high_hz) 250 2500) (clip (mod high) 0 1)
  (clip (mod air_hz) 600 6000) (clip (mod air) 0 1)))
(def left (svf left_body (min (* samplerate 0.4) (clip (mod tone_hz) 400 16000)) 0.7 0))
(def right (svf right_body (min (* samplerate 0.4) (clip (mod tone_hz) 400 16000)) 0.7 0))
(out (* left (clip velocity 0 1) (clip (mod gain) 0 1)) 1 @name left)
(out (* right (clip velocity 0 1) (clip (mod gain) 0 1)) 2 @name right)
