(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))

(param amp_attack @default 2 @min 1 @max 500 @unit ms)
(param amp_decay @default 220 @min 1 @max 2500 @unit ms)
(param amp_sustain @default 0.72 @min 0 @max 1)
(param amp_release @default 95 @min 1 @max 2500 @unit ms)

(param mod_attack @default 1 @min 1 @max 500 @unit ms)
(param mod_decay @default 145 @min 1 @max 2000 @unit ms)
(param mod_sustain @default 0.18 @min 0 @max 1)
(param mod_release @default 80 @min 1 @max 2000 @unit ms)

(param filt_attack @default 2 @min 1 @max 500 @unit ms)
(param filt_decay @default 180 @min 1 @max 2500 @unit ms)
(param filt_sustain @default 0.05 @min 0 @max 1)
(param filt_release @default 120 @min 1 @max 3000 @unit ms)

(param carrier_ratio @default 1 @min 0.25 @max 4)
(param mod_ratio @default 2 @min 0.25 @max 12)
(param sub_level @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)
(param carrier_level @default 0.78 @min 0 @max 1 @mod true @mod-mode additive)
(param mod_index @default 4.2 @min 0 @max 14 @mod true @mod-mode additive)
(param mod_env_amt @default 6.0 @min 0 @max 18)
(param second_mod_ratio @default 3 @min 0.25 @max 16)
(param second_mod_level @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)

(param pitch_env_amt @default 18 @min 0 @max 180 @unit Hz)
(param pitch_decay @default 45 @min 1 @max 500 @unit ms)
(param click_level @default 0.08 @min 0 @max 1)
(param click_decay @default 14 @min 1 @max 120 @unit ms)

(param cutoff @default 980 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param resonance @default 0.24 @min 0 @max 0.95 @mod true @mod-mode additive)
(param filter_env_amt @default 1450 @min 0 @max 9000 @unit Hz)
(param drive @default 2.1 @min 0.5 @max 8 @mod true @mod-mode additive)
(param tone @default 0.62 @min 0 @max 1)
(param gain @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))
(def fm_env (adsr gate trigger mod_attack mod_decay mod_sustain mod_release))
(def filt_env (adsr gate trigger filt_attack filt_decay filt_sustain filt_release))
(def pitch_env (adsr gate trigger 1 pitch_decay 0 1))
(def click_env (adsr gate trigger 1 click_decay 0 1))

(def base_freq (max 8 (+ pitch (* pitch_env pitch_env_amt))))
(def car_freq (* base_freq carrier_ratio))
(def mod_freq (* base_freq mod_ratio))
(def mod2_freq (* base_freq second_mod_ratio))
(def sub_freq (* base_freq 0.5))

(def car_phase (phasor car_freq))
(def mod_phase (phasor mod_freq))
(def mod2_phase (phasor mod2_freq))
(def sub_phase (phasor sub_freq))

(def mod_a (sin (* mod_phase twopi)))
(def mod_b (sin (* mod2_phase twopi)))
(def total_index (+ (clip (mod mod_index) 0 14) (* fm_env mod_env_amt)))
(def phase_fm (* total_index (+ mod_a (* mod_b (clip (mod second_mod_level) 0 1)))))
(def carrier (sin (+ (* car_phase twopi) phase_fm)))
(def sub (sin (* sub_phase twopi)))
(def click (* click_env (noise)))

(def raw_mix (+ (* carrier (clip (mod carrier_level) 0 1)) (* sub (clip (mod sub_level) 0 1)) (* click click_level)))
(def shaped (tanh (* raw_mix (clip (mod drive) 0.5 8))))
(def bright_cut (+ (mod cutoff) (* filt_env filter_env_amt)))
(def dark_cut (* bright_cut (+ 0.45 (* tone 0.85))))
(def filtered (ladder shaped (clip dark_cut 40 12000) (clip (mod resonance) 0 0.95) (clip (mod drive) 0.5 8)))

(out (* filtered amp_env velocity (clip (mod gain) 0 1)) 1 @name audio)
