(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def mul7 (* pitch 0.003))
(def mul4 (* pitch 8.0))
(def phasor1 (phasor mul4))
(def mul5 (* phasor1 twopi))
(def cos3 (cos mul5))
(def mul3 (* cos3 0.1))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def phasor2 (phasor mul7 trigger))
(def mul2 (* phasor2 twopi))
(def cos2 (cos mul2))
(def scale1 (scale cos2 -1.0 1.0 0.1 0.9))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def triangle1 (triangle phase scale1))
(def mul1 (* triangle1 twopi))
(def mul6 (* mul3 mul1))
(def add1 (+ mul3 mul1))
(def mix1 (mix mul6 add1 0.9))
(def sin1 (sin mix1))
(out (* sin1 env velocity (mod gain)) 1 @name audio)