(defmacro pitchless_delay_control (target fade_rate)
  (make-history h_fade)
  (make-history h_fade_dir)
  (make-history h_init)
  (make-history h_tap_a)
  (make-history h_tap_b)
  (def abs-2 (abs (read-history h_fade_dir)))
  (def add-0 (+ (read-history h_fade) (read-history h_fade_dir)))
  (def add-1 (+ (read-history h_fade) (read-history h_fade_dir)))
  (def add-4 (+ (read-history h_fade) (read-history h_fade_dir)))
  (def fade_to_a_finished (<= add-1 0.0))
  (def fade_to_b_finished (>= add-0 1.0))
  (def is_fading (> abs-2 0.0))
  (def is_fading_a (< (read-history h_fade_dir) 0.0))
  (def is_fading_b (> (read-history h_fade_dir) 0.0))
  (def is_first (== (read-history h_init) 0.0))
  (def mul-12 (* is_fading (read-history h_tap_b)))
  (def mul-16 (* is_fading add-4))
  (def mul-18 (* is_first target))
  (def mul-20 (* is_first target))
  (def mul-22 (* is_first 0.0))
  (def mul-24 (* is_first 0.0))
  (def mul-8 (* is_fading (read-history h_tap_a)))
  (def n1 1.0)
  (def n1-1 1.0)
  (def n1-10 1.0)
  (def n1-11 1.0)
  (def n1-12 1.0)
  (def n1-2 1.0)
  (def n1-3 1.0)
  (def n1-4 1.0)
  (def n1-5 1.0)
  (def n1-6 1.0)
  (def n1-7 1.0)
  (def n1-8 1.0)
  (def n1-9 1.0)
  (def settled_at_a (<= (read-history h_fade) 0.0))
  (def settled_at_b (>= (read-history h_fade) 1.0))
  (def sub-0 (- target (read-history h_tap_a)))
  (def abs-0 (abs sub-0))
  (def dev_a (> abs-0 0.5))
  (def sub-1 (- target (read-history h_tap_b)))
  (def abs-1 (abs sub-1))
  (def dev_b (> abs-1 0.5))
  (def sub-10 (- n1-8 is_first))
  (def sub-11 (- n1-9 is_first))
  (def sub-12 (- n1-10 is_first))
  (def sub-13 (- n1-11 is_first))
  (def sub-2 (- n1 fade_to_b_finished))
  (def mul-1 (* (read-history h_fade_dir) sub-2))
  (def mul-0 (* is_fading_b mul-1))
  (def sub-3 (- n1-1 fade_to_a_finished))
  (def mul-3 (* (read-history h_fade_dir) sub-3))
  (def mul-2 (* is_fading_a mul-3))
  (def fading_next_dir (+ mul-0 mul-2))
  (def mul-6 (* is_fading fading_next_dir))
  (def sub-4 (- n1-2 is_fading))
  (def sub-5 (- n1-3 is_fading))
  (def sub-7 (- n1-5 is_fading))
  (def sub-9 (- n1-7 is_fading))
  (def trigger_fade_to_a (* settled_at_b dev_b))
  (def mul-10 (* trigger_fade_to_a target))
  (def mul-5 (* trigger_fade_to_a fade_rate))
  (def sub-6 (- n1-4 trigger_fade_to_a))
  (def mul-11 (* sub-6 (read-history h_tap_a)))
  (def add-2 (+ mul-10 mul-11))
  (def mul-9 (* sub-5 add-2))
  (def next_tap_a (+ mul-8 mul-9))
  (def mul-19 (* sub-10 next_tap_a))
  (def final_tap_a (+ mul-18 mul-19))
  (def trigger_fade_to_b (* settled_at_a dev_a))
  (def mul-14 (* trigger_fade_to_b target))
  (def mul-4 (* trigger_fade_to_b fade_rate))
  (def not_fading_next_dir (- mul-4 mul-5))
  (def mul-7 (* sub-4 not_fading_next_dir))
  (def next_fade_dir (+ mul-6 mul-7))
  (def add-5 (+ (read-history h_fade) next_fade_dir))
  (def mul-17 (* sub-9 add-5))
  (def mul-25 (* sub-13 next_fade_dir))
  (def final_fade_dir (+ mul-24 mul-25))
  (def next_fade (+ mul-16 mul-17))
  (def next_fade_clamped (clip next_fade 0.0 1.0))
  (def mul-23 (* sub-12 next_fade_clamped))
  (def final_fade (+ mul-22 mul-23))
  (def sub-8 (- n1-6 trigger_fade_to_b))
  (def mul-15 (* sub-8 (read-history h_tap_b)))
  (def add-3 (+ mul-14 mul-15))
  (def mul-13 (* sub-7 add-3))
  (def next_tap_b (+ mul-12 mul-13))
  (def mul-21 (* sub-11 next_tap_b))
  (def final_tap_b (+ mul-20 mul-21))
  (write-history h_fade final_fade)
  (write-history h_fade_dir final_fade_dir)
  (write-history h_init n1-12)
  (write-history h_tap_a final_tap_a)
  (write-history h_tap_b final_tap_b)
  (tuple final_tap_a final_tap_b final_fade))
