; Elektron Monomachine DPRO-BBOX-inspired v1
; BeatBox-style note-addressed 12-bit percussive model bank.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(defmacro crush_12 (sig)
  (- (* (/ (floor (* (+ (clip sig -1 1) 1) 0.5 4096)) 4096) 2) 1))

(defmacro pulse_from_phase (phase width)
  (scale (lt phase width) 0 1 -1 1))

(param amp_attack_ms     @default 1    @min 1     @max 5000 @unit ms)
(param amp_decay_ms      @default 340  @min 1     @max 5000 @unit ms)
(param amp_sustain       @default 0.0  @min 0     @max 1)
(param amp_release_ms    @default 35   @min 1     @max 5000 @unit ms)

(param filter_attack_ms  @default 1    @min 1     @max 5000 @unit ms)
(param filter_decay_ms   @default 180  @min 1     @max 5000 @unit ms)
(param filter_sustain    @default 0.0  @min 0     @max 1)
(param filter_release_ms @default 70   @min 1     @max 5000 @unit ms)

(param ptch              @default 0    @min -48   @max 48 @mod true @mod-mode additive)
(param start             @default 0    @min 0     @max 127 @mod true @mod-mode additive)
(param rtrg              @default 0    @min 0     @max 127 @mod true @mod-mode additive)
(param rtim              @default 72   @min 0     @max 127 @mod true @mod-mode additive)

(param cutoff            @default 9000 @min 80    @max 12000 @unit Hz @mod true @mod-mode additive)
(param resonance         @default 0.707 @min 0.5  @max 2.5 @mod true @mod-mode additive)
(param keytrack          @default 0.0  @min 0     @max 2)
(param filter_env_amt    @default 1300 @min -8000 @max 8000 @unit Hz @mod true @mod-mode additive)
(param drive             @default 1.35 @min 0.5   @max 8 @mod true @mod-mode additive)
(param gain              @default 0.24 @min 0     @max 1 @mod true @mod-mode additive)

(def start_norm (/ (clip (mod start) 0 127) 127))
(def transient_amt (- 1 start_norm))
(def decay_scale (clip (- 1 (* start_norm 0.72)) 0.18 1))
(def ptch_ratio (semi_ratio (clip (mod ptch) -48 48)))

; BBOX repeats its 24 sounds outside C-3..B-4, with pitch adjusted by octave.
(def midi_note (+ 69 (/ (* 12 (log (/ pitch 440))) (log 2))))
(def note_from_c3 (floor (+ (- midi_note 48) 0.5)))
(def repeat_oct (floor (/ note_from_c3 24)))
(def sound_idx (+ (floor (wrap note_from_c3 0 24)) 1))
(def octave_ratio (pow 2 repeat_oct))
(def pitch_mul (* ptch_ratio octave_ratio))

(def retrig_norm (/ (clip (mod rtrg) 0 127) 127))
(def rtim_norm (/ (clip (mod rtim) 0 127) 127))
(def retrig_hz (+ 2 (* (pow (- 1 rtim_norm) 2) 118)))
(def retrig_pulse (* gate (gt retrig_norm 0.003) (lt (phasor retrig_hz) 0.002)))
(def hit_trigger (max trigger retrig_pulse))

(def amp_env (adsr gate hit_trigger amp_attack_ms (* amp_decay_ms decay_scale) amp_sustain amp_release_ms))
(def filt_env (adsr gate hit_trigger filter_attack_ms (* filter_decay_ms decay_scale) filter_sustain filter_release_ms))
(def click_env (adsr gate hit_trigger 1 7 0 1))
(def snap_env (adsr gate hit_trigger 1 28 0 1))
(def body_env (adsr gate hit_trigger 1 (* 260 decay_scale) 0 20))
(def noise_env (adsr gate hit_trigger 1 (* 180 decay_scale) 0 18))
(def long_env (adsr gate hit_trigger 1 (* 1050 decay_scale) 0 80))

(def kick_decay (adsr gate hit_trigger 1 (* 95 decay_scale) 0 8))
(def pitch_drop (+ 1 (* 2.8 kick_decay transient_amt)))
(def base_freq (* pitch_mul (selector sound_idx
  54 190 142 182 238 880 710 560 5200 4800 3300 2500
  46 210 330 680 84 1200 1280 1800 6200 7200 1500 980)))
(def tone_freq (* base_freq pitch_drop))
(def ph (wrap (+ (phasor tone_freq hit_trigger) (* start_norm 0.5)) 0 1))
(def ph2 (wrap (+ (phasor (* tone_freq 1.51) hit_trigger) (* start_norm 0.37)) 0 1))
(def ph3 (wrap (+ (phasor (* tone_freq 2.03) hit_trigger) (* start_norm 0.23)) 0 1))

(def sine1 (sin (* twopi ph)))
(def sine2 (sin (* twopi ph2)))
(def sine3 (sin (* twopi ph3)))
(def sq1 (pulse_from_phase ph 0.5))
(def sq2 (pulse_from_phase ph2 0.5))
(def noise_a (noise))
(def noise_b (latch (noise) (lt (phasor (* tone_freq 0.25)) 0.02)))
(def metal (+ (* 0.45 sq1) (* 0.35 sq2) (* 0.20 sine3)))
(def click (* transient_amt click_env (latch (noise) hit_trigger)))
(def body (* body_env sine1))
(def noisy (* noise_env noise_a))
(def cymbal (* long_env (tanh (* 3 (+ (* 0.45 noise_a) (* 0.35 noise_b) (* 0.20 metal))))))

(def bd1 (+ (* 1.45 body) (* 0.22 click)))
(def sn1 (+ (* 0.72 noisy) (* 0.32 body) (* 0.18 click)))
(def tom1 (+ (* 1.05 body) (* 0.10 noisy)))
(def tom2 (+ (* 0.95 body) (* 0.12 noisy)))
(def bongo (+ (* 0.72 body) (* 0.30 (sin (* twopi ph2))) (* 0.05 click)))
(def clap (+ (* 0.95 noisy) (* 0.35 snap_env (pulse_from_phase (phasor 38 hit_trigger) 0.17))))
(def rim (+ (* 0.55 click) (* 0.75 snap_env metal)))
(def cowbell (* snap_env (+ (* 0.68 sq1) (* 0.48 sq2))))
(def chh (* noise_env (+ (* 0.75 noise_a) (* 0.25 metal))))
(def ohh (* long_env (+ (* 0.72 noise_a) (* 0.22 metal))))
(def ride (* long_env (+ (* 0.50 metal) (* 0.33 noise_a) (* 0.17 sine3))))
(def crash (* long_env (tanh (* 2.2 (+ noise_a metal)))))
(def bd2 (+ (* 1.65 body) (* 0.14 click)))
(def sn2 (+ (* 0.86 noisy) (* 0.25 metal) (* 0.22 click)))
(def timbale (+ (* 0.80 body) (* 0.52 (sin (* twopi ph2)))))
(def agogo (* body_env (+ (* 0.65 sine1) (* 0.50 sine2))))
(def timpani (+ (* 1.15 body) (* 0.25 (sin (* twopi ph2)))))
(def snap (+ (* 0.80 click) (* 0.72 snap_env noise_b)))
(def wood (+ (* 0.62 click) (* 0.82 snap_env (sin (* twopi ph3)))))
(def triangle (* long_env (+ (* 0.78 sine1) (* 0.32 sine2))))
(def shaker (* noise_env (latch (noise) (lt (phasor 83) 0.18))))
(def maracas (* noise_env (latch (noise) (lt (phasor 127) 0.23))))
(def whistle (* long_env (sin (* twopi ph))))
(def blipp (* snap_env (+ (* 0.60 sine1) (* 0.65 (sin (* twopi (wrap (+ ph2 (* ph 0.15)) 0 1)))))))

(def raw_selected (selector sound_idx
  bd1 sn1 tom1 tom2 bongo clap rim cowbell chh ohh ride crash
  bd2 sn2 timbale agogo timpani snap wood triangle shaker maracas whistle blipp))
(def bbox_raw (crush_12 raw_selected))
(def driven (tanh (* bbox_raw (clip (mod drive) 0.5 8))))
(def filter_cutoff (clip (+ (mod cutoff) (* pitch keytrack) (* filt_env (mod filter_env_amt))) 80 12000))
(def filtered (biquad driven filter_cutoff (clip (mod resonance) 0.5 2.5) 1 0))
(out (* filtered amp_env velocity (clip (mod gain) 0 1)) 1 @name audio)
