(defmacro xop (input input2) (def phasor2 (phasor 0.3)) (def mul3 (* phasor2 1.0)) (def phasor1 (phasor input)) (def triangle1 (triangle phasor1 mul3)) (def mul1 (* triangle1 twopi)) (def mul2 (* mul1 input2)) (def cos1 (cos mul2)) cos1)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))
(param myparam @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def xop1 (xop pitch 1.0))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def osc (scale phase 0.0 1.0 -1.0 1.0))
(out (* xop1 env velocity (mod gain)) 1 @name audio)