(defmacro karplus-strong (input hz decay_ms)
  (make-history history1)
  (make-history history2)
  (def sr 48100.0)
  (def dt (/ sr (clip hz 20.0 4000.0)))
  (def decay_s (* decay_ms 0.001))
  (def g (pow 0.001 (/ 1.0 (* (max decay_s 0.01) (clip hz 20.0 4000.0)))))
  (make-history fb_hist)
  (make-history lp_hist)
  (def fb (read-history fb_hist))
  (def lp (* 0.5 (+ fb (read-history lp_hist))))
  (write-history lp_hist fb)
  (def sig (+ input (* lp g)))
  (def del_sig (delay sig dt))
  (write-history fb_hist del_sig)
  (make-history dc_in)
  (make-history dc_out)
  (def prev_x (read-history dc_in))
  (def prev_y (read-history dc_out))
  (def filtered (- (+ del_sig (* 0.995 prev_y)) prev_x))
  (write-history dc_in del_sig)
  (write-history dc_out filtered)
  filtered)
(def value2 4200.0)
(def value1 4200.0)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def add1 (+ pitch 3.0))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param attack @group amp @env amp-env @role attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @group amp @env amp-env @role decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0.0 @max 1.0)
(param release @group amp @env amp-env @role release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def scale1 (scale phase 0.0 1.0 -1.0 1.0))
(def karplus-strong2 (karplus-strong (* phase env velocity (mod gain)) add1 value2))
(def karplus-strong1 (karplus-strong (* phase env velocity (mod gain)) pitch value1))
(def add2 (+ karplus-strong2 karplus-strong1))
(def mul1 (* add2 env))
(def mix1 (mix mul1 (* phase env velocity (mod gain)) 0.5))
(out mix1 1 @name audio)