; Heat development voice. Not yet a factory-accepted Analog match.
; Uses physical units throughout. Source waveform/level calibration, hard
; sync, formant control mapping, unison and vibrato remain release work.
; Named host signals distinguish a physical note-on from an envelope trigger.
(use-defmacro heat-envelope)
(use-defmacro heat-pitch-envelope)
(use-defmacro heat-lfo)
(use-defmacro heat-linear-filter)
(use-defmacro heat-drive)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def note_on (in 5 @name note_on))
(def legato (in 6 @name legato))
(def pressure (in 7 @name pressure))
(def mod1 (in 8 @name mod1 @modulator 1))
(def mod2 (in 9 @name mod2 @modulator 2))
(def mod3 (in 10 @name mod3 @modulator 3))
(def mod4 (in 11 @name mod4 @modulator 4))

(defmacro heat-db (db) (exp (* 0.11512925465 db)))
(defmacro heat-octaves (octaves) (exp (* 0.69314718056 octaves)))

; First-order target slew, initialized directly to the first target.
; Smooth continuous level/pan controls without smearing note/event signals.
(defmacro heat-control (target)
  (make-history ready_hist)
  (make-history value_hist)
  (def old (read-history value_hist))
  (def coefficient (- 1 (exp (/ -1 (* 0.002 samplerate)))))
  (def value (gswitch (eq (read-history ready_hist) 0) target
    (+ old (* coefficient (- target old)))))
  (write-history ready_hist 1)
  (write-history value_hist value)
  value)

; Development source family, normalized peak amplitude. The two oscillators
; own separate phases and sub phases. These analytical waveforms still need
; complete comparison against Analog; no reference waveform samples are used.
(defmacro heat-source (frequency wave duty sub_level)
  (def hz (clip frequency 0.01 (* 0.45 samplerate)))
  (def phase (phasor hz))
  (def sub_hz (* 0.5 hz))
  (def sub_phase (phasor sub_hz))
  (def main (selector (+ 1 (clip (round wave) 0 3))
    (sin (* 6.28318530718 phase))
    (polyblep_saw phase hz)
    (polyblep_pulse phase (clip duty 0.01 0.99) hz)
    (noise)))
  (+ main (* (clip sub_level 0 1) (polyblep_pulse sub_phase 0.5 sub_hz))))

(param volume_db @default -18 @min -60 @max 6 @unit dB @mod true @mod-mode additive)
(param tune_semitones @default 0 @min -48 @max 48 @unit st @mod true @mod-mode additive)
(param pressure_pitch_semitones @default 0 @min -24 @max 24 @unit st)
(param pressure_filter_octaves @default 0 @min -8 @max 8)
(param pressure_amp_db @default 0 @min -36 @max 12 @unit dB)

; Lane 1: independently stored source, modulation and articulation.
(param osc1_enabled @default 1 @min 0 @max 1)
(param osc1_wave @default 1 @min 0 @max 3)
(param osc1_level_db @default -6 @min -60 @max 12 @unit dB @mod true @mod-mode additive)
(param osc1_to_filter1 @default 1 @min 0 @max 1 @mod true @mod-mode additive)
(param osc1_pitch_env_initial @default 0 @min -48 @max 48 @unit st)
(param osc1_pitch_env_time_ms @default 500 @min 0 @max 15000 @unit ms)
(param osc1_semitones @default 0 @min -48 @max 48 @unit st @mod true @mod-mode additive)
(param osc1_cents @default 0 @min -300 @max 300 @unit ct @mod true @mod-mode additive)
(param osc1_keytrack @default 1 @min -2 @max 2)
(param osc1_pulse_duty @default 0.5 @min 0.01 @max 0.99 @mod true @mod-mode additive)
(param osc1_sub_level @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param osc1_lfo_pitch_semitones @default 0 @min -24 @max 24 @unit st)
(param osc1_lfo_pw @default 0 @min -0.49 @max 0.49)
(param lfo1_enabled @default 0 @min 0 @max 1)
(param lfo1_rate_hz @default 1 @min 0.01 @max 100)
(param lfo1_shape @default 0 @min 0 @max 4)
(param lfo1_width @default 0.5 @min 0 @max 1)
(param lfo1_retrigger @default 1 @min 0 @max 1)
(param lfo1_phase @default 0 @min 0 @max 1)
(param lfo1_delay_ms @default 0 @min 0 @max 10000)
(param lfo1_fade_ms @default 0 @min 0 @max 10000)
(param filter1_enabled @default 1 @min 0 @max 1)
(param filter1_mode @default 0 @min 0 @max 7)
(param filter1_cutoff_hz @default 1800 @min 30 @max 22000 @unit Hz @mod true @mod-mode additive)
(param filter1_q @default 0.707 @min 0.1 @max 100 @mod true @mod-mode additive)
(param filter1_drive @default 0 @min 0 @max 6)
(param filter1_keytrack @default 0 @min -2 @max 2)
(param filter1_env_octaves @default 2 @min -8 @max 8 @mod true @mod-mode additive)
(param filter1_lfo_octaves @default 0 @min -8 @max 8)
(param filter1_env_q @default 0 @min -50 @max 50)
(param filter1_lfo_q @default 0 @min -50 @max 50)
(param amp1_enabled @default 1 @min 0 @max 1)
(param amp1_level_db @default 0 @min -60 @max 12 @unit dB @mod true @mod-mode additive)
(param amp1_pan @default 0 @min -1 @max 1 @mod true @mod-mode additive)
(param amp1_lfo_level @default 0 @min -1 @max 1)
(param amp1_lfo_pan @default 0 @min -1 @max 1)
(param amp1_env_pan @default 0 @min -1 @max 1)
(param amp1_key_pan @default 0 @min -1 @max 1)
(param amp1_key_level_db @default 0 @min -24 @max 24 @unit dB)
(param filter1_env_attack_ms @default 5 @min 0.01 @max 15000)
(param filter1_env_decay_ms @default 350 @min 0.01 @max 15000)
(param filter1_env_sustain @default 0.25 @min 0 @max 1)
(param filter1_env_sustain_seconds @default -1 @min -1 @max 1000)
(param filter1_env_release_ms @default 250 @min 0.01 @max 15000)
(param filter1_env_exponential @default 1 @min 0 @max 1)
(param filter1_env_loop @default 0 @min 0 @max 3)
(param filter1_env_free @default 0 @min 0 @max 1)
(param filter1_env_legato @default 1 @min 0 @max 1)
(param filter1_env_velocity @default 0 @min 0 @max 1)
(param amp1_env_attack_ms @default 5 @min 0.01 @max 15000)
(param amp1_env_decay_ms @default 150 @min 0.01 @max 15000)
(param amp1_env_sustain @default 0.8 @min 0 @max 1)
(param amp1_env_sustain_seconds @default -1 @min -1 @max 1000)
(param amp1_env_release_ms @default 250 @min 0.01 @max 15000)
(param amp1_env_exponential @default 1 @min 0 @max 1)
(param amp1_env_loop @default 0 @min 0 @max 3)
(param amp1_env_free @default 0 @min 0 @max 1)
(param amp1_env_legato @default 1 @min 0 @max 1)
(param amp1_env_velocity @default 0.5 @min 0 @max 1)

; Lane 2: independently stored source, modulation and articulation.
(param osc2_enabled @default 0 @min 0 @max 1)
(param osc2_wave @default 1 @min 0 @max 3)
(param osc2_level_db @default -6 @min -60 @max 12 @unit dB @mod true @mod-mode additive)
(param osc2_to_filter1 @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param osc2_pitch_env_initial @default 0 @min -48 @max 48 @unit st)
(param osc2_pitch_env_time_ms @default 500 @min 0 @max 15000 @unit ms)
(param osc2_semitones @default 0 @min -48 @max 48 @unit st @mod true @mod-mode additive)
(param osc2_cents @default 0 @min -300 @max 300 @unit ct @mod true @mod-mode additive)
(param osc2_keytrack @default 1 @min -2 @max 2)
(param osc2_pulse_duty @default 0.5 @min 0.01 @max 0.99 @mod true @mod-mode additive)
(param osc2_sub_level @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param osc2_lfo_pitch_semitones @default 0 @min -24 @max 24 @unit st)
(param osc2_lfo_pw @default 0 @min -0.49 @max 0.49)
(param lfo2_enabled @default 0 @min 0 @max 1)
(param lfo2_rate_hz @default 1 @min 0.01 @max 100)
(param lfo2_shape @default 0 @min 0 @max 4)
(param lfo2_width @default 0.5 @min 0 @max 1)
(param lfo2_retrigger @default 1 @min 0 @max 1)
(param lfo2_phase @default 0 @min 0 @max 1)
(param lfo2_delay_ms @default 0 @min 0 @max 10000)
(param lfo2_fade_ms @default 0 @min 0 @max 10000)
(param filter2_enabled @default 1 @min 0 @max 1)
(param filter2_mode @default 0 @min 0 @max 7)
(param filter2_cutoff_hz @default 1800 @min 30 @max 22000 @unit Hz @mod true @mod-mode additive)
(param filter2_q @default 0.707 @min 0.1 @max 100 @mod true @mod-mode additive)
(param filter2_drive @default 0 @min 0 @max 6)
(param filter2_keytrack @default 0 @min -2 @max 2)
(param filter2_env_octaves @default 2 @min -8 @max 8 @mod true @mod-mode additive)
(param filter2_lfo_octaves @default 0 @min -8 @max 8)
(param filter2_env_q @default 0 @min -50 @max 50)
(param filter2_lfo_q @default 0 @min -50 @max 50)
(param amp2_enabled @default 1 @min 0 @max 1)
(param amp2_level_db @default 0 @min -60 @max 12 @unit dB @mod true @mod-mode additive)
(param amp2_pan @default 0 @min -1 @max 1 @mod true @mod-mode additive)
(param amp2_lfo_level @default 0 @min -1 @max 1)
(param amp2_lfo_pan @default 0 @min -1 @max 1)
(param amp2_env_pan @default 0 @min -1 @max 1)
(param amp2_key_pan @default 0 @min -1 @max 1)
(param amp2_key_level_db @default 0 @min -24 @max 24 @unit dB)
(param filter2_env_attack_ms @default 5 @min 0.01 @max 15000)
(param filter2_env_decay_ms @default 350 @min 0.01 @max 15000)
(param filter2_env_sustain @default 0.25 @min 0 @max 1)
(param filter2_env_sustain_seconds @default -1 @min -1 @max 1000)
(param filter2_env_release_ms @default 250 @min 0.01 @max 15000)
(param filter2_env_exponential @default 1 @min 0 @max 1)
(param filter2_env_loop @default 0 @min 0 @max 3)
(param filter2_env_free @default 0 @min 0 @max 1)
(param filter2_env_legato @default 1 @min 0 @max 1)
(param filter2_env_velocity @default 0 @min 0 @max 1)
(param amp2_env_attack_ms @default 5 @min 0.01 @max 15000)
(param amp2_env_decay_ms @default 150 @min 0.01 @max 15000)
(param amp2_env_sustain @default 0.8 @min 0 @max 1)
(param amp2_env_sustain_seconds @default -1 @min -1 @max 1000)
(param amp2_env_release_ms @default 250 @min 0.01 @max 15000)
(param amp2_env_exponential @default 1 @min 0 @max 1)
(param amp2_env_loop @default 0 @min 0 @max 3)
(param amp2_env_free @default 0 @min 0 @max 1)
(param amp2_env_legato @default 1 @min 0 @max 1)
(param amp2_env_velocity @default 0.5 @min 0 @max 1)
(param filter1_to_filter2 @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param filter2_follow @default 0 @min 0 @max 1)
(param filter2_offset_octaves @default 0 @min -8 @max 8 @mod true @mod-mode additive)
(param noise_enabled @default 0 @min 0 @max 1)
(param noise_level_db @default -24 @min -60 @max 12 @unit dB @mod true @mod-mode additive)
(param noise_color_hz @default 8000 @min 30 @max 22000 @unit Hz @mod true @mod-mode additive)
(param noise_to_filter1 @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)

(def expression (clip pressure 0 1))
(def played_octave (/ (log (/ (max pitch 0.01) 261.625565)) 0.69314718056))
(def tuning (+ (mod tune_semitones) (* expression pressure_pitch_semitones)))

(def lfo1 (* lfo1_enabled
  (heat-lfo lfo1_rate_hz lfo1_width lfo1_shape note_on
    lfo1_retrigger lfo1_phase lfo1_delay_ms lfo1_fade_ms)))
(def filter1_env
  (* (+ (- 1 filter1_env_velocity) (* filter1_env_velocity (clip velocity 0 1)))
    (heat-envelope gate (gswitch (gt filter1_env_legato 0.5) trigger note_on)
      filter1_env_attack_ms filter1_env_decay_ms filter1_env_sustain filter1_env_sustain_seconds
      filter1_env_release_ms filter1_env_exponential filter1_env_loop filter1_env_free)))
(def amp1_env
  (* (+ (- 1 amp1_env_velocity) (* amp1_env_velocity (clip velocity 0 1)))
    (heat-envelope gate (gswitch (gt amp1_env_legato 0.5) trigger note_on)
      amp1_env_attack_ms amp1_env_decay_ms amp1_env_sustain amp1_env_sustain_seconds
      amp1_env_release_ms amp1_env_exponential amp1_env_loop amp1_env_free)))
(def osc1_hz (* 261.625565
  (heat-octaves (+ (* played_octave osc1_keytrack)
    (/ (+ tuning (mod osc1_semitones) (/ (mod osc1_cents) 100)
      (* lfo1 osc1_lfo_pitch_semitones)
      (heat-pitch-envelope note_on osc1_pitch_env_initial osc1_pitch_env_time_ms)) 12)))))
(def osc1 (* (heat-control (* osc1_enabled (heat-db (mod osc1_level_db))))
  (heat-source osc1_hz osc1_wave
    (+ (mod osc1_pulse_duty) (* lfo1 osc1_lfo_pw)) (mod osc1_sub_level))))
(def balance1 (heat-control (clip (mod osc1_to_filter1) 0 1)))
(def lfo2 (* lfo2_enabled
  (heat-lfo lfo2_rate_hz lfo2_width lfo2_shape note_on
    lfo2_retrigger lfo2_phase lfo2_delay_ms lfo2_fade_ms)))
(def filter2_env
  (* (+ (- 1 filter2_env_velocity) (* filter2_env_velocity (clip velocity 0 1)))
    (heat-envelope gate (gswitch (gt filter2_env_legato 0.5) trigger note_on)
      filter2_env_attack_ms filter2_env_decay_ms filter2_env_sustain filter2_env_sustain_seconds
      filter2_env_release_ms filter2_env_exponential filter2_env_loop filter2_env_free)))
(def amp2_env
  (* (+ (- 1 amp2_env_velocity) (* amp2_env_velocity (clip velocity 0 1)))
    (heat-envelope gate (gswitch (gt amp2_env_legato 0.5) trigger note_on)
      amp2_env_attack_ms amp2_env_decay_ms amp2_env_sustain amp2_env_sustain_seconds
      amp2_env_release_ms amp2_env_exponential amp2_env_loop amp2_env_free)))
(def osc2_hz (* 261.625565
  (heat-octaves (+ (* played_octave osc2_keytrack)
    (/ (+ tuning (mod osc2_semitones) (/ (mod osc2_cents) 100)
      (* lfo2 osc2_lfo_pitch_semitones)
      (heat-pitch-envelope note_on osc2_pitch_env_initial osc2_pitch_env_time_ms)) 12)))))
(def osc2 (* (heat-control (* osc2_enabled (heat-db (mod osc2_level_db))))
  (heat-source osc2_hz osc2_wave
    (+ (mod osc2_pulse_duty) (* lfo2 osc2_lfo_pw)) (mod osc2_sub_level))))
(def balance2 (heat-control (clip (mod osc2_to_filter1) 0 1)))

(def colored_noise (* (heat-control (* noise_enabled (heat-db (mod noise_level_db))))
  (svf (noise) (mod noise_color_hz) 0.70710678 0)))
(def noise_balance (heat-control (clip (mod noise_to_filter1) 0 1)))
(def input1 (+ (* osc1 balance1) (* osc2 balance2) (* colored_noise noise_balance)))
(def input2 (+ (* osc1 (- 1 balance1)) (* osc2 (- 1 balance2))
  (* colored_noise (- 1 noise_balance))))

(def cutoff1 (clip (* (mod filter1_cutoff_hz)
  (heat-octaves (+ (* played_octave filter1_keytrack)
    (* filter1_env (mod filter1_env_octaves)) (* lfo1 filter1_lfo_octaves)
    (* expression pressure_filter_octaves)))) 30 (min 22000 (* 0.49 samplerate))))
(def resonance1 (clip (+ (mod filter1_q) (* filter1_env filter1_env_q)
  (* lfo1 filter1_lfo_q)) 0.1 100))
(def filtered1 (gswitch (gt filter1_enabled 0.5)
  (heat-drive (heat-linear-filter input1 cutoff1 resonance1 filter1_mode) filter1_drive)
  input1))
(def send1 (heat-control (clip (mod filter1_to_filter2) 0 1)))
(def amplitude1 (* amp1_env
  (heat-control (* amp1_enabled (heat-db (+ (mod amp1_level_db)
    (* played_octave amp1_key_level_db)))))
  (max 0 (+ 1 (* lfo1 amp1_lfo_level)))))
(def pan1 (clip (+ (heat-control (mod amp1_pan)) (* lfo1 amp1_lfo_pan)
 (* amp1_env amp1_env_pan) (* played_octave amp1_key_pan)) -1 1))
(def lane1 (* (* filtered1 (- 1 send1)) amplitude1))
(def cutoff2 (clip (* (gswitch (gt filter2_follow 0.5) (* cutoff1 (heat-octaves (mod filter2_offset_octaves))) (mod filter2_cutoff_hz))
  (heat-octaves (+ (* played_octave filter2_keytrack)
    (* filter2_env (mod filter2_env_octaves)) (* lfo2 filter2_lfo_octaves)
    (* expression pressure_filter_octaves)))) 30 (min 22000 (* 0.49 samplerate))))
(def resonance2 (clip (+ (mod filter2_q) (* filter2_env filter2_env_q)
  (* lfo2 filter2_lfo_q)) 0.1 100))
(def filtered2 (gswitch (gt filter2_enabled 0.5)
  (heat-drive (heat-linear-filter (+ input2 (* filtered1 send1)) cutoff2 resonance2 filter2_mode) filter2_drive)
  (+ input2 (* filtered1 send1))))
(def amplitude2 (* amp2_env
  (heat-control (* amp2_enabled (heat-db (+ (mod amp2_level_db)
    (* played_octave amp2_key_level_db)))))
  (max 0 (+ 1 (* lfo2 amp2_lfo_level)))))
(def pan2 (clip (+ (heat-control (mod amp2_pan)) (* lfo2 amp2_lfo_pan)
 (* amp2_env amp2_env_pan) (* played_octave amp2_key_pan)) -1 1))
(def lane2 (* filtered2 amplitude2))

; Equal-power pan and explicit master gain. No hidden final limiter masks
; filter growth or incorrect gain; measured output-stage calibration remains.
(def gain (heat-control (heat-db (+ (mod volume_db) (* expression pressure_amp_db)))))
(out (* gain (+ (* lane1 (cos (* 0.7853981634 (+ 1 pan1))))
  (* lane2 (cos (* 0.7853981634 (+ 1 pan2)))))) 1)
(out (* gain (+ (* lane1 (sin (* 0.7853981634 (+ 1 pan1))))
  (* lane2 (sin (* 0.7853981634 (+ 1 pan2)))))) 2)
