(defmacro unison-detune-5 (base_freq detune_semitones)
  (def semi_to_factor (* detune_semitones 0.057762265))
  (def r1 (exp semi_to_factor))
  (def r2 (exp (* semi_to_factor 0.5)))
  (def r3 (exp (* semi_to_factor -0.5)))
  (def r4 (exp (- semi_to_factor)))
  (tuple base_freq (* base_freq r2) (* base_freq r3) (* base_freq r1) (* base_freq r4)))
(defmacro semitone-offset-hz (hz semitones) (* hz (pow 2.0 (/ semitones 12.0))))
(defmacro xop (input input2 input3)
  (def phasor1 (phasor input))
  (def triangle1 (triangle phasor1 input3))
  (def mul1 (* triangle1 twopi))
  (def mul2 (* mul1 input2))
  (def cos1 (cos mul2))
  cos1)
(def value1 0.2)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def semitone-offset-hz1 (semitone-offset-hz pitch 0.3))
(def (unison-detune-51 unison-detune-52 unison-detune-53 unison-detune-54 unison-detune-55) (unison-detune-5 pitch value1))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param lfoer @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def modulated1 (mod lfoer))
(def xop2 (xop semitone-offset-hz1 1.0 modulated1))
(def xop7 (xop unison-detune-55 2.0 modulated1))
(def xop6 (xop unison-detune-54 1.0 modulated1))
(def xop5 (xop unison-detune-53 1.0 modulated1))
(def xop4 (xop unison-detune-52 1.0 modulated1))
(def xop3 (xop unison-detune-51 1.0 modulated1))
(param myparam @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def xop1 (xop pitch 1.0 modulated1))
(def mix1 (mix xop1 xop2 0.5))
(def add1 (+ xop3 xop4 xop5 xop6 xop7 mix1))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def osc (scale phase 0.0 1.0 -1.0 1.0))
(out (* add1 env velocity (mod gain)) 1 @name audio)