(param hloss @min 0.0 @max 1.0 @default 0.99)
(param hyst @min 0.1 @max 1.0)
(param drive @min 0.2 @max 8.0 @default 1.0)
(defmacro tape_sat (input drive hysteresis hf_loss) (make-history h_in) (make-history h_slope) (make-history h_out) (def prev_in (read-history h_in)) (def raw_slope (- input prev_in)) (def dummy1 (write-history h_in input)) (def prev_slope (read-history h_slope)) (def slope (mix raw_slope prev_slope 0.8)) (def dummy2 (write-history h_slope slope)) (def driven (* input drive)) (def hyst_shift (* slope (* hysteresis drive))) (def biased (- driven hyst_shift)) (def saturated (tanh biased)) (def prev_out (read-history h_out)) (write-history h_out (mix saturated prev_out hf_loss)))
(def value12 1.0)
(def value11 3.0)
(def value10 1.0)
(def value9 0.99)
(def value8 1.0)
(def value7 0.8)
(def value6 0.2)
(def value5 1.0)
(def value4 300.0)
(def value3 2.0)
(def value2 500.0)
(def value1 1.0)
(defmacro tbridge-kick (trig freq decay_ms pitch_amt pitch_decay_ms) (make-history last_trig) (make-history pitch_env) (make-history amp_env) (def t_prev (read-history last_trig)) (def impulse (max 0.0 (- trig t_prev))) (def write_trig (write-history last_trig trig)) (def p_prev (read-history pitch_env)) (def p_coeff (exp (/ -1.0 (* 44.1 pitch_decay_ms)))) (def p_next (+ impulse (* (- 1.0 impulse) (* p_prev p_coeff)))) (def write_pitch (write-history pitch_env p_next)) (def a_prev (read-history amp_env)) (def a_coeff (exp (/ -1.0 (* 44.1 2.0)))) (def a_next (+ impulse (* (- 1.0 impulse) (* a_prev a_coeff)))) (def write_amp (write-history amp_env a_next)) (def freq_inst (* freq (+ 1.0 (* pitch_amt p_next)))) (def q_val (clip (* freq (* (* pi 0.001) decay_ms)) 0.7 300.0)) (def resonator_out (svf a_next freq_inst q_val 1.0)) (tanh (+ (* resonator_out 2.5) (* impulse 0.2))))
(defmacro tape_hysteresis (input drive width lag) (make-history x_hist) (make-history y_hist) (make-history dir_hist) (def x_prev (read-history x_hist)) (def y_prev (read-history y_hist)) (def dir_prev (read-history dir_hist)) (def dx (- input x_prev)) (def dir (mix (sign dx) dir_prev 0.9)) (def hc (* width dir)) (def target (tanh (* drive (- input hc)))) (def y (mix target y_prev lag)) (write-history x_hist input) (write-history y_hist y) (write-history dir_hist dir) y)
(defmacro tbridge_808 (trig pitch q pitch_decay pitch_amt snap_amt drive) (def mul1 (* (noise) 1.0)) (make-history p_env_hist) (make-history exc_env_hist) (def p_prev (read-history p_env_hist)) (def exc_prev (read-history exc_env_hist)) (def p_env (clip (+ (* p_prev pitch_decay) trig) 0.0 1.0)) (def exc_env (clip (+ (* exc_prev 0.92) trig) 0.0 1.0)) (def p_write (write-history p_env_hist p_env)) (def exc_write (write-history exc_env_hist exc_env)) (def click (* mul1 exc_env snap_amt)) (def pulse (* exc_env 0.3)) (def excitation (+ trig (+ pulse click))) (def current_pitch (* pitch (+ 1.0 (* p_env pitch_amt)))) (def resonance (svf excitation current_pitch q 1.0)) (tanh (* resonance drive)))
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def tbridge-kick1 (tbridge-kick trigger pitch value2 value3 value4))
(def tape_sat1 (tape_sat tbridge-kick1 drive hyst hloss))
(def phasor1 (phasor value1 trigger))
(def ramp2trig1 (ramp2trig phasor1))
(def tape_hysteresis1 (tape_hysteresis tbridge-kick1 value5 value6 value7))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def osc (scale phase 0.0 1.0 -1.0 1.0))
(out (* tape_sat1 env velocity (mod gain)) 1 @name audio)