#!/usr/bin/env python3
"""Derive shareable factory tensor assets from instrument banks.

The wavetable and triton instruments' banks (generated by gen_bank.py /
extract_bank.py) stay private to their instruments; this script extracts
curated subsets of their sets into content/assets/wavetables/ as standalone
tensor assets (see docs/tensor-asset-format-spec.md) so patcher-built
instruments can reference multi-set banks via @file / @options.

Re-run after regenerating either bank:
    python3 extract_asset_bank.py
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
WAVETABLE_BANK = HERE / "bank.json"
TRITON_BANK = HERE.parents[1] / "triton" / "waves" / "bank.json"
ASSETS = HERE.parents[3] / "assets" / "wavetables"

# One output asset per entry: (source bank, output name, shipped `source`
# string, curated set list). The `source` field is user-facing (the patcher's
# asset inspector shows it), so it carries license/provenance a user might
# care about — never this script's derivation story, which stays right here.
EXTRACTIONS = [
    (
        WAVETABLE_BANK,
        "classic-sets.json",
        "ESeq factory library",
        # Spread across the bank's territories: analog basics, additive,
        # pulse, FM, organ, and vocal material.
        [
            "Basic Shapes",
            "Harmonics",
            "Saw Dual",
            "Pulse PW",
            "FM Fold",
            "Organ",
            "Vowels",
            "Galactica",
        ],
    ),
    (
        WAVETABLE_BANK,
        "weird-sets.json",
        "ESeq factory library",
        # The bank's stranger territory: hard sync, FM chaos, inharmonic
        # spectra, noise, and mangled vocal material.
        [
            "Sync Digital",
            "FM Feedback",
            "Primes",
            "Squeeze",
            "Noise",
            "Talk Box",
            "SFX Chaos",
            "Bit Vox",
        ],
    ),
    (
        TRITON_BANK,
        "triton-sets.json",
        "AKWF-FREE (Adventure Kid Waveforms), CC0",
        # The PCM synth's most characterful material: keys, bells, chip
        # tones, voices, and granular texture.
        [
            "Square PW",
            "E.Piano Bell",
            "Clavinet",
            "DX Bell",
            "FM Metal",
            "Chip Digi",
            "Voice Choir",
            "Granular",
        ],
    ),
]


def extract(bank: dict, source: str, set_names: list[str]) -> dict:
    frame_len = bank["shape"][0]
    waves_per_set = bank["waves_per_set"]
    data = bank["data"]
    out_data: list[float] = []
    for name in set_names:
        set_index = bank["sets"].index(name)
        start = set_index * waves_per_set * frame_len
        end = start + waves_per_set * frame_len
        out_data.extend(data[start:end])
    return {
        "shape": [frame_len, waves_per_set * len(set_names)],
        "kind": "wavetable-bank",
        "layout": f"wave-major: index = wave * {frame_len} + sample",
        "source": source,
        "sets": set_names,
        "waves_per_set": waves_per_set,
        "data": [round(value, 8) for value in out_data],
    }


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    for bank_path, output_name, source, set_names in EXTRACTIONS:
        bank = json.loads(bank_path.read_text())
        asset = extract(bank, source, set_names)
        out = ASSETS / output_name
        out.write_text(json.dumps(asset, separators=(",", ":")) + "\n")
        waves = asset["shape"][1]
        print(f"wrote {out} ({len(asset['sets'])} sets, {waves} waves)")


if __name__ == "__main__":
    main()
