(def value9 0.4)
(def value8 1.0)
(def value7 3.0)
(def value6 0.83)
(def value5 0.999)
(def value4 30.0)
(def value3 100.0)
(def value2 16.0)
(def value1 0.2)
(defmacro vibraphone (trigger freq decay hardness trem_speed trem_depth) (def f1 freq) (def f2 (* freq 3.98)) (def f3 (* freq 8.02)) (def q1 (clip (* decay freq 1.42) 20.0 8000.0)) (def q2 (clip (* decay freq 0.71) 15.0 4000.0)) (def q3 (clip (* decay freq 0.28) 10.0 2000.0)) (def strike_env (svf trigger (* 120.0 (+ 1.0 (* hardness 9.0))) 0.5 0.0)) (def strike_noise (* trigger (noise))) (def clack (svf strike_noise (* 2500.0 (+ 1.0 (* hardness 3.0))) 1.5 1.0)) (def exc (+ strike_env (* clack (* hardness 0.2)))) (def m1 (svf exc f1 q1 1.0)) (def m2 (svf exc f2 q2 1.0)) (def m3 (svf exc f3 q3 1.0)) (def lfo (+ 0.5 (* 0.5 (sin (* (phasor trem_speed) twopi))))) (def trem_amp (- 1.0 (* trem_depth lfo))) (def m1_mod (* m1 trem_amp)) (tanh (* 2.5 (+ m1_mod (* m2 0.35) (* m3 0.12) (* clack (* hardness 0.05))))))
(defmacro mallet_resonator (trig freq hardness decay tone) (make-history strike_hist) (def strike_decay (mix 0.85 0.992 (- 1.0 (clip hardness 0.0 1.0)))) (def strike_env (max trig (* (read-history strike_hist) strike_decay))) (write-history strike_hist strike_env) (def strike_noise (* (noise) strike_env)) (def strike_cutoff (clip (* freq (+ 1.0 (* hardness 10.0))) 80.0 16000.0)) (def excitation (svf strike_noise strike_cutoff 0.5 0.0)) (def r2 (mix 3.98 2.76 tone)) (def r3 (mix 9.28 5.4 tone)) (def f1 (clip freq 30.0 15000.0)) (def f2 (clip (* freq r2) 40.0 17000.0)) (def f3 (clip (* freq r3) 50.0 19000.0)) (def base_q (clip (* decay 1000.0) 1.0 8000.0)) (def q1 base_q) (def q2 (max (* base_q 0.5) 1.0)) (def q3 (max (* base_q 0.25) 1.0)) (def mode1 (svf excitation f1 q1 1.0)) (def mode2 (svf excitation f2 q2 1.0)) (def mode3 (svf excitation f3 q3 1.0)) (def amp2 (mix 0.15 0.45 tone)) (def amp3 (mix 0.05 0.3 tone)) (tanh (+ mode1 (* mode2 amp2) (* mode3 amp3))))
(defmacro tr707-kick (trig accent pitch decay tone) (make-history h_eb) (make-history h_ek) (make-history h_ec) (def eb_coeff (- 0.9997 (* 0.002 (- 1.0 decay)))) (def eb (clip (+ (* (read-history h_eb) eb_coeff) trig) 0.0 1.0)) (write-history h_eb eb) (def ek (clip (+ (* (read-history h_ek) 0.993) trig) 0.0 1.0)) (write-history h_ek ek) (def ec (clip (+ (* (read-history h_ec) 0.975) trig) 0.0 1.0)) (write-history h_ec ec) (def p_bend (+ 1.0 (* 1.8 ec))) (def f_body (* 54.0 pitch p_bend)) (def f_knock (* 118.0 pitch p_bend)) (def click_noise (noise)) (def click_filt (svf click_noise 2800.0 1.8 1.0)) (def click_sig (* click_filt ec 0.45)) (def q_body (+ 12.0 (* decay 28.0))) (def body_exc (* trig 2.5)) (def body_res (svf body_exc f_body q_body 1.0)) (def body_out (* body_res eb)) (def knock_exc (+ (* trig 1.5) (* click_noise ec 0.2))) (def knock_res (svf knock_exc f_knock 6.0 1.0)) (def knock_out (* knock_res ek)) (def out_mix (+ (* body_out 1.2) (* knock_out tone 0.8) (* click_sig (+ 0.2 (* tone 0.9))))) (def amp (+ 0.3 (* 0.7 accent))) (tanh (* out_mix amp 1.6)))
(defmacro kick_707_analog (trig pitch_decay_ms amp_decay_ms start_freq end_freq click_amt) (make-history pitch_env_hist) (make-history amp_env_hist) (def p_decay (max pitch_decay_ms 1.0)) (def a_decay (max amp_decay_ms 1.0)) (def pitch_coeff (exp (/ -1.0 (* p_decay 44.1)))) (def amp_coeff (exp (/ -1.0 (* a_decay 44.1)))) (def pitch_env (clip (+ trig (* (read-history pitch_env_hist) pitch_coeff)) 0.0 1.0)) (def amp_env (clip (+ trig (* (read-history amp_env_hist) amp_coeff)) 0.0 1.0)) (write-history pitch_env_hist pitch_env) (write-history amp_env_hist amp_env) (def freq (+ end_freq (* (- start_freq end_freq) (* pitch_env pitch_env)))) (def osc_sig (sin (* (phasor freq) twopi))) (def click_sig (svf (* (noise) pitch_env) 2000.0 1.5 1.0)) (def click_imp (* trig 0.8)) (def kick_body (* osc_sig amp_env)) (def kick_out (+ kick_body (* (+ click_imp click_sig) click_amt))) (tanh kick_out))
(defmacro roland_analog_kick (trig pitch decay click_amt overdrive) (make-history prev_trig) (def diff (- trig (read-history prev_trig))) (write-history prev_trig trig) (def impulse (max diff 0.0)) (make-history pitch_state) (def p_env (+ (* (read-history pitch_state) 0.993) impulse)) (write-history pitch_state p_env) (def cutoff (+ pitch (* p_env 140.0))) (make-history click_state) (def c_env (+ (* (read-history click_state) 0.96) impulse)) (write-history click_state c_env) (def click_sig (+ (* (noise) c_env click_amt) (* impulse 0.3))) (def resonator (svf impulse cutoff decay 1.0)) (def mixed (+ (* resonator 6.0) (* click_sig 0.5))) (tanh (* mixed overdrive)))
(defmacro tbridge_909_kick (trigger pitch decay pitch_env pitch_decay click_level drive) (make-history prev_trig) (def edge (> trigger (read-history prev_trig))) (write-history prev_trig trigger) (make-history p_env_hist) (def p_coeff (exp (/ -3.0 (max 1.0 (* pitch_decay 44100.0))))) (def p_env (max edge (* (read-history p_env_hist) p_coeff))) (write-history p_env_hist p_env) (def freq (clip (+ pitch (* p_env pitch_env)) 20.0 4000.0)) (def q_val (+ 1.5 (* decay 120.0))) (def excitation (* edge 4.0)) (def osc (svf excitation freq q_val 1.0)) (make-history click_env_hist) (def c_coeff (exp (/ -3.0 (* 0.004 44100.0)))) (def c_env (max edge (* (read-history click_env_hist) c_coeff))) (write-history click_env_hist c_env) (def click_noise (* (noise) c_env)) (def click_hp (svf click_noise 3000.0 0.5 2.0)) (def click_sig (+ (* c_env 2.0) (* click_hp 0.8))) (def raw_sum (+ osc (* click_sig click_level))) (tanh (* raw_sum drive)))
(defmacro tbridge_kick (trig pitch sweep decay click) (make-history p_env) (make-history click_env) (def p_val (+ trig (* (read-history p_env) 0.992))) (write-history p_env p_val) (def c_val (+ trig (* (read-history click_env) 0.985))) (write-history click_env c_val) (def freq (+ pitch (* sweep p_val))) (def q (+ 1.5 (* decay 28.5))) (def excitation (+ trig (* click c_val (noise)))) (def resonance (svf excitation freq q 1.0)) (tanh (* (+ resonance (* click c_val)) 1.8)))
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def div2 (/ pitch 16.0))
(def div1 (/ pitch 8.0))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def vibraphone1 (vibraphone trigger pitch value5 value6 value7 value8))
(def tr707-kick1 (tr707-kick trigger value1 div2 value2 value3))
(def mix1 (mix vibraphone1 tr707-kick1 0.5))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def osc (scale phase 0.0 1.0 -1.0 1.0))
(out (* mix1 env velocity (mod gain)) 1 @name audio)