;; Drag/drop handlers for adding, inserting, and moving effects.
(def fx-drop-library-effect (payload target)
  (let ((kind (get payload :kind))
        (name (get payload :name))
        (chain (get target :chain))
        (track (get target :track))
        (bus (get target :bus))
        (slot (get target :slot)))
    (if (= chain "append")
      (if (and (not (= bus nil)) (>= bus 0))
        (if (= kind "builtin-audio-effect")
          (host-command "add-builtin-bus-effect" (dict :bus bus :name name))
          (if (= kind "custom-audio-effect")
            (host-command "add-bus-effect" (dict :bus bus :name name))
            (status "Drop an audio effect on a bus")))
        (if (= kind "builtin-audio-effect")
          (host-command "add-builtin-effect-to-track" (dict :track track :name name))
          (if (= kind "custom-audio-effect")
            (host-command "add-effect-to-track" (dict :track track :name name))
            (if (= kind "midi-effect")
              (host-command "add-midi-fx-to-track" (dict :track track :name name))
              (status "Drop an audio or MIDI effect")))))
      (if (and (= chain "audio") (= kind "builtin-audio-effect"))
        (host-command "insert-builtin-effect-before-slot" (dict :track track :slot slot :name name))
        (if (and (= chain "audio") (= kind "custom-audio-effect"))
          (host-command "insert-effect-before-slot" (dict :track track :slot slot :name name))
          (if (and (= chain "midi") (= kind "midi-effect"))
            (host-command "insert-midi-fx-before-slot" (dict :track track :slot slot :name name))
            (if (and (= chain "bus") (= kind "builtin-audio-effect"))
              (host-command "insert-builtin-bus-effect-before-slot" (dict :bus bus :slot slot :name name))
              (if (and (= chain "bus") (= kind "custom-audio-effect"))
                (host-command "insert-bus-effect-before-slot" (dict :bus bus :slot slot :name name))
                (status "That effect type does not belong in this chain")))))))))

(def fx-drop-existing-effect (payload target)
  (let ((kind (get payload :kind))
        (source-chain (get payload :chain))
        (source-track (get payload :track))
        (source-slot (get payload :slot))
        (target-chain (get target :chain))
        (target-track (get target :track))
        (source-bus (get payload :bus))
        (target-bus (get target :bus))
        (target-slot (get target :slot)))
    (if (and (= kind "audio-effect-instance") (= source-chain "audio")
             (or (= target-chain "audio") (= target-chain "append")))
      (host-command "move-effect-slot"
        (dict :source-track source-track :source-slot source-slot
              :target-track target-track :target-slot target-slot
              :position target-chain))
      (if (and (= kind "midi-effect-instance") (= source-chain "midi")
               (or (= target-chain "midi") (= target-chain "append")))
        (host-command "move-midi-fx-slot"
          (dict :source-track source-track :source-slot source-slot
                :target-track target-track :target-slot target-slot
                :position target-chain))
        (if (and (= kind "bus-effect-instance") (= source-chain "bus")
                 (or (= target-chain "bus") (= target-chain "append"))
                 (= source-bus target-bus))
          (host-command "move-bus-effect-slot"
            (dict :bus target-bus :source-slot source-slot
                  :target-slot target-slot :position target-chain))
          (if (and (= kind "rack-effect-instance") (= source-chain "rack")
                   (or (= target-chain "rack") (= target-chain "append"))
                   (= source-track target-track)
                   (= (get payload :rack-slot) (get target :rack-slot)))
            (host-command "move-rack-slot-effect"
              (dict :track target-track
                    :rack-slot (get target :rack-slot)
                    :source-slot source-slot
                    :target-slot target-slot
                    :position target-chain))
            (status "Move effects within the same audio, MIDI, bus, or rack-slot chain")))))))

(def fx-drop-on-effect (event)
  (let ((payload (get event :payload))
        (target (get event :target)))
    (let ((kind (get payload :kind)))
      (if (or (= kind "audio-effect-instance")
              (= kind "midi-effect-instance")
              (= kind "bus-effect-instance")
              (= kind "rack-effect-instance"))
        (fx-drop-existing-effect payload target)
        (fx-drop-library-effect payload target)))))
