;; Two independent hit slots, using the 808 Kick's exponential retrigger
;; crossfade. At 5 ms the old slot is -60 dB; the first hit bypasses the
;; gain ramp to preserve its attack. Return weights before updating them
;; so the outgoing hit continues at the trigger sample.
(defmacro kick-retrigger-gain (target first_hit)
  (make-history gain_h)
  (def previous_gain (read-history gain_h))
  (def coefficient (exp (/ -6.9077553 (* samplerate 0.005))))
  (def next_gain (gswitch first_hit target
    (+ target (* coefficient (- previous_gain target)))))
  (write-history gain_h next_gain)
  (gswitch first_hit target previous_gain))

(defmacro kick-retrigger (trigger gate)
  (make-history previous_trigger)
  (make-history previous_gate)
  (def trigger_high (gt trigger 0.5))
  (def gate_high (gt gate 0.5))
  (def onset (max (* trigger_high (lte (read-history previous_trigger) 0.5))
    (* gate_high (lte (read-history previous_gate) 0.5))))
  (write-history previous_trigger trigger_high)
  (write-history previous_gate gate_high)
  (make-history selector_h)
  (def previous_selector (read-history selector_h))
  (def slot (gswitch onset (- 1 previous_selector) previous_selector))
  (write-history selector_h slot)
  (make-history ever_triggered)
  (def first_hit (* onset (lte (read-history ever_triggered) 0.5)))
  (write-history ever_triggered (max onset (read-history ever_triggered)))
  (def target_a (lt slot 0.5))
  (def target_b (- 1 target_a))
  (def gain_a (kick-retrigger-gain target_a first_hit))
  (def gain_b (kick-retrigger-gain target_b first_hit))
  (tuple (* onset target_a) (* onset target_b) gain_a gain_b))

;; Reduced three-mode resonant kick study, fit to a local sample family.
;; Shared empirical tension relaxation, independent modal initial conditions,
;; radiation rise and damping, followed by a saturating recording stage/gate.
;; This is NOT an identified two-head drum geometry or sample playback.
;; See tools/pm-doom-kick/README.md for fit errors and model limitations.
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(param frequency @default 40.21499945 @min 15 @max 100 @unit Hz)
(param bend_fast @default 10.44974523 @min 0 @max 30)
(param fast_ms @default 6.105163625 @min 0.25 @max 30 @unit ms)
(param bend_slow @default 3.294748314 @min 0 @max 10)
(param slow_ms @default 33.88381691 @min 5 @max 250 @unit ms)
(param attack_ms @default 20 @min 0.03 @max 20 @unit ms)
(param hold_ms @default 119.947127 @min 60 @max 350 @unit ms)
(param fade_ms @default 100 @min 2 @max 100 @unit ms)
(param level @default 0.7746509754 @min 0.05 @max 1.2)
(param saturation @default 0.6983697466 @min 0 @max 1)
(param shape @default 24 @min 2 @max 24)
(param mode1_gain @default 1.713661379 @min 0.01 @max 8)
(param mode1_decay @default 135.4710791 @min 8 @max 400 @unit ms)
(param mode1_phase @default -2.891596611 @min -3.141592654 @max 3.141592654)
(param mode2_ratio @default 0.8490663241 @min 0.65 @max 1.8)
(param mode2_gain @default 1.959412946 @min 0 @max 3)
(param mode2_decay @default 19.77326608 @min 5 @max 300 @unit ms)
(param mode2_phase @default -3.141592654 @min -3.141592654 @max 3.141592654)
(param mode3_ratio @default 3.446906316 @min 1.8 @max 8)
(param mode3_gain @default 0.05277703169 @min 0 @max 1)
(param mode3_decay @default 69.2096387 @min 1 @max 100 @unit ms)
(param mode3_phase @default -3.141592654 @min -3.141592654 @max 3.141592654)
(param mode2_bend @default 0.949698239 @min 0 @max 2)
(param mode3_bend @default 0.7634846471 @min 0 @max 2)
(param mode2_attack_ms @default 36.23988585 @min 0.03 @max 50 @unit ms)
(param mode3_attack_ms @default 20 @min 0.03 @max 20 @unit ms)

(defmacro kick-hit (onset pitch velocity)
(make-history elapsed)
(make-history armed)
(def played (max onset (read-history armed)))
(write-history armed played)
;; Bounded integer-valued sample age avoids accumulating floating time error.
(def age_samples (gswitch onset 0 (min (* 2 samplerate) (+ 1 (read-history elapsed)))))
(write-history elapsed age_samples)
(def age (/ age_samples samplerate))
(def hit_velocity (latch (clip velocity 0 1) onset))
(def tuning (* 2 (clip (latch (/ pitch 440) onset) 0.25 4)))
(def frequency_v (clip (latch frequency onset) 15 100))
(def bend_fast_v (clip (latch bend_fast onset) 0 30))
(def fast_ms_v (clip (latch fast_ms onset) 0.25 30))
(def bend_slow_v (clip (latch bend_slow onset) 0 10))
(def slow_ms_v (clip (latch slow_ms onset) 5 250))
(def attack_ms_v (clip (latch attack_ms onset) 0.03 20))
(def hold_ms_v (clip (latch hold_ms onset) 60 350))
(def fade_ms_v (clip (latch fade_ms onset) 2 100))
(def level_v (clip (latch level onset) 0.05 1.2))
(def saturation_v (clip (latch saturation onset) 0 1))
(def shape_v (clip (latch shape onset) 2 24))
(def mode1_gain_v (clip (latch mode1_gain onset) 0.01 8))
(def mode1_decay_v (clip (latch mode1_decay onset) 8 400))
(def mode1_phase_v (clip (latch mode1_phase onset) -3.141592654 3.141592654))
(def mode2_ratio_v (clip (latch mode2_ratio onset) 0.65 1.8))
(def mode2_gain_v (clip (latch mode2_gain onset) 0 3))
(def mode2_decay_v (clip (latch mode2_decay onset) 5 300))
(def mode2_phase_v (clip (latch mode2_phase onset) -3.141592654 3.141592654))
(def mode3_ratio_v (clip (latch mode3_ratio onset) 1.8 8))
(def mode3_gain_v (clip (latch mode3_gain onset) 0 1))
(def mode3_decay_v (clip (latch mode3_decay onset) 1 100))
(def mode3_phase_v (clip (latch mode3_phase onset) -3.141592654 3.141592654))
(def mode2_bend_v (clip (latch mode2_bend onset) 0 2))
(def mode3_bend_v (clip (latch mode3_bend onset) 0 2))
(def mode2_attack_ms_v (clip (latch mode2_attack_ms onset) 0.03 50))
(def mode3_attack_ms_v (clip (latch mode3_attack_ms onset) 0.03 20))

(def fast_s (* 0.001 fast_ms_v))
(def slow_s (* 0.001 slow_ms_v))
(def fast_e (exp (/ (- age) fast_s)))
(def slow_e (exp (/ (- age) slow_s)))
(def relaxed_time (+ (* bend_fast_v fast_s (- 1 fast_e)) (* bend_slow_v slow_s (- 1 slow_e))))
(def instantaneous_bend (+ (* bend_fast_v fast_e) (* bend_slow_v slow_e)))
(def f (* frequency_v tuning))
(defmacro kick-mode (time relaxed bend_now frequency bend gain decay phase attack)
  (def cycles (* frequency (+ time (* bend relaxed))))
  (def rise (- 1 (exp (/ (- time) (* 0.001 attack)))))
  (def envelope (* rise (exp (/ (- time) (* 0.001 decay)))))
  ;; Avoid oscillator foldover outside the fitted register during transposition.
  (def hz (* frequency (+ 1 (* bend bend_now))))
  (def audible (clip (/ (- (* 0.48 samplerate) hz) (* 0.08 samplerate)) 0 1))
  (* gain envelope audible (sin (+ (* twopi (wrap cycles 0 1)) phase))))
(def head_a (kick-mode age relaxed_time instantaneous_bend f 1
  mode1_gain_v mode1_decay_v mode1_phase_v attack_ms_v))
(def head_b (kick-mode age relaxed_time instantaneous_bend (* f mode2_ratio_v) mode2_bend_v
  mode2_gain_v mode2_decay_v mode2_phase_v mode2_attack_ms_v))
(def contact (kick-mode age relaxed_time instantaneous_bend (* f mode3_ratio_v) mode3_bend_v
  mode3_gain_v mode3_decay_v mode3_phase_v mode3_attack_ms_v))
(def raw (* (+ head_a head_b contact) hit_velocity))
;; Smooth saturation knee, from rounded to nearly hard clipping. This models
;; the processed recording, not membrane motion. No output normalization.
(def compressed (/ raw (pow (+ 1 (pow (abs raw) shape_v)) (/ 1 shape_v))))
(def u (clip (/ (- age (* 0.001 hold_ms_v)) (* 0.001 fade_ms_v)) 0 1))
(def recording_gate (- 1 (* u u (- 3 (* 2 u)))))
(def output (* played level_v recording_gate (mix raw compressed saturation_v)))
output)
(def (trigger_a trigger_b gain_a gain_b) (kick-retrigger trigger gate))
(def hit_a (kick-hit trigger_a pitch velocity))
(def hit_b (kick-hit trigger_b pitch velocity))
(def mixed (+ (* hit_a gain_a) (* hit_b gain_b)))
(out mixed 1 @name left)
(out mixed 2 @name right)
