(defmacro xy (input input2)
  (def scale1 (scale input2 0.0 1.0 1.0 8.0))
  (def phasor1 (phasor input))
  (def ramp2trig1 (ramp2trig phasor1))
  (def latch1 (latch input2 ramp2trig1))
  (def triangle1 (triangle phasor1 latch1))
  (def mul1 (* triangle1 twopi))
  (def mul2 (* mul1 scale1))
  (def cos1 (cos mul2))
  cos1)
(use-defmacro unison-frequencies)
(use-defmacro simp2)
(use-defmacro gain2)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param modder @min 0.0 @max 1.0 @default 1.0 @mod true @mod-mode additive)
(param detune @min -2.0 @max 2.0 @mod true @mod-mode additive)
(def modulated2 (mod modder))
(def modulated1 (mod detune))
(def (unison-frequencies1 unison-frequencies2 unison-frequencies3 unison-frequencies4 unison-frequencies5 unison-frequencies6 unison-frequencies7) (unison-frequencies pitch modulated1))
(def xy6 (xy unison-frequencies6 modulated2))
(def xy5 (xy unison-frequencies5 modulated2))
(def xy4 (xy unison-frequencies4 modulated2))
(def xy3 (xy unison-frequencies3 modulated2))
(def xy2 (xy unison-frequencies2 modulated2))
(def xy1 (xy unison-frequencies1 modulated2))
(def add1 (+ xy1 xy2 xy3 xy4 xy5 xy6))
(def mul1 (* add1 0.1))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def phase (phasor pitch))
(def osc (scale phase 0.0 1.0 -1.0 1.0))
(out (* mul1 env velocity (mod gain)) 1 @name audio)