#!/usr/bin/env python3
"""Embed measured passive modal coefficients in the authored piano source."""
import argparse
import hashlib
import json

import numpy as np

from common import HERE, SOURCE

START = ';; BEGIN GENERATED CALIBRATION'
END = ';; END GENERATED CALIBRATION'
MODEL_MODES = 64
AFTERSOUND_MODES = 32


def tables():
    analysis_path = HERE / 'reference-analysis.json'
    data = json.loads(analysis_path.read_text())
    notes = data['notes']
    assert [r['midi'] for r in notes] == list(range(21, 109, 3))
    coefficients = np.array([r['modes'] for r in notes])
    assert coefficients.shape == (30, 96, 4) and np.isfinite(coefficients).all()
    coefficients = coefficients[:, :MODEL_MODES]
    stiffness = np.array([r['stiffness_B'] for r in notes])
    # One observed partial cannot identify dispersion. Continue the measured
    # treble trend from the last identifiable string; never fit noise peaks.
    for i, r in enumerate(notes):
        if not r['stiffness_identified']:
            last = max(j for j in range(i) if notes[j]['stiffness_identified'])
            stiffness[i] = stiffness[last] * 2**((r['midi']-notes[last]['midi'])/12)
    result = [START,
              ';; Alexander Holm / Salamander Grand Piano V3 / CC BY 3.0.',
              f';; 30 register rows, A0-C8 in minor thirds, {MODEL_MODES} string modes per row.',
              ';; Generated by tools/pm-piano/calibrate.py; no PCM or recorded phases.',
              f';; Analysis SHA256: {hashlib.sha256(analysis_path.read_bytes()).hexdigest()}']
    arrays = {'mode_number': np.arange(1, MODEL_MODES+1), 'tuning_table': np.array([r['tuning_cents'] for r in notes]),
              'aftersound_indices': np.arange(AFTERSOUND_MODES),
              'stiffness_table': stiffness, 'fast_amp_table': coefficients[:, :, 0],
              'balance_table': np.array([np.clip(.065/r['rms_first_second'], .6, 6) for r in notes]),
              'fast_rate_table': np.maximum(.22, coefficients[:, :, 1]),
              'slow_amp_table': coefficients[:, :AFTERSOUND_MODES, 2],
              'slow_rate_table': np.maximum(.22, coefficients[:, :AFTERSOUND_MODES, 3])}
    for name, a in arrays.items():
        shape = ' '.join(str(x) for x in a.shape)
        result.append(f'(def {name} (tensor @shape [{shape}] @data [')
        for row in a.reshape(-1, a.shape[-1]):
            result.append('  ' + ' '.join(f'{x:.8g}' for x in row))
        result.append(']))')
    return '\n'.join(result) + '\n' + END


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = SOURCE.read_text()
    a, b = source.index(START), source.index(END) + len(END)
    updated = source[:a] + tables() + source[b:]
    if args.check:
        assert updated == source, 'Regenerate the piano calibration tables'
    else:
        SOURCE.write_text(updated)


if __name__ == '__main__':
    main()
