; Machinedrum-style cymbal machines: TRX-CY, EFM-CY, PI-RC, PI-CC.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro md-ping (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def y (- (+ exc (* 2 r (cos (* twopi (/ (clip freq 8 19000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def hz (exp (+ (log 300.0) (* (- 1 (clip amount 0 1)) (- (log 44100.0) (log 300.0))))))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (latch x tick))
(defmacro metal6 (tune spread jit)
  (def t (semi tune))
  (def s (clip spread 0 2))
  (+ (* 0.18 (polyblep_pulse (phasor (* 205.3 t (+ 1 (* s -0.18)) (+ 1 (* jit 0.015)))) 0.48 (* 205.3 t)))
     (* 0.17 (polyblep_pulse (phasor (* 304.4 t (+ 1 (* s -0.08)))) 0.48 (* 304.4 t)))
     (* 0.16 (polyblep_pulse (phasor (* 369.6 t (+ 1 (* s 0.04)))) 0.48 (* 369.6 t)))
     (* 0.16 (polyblep_pulse (phasor (* 522.7 t (+ 1 (* s 0.16)))) 0.48 (* 522.7 t)))
     (* 0.15 (polyblep_pulse (phasor (* 540.0 t (+ 1 (* s 0.24)))) 0.48 (* 540.0 t)))
     (* 0.13 (polyblep_pulse (phasor (* 800.0 t (+ 1 (* s 0.38)))) 0.48 (* 800.0 t)))))
(defmacro swing-vca (x env)
  (tanh (* 2.4 (min x (+ env (* 0.10 (pow (abs x) 3.5)))))))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 19000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 4)
(param rich @default 0.38 @min 0 @max 1 @mod true @mod-mode additive)
(param dec @default 720 @min 60 @max 4000 @unit ms @mod true @mod-mode additive)
(param top @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param ttun @default 7800 @min 3000 @max 12000 @unit Hz @mod true @mod-mode additive)
(param size @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param peak @default 1.8 @min 0.5 @max 8 @mod true @mod-mode additive)

(param ptch @default 0 @min -36 @max 48 @mod true @mod-mode additive)
(param mod_amt @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 4200 @min 100 @max 12000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 120 @min 1 @max 1200 @unit ms)
(param fb @default 0.62 @min 0 @max 1 @mod true @mod-mode additive)
(param hpf @default 7600 @min 500 @max 15000 @unit Hz @mod true @mod-mode additive)

(param hard @default 0.55 @min 0 @max 1 @mod true @mod-mode additive)
(param clsn @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param ring @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)
(param grab @default 0.0 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 30 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 6200 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 1200 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 16500 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.72 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.06 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def jit (* (latch-trig (noise) trigger) humanize))
(def cluster (metal6 (* -12 (mod size)) (+ 0.35 (* (mod rich) 1.2)) jit))
(def cy_env (md-env trigger (clip (mod dec) 60 4000)))
(def top_env (md-env trigger (clip (* (mod dec) 0.42) 30 1200)))
(def b1 (swing-vca (* (svf cluster 3440 2.0 1) cy_env) cy_env))
(def b2 (swing-vca (* (svf cluster (clip (mod ttun) 3000 12000) (clip (mod peak) 0.5 8) 1) top_env) top_env))
(def tilt (- (+ b1 (* b2 (mod top) 1.6)) (* 0.72 (delay (+ b1 b2) 1))))
(def trx_cy (svf tilt 10500 0.7 2))

(make-history fmfb)
(def fm_env (md-env trigger (clip mdec 1 1200)))
(def fm_m (sin (+ (* (retrig-phasor (clip (mod mfrq) 100 12000) trigger) twopi) (* (read-history fmfb) (mod fb) 8.0))))
(write-history fmfb (clip fm_m -1 1))
(def efm_cy (svf (* (sin (+ (* (retrig-phasor (clip (* pitch (semi (mod ptch)) 16) 300 15000) trigger) twopi) (* fm_m fm_env (mod mod_amt) 18))) cy_env) (clip (mod hpf) 500 15000) 0.7 2))

(def energy (md-env trigger (clip (mod dec) 60 4000)))
(def collide (gt (noise) (- 1 (* (mod clsn) energy 0.7))))
(def exc (+ (* (noise) (md-env trigger (+ 1 (* (- 1 (mod hard)) 9)))) (* (noise) (gswitch collide energy 0.0))))
(def damp (* (- 1 (* (mod grab) 0.86)) (+ 0.35 (* (mod ring) 1.2))))
(def pf (clip (* pitch (semi (mod ptch)) (+ 5 (* (mod size) -2))) 240 2400))
(def pi_rc (+ (md-ping exc (* pf 1.00) (* (mod dec) damp 1.3))
              (md-ping exc (* pf 1.19) (* (mod dec) damp 1.1))
              (md-ping exc (* pf 1.41) (* (mod dec) damp 0.95))
              (md-ping exc (* pf 1.73) (* (mod dec) damp 0.80))
              (md-ping exc (* pf 2.10) (* (mod dec) damp 0.72))
              (md-ping exc (* pf 2.56) (* (mod dec) damp 0.62))
              (md-ping exc (* pf 3.18) (* (mod dec) damp 0.52))
              (md-ping exc (* pf 3.87) (* (mod dec) damp 0.44))))
(def pi_cc (+ (* 0.68 pi_rc) (* (svf (noise) 8800 1.0 2) energy (mod hard) 0.65)))

(def voice (selector eng trx_cy efm_cy pi_rc pi_cc))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
