;; Running export: no worker is started and no recording is written.
(capture-project (track :sampler :name "Sampler"))
(def capture-after-sync ()
  (reactive-set "EXPORT" "export-project" "Night Drive")
  (reactive-set "EXPORT" "export-output-name" "Night Drive (2).wav")
  (reactive-set "EXPORT" "export-folder" "recordings")
  (reactive-set "EXPORT" "export-busy" true)
  (reactive-set "EXPORT" "export-done" false)
  (reactive-set "EXPORT" "export-percent" 37)
  (reactive-set "EXPORT" "export-message" "Exporting audio — 37%")
  (eseq.export-song/open))
