(capture-project (track :sampler :name "Sampler"))
(def capture-after-sync ()
  (eseq.browser/select-tab "instruments")
  (let ((p eseq.browser/instrument-pick)) (set! p.origin "factory"))
  (let ((v eseq.browser/browser-view)) (set! v.search "Physical Models")))
