;; Final visual state for the Escape deselection regression: a dense project,
;; 64 visible steps on the first track, and no selected step shells.
(capture-project
  (track :sampler :name "64-step target" :num-steps 64)
  (track :sampler :name "Track 2")
  (track :sampler :name "Track 3")
  (track :sampler :name "Track 4")
  (track :sampler :name "Track 5")
  (track :sampler :name "Track 6")
  (track :sampler :name "Track 7")
  (track :sampler :name "Track 8")
  (track :sampler :name "Track 9")
  (track :sampler :name "Track 10"))

(seq-toggle-track-step 0 0)
(seq-toggle-track-step 0 2)
(seq-toggle-track-step 0 4)
(seq-toggle-track-step 0 6)
(seq-toggle-track-step 0 8)
(seq-toggle-track-step 0 10)
(seq-toggle-track-step 0 12)
(seq-toggle-track-step 0 14)
(seq-toggle-track-step 0 16)
(seq-toggle-track-step 0 18)
(seq-toggle-track-step 0 20)
(seq-toggle-track-step 0 22)
(seq-toggle-track-step 0 24)
(seq-toggle-track-step 0 26)
(seq-toggle-track-step 0 28)
(seq-toggle-track-step 0 30)
(seq-toggle-track-step 0 32)
(seq-toggle-track-step 0 34)
(seq-toggle-track-step 0 36)
(seq-toggle-track-step 0 38)
(seq-toggle-track-step 0 40)
(seq-toggle-track-step 0 42)
(seq-toggle-track-step 0 44)
(seq-toggle-track-step 0 46)
(seq-toggle-track-step 0 48)
(seq-toggle-track-step 0 50)
(seq-toggle-track-step 0 52)
(seq-toggle-track-step 0 54)
(seq-toggle-track-step 0 56)
(seq-toggle-track-step 0 58)
(seq-toggle-track-step 0 60)
(seq-toggle-track-step 0 62)
