; ULTRAPERC — layered percussion designer with Machinedrum DNA.
; BODY engine (BELL/WOOD/METAL/SHAKE, three contextual character knobs bx/by/bz)
; + always-on TRANSIENT / RATTLE / RING layers
; + PUNCH enhancer -> DRIVE -> DIRT -> HP/LP output stage.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))

(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro latch-trig (sig trig)
  (make-history h)
  (def old (read-history h))
  (def v (gswitch (gt trig 0.5) sig old))
  (write-history h v)
  v)

(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)

(defmacro md-ping (exc freq t60_ms trig)
  (make-history y1)
  (make-history y2)
  (def y1p (gswitch (gt trig 0.5) 0.0 (read-history y1)))
  (def y2p (gswitch (gt trig 0.5) 0.0 (read-history y2)))
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def c (* 2.0 r (cos (* twopi (/ (clip freq 8 18000) samplerate)))))
  (def y (- (+ exc (* c y1p)) (* r r y2p)))
  (write-history y2 y1p)
  (write-history y1 y)
  y)

(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (def hard (clip (* x (+ 1 (* 16 d))) -1 1))
  (def soft (tanh (* x (+ 1 (* 5 d)))))
  (+ (* soft (- 1 d)) (* hard d)))

(defmacro md-srr (x amount trig)
  (def a (clip amount 0 1))
  (def hold_hz (* samplerate (pow (/ 300.0 samplerate) a)))
  (def ph (retrig-phasor hold_hz trig))
  (make-history prev)
  (make-history held)
  (def tick (lt ph (read-history prev)))
  (def reset (gt trig 0.5))
  (def should_sample (gt (+ (gswitch reset 1.0 0.0) (gswitch tick 1.0 0.0)) 0.5))
  (def sampled (gswitch should_sample x (read-history held)))
  (write-history prev ph)
  (write-history held sampled)
  (gswitch (lt a 0.0001) x sampled))

(defmacro md-bits (x amount)
  (def bits (+ 2 (* (- 1 (clip amount 0 1)) 10)))
  (def steps (pow 2 bits))
  (/ (floor (* x steps)) steps))

(defmacro md-reset-lp (x cutoff trig)
  (make-history y)
  (def c (exp (/ (* -2.0 pi (clip cutoff 20 18000)) samplerate)))
  (def yp (gswitch (gt trig 0.5) 0.0 (read-history y)))
  (def next (+ (* (- 1.0 c) x) (* c yp)))
  (write-history y next)
  next)

(defmacro md-reset-hp (x cutoff trig)
  (- x (md-reset-lp x cutoff trig)))

(param engine @default 1 @min 1 @max 4)

(param ptch @default 0 @min -36 @max 48 @mod true @mod-mode additive)
(param dec @default 220 @min 15 @max 2500 @unit ms @mod true @mod-mode additive)
(param sweep @default 0 @min -48 @max 48 @mod true @mod-mode additive)
(param swpt @default 30 @min 2 @max 300 @unit ms)

(param bx @default 0.40 @min 0 @max 1 @mod true @mod-mode additive)
(param by @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param bz @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)

(param ttyp @default 0 @min 0 @max 3)
(param tamt @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param ttun @default 4200 @min 200 @max 9000 @unit Hz @mod true @mod-mode additive)
(param tdec @default 4 @min 1 @max 80 @unit ms)

(param ratl @default 0.15 @min 0 @max 1 @mod true @mod-mode additive)
(param rgrn @default 0.50 @min 0 @max 1 @mod true @mod-mode additive)
(param rlen @default 25 @min 5 @max 120 @unit ms)

(param ring @default 0.12 @min 0 @max 1 @mod true @mod-mode additive)
(param rtun @default 4.5 @min 2 @max 10)
(param rdec @default 220 @min 10 @max 1500 @unit ms)

(param pnch @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param driv @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)
(param dirt @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param hpf @default 60 @min 20 @max 4000 @unit Hz @mod true @mod-mode additive)
(param lpf @default 16000 @min 200 @max 18000 @unit Hz @mod true @mod-mode additive)
(param humanize @default 0.2 @min 0 @max 1)
(param level @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def jit2 (* (latch-trig (noise) trigger) humanize))

(def dec_v (* (clip (mod dec) 15 2500) (+ 1 (* jit2 0.12))))
(def swpt_v (clip swpt 2 300))
(def bx_v (clip (mod bx) 0 1))
(def by_v (clip (mod by) 0 1))
(def bz_v (clip (mod bz) 0 1))
(def tamt_v (clip (mod tamt) 0 1))
(def ttun_v (clip (mod ttun) 200 9000))
(def tdec_v (clip tdec 1 80))
(def ratl_v (clip (mod ratl) 0 1))
(def rgrn_v (clip (mod rgrn) 0 1))
(def rlen_v (clip rlen 5 120))
(def ring_v (clip (mod ring) 0 1))
(def rtun_v (clip rtun 2 10))
(def rdec_v (clip rdec 10 1500))
(def pnch_v (clip (mod pnch) 0 1))
(def driv_v (clip (mod driv) 0 1))
(def dirt_v (clip (mod dirt) 0 1))
(def hpf_v (clip (mod hpf) 20 4000))
(def lpf_v (clip (mod lpf) 200 18000))

(def base (clip (* pitch (semi (+ (mod ptch) (* jit 1.2)))) 60 4000))
(def amp (md-env trigger dec_v))
(def p_env (md-env trigger swpt_v))
(def sweep_semi (* (clip (mod sweep) -48 48) p_env (+ 0.7 (* 0.3 accent))))
(def f0 (clip (* base (semi sweep_semi)) 30 9000))
(def body_gain (+ 0.6 (* 0.4 accent)))
; excitation normalized by burst length so ping ring level is independent of samplerate
(def m_norm (/ 1.0 (max 8.0 (* 0.0015 samplerate))))

; BELL body (TRX-CB cowbell): X=SPRD pulse interval, Y=BITE resonant bark, Z=BUMP attack pitch bump
; anchored ~2.45x above the note so the default register is classic cowbell (540 Hz-ish)
(def bl_f0 (* f0 2.45))
(def bl_bump (semi (* bz_v 30 (md-env trigger 16))))
(def bl_f1 (clip (* bl_f0 bl_bump) 80 8000))
(def bl_r2 (+ 1.35 (* bx_v 0.75)))
(def bl_f2 (clip (* bl_f0 bl_r2 bl_bump) 100 10000))
(def bl_src (+ (* 0.55 (polyblep_pulse (retrig-phasor bl_f1 trigger) 0.48 bl_f1)) (* 0.45 (polyblep_pulse (retrig-phasor bl_f2 trigger) 0.48 bl_f2))))
(def bl_hi (svf bl_src (clip (* bl_f0 4.8) 600 12000) (+ 1 (* by_v 6)) 1))
(def bl_lo (svf bl_src (clip (* bl_f0 1.6) 300 8000) 1.1 1))
(def bell_b (* (md-clip (* (+ bl_hi (* bl_lo 0.7)) amp) (* by_v 0.35)) body_gain 1.1))

; WOOD body (claves/woodblock): X=HARD mallet, Y=DUAL double strike, Z=DAMP
(def wd_exc1 (* (svf (noise) (clip (+ 2000 (* bx_v 8000)) 800 12000) 1.0 0) (md-env trigger 1.2) m_norm))
(def wd_trig2 (delay trigger (* 0.008 samplerate)))
(def wd_exc2 (* (svf (noise) (clip (+ 2000 (* bx_v 8000)) 800 12000) 1.0 0) (md-env wd_trig2 1.2) m_norm by_v))
(def wd_exc (+ wd_exc1 wd_exc2))
(def wd_damp (+ 0.10 (* (- 1 bz_v) 0.45)))
(def wd_p1 (md-ping wd_exc (clip (* f0 2.2) 150 9000) (* dec_v wd_damp) trigger))
(def wd_p2 (md-ping wd_exc (clip (* f0 5.6) 300 12000) (* dec_v wd_damp 0.5) trigger))
(def wd_p3 (md-ping wd_exc (clip (* f0 9.2) 500 15000) (* dec_v wd_damp 0.35) trigger))
(def wood_b (* (+ (* wd_p1 0.60) (* wd_p2 0.32) (* wd_p3 (+ 0.18 (* bx_v 0.25)))) body_gain 1.55))

; METAL body (gamelan/bell): X=RICH upper partials, Y=TENS tension glide, Z=SIZE
; struck-metal signature: high strike register, uppers ring as long as the fundamental,
; detuned doublets for shimmer/beating, broadband clang on the attack
(def mt_energy (md-env trigger (* dec_v 0.5)))
(def mt_tens (+ 1 (* by_v 0.40 accent mt_energy mt_energy)))
(def mt_f (clip (* f0 (+ 1.2 (* (- 1 bz_v) 2.0))) 150 5000))
(def mt_exc (* (svf (noise) (clip (+ 2500 (* bx_v 9000)) 1000 14000) 0.9 0) (md-env trigger 1.5) m_norm))
(def mt_p1 (md-ping mt_exc (* mt_f 1.00 mt_tens) (* dec_v 0.50) trigger))
(def mt_p2a (md-ping mt_exc (* mt_f 2.76 mt_tens) (* dec_v 0.46) trigger))
(def mt_p2b (md-ping mt_exc (* mt_f 2.76 1.006 mt_tens) (* dec_v 0.44) trigger))
(def mt_p3a (md-ping mt_exc (* mt_f 4.07 mt_tens) (* dec_v 0.42) trigger))
(def mt_p3b (md-ping mt_exc (* mt_f 4.07 1.007 mt_tens) (* dec_v 0.40) trigger))
(def mt_p4 (md-ping mt_exc (* mt_f 5.52 mt_tens) (* dec_v 0.36) trigger))
(def mt_p5 (md-ping mt_exc (* mt_f 6.79 mt_tens) (* dec_v 0.32) trigger))
(def mt_clang (* (svf (noise) (clip (* mt_f 3.5) 800 12000) 1.4 1) (md-env trigger 7) (+ 0.25 (* bx_v 0.5))))
(def metal_b (* (+ (* mt_p1 0.40)
                   (* (+ mt_p2a mt_p2b) (+ 0.16 (* bx_v 0.20)))
                   (* (+ mt_p3a mt_p3b) (+ 0.14 (* bx_v 0.18)))
                   (* mt_p4 (+ 0.20 (* bx_v 0.30)))
                   (* mt_p5 (+ 0.14 (* bx_v 0.26)))
                   mt_clang)
                body_gain 1.55))

; SHAKE body (PhISEM shaker): X=GRNS grain density, Y=GLEN grain length, Z=SIZE resonance
(make-history sh_energy_h)
(make-history sh_level_h)
(def sh_decay (exp (/ -6.907755 (max 1.0 (* dec_v 0.001 samplerate)))))
(def sh_energy (clip (+ (* (read-history sh_energy_h) sh_decay) (* trigger accent)) 0 1))
(def sh_col (gt (noise) (- 1 (* (+ 0.02 (* bx_v 0.55)) sh_energy))))
(def sh_snd_decay (exp (/ -6.907755 (max 1.0 (* (+ 8 (* by_v 100)) 0.001 samplerate)))))
(def sh_level (+ (* (read-history sh_level_h) sh_snd_decay) (gswitch sh_col (* sh_energy (/ (log (+ 2 (* bx_v 200))) (+ 4 (* bx_v 200)))) 0.0)))
(write-history sh_energy_h sh_energy)
(write-history sh_level_h sh_level)
; jingle bank: four inharmonic high pings spread by SIZE, so shakes ring metallic
; instead of sounding like filtered noise
(def sh_spread (+ 0.75 (* bz_v 0.85)))
; sustained excitation into md-ping accumulates ~proportional to samplerate; normalize
(def sh_norm (/ 120.0 samplerate))
(def sh_exc (* sh_level (noise) sh_norm))
(def sh_j1 (md-ping sh_exc (clip (* 4300 sh_spread) 2000 16000) 55 trigger))
(def sh_j2 (md-ping sh_exc (clip (* 5560 sh_spread) 2000 16000) 75 trigger))
(def sh_j3 (md-ping sh_exc (clip (* 6910 sh_spread) 2000 17000) 90 trigger))
(def sh_j4 (md-ping sh_exc (clip (* 8240 sh_spread) 2000 17500) 110 trigger))
(def sh_skin (* (svf (* sh_level (noise)) 6000 0.8 2) 0.10))
(def shake_b (* (+ sh_j1 sh_j2 sh_j3 sh_j4 sh_skin) body_gain 2.6))

(def body (selector eng bell_b wood_b metal_b shake_b))

; TRANSIENT layer: TICK / STICK / CLICK / RIM
(def t_env (md-env trigger tdec_v))
(def tr_tick (* (svf (noise) (clip ttun_v 500 12000) 1.2 2) t_env 2.0))
(def tr_stick (* (svf (noise) (clip ttun_v 200 4000) 3.0 1) t_env 3.2))
(def tr_click_exc (* (noise) (md-env trigger 0.7)))
(def tr_click (md-ping tr_click_exc (clip ttun_v 200 9000) (clip (* tdec_v 2.5) 2 200) trigger))
(def rim_norm (/ 1.0 (max 8.0 (* 0.003 samplerate))))
(def tr_rim_exc (* (md-env trigger 3) (+ 1 (* 0.5 (noise))) rim_norm))
(def tr_rim (* (+ (md-ping tr_rim_exc (clip (* f0 2.65) 100 8000) 80 trigger) (* 0.55 (md-ping tr_rim_exc (clip (* f0 9.5) 200 15000) 55 trigger))) 0.45))
(def ttyp_i (clip (round ttyp) 0 3))
(def trans (* (selector (+ ttyp_i 1) tr_tick tr_stick tr_click tr_rim) tamt_v 1.4 accent))

; RATTLE layer: granular dust (mini PhISEM) on top of any body
(make-history rt_lvl_h)
(def rt_energy (md-env trigger dec_v))
(def rt_col (gt (noise) (- 1 (* rgrn_v 0.35 rt_energy))))
(def rt_coef (exp (/ -6.907755 (max 1.0 (* rlen_v 0.001 samplerate)))))
(def rt_lvl (+ (* (read-history rt_lvl_h) rt_coef) (gswitch rt_col (* rt_energy 0.08) 0.0)))
(write-history rt_lvl_h rt_lvl)
; resonant doublet gives the dust a jingle ring instead of plain filtered noise
(def rattle_l (* (+ (* (svf (* rt_lvl (noise)) 7500 1.2 1) 0.5)
                    (svf (* rt_lvl (noise)) 6200 5.0 1)
                    (svf (* rt_lvl (noise)) 8600 5.0 1))
                 ratl_v 2.2))

; RING layer: metallic clang, two detuned pings above the fundamental
(def r_exc (* (svf (noise) 4000 1.0 0) (md-env trigger 1.2) m_norm))
(def ring_f (clip (* base rtun_v) 200 14000))
(def ring_sig (* (+ (md-ping r_exc ring_f rdec_v trigger) (md-ping r_exc (clip (* ring_f 1.037) 200 14000) (* rdec_v 0.8) trigger)) ring_v 3.5))

; PUNCH enhancer -> DRIVE -> DIRT
(def punch_env (md-env trigger 20))
(def pre (* (+ body trans rattle_l ring_sig) (+ 1 (* pnch_v 1.8 punch_env))))
(def driven (md-clip pre driv_v))
(def srrd (md-srr driven (* dirt_v 0.75) trigger))
(def dirted (+ (* srrd (- 1 (* dirt_v 0.5))) (* (md-bits srrd (* dirt_v 0.9)) dirt_v 0.5)))

; OUTPUT: 12 dB HP + 12 dB LP, level, velocity
(def hp2 (md-reset-hp (md-reset-hp dirted hpf_v trigger) hpf_v trigger))
(def lp2 (md-reset-lp (md-reset-lp hp2 lpf_v trigger) lpf_v trigger))
(out (* lp2 (clip (mod level) 0 1) vel) 1 @name audio)
