(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(defmacro cent_ratio (cents)
  (exp (/ (* (log 2) (/ cents 100.0)) 12)))

(defmacro op_freq (base ratio detune_cents pitch_lfo_st)
  (clip (* base (max ratio 0.125) (cent_ratio detune_cents) (semi_ratio pitch_lfo_st)) 1 18000))

(defmacro formant_bank (input vowel_idx shift_st q_amt)
  (def shift_ratio (semi_ratio shift_st))
  (def v (+ (clip (round vowel_idx) 0 4) 1))
  (def f1 (clip (* shift_ratio (selector v 800 400 350 450 325)) 70 12000))
  (def f2 (clip (* shift_ratio (selector v 1150 1700 2200 800 700)) 90 13000))
  (def f3 (clip (* shift_ratio (selector v 2900 2600 3000 2830 2530)) 120 14000))
  (def q (clip q_amt 0.7 22.0))
  (def b1 (svf input f1 q 1))
  (def b2 (svf input f2 q 1))
  (def b3 (svf input f3 q 1))
  (tanh (* 1.45 (+ (* b1 1.00) (* b2 0.78) (* b3 0.52)))))

(param op1_ratio @default 1.00 @min 0.25 @max 16.00)
(param op1_detune @default 0 @min -100 @max 100 @unit ct)
(param op1_level @default 0.82 @min 0 @max 1 @mod true @mod-mode additive)

(param op2_ratio @default 2.00 @min 0.25 @max 16.00)
(param op2_detune @default 0 @min -100 @max 100 @unit ct)
(param op2_level @default 0.12 @min 0 @max 1 @mod true @mod-mode additive)
(param op2_to_op1 @default 2.75 @min 0 @max 12 @mod true @mod-mode additive)

(param op3_ratio @default 3.00 @min 0.25 @max 16.00)
(param op3_detune @default 2 @min -100 @max 100 @unit ct)
(param op3_level @default 0.04 @min 0 @max 1 @mod true @mod-mode additive)
(param op3_to_op2 @default 1.90 @min 0 @max 12 @mod true @mod-mode additive)
(param op3_to_op1 @default 0.35 @min 0 @max 12 @mod true @mod-mode additive)

(param op4_ratio @default 5.00 @min 0.25 @max 16.00)
(param op4_detune @default -3 @min -100 @max 100 @unit ct)
(param op4_level @default 0.02 @min 0 @max 1 @mod true @mod-mode additive)
(param op4_to_op3 @default 1.45 @min 0 @max 12 @mod true @mod-mode additive)
(param op4_feedback @default 0.28 @min 0 @max 3 @mod true @mod-mode additive)

(param amp_attack @default 4 @min 1 @max 5000 @unit ms)
(param amp_decay @default 260 @min 1 @max 8000 @unit ms)
(param amp_sustain @default 0.72 @min 0 @max 1)
(param amp_release @default 220 @min 1 @max 9000 @unit ms)
(param amp_vel_amt @default 0.35 @min 0 @max 1)

(param mod_attack @default 2 @min 1 @max 5000 @unit ms)
(param mod_decay @default 520 @min 1 @max 9000 @unit ms)
(param mod_sustain @default 0.42 @min 0 @max 1)
(param mod_release @default 170 @min 1 @max 9000 @unit ms)
(param mod_vel_amt @default 0.25 @min 0 @max 1)

(param lfo_rate @default 0.27 @min 0.03 @max 18 @unit Hz)
(param lfo_to_pitch @default 0.00 @min 0 @max 1.00 @unit st)
(param lfo_to_index @default 0.10 @min 0 @max 1.50)
(param lfo_to_formant @default 0.00 @min -12 @max 12 @unit st)

(param vowel @default 0 @min 0 @max 4)
(param formant_shift @default 0 @min -24 @max 24 @unit st @mod true @mod-mode additive)
(param formant_env_shift @default 2.5 @min -24 @max 24 @unit st)
(param formant_q @default 8.5 @min 0.7 @max 22.0 @mod true @mod-mode additive)
(param formant_mix @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)
(param formant_drive @default 1.55 @min 0.5 @max 6 @mod true @mod-mode additive)
(param body_tone @default 6500 @min 400 @max 14000 @unit Hz @mod true @mod-mode additive)
(param output_gain @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))
(def mod_env_raw (adsr gate trigger mod_attack mod_decay mod_sustain mod_release))
(def mod_env (* mod_env_raw (+ (- 1 mod_vel_amt) (* velocity mod_vel_amt))))
(def amp_vel (+ (- 1 amp_vel_amt) (* velocity amp_vel_amt)))

(def lfo_phase (phasor lfo_rate))
(def lfo (sin (* lfo_phase twopi)))
(def pitch_lfo_st (* lfo lfo_to_pitch))
(def index_motion (clip (+ mod_env (* lfo lfo_to_index)) 0 2))

(def f1 (op_freq pitch op1_ratio op1_detune pitch_lfo_st))
(def f2 (op_freq pitch op2_ratio op2_detune pitch_lfo_st))
(def f3 (op_freq pitch op3_ratio op3_detune pitch_lfo_st))
(def f4 (op_freq pitch op4_ratio op4_detune pitch_lfo_st))

(def ph1 (phasor f1))
(def ph2 (phasor f2))
(def ph3 (phasor f3))
(def ph4 (phasor f4))

(def i21 (* (clip (mod op2_to_op1) 0 12) index_motion))
(def i32 (* (clip (mod op3_to_op2) 0 12) index_motion))
(def i31 (* (clip (mod op3_to_op1) 0 12) index_motion))
(def i43 (* (clip (mod op4_to_op3) 0 12) index_motion))
(def fb4 (* (clip (mod op4_feedback) 0 3) index_motion))

(make-history op4_fb_hist)
(def op4_fb_prev (read-history op4_fb_hist))
(def op4_phase (+ ph4 (* op4_fb_prev fb4)))
(def op4 (sin (* op4_phase twopi)))
(write-history op4_fb_hist (tanh op4))

(def op3_phase (+ ph3 (* op4 i43)))
(def op3 (sin (* op3_phase twopi)))
(def op2_phase (+ ph2 (* op3 i32)))
(def op2 (sin (* op2_phase twopi)))
(def op1_phase (+ ph1 (* op2 i21) (* op3 i31)))
(def op1 (sin (* op1_phase twopi)))

(def carrier (+ (* op1 (clip (mod op1_level) 0 1))
                (* op2 (clip (mod op2_level) 0 1))
                (* op3 (clip (mod op3_level) 0 1))
                (* op4 (clip (mod op4_level) 0 1))))
(def driven (tanh (* carrier (clip (mod formant_drive) 0.5 6))))
(def formant_shift_st (+ (mod formant_shift) (* mod_env formant_env_shift) (* lfo lfo_to_formant)))
(def vowel_idx (clip (round vowel) 0 4))
(def formanted (formant_bank driven vowel_idx formant_shift_st (clip (mod formant_q) 0.7 22)))
(def f_mix (clip (mod formant_mix) 0 1))
(def shaped (+ (* driven (- 1 f_mix)) (* formanted f_mix)))
(def toned (svf shaped (clip (mod body_tone) 400 14000) 0.7 0))
(def final (* (tanh toned) amp_env amp_vel (clip (mod output_gain) 0 1)))

(out final 1 @name audio)
