; Machinedrum-style tom machines: TRX-XT, TRX-XC, EFM-XT, PI-XT.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro md-ping (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def y (- (+ exc (* 2 r (cos (* twopi (/ (clip freq 8 18000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def a (clip amount 0 1))
  (def hz (* samplerate (pow (/ 300.0 samplerate) a)))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (def sampled (latch x tick))
  (gswitch (lt a 0.0001) x sampled))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 18000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 4)
(param ptch @default -5 @min -48 @max 48 @mod true @mod-mode additive)
(param dec @default 540 @min 30 @max 2600 @unit ms @mod true @mod-mode additive)
(param ramp @default 18 @min -24 @max 72 @mod true @mod-mode additive)
(param rdec @default 55 @min 2 @max 500 @unit ms)
(param damp @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param distype @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)
(param clic @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)

(param mod_amt @default 0.44 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 180 @min 10 @max 2600 @unit Hz @mod true @mod-mode additive)
(param mdec @default 70 @min 1 @max 700 @unit ms)
(param fb @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)

(param hard @default 0.48 @min 0 @max 1 @mod true @mod-mode additive)
(param tens @default 0.32 @min 0 @max 1 @mod true @mod-mode additive)
(param size @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param pos @default 0.40 @min 0 @max 1 @mod true @mod-mode additive)
(param skin_tune @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.60 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 31 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 900 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 45 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 16000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.72 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.08 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def base (clip (* pitch (semi (+ (mod ptch) (* jit 2)))) 35 900))
(def penv (md-env trigger (clip rdec 2 500)))
(def freq (clip (* base (semi (* (mod ramp) penv))) 25 3000))
(def amp (md-env trigger (clip (mod dec) 30 2600)))
(def click (* (svf (noise) 3600 1.0 2) (md-env trigger 6) (mod clic) accent))

(def trx_xt (md-clip (+ (* (sin (* (retrig-phasor freq trigger) twopi)) amp) click (* (svf (noise) 900 1.3 1) (md-env trigger 18) 0.08)) (mod distype)))
(def xc_freq (clip (* freq 1.72) 45 4200))
(def trx_xc (md-clip (+ (* (sin (+ (* (retrig-phasor xc_freq trigger) twopi) (* amp 0.4 (sin (* (retrig-phasor (* xc_freq 1.52) trigger) twopi))))) amp) click) (+ 0.12 (mod distype))))

(make-history fmfb)
(def fm_env (md-env trigger (clip mdec 1 700)))
(def fm_m (sin (+ (* (retrig-phasor (clip (mod mfrq) 10 2600) trigger) twopi) (* (read-history fmfb) (mod fb) 7.0))))
(write-history fmfb (clip fm_m -1 1))
(def efm_xt (+ (* (sin (+ (* (retrig-phasor freq trigger) twopi) (* fm_m fm_env (mod mod_amt) 15))) amp) click))

(def energy (md-env trigger (clip (mod dec) 30 2600)))
(def tens_mul (+ 1 (* (mod tens) 0.38 accent energy energy)))
(def exc (* (svf (noise) (+ 1400 (* (mod hard) 8500)) 0.8 0) (md-env trigger (+ 1 (* (- 1 (mod hard)) 7)))))
(def pf (* base (+ 0.65 (* (- 1 (mod size)) 0.85))))
(def pos1 (abs (sin (* (+ 0.12 (* (mod pos) 0.76)) pi))))
(def pos2 (abs (sin (* (+ 0.12 (* (mod pos) 0.76)) pi 2))))
(def det (+ 1 (* (mod skin_tune) 0.018)))
(def pi_xt (+ (* pos1 (md-ping exc (* pf 1.00 tens_mul) (* (mod dec) (+ 0.20 (* (- 1 (mod damp)) 1.0)))))
              (* pos1 0.55 (md-ping exc (* pf det 1.50 tens_mul) (* (mod dec) (+ 0.12 (* (- 1 (mod damp)) 0.58)))))
              (* pos2 0.42 (md-ping exc (* pf 2.20 tens_mul) (* (mod dec) (+ 0.08 (* (- 1 (mod damp)) 0.42)))))
              (* pos2 0.25 (md-ping exc (* pf 2.95 tens_mul) (* (mod dec) (+ 0.06 (* (- 1 (mod damp)) 0.32)))))))

(def voice (selector eng trx_xt trx_xc efm_xt pi_xt))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
