; Delay articulation rather than audio. A pending voice is cancelled if its
; key is released; an already sounding legato voice follows without another
; onset delay. Retriggers start a new delay while the previous contour releases.
; Enabling a copy during a held note starts its own articulation. Pitch and
; velocity stay with the previous contour until the new onset becomes due.
(defmacro heat-unison-onset (gate note_on trigger legato pitch velocity enabled delay_ms)
  (make-history enabled_hist)
  (make-history gate_hist)
  (make-history pending_hist)
  (make-history elapsed_hist)
  (make-history duration_hist)
  (make-history pitch_hist)
  (make-history velocity_hist)
  (make-history ready_hist)
  (def held (* (gt gate 0.5) (gt enabled 0.5)))
  (def activate (* held (lt (read-history enabled_hist) 0.5)))
  (def requested (max (* held (gt note_on 0.5)) activate))
  (def overlap (* requested (* (gt legato 0.5) (gt (read-history gate_hist) 0.5))))
  (def restart (* requested (eq overlap 0)))
  (def duration (gswitch restart (round (* (max 0 delay_ms) (/ samplerate 1000)))
    (read-history duration_hist)))
  (def elapsed (gswitch restart 0 (min duration (+ 1 (read-history elapsed_hist)))))
  (def pending (* held (max restart (read-history pending_hist))))
  (def fire (* pending (gte elapsed duration)))
  (def waiting (* pending (eq fire 0)))
  (def gate_out (* held (eq waiting 0)))
  (def note_out (max fire overlap))
  (def trigger_out (max fire (* overlap (gt trigger 0.5))))
  (def first (eq (read-history ready_hist) 0))
  (def pitch_out (gswitch (max first gate_out) pitch (read-history pitch_hist)))
  (def velocity_out (gswitch (max first gate_out) velocity (read-history velocity_hist)))
  (write-history enabled_hist enabled)
  (write-history gate_hist gate_out)
  (write-history pending_hist waiting)
  (write-history elapsed_hist elapsed)
  (write-history duration_hist duration)
  (write-history pitch_hist pitch_out)
  (write-history velocity_hist velocity_out)
  (write-history ready_hist (max (read-history ready_hist) note_out))
  (tuple gate_out note_out trigger_out overlap pitch_out velocity_out))
