; Analog-style dual oscillator subtractive synth.
; This version follows the Ableton Analog panel model more closely than the
; generic bread-and-butter draft: discrete source waveforms, per-source routing
; to two filters, dual filter modes, two LFOs, filter/amp envelopes, and
; conservative staged saturation.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(defmacro cent_ratio (cents)
  (exp (/ (* (log 2) (/ cents 100.0)) 12)))

(defmacro lfo_wave (phase width shape)
  (def idx (clip (round shape) 0 3))
  (def sine (sin (* phase twopi)))
  (def tri (triangle phase))
  (def saw (- (* phase 2) 1))
  (def pulse (scale (lt phase (clip width 0.05 0.95)) 0 1 -1 1))
  (selector (+ idx 1) sine tri saw pulse))

(param osc1_wave @default 1 @min 0 @max 3)
(param osc1_octave @default 0 @min -2 @max 2 @unit oct)
(param osc1_semitones @default 0 @min -24 @max 24 @unit st @mod true @mod-mode additive @mod-depth-min -12 @mod-depth-max 12 @mod-unit st)
(param osc1_detune_cents @default 0 @min -50 @max 50 @unit ct @mod true @mod-mode additive @mod-depth-min -25 @mod-depth-max 25 @mod-unit ct)
(param osc1_level @default 0.78 @min 0 @max 1)
(param osc1_to_f2 @default 0.18 @min 0 @max 1)
(param osc1_pan @default -0.04 @min -1 @max 1)

(param osc2_wave @default 2 @min 0 @max 3)
(param osc2_octave @default 0 @min -2 @max 2 @unit oct)
(param osc2_semitones @default 0 @min -24 @max 24 @unit st @mod true @mod-mode additive @mod-depth-min -12 @mod-depth-max 12 @mod-unit st)
(param osc2_detune_cents @default 6 @min -50 @max 50 @unit ct @mod true @mod-mode additive @mod-depth-min -25 @mod-depth-max 25 @mod-unit ct)
(param osc2_level @default 0.56 @min 0 @max 1)
(param osc2_to_f2 @default 0.82 @min 0 @max 1)
(param osc2_pan @default 0.05 @min -1 @max 1)

(param pulse_width @default 0.48 @min 0.08 @max 0.92 @mod true @mod-mode additive @mod-depth-min -0.35 @mod-depth-max 0.35)
(param sub_mode @default 1 @min 0 @max 2)
(param sub_level @default 0.12 @min 0 @max 0.6)
(param sub_to_f2 @default 0.05 @min 0 @max 1)
(param noise_level @default 0.012 @min 0 @max 0.28)
(param noise_color @default 0.42 @min 0 @max 1)
(param noise_to_f2 @default 0.50 @min 0 @max 1)
(param osc_slop @default 0.12 @min 0 @max 1)

(param filt1_mode @default 1 @min 0 @max 3)
(param filt1_cutoff @default 900 @min 35 @max 14000 @unit Hz @mod true @mod-mode additive @mod-depth-min -8000 @mod-depth-max 8000 @mod-unit Hz)
(param filt1_resonance @default 0.22 @min 0.45 @max 4.2 @mod true @mod-mode additive @mod-depth-min -1.5 @mod-depth-max 1.5)
(param filt1_env_amt @default 2600 @min -8000 @max 9000 @unit Hz @mod true @mod-mode additive @mod-depth-min -6000 @mod-depth-max 6000 @mod-unit Hz)
(param filt1_keytrack @default 0.38 @min 0 @max 1.2)
(param filt1_drive @default 1.35 @min 0.7 @max 4.5 @mod true @mod-mode additive @mod-depth-min -1.5 @mod-depth-max 1.5)

(param filt2_mode @default 0 @min 0 @max 3)
(param filt2_cutoff @default 1800 @min 35 @max 14000 @unit Hz @mod true @mod-mode additive @mod-depth-min -8000 @mod-depth-max 8000 @mod-unit Hz)
(param filt2_resonance @default 0.62 @min 0.45 @max 4.2 @mod true @mod-mode additive @mod-depth-min -1.5 @mod-depth-max 1.5)
(param filt2_env_amt @default 800 @min -8000 @max 9000 @unit Hz @mod true @mod-mode additive @mod-depth-min -6000 @mod-depth-max 6000 @mod-unit Hz)
(param filt2_keytrack @default 0.22 @min 0 @max 1.2)
(param filt2_drive @default 1.05 @min 0.7 @max 4.5 @mod true @mod-mode additive @mod-depth-min -1.5 @mod-depth-max 1.5)
(param f1_to_f2 @default 0.12 @min 0 @max 1)

(param amp_attack_ms @default 5 @min 1 @max 5000 @unit ms)
(param amp_decay_ms @default 220 @min 5 @max 10000 @unit ms)
(param amp_sustain @default 0.78 @min 0 @max 1)
(param amp_release_ms @default 180 @min 5 @max 12000 @unit ms)
(param amp_vel_amt @default 0.28 @min 0 @max 1)
(param amp1_level @default 0.80 @min 0 @max 1)
(param amp2_level @default 0.70 @min 0 @max 1)
(param amp1_pan @default -0.08 @min -1 @max 1)
(param amp2_pan @default 0.08 @min -1 @max 1)

(param filt_attack_ms @default 3 @min 1 @max 5000 @unit ms)
(param filt_decay_ms @default 360 @min 5 @max 10000 @unit ms)
(param filt_sustain @default 0.18 @min 0 @max 1)
(param filt_release_ms @default 240 @min 5 @max 12000 @unit ms)
(param env_vel_amt @default 0.25 @min 0 @max 1)

(param lfo1_wave @default 0 @min 0 @max 3)
(param lfo1_rate_hz @default 0.42 @min 0.03 @max 18 @unit Hz)
(param lfo1_width @default 0.50 @min 0.05 @max 0.95)
(param lfo1_delay_ms @default 0 @min 0 @max 5000 @unit ms)
(param lfo1_attack_ms @default 120 @min 0 @max 5000 @unit ms)
(param lfo1_to_pitch @default 0.00 @min 0 @max 0.14 @unit st @mod true @mod-mode additive @mod-depth-min -0.08 @mod-depth-max 0.08 @mod-unit st)
(param lfo1_to_pw @default 0.035 @min 0 @max 0.30 @mod true @mod-mode additive @mod-depth-min -0.20 @mod-depth-max 0.20)

(param lfo2_wave @default 1 @min 0 @max 3)
(param lfo2_rate_hz @default 0.21 @min 0.03 @max 18 @unit Hz)
(param lfo2_width @default 0.50 @min 0.05 @max 0.95)
(param lfo2_delay_ms @default 0 @min 0 @max 5000 @unit ms)
(param lfo2_attack_ms @default 300 @min 0 @max 5000 @unit ms)
(param lfo2_to_f1 @default 35 @min 0 @max 2200 @unit Hz @mod true @mod-mode additive @mod-depth-min -1600 @mod-depth-max 1600 @mod-unit Hz)
(param lfo2_to_f2 @default 15 @min 0 @max 2200 @unit Hz @mod true @mod-mode additive @mod-depth-min -1600 @mod-depth-max 1600 @mod-unit Hz)
(param lfo2_to_pan @default 0.00 @min 0 @max 1)

(param glide_ms @default 0 @min 0 @max 500 @unit ms)
(param vibrato @default 0.00 @min 0 @max 0.12 @unit st @mod true @mod-mode additive @mod-depth-min -0.08 @mod-depth-max 0.08 @mod-unit st)
(param output_gain @default 0.28 @min 0 @max 1)

(def amp_env (adsr gate trigger amp_attack_ms amp_decay_ms amp_sustain amp_release_ms))
(def filt_env_raw (adsr gate trigger filt_attack_ms filt_decay_ms filt_sustain filt_release_ms))
(def filt_env (* filt_env_raw (+ (- 1 env_vel_amt) (* velocity env_vel_amt))))
(def lfo1_env (adsr gate trigger (max 1 lfo1_attack_ms) 12 1 60))
(def lfo2_env (adsr gate trigger (max 1 lfo2_attack_ms) 12 1 60))

(def glide_coeff (exp (/ -1.0 (max 1.0 (* glide_ms 0.001 samplerate)))))
(make-history glide_hist)
(def prev_glide (read-history glide_hist))
(def glide_pitch (+ (* pitch (- 1 glide_coeff)) (* prev_glide glide_coeff)))
(def base_pitch (gswitch (gt glide_ms 0.1) glide_pitch pitch))
(write-history glide_hist base_pitch)

(def lfo1_phase (phasor lfo1_rate_hz))
(def lfo2_phase (phasor lfo2_rate_hz))
(def lfo1_delay_env (adsr gate trigger (max 1 (+ lfo1_delay_ms lfo1_attack_ms)) 12 1 60))
(def lfo2_delay_env (adsr gate trigger (max 1 (+ lfo2_delay_ms lfo2_attack_ms)) 12 1 60))
(def lfo1 (* (lfo_wave lfo1_phase lfo1_width lfo1_wave) lfo1_env lfo1_delay_env))
(def lfo2 (* (lfo_wave lfo2_phase lfo2_width lfo2_wave) lfo2_env lfo2_delay_env))

(def drift1 (triangle (phasor 0.11)))
(def drift2 (triangle (phasor 0.17)))
(def drift3 (triangle (phasor 0.07)))
(def slop_cents (* osc_slop 2.8))
(def pitch_mod_st (+ (* lfo1 (mod lfo1_to_pitch)) (* lfo1 (mod vibrato))))
(def common_ratio (semi_ratio pitch_mod_st))

(def pw (clip (+ (mod pulse_width) (* lfo1 (mod lfo1_to_pw)) (* drift3 osc_slop 0.016)) 0.08 0.92))
(def f1 (* base_pitch common_ratio
           (semi_ratio (+ (* (clip (round osc1_octave) -2 2) 12) (clip (mod osc1_semitones) -24 24)))
           (cent_ratio (+ (clip (mod osc1_detune_cents) -50 50) (* drift1 slop_cents -0.7)))))
(def f2 (* base_pitch common_ratio
           (semi_ratio (+ (* (clip (round osc2_octave) -2 2) 12) (clip (mod osc2_semitones) -24 24)))
           (cent_ratio (+ (clip (mod osc2_detune_cents) -50 50) (* drift2 slop_cents 0.9)))))
(def fsub (* f1 (selector (+ (clip (round sub_mode) 0 2) 1) 0.25 0.5 1.0)))

(def ph1 (phasor f1))
(def ph2 (phasor f2))
(def phs (phasor fsub))
(def osc1 (selector (+ (clip (round osc1_wave) 0 3) 1)
             (sin (* ph1 twopi))
             (polyblep_saw ph1 f1)
             (polyblep_pulse ph1 pw f1)
             (triangle ph1)))
(def osc2 (selector (+ (clip (round osc2_wave) 0 3) 1)
             (sin (* ph2 twopi))
             (polyblep_saw ph2 f2)
             (polyblep_pulse ph2 pw f2)
             (triangle ph2)))
(def sub (selector (+ (clip (round sub_mode) 0 2) 1)
           (sin (* phs twopi))
           (polyblep_pulse phs 0.5 fsub)
           (triangle phs)))
(def noise_cut (clip (+ 160 (* noise_color 7200)) 120 9000))
(def noise_coeff (- 1.0 (exp (/ (* -2.0 pi noise_cut) samplerate))))
(make-history noise_lp_hist)
(def noise_lp_prev (read-history noise_lp_hist))
(def colored_noise (+ noise_lp_prev (* noise_coeff (- (noise) noise_lp_prev))))
(write-history noise_lp_hist colored_noise)

(def o1_lvl (* osc1_level 0.56))
(def o2_lvl (* osc2_level 0.54))
(def sub_lvl (* sub_level 0.42))
(def noise_lvl (* noise_level 0.32))
(def src1 (* osc1 o1_lvl))
(def src2 (* osc2 o2_lvl))
(def src_sub (* sub sub_lvl))
(def src_noise (* colored_noise noise_lvl))

(def f1_input (+ (* src1 (- 1 osc1_to_f2))
                 (* src2 (- 1 osc2_to_f2))
                 (* src_sub (- 1 sub_to_f2))
                 (* src_noise (- 1 noise_to_f2))))
(def f2_direct (+ (* src1 osc1_to_f2)
                  (* src2 osc2_to_f2)
                  (* src_sub sub_to_f2)
                  (* src_noise noise_to_f2)))

(def f1_cut (clip (+ (mod filt1_cutoff) (* base_pitch filt1_keytrack) (* filt_env (mod filt1_env_amt)) (* lfo2 (mod lfo2_to_f1))) 35 14000))
(def f2_cut (clip (+ (mod filt2_cutoff) (* base_pitch filt2_keytrack) (* filt_env (mod filt2_env_amt)) (* lfo2 (mod lfo2_to_f2))) 35 14000))
(def f1_q (clip (mod filt1_resonance) 0.45 4.2))
(def f2_q (clip (mod filt2_resonance) 0.45 4.2))

(def f1_driven (tanh (* f1_input (clip (mod filt1_drive) 0.7 4.5))))

(def f1_safe_cut (clip f1_cut 1.0 (* samplerate 0.49)))
(def f1_g (tan (* pi (/ f1_safe_cut samplerate))))
(def f1_k (/ 1.0 (max f1_q 0.001)))
(def f1_a1 (/ 1.0 (+ 1.0 (* f1_g (+ f1_g f1_k)))))
(def f1_a2 (* f1_g f1_a1))
(def f1_a3 (* f1_g f1_a2))
(make-history f1_ic1eq)
(make-history f1_ic2eq)
(def f1_ic1 (read-history f1_ic1eq))
(def f1_ic2 (read-history f1_ic2eq))
(def f1_v3 (- f1_driven f1_ic2))
(def f1_v1 (+ (* f1_a1 f1_ic1) (* f1_a2 f1_v3)))
(def f1_v2 (+ f1_ic2 (* f1_a2 f1_ic1) (* f1_a3 f1_v3)))
(write-history f1_ic1eq (- (* 2.0 f1_v1) f1_ic1))
(write-history f1_ic2eq (- (* 2.0 f1_v2) f1_ic2))
(def f1_lp12 f1_v2)
(def f1_bp f1_v1)
(def f1_hp (- f1_driven (* f1_k f1_v1) f1_v2))
(def f1_ladder_res (clip (/ (- f1_q 0.45) 3.75) 0 0.92))
(def f1_lad24 (ladder f1_driven f1_safe_cut f1_ladder_res (clip (mod filt1_drive) 0.7 4.5)))
(def f1_mode_idx (clip (round filt1_mode) 0 3))
(def f1_out (selector (+ f1_mode_idx 1) f1_lp12 f1_lad24 f1_bp f1_hp))

(def f2_input (+ f2_direct (* f1_out f1_to_f2)))
(def f2_driven (tanh (* f2_input (clip (mod filt2_drive) 0.7 4.5))))

(def f2_safe_cut (clip f2_cut 1.0 (* samplerate 0.49)))
(def f2_g (tan (* pi (/ f2_safe_cut samplerate))))
(def f2_k (/ 1.0 (max f2_q 0.001)))
(def f2_a1 (/ 1.0 (+ 1.0 (* f2_g (+ f2_g f2_k)))))
(def f2_a2 (* f2_g f2_a1))
(def f2_a3 (* f2_g f2_a2))
(make-history f2_ic1eq)
(make-history f2_ic2eq)
(def f2_ic1 (read-history f2_ic1eq))
(def f2_ic2 (read-history f2_ic2eq))
(def f2_v3 (- f2_driven f2_ic2))
(def f2_v1 (+ (* f2_a1 f2_ic1) (* f2_a2 f2_v3)))
(def f2_v2 (+ f2_ic2 (* f2_a2 f2_ic1) (* f2_a3 f2_v3)))
(write-history f2_ic1eq (- (* 2.0 f2_v1) f2_ic1))
(write-history f2_ic2eq (- (* 2.0 f2_v2) f2_ic2))
(def f2_lp12 f2_v2)
(def f2_bp f2_v1)
(def f2_hp (- f2_driven (* f2_k f2_v1) f2_v2))
(def f2_ladder_res (clip (/ (- f2_q 0.45) 3.75) 0 0.92))
(def f2_lad24 (ladder f2_driven f2_safe_cut f2_ladder_res (clip (mod filt2_drive) 0.7 4.5)))
(def f2_mode_idx (clip (round filt2_mode) 0 3))
(def f2_out (selector (+ f2_mode_idx 1) f2_lp12 f2_lad24 f2_bp f2_hp))

(def amp_vel (+ (- 1 amp_vel_amt) (* velocity amp_vel_amt)))
(def amp1 (* (tanh (* f1_out 1.10)) amp1_level amp_env amp_vel))
(def amp2 (* (tanh (* f2_out 1.10)) amp2_level amp_env amp_vel))
(def pan_motion (* lfo2 lfo2_to_pan 0.22))
(def a1_pan (clip (+ amp1_pan pan_motion) -1 1))
(def a2_pan (clip (- amp2_pan pan_motion) -1 1))
(def left (+ (* amp1 (clip (- 1 (* a1_pan 0.45)) 0.2 1.45))
             (* amp2 (clip (- 1 (* a2_pan 0.45)) 0.2 1.45))))
(def right (+ (* amp1 (clip (+ 1 (* a1_pan 0.45)) 0.2 1.45))
              (* amp2 (clip (+ 1 (* a2_pan 0.45)) 0.2 1.45))))

(out (* (tanh left) output_gain) 1 @name left)
(out (* (tanh right) output_gain) 2 @name right)
