; Switched-capacitor dual filterbank — the Sherman FB2 core, interview-faithful.
;
; The filters are CLOCK-driven, not voltage-driven: each SVF core holds a
; CONSTANT coefficient g = 2*sin(pi/ratio) and only ever changes its internal
; clock rate f_clk = ratio * fc. Cutoff sweeps move the clock; the sampled
; core leaks ZOH stepping and inharmonic aliasing as the clock falls into the
; audible band (crunch). Filter 2 has no cutoff of its own — its clock is
; filter 1's clock through a divider (1, 1.2, 1.5, 2, 3, 4, 5, 7), so the two
; resonances stay in a harmonic relation through any sweep.
;
; Realism layer (beyond the Rust builtin):
;  - the clock is a VCO, not a number: cutoff slews through an asymmetric
;    expo-converter lag (up faster than down) and the clock phase jitters
;  - the resonance is a lockable oscillator: van-der-Pol amplitude-dependent
;    damping gives a hard self-osc threshold, and a biased-tanh (asymmetric)
;    loop nonlinearity lets the scream injection-lock to the program
;  - serial mode drives F2 through a saturating inter-filter stage, so F2
;    filters harmonics GENERATED by F1's resonance
;  - one shared output tanh stage: the scream eats headroom and compresses
;    the program under it instead of summing on top
;  - clock bleed is multiplicative (charge injection): level rides the input
;    envelope; fast sweeps inject a DC thump into the loop
;
; (floor harmonics) below needs dgenlisp >= v0.1.6 — before that, floor on a
; scalar signal was silently a no-op and the divider would read between taps.

(def in-l (in 1 @name signal-l))
(def in-r (in 2 @name signal-r))
(def dry (* 0.5 (+ in-l in-r)))

(param drive @min 0 @max 1 @default 0.35)
(param freq @min 0 @max 1 @default 0.5)
(param res @min 0 @max 1 @default 0.55)
(param mode @min 0 @max 1 @default 0)
(param mode2 @min 0 @max 1 @default 0)
(param harmonics @min 0 @max 7 @default 3)
(param crunch @min 0 @max 1 @default 0.25)
(param serial @min 0 @max 1 @default 0)
(param lfo-rate @min 0.02 @max 8 @default 0.4)
(param lfo-depth @min 0 @max 1 @default 0)
(param blend @min 0 @max 1 @default 0.5)
(param mix-wet @min 0 @max 1 @default 1)

; --- input drive: hairy before the filters, like the hardware's input stage
(def x (tanh (* dry (+ 1 (* drive 24)))))

; input envelope (for charge-injection bleed keying), ~10 ms follower
(make-history envh)
(def env (+ (read-history envh) (* 0.003 (- (abs x) (read-history envh)))))
(write-history envh env)

; --- cutoff position: exponential 30 Hz .. 8 kHz, LFO rides pre-link
(def lfo (* (* lfo-depth 0.35) (sin (* twopi (phasor lfo-rate)))))
(def fpos-target (clip (+ freq lfo) 0 1))

; --- VCO slew: the expo converter lags, and asymmetrically (up faster than
; down). Slewing in the log domain matches the analog control path.
(make-history fposh)
(def fpos-diff (- fpos-target (read-history fposh)))
(def fpos (+ (read-history fposh)
             (* (mix 0.0015 0.006 (> fpos-diff 0)) fpos-diff)))
(write-history fposh fpos)
(def fc (* 30 (exp (* 5.586 fpos))))

; --- the switched-cap clock: crunch morphs ratio 100:1 -> 25:1 (log)
(def ratio (* 100 (exp (* crunch (log 0.25)))))
(def gc (* 2 (sin (/ pi ratio))))
; van der Pol damping: base k dips slightly negative at max res; the +bp^2
; term (inside the core) restores damping as amplitude grows -> hard
; self-osc threshold and a bounded limit cycle instead of a polite fade
(def k (- (* 2.08 (- 1 res)) 0.22))

; --- clock jitter: an analog VCO wobbles; depth keyed to crunch
(make-history nzh)
(def nz (+ (read-history nzh) (* 0.05 (- (noise) (read-history nzh)))))
(write-history nzh nz)
(def fclk (clip (* (* fc ratio) (+ 1 (* (* 0.012 (+ 0.3 crunch)) nz)))
                200 (* samplerate 0.99)))
(def ph1 (phasor fclk))
; explicit wrap detector: ramp2trig misses wraps once the clock nears the
; host rate (phase decrements are tiny), and the clock lives up there
(make-history prevph)
(def tick1 (< ph1 (read-history prevph)))
(write-history prevph ph1)

; --- clock divider (the interview's harmonics knob): F2's clock is F1's
; clock divided by the selected ratio. Fractional ratios use a subtract-N
; accumulator, which is the dataflow form of a dual-modulus divider.
; selector is 1-based; (floor harmonics) demands dgenlisp >= v0.1.6
(def divisor (selector (+ 1 (floor harmonics)) 1 1.2 1.5 2 3 4 5 7))
(make-history divcnt)
(def cnt (+ (read-history divcnt) tick1))
(def fire2 (>= cnt divisor))
(write-history divcnt (- cnt (* divisor fire2)))
(def tick2 (* tick1 fire2))

; --- sweep thump: charge injection puts a moving DC offset into the loop
; while the clock slews; resonance rings it into a growl
(def thump (* 60 fpos-diff (mix 0.0015 0.006 (> fpos-diff 0))))
(def xin (+ x thump))

; --- one switched-cap SVF core: input sampled on the tick, Chamberlin
; update gated to the tick, states held (ZOH) between ticks.
;  - biased tanh on the bp state: asymmetric knees couple the input phase
;    into the oscillation -> the scream injection-locks to the program
;  - amplitude-dependent damping (van der Pol) bounds the scream with a
;    hard threshold instead of a soft fade
(defmacro sc-svf (sig tick morph)
  (make-history lp)
  (make-history bp)
  (def xs (latch sig tick))
  (def keff (+ k (* 1.2 (* (read-history bp) (read-history bp)))))
  (def hp (- xs (+ (read-history lp) (* keff (read-history bp)))))
  ; biased tanh normalized to unity small-signal gain (1/sech^2(0.28)):
  ; asymmetric rails without adding linear damping to the loop
  (def bpn (* 1.078 (- (tanh (+ (+ (read-history bp) (* gc hp)) 0.28)) (tanh 0.28))))
  (def lpn (+ (read-history lp) (* gc bpn)))
  (write-history bp (mix (read-history bp) bpn tick))
  (write-history lp (mix (read-history lp) lpn tick))
  (def lpw (clip (- 1 (* 2 morph)) 0 1))
  (def hpw (clip (- (* 2 morph) 1) 0 1))
  (+ (* (read-history lp) lpw)
     (+ (* (read-history bp) (- 1 (+ lpw hpw)))
        (* hp hpw))))

(def f1 (sc-svf xin tick1 mode))

; --- serial path: F1's resonance overdrives the stage feeding F2, so F2
; filters harmonics generated by F1 — the snarl of hardware serial mode
(def f2in (mix xin (tanh (* 1.7 f1)) serial))
(def f2 (sc-svf f2in tick2 mode2))

; --- clock bleed as charge injection: multiplicative, riding the input
; envelope, rising as the clock falls into the audible band
(def bleed (* (* (* (* crunch crunch) (* 0.02 (clip (- 1 (/ fclk 6000)) 0 1)))
                 (+ 0.3 (* 1.6 env)))
              (- (* 2 (< ph1 0.5)) 1)))

; --- shared output stage: an envelope-coupled gain (fast attack, slow
; release, no makeup) into ONE tanh. When the resonance screams it charges
; the envelope and the whole program ducks under it with a pump, the way
; every stage after the chip sags in the hardware.
(def pre (+ (+ (* (- 1 blend) f1) (* blend f2)) bleed))
(make-history cmph)
(def cmpa (abs pre))
(write-history cmph (+ (read-history cmph)
                       (* (mix 0.0004 0.02 (> cmpa (read-history cmph)))
                          (- cmpa (read-history cmph)))))
(def cmp (/ 1 (+ 1 (* 3.2 (read-history cmph)))))
(def wet (* 0.85 (tanh (* 1.7 (* pre cmp)))))

(out (+ (* (- 1 mix-wet) in-l) (* mix-wet wet)) 1 @name out-l)
(out (+ (* (- 1 mix-wet) in-r) (* mix-wet wet)) 2 @name out-r)
