;; Compact performance surface. DSP voicing and presets remain intact.
;; Graphics show named analytic mechanisms, not rendered audio.
(defsynth-ui
  (eseq.effects.drum-surface/panel "DIGI HAT"
    (list
      (list "Play" (list "tune" "Tune" 1 nil) (list "dec" "Decay ms" 0 nil))
      (list "Machine" (list "humanize" "Humanize" 2 nil) (list "level" "Level" 2 nil))
      (list "Filter" (list "fltf" "Filter Hz" 0 nil) (list "fltw" "Width Hz" 0 nil))
      (list "Color" (list "dist" "Distortion" 2 nil) (list "srr" "Crush" 2 nil)))
    (list
      (dict :title "Play" :controls (lambda () (list (list "engine" "Engine" 0 '("TRX-HH" "EFM-HH" "PI-HH")) (list "tune" "Tune" 1 nil) (list "dec" "Decay ms" 0 nil) (list "humanize" "Humanize" 2 nil) (list "level" "Level" 2 nil)))
        :visual (lambda () (if (= (eseq.effects.drum-surface/value "engine") 1) (eseq.effects.drum-surface/envelope "TRX low band T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "TRX high band T60 / 0–1 s" (* 0.55 (eseq.effects.drum-surface/value "dec")) "dec" "dec") (if (= (eseq.effects.drum-surface/value "engine") 2) (eseq.effects.drum-surface/envelope "Amplitude T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "FM depth T60 / 0–1 s" (eseq.effects.drum-surface/bind "mdec") "dec" "mdec") (eseq.effects.drum-surface/envelope "PI first mode T60 / 0–1 s" (* (eseq.effects.drum-surface/value "dec") (- 1 (* (/ (eseq.effects.drum-surface/value "clos") 127) 0.85)) (+ 0.20 (* (eseq.effects.drum-surface/value "ring") 1.3))) "PI excitation energy T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "dec" "dec")))))
      (dict :title "Machine" :controls (lambda () (if (= (eseq.effects.drum-surface/value "engine") 1) (list (list "gap" "Gap" 2 nil) (list "mtal" "Metal" 2 nil) (list "hpf" "Hpf" 0 nil) (list "lpf" "Lpf" 0 nil)) (if (= (eseq.effects.drum-surface/value "engine") 2) (list (list "ptch" "Pitch" 1 nil) (list "trem" "Trem" 2 nil) (list "tfrq" "Trem Hz" 0 nil) (list "mod_amt" "FM depth" 2 nil) (list "mfrq" "FM Hz" 0 nil) (list "mdec" "FM decay ms" 0 nil) (list "fb" "Feedback" 2 nil)) (list (list "ptch" "Pitch" 1 nil) (list "clsn" "Collision" 2 nil) (list "ring" "Ring" 2 nil) (list "ag" "Air" 2 nil) (list "au" "Damping" 2 nil) (list "br" "Body" 2 nil) (list "clos" "Closed" 0 nil)))))
        :visual (lambda () (if (= (eseq.effects.drum-surface/value "engine") 1) (eseq.effects.drum-surface/envelope "TRX low band T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "TRX high band T60 / 0–1 s" (* 0.55 (eseq.effects.drum-surface/value "dec")) "dec" "dec") (if (= (eseq.effects.drum-surface/value "engine") 2) (eseq.effects.drum-surface/envelope "Amplitude T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "FM depth T60 / 0–1 s" (eseq.effects.drum-surface/bind "mdec") "dec" "mdec") (eseq.effects.drum-surface/envelope "PI first mode T60 / 0–1 s" (* (eseq.effects.drum-surface/value "dec") (- 1 (* (/ (eseq.effects.drum-surface/value "clos") 127) 0.85)) (+ 0.20 (* (eseq.effects.drum-surface/value "ring") 1.3))) "PI excitation energy T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "dec" "dec")))))
      (dict :title "Filter" :controls (lambda () (list (list "fltf" "Filter Hz" 0 nil) (list "fltw" "Width Hz" 0 nil) (list "fltq" "Filter Q" 2 nil) (list "eqf" "EQ Hz" 0 nil) (list "eqg" "EQ dB" 1 nil)))
        :visual (lambda () (if (= (eseq.effects.drum-surface/value "engine") 1) (eseq.effects.drum-surface/envelope "TRX low band T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "TRX high band T60 / 0–1 s" (* 0.55 (eseq.effects.drum-surface/value "dec")) "dec" "dec") (if (= (eseq.effects.drum-surface/value "engine") 2) (eseq.effects.drum-surface/envelope "Amplitude T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "FM depth T60 / 0–1 s" (eseq.effects.drum-surface/bind "mdec") "dec" "mdec") (eseq.effects.drum-surface/envelope "PI first mode T60 / 0–1 s" (* (eseq.effects.drum-surface/value "dec") (- 1 (* (/ (eseq.effects.drum-surface/value "clos") 127) 0.85)) (+ 0.20 (* (eseq.effects.drum-surface/value "ring") 1.3))) "PI excitation energy T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "dec" "dec")))))
      (dict :title "Color" :controls (lambda () (list (list "dist" "Distortion" 2 nil) (list "srr" "Crush" 2 nil) (list "amd" "AM depth" 2 nil) (list "amf" "AM Hz" 0 nil)))
        :visual (lambda () (if (= (eseq.effects.drum-surface/value "engine") 1) (eseq.effects.drum-surface/envelope "TRX low band T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "TRX high band T60 / 0–1 s" (* 0.55 (eseq.effects.drum-surface/value "dec")) "dec" "dec") (if (= (eseq.effects.drum-surface/value "engine") 2) (eseq.effects.drum-surface/envelope "Amplitude T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "FM depth T60 / 0–1 s" (eseq.effects.drum-surface/bind "mdec") "dec" "mdec") (eseq.effects.drum-surface/envelope "PI first mode T60 / 0–1 s" (* (eseq.effects.drum-surface/value "dec") (- 1 (* (/ (eseq.effects.drum-surface/value "clos") 127) 0.85)) (+ 0.20 (* (eseq.effects.drum-surface/value "ring") 1.3))) "PI excitation energy T60 / 0–1 s" (eseq.effects.drum-surface/bind "dec") "dec" "dec"))))))))
