; DGenLisp instrument — generates audio from gate, pitch, velocity, trigger, and shared mod buses
; Inputs: gate (ch 1), pitch_hz (ch 2), velocity (ch 3), trigger (ch 4)
; Mod inputs: mod1..mod6 (ch 5..10)
; Output: audio (ch 1)
; Helpers injected at compile time: adsr/modulation macros

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(param attack @min 0 @max 1000 @default 400)
(param decay @min 0 @max 1000)
(param sustain @default 1)
(param release @min 0 @max 1000 @default 600)
(def env (* 1 (adsr gate trigger attack decay sustain release)))
(param fmmod @min 0.1 @max 3 @default 1 )
(def fm (* fmmod (sin (* (phasor (* 1 pitch)) twopi))))
(def fm2 (* fmmod (sin (* (phasor (* 1.03 pitch)) twopi))))
(param trimod @min 0 @max 1 @mod true @mod-mode additive)
(param oscdiv1 @min 1 @max 8 @default 6)
(param oscdiv2 @min 1 @max 8 @default 4)
(def osc (sin (+ (* env fm) (* (triangle (phasor (/ pitch oscdiv1)) (mod trimod)) twopi))))
(def osc2 (sin (+ (* env fm2) (* (triangle (phasor (/ pitch oscdiv2)) (mod trimod)) twopi))))
(def sum (mix osc osc2 0.5))
(param res @min 1 @max 9 @default 2)
(param cutoff @min 50 @max 1000 @default 500 @mod true @mod-mode additive)
(param filtmod @min 0 @max 5000 @default 1000)
(def cmod (+ (mod cutoff) (* filtmod (adsr gate trigger 50 120 0.4 400))))
(def filtered (biquad sum cmod res 1 0))
(out (* filtered 0.05 env velocity) 1 @name audio)
