; Rhodes-style electric piano — modal tine/tonebar model

(def gate     (in 1  @name gate))
(def pitch    (in 2  @name pitch))
(def velocity (in 3  @name velocity))
(def trigger  (in 4  @name trigger))
(def mod1 (in 5  @name mod1 @modulator 1))
(def mod2 (in 6  @name mod2 @modulator 2))
(def mod3 (in 7  @name mod3 @modulator 3))
(def mod4 (in 8  @name mod4 @modulator 4))
(def mod5 (in 9  @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(param amp_attack_ms  @default 1    @min 0    @max 50   @unit ms)
(param decay_ms       @default 3200 @min 200  @max 9000 @unit ms @mod true @mod-mode additive)
(param release_ms     @default 900  @min 20   @max 5000 @unit ms)
(param tone           @default 0.38 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param tine_mix       @default 0.20 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param bell           @default 0.14 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param bark           @default 0.22 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param pickup         @default 0.55 @min 0.05 @max 0.95)
(param body_ratio     @default 1.00 @min 0.5  @max 3.0  @mod true @mod-mode additive)
(param tine_ratio     @default 2.85 @min 1.0  @max 8.0  @mod true @mod-mode additive)
(param bell_ratio     @default 6.90 @min 1.0  @max 16.0 @mod true @mod-mode additive)
(param vel_bright     @default 0.70 @min 0.0  @max 1.0)
(param trem_rate      @default 4.8  @min 0.1  @max 12.0 @unit hz @mod true @mod-mode additive)
(param trem_depth     @default 0.10 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param gain           @default 0.24 @min 0.0  @max 1.0)

(def env_amp  (adsr gate trigger amp_attack_ms decay_ms 0.18 release_ms))
(def env_hit  (adsr gate trigger 0 22 0 10))
(def env_tine (adsr gate trigger 0 480 0 40))
(def env_bell (adsr gate trigger 0 180 0 30))

(def vel_factor (+ (- 1 vel_bright) (* vel_bright velocity)))
(def tone_shaped (clip (mod tone) 0.0 1.0))
(def tine_amt    (clip (mod tine_mix) 0.0 1.0))
(def bell_amt    (clip (mod bell) 0.0 1.0))
(def bark_amt    (clip (mod bark) 0.0 1.0))

(def noise_hit (* (noise) env_hit))
(def hammer_lp (biquad noise_hit (+ 700.0 (* tone_shaped 2600.0) (* vel_factor 1200.0)) 0.8 0.9 0))
(def hammer_bp (biquad hammer_lp (+ 1200.0 (* bark_amt 1800.0) (* velocity 1200.0)) 1.1 0.35 2))
(def hammer (+ (* hammer_lp 0.08) (* hammer_bp (+ 0.02 (* bark_amt 0.08) (* velocity 0.04)))))

(def p_body (phasor (* pitch (mod body_ratio))))
(def p_tine (phasor (* pitch (mod tine_ratio))))
(def p_bell (phasor (* pitch (mod bell_ratio))))
(def p_det  (phasor (* pitch (+ (mod tine_ratio) 0.03))))

(def body1 (sin (* twopi p_body)))
(def body2 (sin (* twopi (* p_body 2.0))))
(def tine1 (sin (* twopi p_tine)))
(def tine2 (sin (* twopi p_det)))
(def bell1 (sin (* twopi p_bell)))

(def body_core (* (+ (* body1 0.82) (* body2 0.18)) env_amp vel_factor))
(def tine_env (* env_tine (+ 0.25 (* 0.9 vel_factor) (* 0.7 tine_amt))))
(def tine_core (* (+ (* tine1 0.7) (* tine2 0.3)) tine_env))
(def bell_env (* env_bell bell_amt vel_factor (+ 0.2 (* 0.8 velocity))))
(def bell_core (* bell1 bell_env))

(def pickup_notch (- body_core (* 0.45 (sin (* twopi (+ p_body (* pickup 0.12)))) env_amp vel_factor)))
(def reson (+ pickup_notch
              (* tine_core (+ 0.10 (* 0.55 tine_amt)))
              (* bell_core (+ 0.05 (* 0.60 bell_amt)))))

(def bark_drive (+ 1.0 (* velocity 1.4 bark_amt) (* vel_factor 0.4)))
(def struck (+ reson hammer))
(def saturated (tanh (* struck bark_drive)))
(def voiced_lp (biquad saturated (+ 900.0 (* tone_shaped 3200.0) (* vel_factor 1000.0)) 0.9 0.92 0))
(def voiced_bp1 (biquad voiced_lp 280.0 1.3 0.10 2))
(def voiced_bp2 (biquad voiced_lp 780.0 1.1 0.08 2))
(def voiced (+ voiced_lp voiced_bp1 voiced_bp2))

(def trem_lfo (+ 1.0 (* (sin (* twopi (phasor trem_rate))) trem_depth)))
(def final (* voiced trem_lfo velocity gain))

(out final 1 @name audio)