; Rhodes-style electric piano — refined modal tine/tonebar model

(def gate     (in 1  @name gate))
(def pitch    (in 2  @name pitch))
(def velocity (in 3  @name velocity))
(def trigger  (in 4  @name trigger))
(def mod1 (in 5  @name mod1 @modulator 1))
(def mod2 (in 6  @name mod2 @modulator 2))
(def mod3 (in 7  @name mod3 @modulator 3))
(def mod4 (in 8  @name mod4 @modulator 4))
(def mod5 (in 9  @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(param amp_attack_ms  @default 1    @min 0    @max 40   @unit ms)
(param decay_ms       @default 4200 @min 400  @max 12000 @unit ms @mod true @mod-mode additive)
(param release_ms     @default 1200 @min 40   @max 7000 @unit ms)
(param tone           @default 0.34 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param tine_mix       @default 0.16 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param bell           @default 0.10 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param bark           @default 0.18 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param pickup         @default 0.60 @min 0.05 @max 0.95 @mod true @mod-mode additive)
(param body_ratio     @default 1.00 @min 0.5  @max 3.0  @mod true @mod-mode additive)
(param tine_ratio     @default 2.62 @min 1.0  @max 8.0  @mod true @mod-mode additive)
(param tine_detune    @default 0.018 @min 0.0 @max 0.08 @mod true @mod-mode additive)
(param bell_ratio     @default 6.25 @min 1.0  @max 16.0 @mod true @mod-mode additive)
(param tonebar_mix    @default 0.24 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param hammer_noise   @default 0.09 @min 0.0  @max 0.5  @mod true @mod-mode additive)
(param vel_bright     @default 0.62 @min 0.0  @max 1.0)
(param trem_rate      @default 4.8  @min 0.1  @max 12.0 @unit hz @mod true @mod-mode additive)
(param trem_depth     @default 0.06 @min 0.0  @max 1.0  @mod true @mod-mode additive)
(param gain           @default 0.22 @min 0.0  @max 1.0)

(def env_amp   (adsr gate trigger amp_attack_ms decay_ms 0.20 release_ms))
(def env_hit   (adsr gate trigger 0 18 0 14))
(def env_bark  (adsr gate trigger 0 140 0 35))
(def env_tine  (adsr gate trigger 0 780 0 90))
(def env_bell  (adsr gate trigger 0 260 0 40))
(def env_body2 (adsr gate trigger 0 2200 0 180))

(def vel_factor (+ (- 1 vel_bright) (* vel_bright velocity)))
(def tone_shaped  (clip (mod tone) 0.0 1.0))
(def tine_amt     (clip (mod tine_mix) 0.0 1.0))
(def bell_amt     (clip (mod bell) 0.0 1.0))
(def bark_amt     (clip (mod bark) 0.0 1.0))
(def pickup_pos   (clip (mod pickup) 0.05 0.95))
(def tonebar_amt  (clip (mod tonebar_mix) 0.0 1.0))
(def hammer_amt   (clip (mod hammer_noise) 0.0 0.5))
(def detune_amt   (clip (mod tine_detune) 0.0 0.08))

(def hammer_raw (* (noise) env_hit))
(def hammer_lp (biquad hammer_raw (+ 900.0 (* tone_shaped 2000.0) (* vel_factor 700.0)) 0.8 0.9 0))
(def hammer_bp (biquad hammer_lp (+ 1700.0 (* bark_amt 1400.0) (* velocity 900.0)) 1.2 0.28 2))
(def hammer (+ (* hammer_lp hammer_amt) (* hammer_bp (+ (* bark_amt 0.06) (* velocity 0.03)))))

(def p_body   (phasor (* pitch (mod body_ratio))))
(def p_body2  (phasor (* pitch (* (mod body_ratio) 2.0))))
(def p_tbar   (phasor (* pitch 0.50)))
(def p_tine   (phasor (* pitch (mod tine_ratio))))
(def p_tine_d (phasor (* pitch (+ (mod tine_ratio) detune_amt))))
(def p_bell   (phasor (* pitch (mod bell_ratio))))

(def s_body1 (sin (* twopi p_body)))
(def s_body2 (sin (* twopi p_body2)))
(def s_tbar  (sin (* twopi p_tbar)))
(def s_tine1 (sin (* twopi p_tine)))
(def s_tine2 (sin (* twopi p_tine_d)))
(def s_bell  (sin (* twopi p_bell)))

(def body_core (* (+ (* s_body1 0.78) (* s_body2 0.12 env_body2) (* s_tbar 0.18 tonebar_amt)) env_amp vel_factor))
(def tine_core (* (+ (* s_tine1 0.72) (* s_tine2 0.28)) env_tine (+ 0.16 (* 0.70 tine_amt) (* 0.20 vel_factor))))
(def bell_core (* s_bell env_bell bell_amt (+ 0.10 (* 0.75 velocity))))
(def bark_core (* (+ (* s_tine1 0.6) (* s_bell 0.4)) env_bark bark_amt velocity 0.35))

(def pickup_fund (- s_body1 (* 0.52 (sin (* twopi (+ p_body (* pickup_pos 0.17)))))))
(def pickup_tine (- s_tine1 (* 0.46 (sin (* twopi (+ p_tine (* pickup_pos 0.11)))))))

(def body_pick (* pickup_fund env_amp vel_factor 0.85))
(def tine_pick (* (+ (* pickup_tine 0.74) (* s_tine2 0.26)) env_tine (+ 0.10 (* 0.62 tine_amt))))

(def reson (+ body_core body_pick tine_core tine_pick bell_core bark_core hammer))
(def drive (+ 1.0 (* velocity bark_amt 1.0) (* vel_factor 0.25)))
(def sat (tanh (* reson drive)))
(def body_lp (biquad sat (+ 1100.0 (* tone_shaped 2200.0) (* vel_factor 700.0)) 0.85 0.92 0))
(def wood1 (biquad body_lp 310.0 1.1 0.08 2))
(def wood2 (biquad body_lp 890.0 1.0 0.06 2))
(def sparkle (biquad body_lp (+ 2400.0 (* tone_shaped 2200.0)) 0.8 0.05 2))
(def voiced (+ body_lp wood1 wood2 (* sparkle (+ 0.05 (* 0.30 tine_amt) (* 0.25 bell_amt)))))

(def trem_lfo (+ 1.0 (* (sin (* twopi (phasor trem_rate))) trem_depth)))
(def final (* voiced trem_lfo velocity gain))

(out final 1 @name audio)