#!/usr/bin/env python3
"""Generate the research 2x polyphase FIR pair; round-trip latency is 63 frames.

At 48 kHz base rate, the interpolation filter passes through 20 kHz and
rejects images from 28 kHz. The odd phase is exactly a half-gain delay.
Explicit histories avoid dynamic indexing in the per-sample audio graph.
"""
from pathlib import Path

import numpy as np
from scipy.signal import firwin, freqz


def coefficients():
    h = firwin(127, .5, window=("kaiser", 10.5), scale=False)
    h[1::2] = 0
    h[63] = .5
    h[::2] *= .5 / h[::2].sum()
    return h


def histories(prefix, signal, count):
    lines = [f"  (def {prefix}0 {signal})"]
    for i in range(1, count+1):
        lines.extend([f"  (make-history {prefix}h{i})",
                      f"  (def {prefix}{i} (read-history {prefix}h{i}))"])
    for i in range(1, count+1):
        lines.append(f"  (write-history {prefix}h{i} {prefix}{i-1})")
    return lines


def generate():
    h = coefficients()
    frequency, response = freqz(h, worN=65536, fs=2)
    ripple = float(np.max(abs(20*np.log10(abs(response[frequency <= 5/12])))))
    stop = float(np.max(20*np.log10(np.maximum(abs(response[frequency >= 7/12]), 1e-30))))
    if ripple > .001 or stop > -90:
        raise ValueError(f"FIR design failed: ripple={ripple}, stop={stop}")
    lines = ["; Generated by tools/drift/generate_halfband.py; research only.",
             "; 127 taps, 63 base-frame round-trip latency. Do not edit coefficients.",
             "; Up returns the even and odd samples in chronological order.",
             "(defmacro drift-research-up2 (x)"]
    lines += histories("x", "x", 63)
    terms = " ".join(f"(* {2*c:.17g} x{i})" for i, c in enumerate(h[::2]))
    lines += [f"  (tuple (+ {terms}) x31))", "",
              "(defmacro drift-research-down2 (even odd)"]
    lines += histories("e", "even", 63)
    lines += histories("o", "odd", 32)
    terms = " ".join(f"(* {c:.17g} e{i})" for i, c in enumerate(h[::2]))
    lines += [f"  (+ {terms} (* .5 o32)))", ""]
    return "\n".join(lines), ripple, stop


if __name__ == "__main__":
    source, ripple, stop = generate()
    path = Path(__file__).resolve().parent / "prototypes/halfband2x.lisp"
    path.write_text(source)
    print(f"{path}: passband error {ripple:.6f} dB, stopband {stop:.2f} dB")
