(defmacro schroeder-allpass (input delay_samples feedback)
  (make-history w_hist)
  (def w_prev (read-history w_hist))
  (def d (delay w_prev delay_samples))
  (def w (+ input (* feedback d)))
  (def out (- d (* feedback w)))
  (write-history w_hist w)
  out)
(defmacro allpass-filter (input cutoff q) (svf input cutoff q 4.0))
(make-history history1)
(def value2 0.6)
(def value1 0.8)
(param rate @min 1.0 @max 128.0 @default 32.0)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def div1 (/ pitch 8.0))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mul1 (* clock rate))
(def wrap1 (wrap mul1 0.0 1.0))
(def ramp2trig2 (ramp2trig wrap1))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))
(param trishape @mod true @mod-mode additive @min 0.0 @max 1.0)
(def modulated1 (mod trishape))
(def latch2 (latch modulated1 ramp2trig2))
(def triangle1 (triangle wrap1 latch2))
(def mul5 (* triangle1 2.0))
(def scale2 (scale triangle1 0.0 1.0 500.0 501.0))
(def scale1 (scale triangle1 0.0 1.0 53.0 20.0))
(def add2 (+ scale1 div1))
(def mul4 (* (read-history history1) mul5))
(def phasor1 (phasor add2))
(def ramp2trig1 (ramp2trig phasor1))
(def latch1 (latch triangle1 ramp2trig1))
(def triangle2 (triangle phasor1 latch1))
(def mul3 (* triangle2 twopi))
(def add1 (+ mul3 mul4))
(def cos1 (cos add1))
(def schroeder-allpass1 (schroeder-allpass cos1 scale2 value2))
(def schroeder-allpass2 (schroeder-allpass schroeder-allpass1 scale2 value1))
(def mix1 (mix cos1 schroeder-allpass2 0.5))
(param attack @group amp @env amp-env @role attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @group amp @env amp-env @role decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0.0 @max 1.0)
(param release @group amp @env amp-env @role release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(def mul2 (* env (pow triangle1 4.0)))
(def phase (phasor pitch))
(out mix1 1 @name audio)
(out mul2 2 @name md @modulator 1)
(write-history history1 cos1)