;; Cylindrical single-reed waveguide. The bore carries pressure waves; its
;; inverting open termination gives the closed/open tube its odd resonances.
;; See tools/pm-clarinet/README.md for the model, reference and render checks.

(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro clarinet-smooth (target ms)
  (make-history previous)
  (make-history ready)
  (def coefficient (exp (/ -1 (* 0.001 ms samplerate))))
  (def value (gswitch (read-history ready) (mix target (read-history previous) coefficient) target))
  (write-history previous value)
  (write-history ready 1)
  value)

(defmacro clarinet-cylinder (frequency mouth stiffness closure curvature cutoff loss warp)
  (make-history outgoing_h)
  (make-history low_h)
  (make-history ap_x)
  (make-history ap_y)
  (make-history dc_x)
  (make-history dc_y)
  (def f (clip frequency 25 4000))
  (def pole (exp (/ (* -1 twopi (clip cutoff 500 15000)) samplerate)))
  (def omega (/ (* twopi f) samplerate))
  (def low_phase (/ (atan (/ (* pole (sin omega)) (- 1 (* pole (cos omega))))) omega))
  ;; A passive allpass provides controllable dispersion. At Warp=0 it is
  ;; exactly one sample; subtract both filter phases from the half-period.
  (def a (- (clip warp 0 0.75)))
  (def half_omega (* 0.5 omega))
  (def allpass_phase (/ (* 2 (atan (* (/ (- 1 a) (+ 1 a))
    (/ (sin half_omega) (cos half_omega))))) omega))
  (def length (max 2 (- (/ samplerate (* 2 f)) low_phase allpass_phase 1)))
  (def arrival (delay (read-history outgoing_h) length))
  (def low (mix arrival (read-history low_h) pole))
  (def dispersed (+ (* a low) (read-history ap_x) (* (- a) (read-history ap_y))))
  (def reflected (* (- (- 1 (clip loss 0.002 0.15))) dispersed))
  (def delta (- mouth reflected))
  (def linear (clip (+ closure (* stiffness delta)) -1 1))
  (def shaped (pow (abs linear) curvature))
  (def reflection (gswitch (lt linear 0) (- shaped) shaped))
  (def outgoing (- mouth (* delta reflection)))
  (def dc (+ (- arrival (read-history dc_x))
    (* (exp (/ (* -20 twopi) samplerate)) (read-history dc_y))))
  (write-history outgoing_h outgoing)
  (write-history low_h low)
  (write-history ap_x low)
  (write-history ap_y dispersed)
  (write-history dc_x arrival)
  (write-history dc_y dc)
  dc)

(defmacro clarinet-expression (gate trigger rate depth delay_ms breath_depth growl_hz growl_depth)
  (make-history age)
  (make-history last_gate)
  (def onset (max trigger (* (gt gate 0.5) (lte (read-history last_gate) 0.5))))
  (def elapsed (gswitch onset 0 (min 60 (+ (read-history age) (/ 1 samplerate)))))
  (def fade (clip (/ (- elapsed (* delay_ms 0.001)) 0.15) 0 1))
  (def wave (* fade (sin (* twopi (phasor rate)))))
  (def ratio (pow 2 (/ (* depth wave) 1200)))
  (def growl (sin (* twopi (phasor growl_hz))))
  (def pressure_motion (* (+ 1 (* wave breath_depth)) (+ 1 (* growl growl_depth))))
  (write-history age elapsed)
  (write-history last_gate gate)
  (tuple ratio pressure_motion))

(param attack @group amp @env amp-env @role attack @default 25 @min 0 @max 2000 @unit ms)
(param decay @group amp @env amp-env @role decay @default 180 @min 1 @max 2000 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.95 @min 0 @max 1)
(param release @group amp @env amp-env @role release @default 90 @min 1 @max 5000 @unit ms)
(param pressure @group reed @default 0.845 @min 0 @max 1.3 @mod true @mod-mode additive)
(param stiffness @group reed @default 0.309 @min 0.12 @max 0.65 @mod true @mod-mode additive)
(param closure @group reed @default 0.528 @min 0.35 @max 0.9 @mod true @mod-mode additive)
(param curve @group reed @default 2.421 @min 0.5 @max 3 @mod true @mod-mode additive)
(param air @group reed @default 0.008 @min 0 @max 0.25 @mod true @mod-mode additive)
(param vel_blow @group reed @default 0.2 @min 0 @max 1)
(param damping_hz @group bore @default 3608.461 @min 500 @max 15000 @unit Hz @mod true @mod-mode additive)
(param loss @group bore @default 0.051 @min 0.002 @max 0.15 @mod true @mod-mode additive)
(param warp @group bore @default 0 @min 0 @max 0.75 @mod true @mod-mode additive)
(param tune @group bore @default 0 @min -100 @max 100 @unit cents @mod true @mod-mode additive)
(param bell_hz @group color @default 8912.585 @min 800 @max 16000 @unit Hz @mod true @mod-mode additive)
(param body @group color @default 0.897 @min 0 @max 0.9 @mod true @mod-mode additive)
(param body_hz @group color @default 960.542 @min 200 @max 5000 @unit Hz @mod true @mod-mode additive)
(param body_q @group color @default 3.841 @min 0.5 @max 6 @mod true @mod-mode additive)
(param vib_cent @group expression @default 0 @min 0 @max 100 @unit cents @mod true @mod-mode additive)
(param vib_hz @group expression @default 5.3 @min 0.1 @max 12 @unit Hz @mod true @mod-mode additive)
(param vib_wait @group expression @default 240 @min 0 @max 2000 @unit ms)
(param vib_air @group expression @default 0 @min 0 @max 0.3 @mod true @mod-mode additive)
(param growl @group expression @default 0 @min 0 @max 0.7 @mod true @mod-mode additive)
(param growl_hz @group expression @default 75 @min 15 @max 250 @unit Hz @mod true @mod-mode additive)
(param gain @default 0.6 @min 0 @max 1 @mod true @mod-mode additive)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def envelope (adsr gate trigger attack decay sustain release))
(def pressure_level (clarinet-smooth (clip (mod pressure) 0 1.3) 8))
(def reed_slope (clarinet-smooth (clip (mod stiffness) 0.12 0.65) 5))
(def reed_closure (clarinet-smooth (clip (mod closure) 0.35 0.9) 5))
(def reed_curve (clarinet-smooth (clip (mod curve) 0.5 3) 5))
(def bore_cutoff (clarinet-smooth (clip (mod damping_hz) 500 15000) 8))
(def bore_loss (clarinet-smooth (clip (mod loss) 0.002 0.15) 8))
(def bore_warp (clarinet-smooth (clip (mod warp) 0 0.75) 8))
(def (pitch_motion breath_motion) (clarinet-expression gate trigger
  (clip (mod vib_hz) 0.1 12) (clip (mod vib_cent) 0 100) vib_wait
  (clip (mod vib_air) 0 0.3) (clip (mod growl_hz) 15 250) (clip (mod growl) 0 0.7)))
(def air_noise (svf (noise) 4000 0.7 0))
(def blowing (clip (* envelope pressure_level (mix 1 (clip velocity 0 1) vel_blow)
  breath_motion (+ 1 (* (clip (mod air) 0 0.25) air_noise))) 0 2))
(def frequency (* pitch pitch_motion (pow 2 (/ (clip (mod tune) -100 100) 1200))))
(def bore (clarinet-cylinder frequency blowing reed_slope reed_closure reed_curve bore_cutoff bore_loss bore_warp))
(def bell (svf bore (min (* samplerate 0.4) (clip (mod bell_hz) 800 16000)) 0.7 0))
(def q (clip (mod body_q) 0.5 6))
(def band (/ (svf bell (clip (mod body_hz) 200 5000) q 1) q))
(def colored (mix bell band (clip (mod body) 0 0.9)))
(out (* colored (clip velocity 0 1) (clip (mod gain) 0 1)) 1 @name audio)
