(defmacro subtle_saturator (input drive makeup mix_amt)
  (def x (* input drive))
  (def xc (clip x -1.0 1.0))
  (def sat (- xc (/ (* (* xc xc) xc) 3.0)))
  (def wet (* sat makeup))
  (mix input wet mix_amt))
(defmacro triangle_909_kick (trigger tune decay click_amt distortion)
  (make-history amp_h)
  (make-history pitch_h)
  (make-history click_h)
  (def amp_decay (+ 0.995 (* decay 0.0045)))
  (def amp_next (clip (+ trigger (* (read-history amp_h) amp_decay)) 0.0 1.5))
  (write-history amp_h amp_next)
  (def pitch_next (clip (+ trigger (* (read-history pitch_h) 0.988)) 0.0 1.5))
  (write-history pitch_h pitch_next)
  (def click_next (clip (+ trigger (* (read-history click_h) 0.93)) 0.0 1.5))
  (write-history click_h click_next)
  (def freq (clip (+ tune (* pitch_next 180.0)) 20.0 1000.0))
  (def phasor1 (phasor freq))
  (def tri_osc (triangle phasor1))
  (def click_noise (svf (* (noise) click_next) 3500.0 1.0 1.0))
  (def raw_kick (+ (* tri_osc amp_next) (* click_noise click_amt 0.3)))
  (tanh (* raw_kick (+ 1.0 (* distortion 3.0)))))
(param makup @min 0.0 @max 8.0)
(param drive @min 1.0 @default 1.0 @max 4.0)
(param drivemix)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def triangle_909_kick1 (triangle_909_kick trigger pitch 0.9999 0.5 0.5))
(def subtle_saturator1 (subtle_saturator triangle_909_kick1 drive makup drivemix))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(out (* subtle_saturator1 env velocity (mod gain)) 1 @name audio)