(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(defmacro semi_ratio (semi)
  (exp (/ (* (log 2) semi) 12)))

(param sub_level @default 0.95 @min 0 @max 1)
(param deep_sub_level @default 0.45 @min 0 @max 1)
(param saw_level @default 0.48 @min 0 @max 1)
(param pulse_level @default 0.34 @min 0 @max 1)
(param pulse_width @default 0.46 @min 0.05 @max 0.95)
(param pulse_transpose @default 0 @min -24 @max 12 @unit st)
(param detune @default -7 @min -30 @max 30 @unit cent)
(param fat_spread @default 9 @min 0 @max 35 @unit cent)
(param fatness @default 0.62 @min 0 @max 1)

(param cutoff @default 240 @min 40 @max 5000 @unit Hz @mod true @mod-mode additive)
(param resonance @default 0.28 @min 0 @max 0.95 @mod true @mod-mode additive)
(param filter_env_amount @default 760 @min -1500 @max 4000 @unit Hz)
(param filter_model @default 1 @min 0 @max 1)
(param drive @default 2.7 @min 1 @max 7)
(param bass_boost @default 0.42 @min 0 @max 1)

(param amp_attack @default 3 @min 1 @max 500 @unit ms)
(param amp_decay @default 210 @min 1 @max 2000 @unit ms)
(param amp_sustain @default 0.76 @min 0 @max 1)
(param amp_release @default 320 @min 1 @max 3000 @unit ms)

(param filt_attack @default 5 @min 1 @max 1000 @unit ms)
(param filt_decay @default 460 @min 1 @max 3000 @unit ms)
(param filt_sustain @default 0.16 @min 0 @max 1)
(param filt_release @default 540 @min 1 @max 4000 @unit ms)

(param tone @default 0.38 @min 0 @max 1)
(param gain @default 0.24 @min 0 @max 1)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))
(def filt_env (adsr gate trigger filt_attack filt_decay filt_sustain filt_release))

(def detune_ratio (pow 2 (/ detune 1200)))
(def pulse_transpose_ratio (semi_ratio pulse_transpose))
(def pulse_ratio (* detune_ratio pulse_transpose_ratio))
(def spread_ratio_up (pow 2 (/ fat_spread 1200)))
(def spread_ratio_dn (pow 2 (/ (- 0 fat_spread) 1200)))

(def phase_sub (phasor (* pitch 0.5)))
(def phase_deep (phasor (* pitch 0.25)))
(def phase_saw (phasor pitch))
(def phase_saw_up (phasor (* pitch spread_ratio_up)))
(def phase_saw_dn (phasor (* pitch spread_ratio_dn)))
(def phase_pulse (phasor (* pitch pulse_ratio)))

(def sub_sine (sin (* phase_sub twopi)))
(def deep_sine (sin (* phase_deep twopi)))
(def deep_pulse (polyblep_pulse phase_sub 0.5 (* pitch 0.5)))
(def deep_blend (+ (* deep_sine 0.72) (* deep_pulse 0.28)))

(def saw_mid (polyblep_saw phase_saw pitch))
(def saw_up (polyblep_saw phase_saw_up (* pitch spread_ratio_up)))
(def saw_dn (polyblep_saw phase_saw_dn (* pitch spread_ratio_dn)))
(def wide_saw (/ (+ saw_up saw_dn) 2))
(def fat_saw (+ (* saw_mid (- 1 fatness)) (* wide_saw fatness)))

(def pulse_freq (* pitch pulse_ratio))
(def pulse_osc (polyblep_pulse phase_pulse (clip pulse_width 0.05 0.95) pulse_freq))

(def raw_mix (+ (* sub_sine sub_level) (* deep_blend deep_sub_level) (* fat_saw saw_level) (* pulse_osc pulse_level)))
(def mix_gain (/ 1 (+ 0.48 sub_level deep_sub_level saw_level pulse_level)))
(def driven (tanh (* raw_mix mix_gain drive)))

(def env_cutoff (+ (clip (mod cutoff) 40 5000) (* filt_env filter_env_amount)))
(def bright_cutoff (+ env_cutoff (* tone 1300)))
(def safe_cutoff (clip bright_cutoff 35 9000))
(def safe_res (clip (mod resonance) 0 0.95))
(def svf_q (+ 0.55 (* safe_res 3.65)))
(def svf_filtered (svf driven safe_cutoff svf_q 0))
(def ladder_filtered (ladder driven safe_cutoff safe_res drive))
(def filtered (selector (+ 1 filter_model) svf_filtered ladder_filtered))

(def clean_low (svf (+ (* sub_sine sub_level) (* deep_blend deep_sub_level)) 150 0.65 0))
(def boosted (+ filtered (* clean_low bass_boost 0.00012)))
(def thick (tanh (* boosted (+ 1 (* fatness 0.65)))))

(out (* thick amp_env velocity gain) 1 @name audio)
