; Machinedrum-style kick machines: TRX-BD, TRX-B2, EFM-BD, PI-BD, GND-SN.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))

(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro md-env-hold (trig hold_ms decay_ms)
  (make-history e)
  (make-history age)
  (def prev_age (read-history age))
  (def next_age (gswitch (gt trig 0.5) 0.0 (+ prev_age 1.0)))
  (def held (lt next_age (* hold_ms 0.001 samplerate)))
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (gswitch held 1.0 (* (read-history e) coef))))
  (write-history age next_age)
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro latch-trig (sig trig)
  (make-history h)
  (def old (read-history h))
  (def v (gswitch (gt trig 0.5) sig old))
  (write-history h v)
  v)

(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)

(defmacro md-ping (exc freq t60_ms trig)
  (make-history y1)
  (make-history y2)
  (def y1p (gswitch (gt trig 0.5) 0.0 (read-history y1)))
  (def y2p (gswitch (gt trig 0.5) 0.0 (read-history y2)))
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def c (* 2.0 r (cos (* twopi (/ (clip freq 8 18000) samplerate)))))
  (def y (- (+ exc (* c y1p)) (* r r y2p)))
  (write-history y2 y1p)
  (write-history y1 y)
  y)

(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (def hard (clip (* x (+ 1 (* 16 d))) -1 1))
  (def soft (tanh (* x (+ 1 (* 5 d)))))
  (+ (* soft (- 1 d)) (* hard d)))

(defmacro md-srr (x amount trig)
  (def a (clip amount 0 1))
  (def hold_hz (exp (+ (log 300.0) (* (- 1 a) (- (log 44100.0) (log 300.0))))))
  (def ph (retrig-phasor hold_hz trig))
  (make-history prev)
  (make-history held)
  (def tick (lt ph (read-history prev)))
  (def reset (gt trig 0.5))
  (def should_sample (gt (+ (gswitch reset 1.0 0.0) (gswitch tick 1.0 0.0)) 0.5))
  (def sampled (gswitch should_sample x (read-history held)))
  (write-history prev ph)
  (write-history held sampled)
  (gswitch (lt a 0.0001) x sampled))

(defmacro md-bits (x amount)
  (def bits (+ 2 (* (- 1 (clip amount 0 1)) 10)))
  (def steps (pow 2 bits))
  (/ (floor (* x steps)) steps))

(defmacro md-reset-lp (x cutoff trig)
  (make-history y)
  (def c (exp (/ (* -2.0 pi (clip cutoff 20 18000)) samplerate)))
  (def yp (gswitch (gt trig 0.5) 0.0 (read-history y)))
  (def next (+ (* (- 1.0 c) x) (* c yp)))
  (write-history y next)
  next)

(defmacro md-reset-hp (x cutoff trig)
  (- x (md-reset-lp x cutoff trig)))

(defmacro md-out (x trig)
  (def am_phase (retrig-phasor (clip (mod amf) 0.1 2000) trig))
  (def am (* (- 1 (clip (mod amd) 0 1)) (+ 1 (* (clip (mod amd) 0 1) (sin (* am_phase twopi))))))
  (def amed (* x am))
  (def eq_peak (svf amed (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ amed (* eq_peak (/ (clip (mod eqg) -15 15) 15))))
  (def hp (md-reset-hp (md-reset-hp eqd (clip (mod fltf) 20 14000) trig) (clip (mod fltf) 20 14000) trig))
  (def lpf (clip (+ (mod fltf) (mod fltw)) 40 18000))
  (def lp (md-reset-lp (md-reset-lp hp lpf trig) lpf trig))
  (md-clip (md-srr lp (mod srr) trig) (mod dist)))

(param engine @default 1 @min 1 @max 5)

(param ptch @default -28 @min -60 @max 24 @mod true @mod-mode additive)
(param dec @default 650 @min 30 @max 3000 @unit ms @mod true @mod-mode additive)
(param ramp @default 32 @min -24 @max 96 @mod true @mod-mode additive)
(param rdec @default 36 @min 2 @max 500 @unit ms)
(param strt @default 22 @min 0 @max 48 @mod true @mod-mode additive)
(param nois @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)
(param harm @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)
(param clip @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)

(param hold @default 80 @min 0 @max 500 @unit ms @mod true @mod-mode additive)
(param tick @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param dirt @default 0.10 @min 0 @max 1 @mod true @mod-mode additive)

(param mod_amt @default 0.62 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 86 @min 10 @max 2000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 42 @min 1 @max 700 @unit ms)
(param mfb @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)

(param hard @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param hamr @default 2.3 @min 0.3 @max 8 @unit ms)
(param tens @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param damp @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)

(param humanize @default 0 @min 0 @max 1)
(param level @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 38 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 1100 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 24 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 17000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.72 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.08 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 5))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def base (clip (* pitch (semi (mod ptch))) 12 450))
(def amp (md-env trigger (* (clip (mod dec) 30 3000) (+ 1 (* jit 0.12)))))
(def p_env (md-env trigger (clip rdec 2 500)))
(def start_env (md-env trigger 6))
(def sigh (md-env trigger 300))
(def sweep_semi (+ (* (mod ramp) p_env (+ 0.7 (* 0.3 accent))) (* (mod strt) start_env) (* -1.5 sigh)))
(def f0 (clip (* base (semi sweep_semi)) 8 2600))

; TRX-BD
(def bd_ph (retrig-phasor f0 trigger))
(def bd_body_raw (sin (+ (* bd_ph twopi) (* (mod harm) 2.2 (sin (* bd_ph twopi 2))))))
(def bd_body (* bd_body_raw amp (+ 0.5 (* 0.5 accent))))
(def bd_noise (* (svf (noise) 900 2.0 1) (md-env trigger 8) (mod nois) accent))
(def trx_bd (md-clip (+ bd_body bd_noise) (mod clip)))

; TRX-B2
(def b2_amp (md-env-hold trigger (clip (mod hold) 0 500) (clip (mod dec) 30 3000)))
(def b2_freq (clip (* base (semi (* (mod ramp) (md-env trigger 20)))) 10 1800))
(def b2_body (* (sin (* (retrig-phasor b2_freq trigger) twopi)) b2_amp))
(def b2_tick (* (svf (noise) 5200 1.4 2) (md-env trigger 4) (mod tick)))
(def trx_b2 (md-clip (md-bits (+ b2_body (* b2_tick accent) (* (svf (noise) 1100 1.8 1) (md-env trigger 12) (mod nois))) (mod dirt)) (mod clip)))

; EFM-BD
(make-history fm_fb)
(def fm_m_env (md-env trigger (clip mdec 1 700)))
(def fm_fb_prev (gswitch (gt trigger 0.5) 0.0 (read-history fm_fb)))
(def fm_mod_ph (retrig-phasor (clip (mod mfrq) 10 2000) trigger))
(def fm_mod (sin (+ (* fm_mod_ph twopi) (* (mod mfb) 8.0 fm_fb_prev))))
(write-history fm_fb (clip fm_mod -1 1))
(def fm_car_ph (retrig-phasor f0 trigger))
(def efm_bd (* (sin (+ (* fm_car_ph twopi) (* fm_mod fm_m_env (mod mod_amt) 15))) amp))

; PI-BD
(def pi_energy (md-env trigger (clip (mod dec) 30 3000)))
(def tens_mul (+ 1 (* (mod tens) 0.42 accent pi_energy pi_energy)))
(def mallet (* (svf (noise) (clip (+ 2600 (* (mod hard) 9000)) 800 12000) 1.0 0) (md-env trigger (clip hamr 0.3 8))))
(def p1 (md-ping mallet (* base tens_mul) (* (mod dec) (+ 0.28 (* (- 1 (mod damp)) 0.95))) trigger))
(def p2 (md-ping mallet (* base 1.50 tens_mul) (* (mod dec) (+ 0.15 (* (- 1 (mod damp)) 0.55))) trigger))
(def p3 (md-ping mallet (* base 2.20 tens_mul) (* (mod dec) (+ 0.09 (* (- 1 (mod damp)) 0.38))) trigger))
(def pi_bd (md-clip (+ (* p1 0.95) (* p2 (mod hard) 0.32) (* p3 (mod hard) 0.20)) (mod clip)))

; GND-SN
(def gnd_f (clip (* base (semi (* (mod ramp) (md-env trigger (clip rdec 2 500))))) 8 1200))
(def gnd_sn (* (sin (* (retrig-phasor gnd_f trigger) twopi)) (md-env trigger (clip (mod dec) 30 3000))))

(def voice (selector eng trx_bd trx_b2 efm_bd pi_bd gnd_sn))
(def outv (md-out voice trigger))
(out (* outv (clip (mod level) 0 1) vel) 1 @name audio)
