;; Generated by research/hats/master/build_master.py.
;; Same physical-model surface as the source hats and Master Snare.
(defsynth-ui
  (eseq.effects.physical-model-surface/panel "VILLAIN HAT"
    (list
      '("HATS" ("hat_a" "Hat A" 0 :linear) ("hat_b" "Hat B" 0 :linear))
      '("MORPH" ("blend" "Blend" 2 :linear) ("exaggerate" "Exagg" 2 :linear))
      '("NOTE" ("release" "Release" 0 :log) ("keytrack" "Keytrk" 2 :linear))
      '("DECAY" ("decay" "Decay" 2 :log) ("pedal" "Pedal" 2 :linear)))
    (list
      (dict :title "Hats"
        :view (lambda () (v-stack :gap 0.4 :padding 0.3 (label "0 Hat81  1 Hat93  2 Hat94  3 Hat95" :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1)) (label "4 Hat96  5 OHat54  6 OHat78  7 OHat83" :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1)) (label "8 OHat85  9 OHat89  10 OHat100  11 OHat104" :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1))))
        :controls (lambda () '(("tune" "Tune" 2) ("metal" "Metal dB" 1) ("tick" "Tick" 2) ("sizzle" "Sizzle" 2) ("tone" "Tone" 2) ("level" "Level" 2)))
        :hint "Hat A and Hat B pick two of the 12; Blend morphs A to B.")
      (dict :title "Note"
        :view (lambda () (v-stack :gap 0.4 :padding 0.3 (label "C4 plays the hat as recorded; notes transpose it." :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1)) (label "Release: fade after the note ends. 2000 = Hold." :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1))))
        :controls (lambda () '(("release" "Release ms" 0) ("keytrack" "Keytrack" 2) ("tune" "Tune" 2) ("pedal" "Pedal" 2) ("decay" "Decay" 2) ("length" "Length" 2)))
        :hint "Hold ignores note length and rack choke. Choke across notes: mono track.")
      (dict :title "Record"
        :view (lambda () (v-stack :gap 0.4 :padding 0.3 (label "The record: bleed, rumble, hiss, codec edge, sampler." :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1)) (label "None of it follows the note." :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1))))
        :controls (lambda () '(("grit" "Grit" 2) ("codec" "Codec" 2) ("record" "Record" 2) ("drive" "Drive" 2) ("length" "Length" 2) ("level" "Level" 2)))
        :hint "Grit 0 and Codec 1 are the recorded hats.")
      (dict :title "Blend"
        :view (lambda () (v-stack :gap 0.4 :padding 0.3 (label "Exaggerate pushes away from the average hat:" :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1)) (label "decays, layer levels, bands, drive; never structure." :height 0.7 :font-size 10 :bg :transparent :v-align :center :color (rgba 0.16 0.06 0.11 1))))
        :controls (lambda () '(("exaggerate" "Exaggerate" 2) ("ring" "Ring" 2) ("motion" "Motion" 2) ("metal" "Metal dB" 1) ("tick" "Tick" 2) ("sizzle" "Sizzle" 2)))
        :hint "A part only one hat has fades in with its own timing."))))
