; Machinedrum-style percussion machines: TRX-CP, TRX-CB, TRX-CL, TRX-MA, EFM-CB, PI-ML, PI-MA.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro md-ping (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def y (- (+ exc (* 2 r (cos (* twopi (/ (clip freq 8 18000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro pulse (freq)
  (polyblep_pulse (phasor freq) 0.48 freq))
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def hz (exp (+ (log 300.0) (* (- 1 (clip amount 0 1)) (- (log 44100.0) (log 300.0))))))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (latch x tick))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 18000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 7)
(param ptch @default 0 @min -48 @max 48 @mod true @mod-mode additive)
(param dec @default 260 @min 20 @max 2500 @unit ms @mod true @mod-mode additive)

(param clpy @default 3 @min 2 @max 5 @mod true @mod-mode additive)
(param tone @default 0.52 @min 0 @max 1 @mod true @mod-mode additive)
(param hard @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param rich @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param rate @default 11 @min 6 @max 18 @unit ms @mod true @mod-mode additive)
(param room @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param rsiz @default 110 @min 40 @max 400 @unit ms)
(param rtun @default 1050 @min 300 @max 3500 @unit Hz @mod true @mod-mode additive)

(param enh @default 0.55 @min 0 @max 1 @mod true @mod-mode additive)
(param damp @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param bump @default 12 @min -24 @max 48 @mod true @mod-mode additive)
(param dual @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param clic @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)

(param rattl @default 0.32 @min 0 @max 1 @mod true @mod-mode additive)
(param glen @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param grns @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param size @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param tens @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)
(param rev @default 0 @min 0 @max 1 @mod true @mod-mode additive)

(param mod_amt @default 0.52 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 540 @min 20 @max 4000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 75 @min 1 @max 800 @unit ms)
(param fb @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.58 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 55 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 1400 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 80 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 16000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.72 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.08 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 7))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def base (clip (* pitch (semi (+ (mod ptch) (* jit 2)))) 60 4000))
(def n (noise))

; TRX-CP clap: delayed noise bursts plus a separate room tail.
(def rate_samp (* (clip (mod rate) 6 18) 0.001 samplerate))
(def t1 trigger)
(def t2 (* (delay trigger rate_samp) (gte (mod clpy) 2.5)))
(def t3 (* (delay trigger (* rate_samp 2)) (gte (mod clpy) 3.5)))
(def t4 (* (delay trigger (* rate_samp 3)) (gte (mod clpy) 4.5)))
(def clap_bursts (+ (md-env t1 10) (md-env t2 10) (md-env t3 10) (md-env t4 10) (* 0.65 (md-env (delay trigger (* rate_samp 4)) 22))))
(def clap_filter (svf n (clip (mod rtun) 300 3500) (+ 0.7 (* (mod tone) 4.5)) 1))
(def clap_room (* (svf n (clip (mod rtun) 300 3500) 1.1 1) (md-env trigger (clip rsiz 40 400)) (mod room)))
(def trx_cp (md-clip (+ (* clap_filter clap_bursts (+ 0.7 (* (mod rich) 0.8))) clap_room) (mod hard)))

; TRX-CB cowbell.
(def cb_env (md-env trigger (clip (mod dec) 20 900)))
(def cb_bump (semi (* (mod bump) (md-env trigger 18))))
(def cb_src (+ (* 0.55 (pulse (* 540 cb_bump (semi (mod ptch))))) (* 0.45 (pulse (* 800 cb_bump (semi (mod ptch)))))))
(def trx_cb (md-clip (+ (* (svf cb_src 2640 (+ 1 (* (mod enh) 6)) 1) cb_env) (* (svf cb_src 900 1.1 1) cb_env (mod enh))) (mod hard)))

; TRX-CL claves.
(def cl_exc (+ (* (md-env trigger 2) 1.0) (* (md-env (delay trigger (* 0.008 samplerate)) 2) (mod dual))))
(def trx_cl (md-clip (+ (md-ping cl_exc (* base 4.2) (* (mod dec) (+ 0.10 (* (- 1 (mod damp)) 0.38)))) (* (svf n 4500 0.8 2) (md-env trigger 3) (mod clic))) (mod hard)))

; TRX-MA maraca/tambourine.
(def ma_attack (md-env trigger (+ 1 (* (- 1 (mod hard)) 18))))
(def ma_decay (md-env trigger (clip (mod dec) 20 1600)))
(def ma_env (+ (* ma_decay (- 1 (mod rev))) (* (- 1 ma_decay) (mod rev) ma_attack)))
(def grain (gt (noise) (- 1 (* (mod rattl) ma_decay 0.9))))
(def trx_ma (+ (* (svf n 5200 0.7 2) ma_env) (* (svf n 9000 1.4 1) (gswitch grain ma_decay 0.0) (mod rattl))))

; EFM-CB.
(make-history fmfb)
(def fm_env (md-env trigger (clip mdec 1 800)))
(def fm_m (sin (+ (* (retrig-phasor (clip (mod mfrq) 20 4000) trigger) twopi) (* (read-history fmfb) (mod fb) 7.0))))
(write-history fmfb (clip fm_m -1 1))
(def efm_cb (* (sin (+ (* (retrig-phasor (* base 1.7) trigger) twopi) (* fm_m fm_env (mod mod_amt) 14))) (md-env trigger (clip (mod dec) 20 1200))))

; PI-ML metallic bank.
(def energy (md-env trigger (clip (mod dec) 20 2500)))
(def tens_mul (+ 1 (* (mod tens) 0.35 accent energy energy)))
(def exc (* (svf n (+ 1600 (* (mod hard) 9000)) 0.8 0) (md-env trigger (+ 1 (* (- 1 (mod hard)) 7)))))
(def ml_f (clip (* base (+ 0.6 (* (- 1 (mod size)) 1.4))) 120 3000))
(def pi_ml (+ (md-ping exc (* ml_f 1.00 tens_mul) (* (mod dec) 0.42))
              (md-ping exc (* ml_f 4.08 tens_mul) (* (mod dec) 0.28))
              (md-ping exc (* ml_f 6.67 tens_mul) (* (mod dec) 0.22))
              (md-ping exc (* ml_f 9.00 tens_mul) (* (mod dec) 0.18))))

; PI-MA PhISEM-style shaker.
(make-history shake_energy_h)
(make-history sound_level_h)
(def prev_energy (read-history shake_energy_h))
(def shake_decay (exp (/ -6.907755 (max 1.0 (* (mod dec) 0.001 samplerate)))))
(def shake_energy (clip (+ (* prev_energy shake_decay) (* trigger accent)) 0 1))
(def collision (gt (noise) (- 1 (* (+ 0.02 (* (mod grns) 0.55)) shake_energy))))
(def sound_decay (exp (/ -6.907755 (max 1.0 (* (+ 8 (* (mod glen) 100)) 0.001 samplerate)))))
(def sound_level (+ (* (read-history sound_level_h) sound_decay) (gswitch collision (* shake_energy (/ (log (+ 2 (* (mod grns) 200))) (+ 4 (* (mod grns) 200)))) 0.0)))
(write-history shake_energy_h shake_energy)
(write-history sound_level_h sound_level)
(def shaker_res (clip (+ 2000 (* (mod size) 3500)) 2000 5500))
(def pi_ma (+ (md-ping (* sound_level n) shaker_res (+ 20 (* (mod hard) 180))) (* (md-ping (* sound_level n) 5600 (+ 10 (* (mod hard) 80))) (mod hard) 0.4)))

(def voice (selector eng trx_cp trx_cb trx_cl trx_ma efm_cb pi_ml pi_ma))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
