;; generated by the patch editor — edit via the patcher or eject to code

(use-defmacro pitch-transpose)

(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(param attack @group amp @env amp-env @role attack @default 5 @min 0 @max 1000 @unit ms)
(param xyz @min 0 @max 1 @mod true @mod-mode additive)
(param decay @group amp @env amp-env @role decay @default 120 @min 1 @max 2000 @unit ms)
(param gain @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)
(param release @group amp @env amp-env @role release @default 180 @min 1 @max 5000 @unit ms)
(param sustain @group amp @env amp-env @role sustain @default 0.8 @min 0 @max 1)

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))

(def env (adsr gate trigger attack decay sustain release))
(def tensor-2 (tensor @shape [2 2] @data [0 4 9 13]))
(def tensor-3 (tensor @shape [2 2] @data [1 3 2 1]))
(def mul-2 (* tensor-3 (mod xyz)))
(def matmul-2 (matmul tensor-2 mul-2))
(def phasor-2 (phasor mul-2))
(def pitch-transpose-2 (pitch-transpose pitch matmul-2))
(def phasor-3 (phasor pitch-transpose-2))
(def triangle-2 (triangle phasor-3 phasor-2))
(def mul-3 (* triangle-2 twopi))
(def cos-2 (cos mul-3))
(def sum-2 (sum cos-2))
(def mul (* sum-2 0.25))
(def mul-0 (* mul env velocity (mod gain)))

(out mul-0 1 @name audio)
