(param am @min 0.1 @max 320.0 @default 0.1)
(def phasor1 (phasor am))
(def mul3 (* phasor1 twopi))
(def cos1 (cos mul3))
(def input_l (in 1 @name Left))
(def mul1 (* input_l cos1))
(def input_r (in 2 @name Right))
(def mul2 (* input_r cos1))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def processed_l input_l)
(def processed_r input_r)
(out (mix input_l mul1 mix-amt) 1 @name Left)
(out (mix input_r mul2 mix-amt) 2 @name Right)