; Machinedrum-style cymbal machines: TRX-CY, EFM-CY, PI-RC, PI-CC.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro md-ping-n (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  ; input normalized by resonator bandwidth so ring amplitude tracks the
  ; excitation instead of blowing up ~1/(1-r) at long decays
  (def g (* 2.2 (sqrt (max 0.00001 (- 1.0 r)))))
  (def y (- (+ (* exc g) (* 2 r (cos (* twopi (/ (clip freq 8 19000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def a (clip amount 0 1))
  (def hz (* samplerate (pow (/ 300.0 samplerate) a)))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (def sampled (latch x tick))
  (gswitch (lt a 0.0001) x sampled))
(defmacro metal6 (tune spread jit)
  (def t (semi tune))
  (def s (clip spread 0 2))
  (+ (* 0.18 (polyblep_pulse (phasor (* 205.3 t (+ 1 (* s -0.18)) (+ 1 (* jit 0.015)))) 0.48 (* 205.3 t)))
     (* 0.17 (polyblep_pulse (phasor (* 304.4 t (+ 1 (* s -0.08)))) 0.48 (* 304.4 t)))
     (* 0.16 (polyblep_pulse (phasor (* 369.6 t (+ 1 (* s 0.04)))) 0.48 (* 369.6 t)))
     (* 0.16 (polyblep_pulse (phasor (* 522.7 t (+ 1 (* s 0.16)))) 0.48 (* 522.7 t)))
     (* 0.15 (polyblep_pulse (phasor (* 540.0 t (+ 1 (* s 0.24)))) 0.48 (* 540.0 t)))
     (* 0.13 (polyblep_pulse (phasor (* 800.0 t (+ 1 (* s 0.38)))) 0.48 (* 800.0 t)))))
(defmacro swing-vca (x env)
  (tanh (* 2.4 (min x (+ env (* 0.10 (pow (abs x) 3.5)))))))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 19000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 4)
(param rich @default 0.38 @min 0 @max 1 @mod true @mod-mode additive)
(param dec @default 720 @min 60 @max 4000 @unit ms @mod true @mod-mode additive)
(param top @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param ttun @default 7800 @min 3000 @max 12000 @unit Hz @mod true @mod-mode additive)
(param size @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param peak @default 1.8 @min 0.5 @max 8 @mod true @mod-mode additive)

(param ptch @default 0 @min -36 @max 48 @mod true @mod-mode additive)
(param mod_amt @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 4200 @min 100 @max 12000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 120 @min 1 @max 1200 @unit ms)
(param fb @default 0.62 @min 0 @max 1 @mod true @mod-mode additive)
(param hpf @default 1400 @min 500 @max 15000 @unit Hz @mod true @mod-mode additive)

(param hard @default 0.55 @min 0 @max 1 @mod true @mod-mode additive)
(param clsn @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param ring @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)
(param grab @default 0.0 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 30 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 6200 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 1200 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 16500 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.72 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.06 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def jit (* (latch-trig (noise) trigger) humanize))
(def cluster (metal6 (* -12 (mod size)) (+ 0.35 (* (mod rich) 1.2)) jit))
(def cy_env (md-env trigger (clip (mod dec) 60 4000)))
(def top_env (md-env trigger (clip (* (mod dec) 0.42) 30 1200)))
(def b1 (swing-vca (* (svf cluster 3440 2.0 1) cy_env) cy_env))
(def b2 (swing-vca (* (svf cluster (clip (mod ttun) 3000 12000) (clip (mod peak) 0.5 8) 1) top_env) top_env))
(def tilt (- (+ b1 (* b2 (mod top) 1.6)) (* 0.72 (delay (+ b1 b2) 1))))
(def trx_cy (svf tilt 10500 0.7 2))

(make-history fmfb)
(def fm_env (md-env trigger (clip mdec 1 1200)))
(def fm_m (sin (+ (* (retrig-phasor (clip (mod mfrq) 100 12000) trigger) twopi) (* (read-history fmfb) (mod fb) (mod fb) 5.0))))
(write-history fmfb (clip fm_m -1 1))
; squared index taper keeps the low half of mod_amt usable instead of
; saturating into noise by 0.35
(def efm_idx (* (mod mod_amt) (mod mod_amt) 14))
(def efm_car (sin (+ (* (retrig-phasor (clip (* pitch (semi (mod ptch)) 6) 60 15000) trigger) twopi) (* fm_m fm_env efm_idx))))
(def efm_cy (* 0.28 (svf (* efm_car cy_env) (clip (mod hpf) 500 15000) 0.7 2)))

(def energy (md-env trigger (clip (mod dec) 60 4000)))
; sparse random re-strikes (~a few hundred per second max), not a noise bed
(def collide (gt (noise) (- 1 (* (mod clsn) energy 0.012))))
(def wn (noise))
(make-history wn1)
(def hn (* 0.7 (- wn (read-history wn1))))
(write-history wn1 wn)
; hard blends toward differentiated (bright) noise and a shorter burst
(def strike_n (+ (* wn (- 1 (* (mod hard) 0.8))) (* hn (mod hard) 1.8)))
(def strike (* strike_n (md-env trigger (+ 0.6 (* (- 1 (mod hard)) 9))) (+ 0.5 (* (mod hard) 1.6))))
(def exc (+ (* strike 1.6) (* (noise) (gswitch collide energy 0.0) 1.4) (* wn energy 0.10)))
(def damp (* (- 1 (* (mod grab) 0.86)) (+ 0.35 (* (mod ring) 1.2))))
(def pf (clip (* pitch (semi (mod ptch)) (+ 8 (* (mod size) -3.5))) 400 3600))
; dense bank of close-spaced (detuned-pair) inharmonic modes: the pairs beat
; against each other, which is the metallic swirl a sparse bank can't make;
; flat-ish weights keep any single mode from reading as a wine glass
(def pi_body (+ (* 0.13 (md-ping-n exc (* pf 1.00) (* (mod dec) damp 1.30)))
                (* 0.11 (md-ping-n exc (* pf 1.09) (* (mod dec) damp 1.15)))
                (* 0.14 (md-ping-n exc (* pf 1.48) (* (mod dec) damp 1.00)))
                (* 0.12 (md-ping-n exc (* pf 1.60) (* (mod dec) damp 0.90)))
                (* 0.16 (md-ping-n exc (* pf 2.04) (* (mod dec) damp 0.80)))
                (* 0.14 (md-ping-n exc (* pf 2.19) (* (mod dec) damp 0.74)))
                (* 0.15 (md-ping-n exc (* pf 2.73) (* (mod dec) damp 0.66)))
                (* 0.13 (md-ping-n exc (* pf 2.95) (* (mod dec) damp 0.60)))
                (* 0.13 (md-ping-n exc (* pf 3.42) (* (mod dec) damp 0.54)))
                (* 0.11 (md-ping-n exc (* pf 3.71) (* (mod dec) damp 0.49)))
                (* 0.11 (md-ping-n exc (* pf 4.36) (* (mod dec) damp 0.44)))
                (* 0.09 (md-ping-n exc (* pf 4.71) (* (mod dec) damp 0.40)))
                (* 0.09 (md-ping-n exc (* pf 5.52) (* (mod dec) damp 0.35)))
                (* 0.08 (md-ping-n exc (* pf 5.98) (* (mod dec) damp 0.31)))
                (* 0.07 (md-ping-n exc (* pf 7.11) (* (mod dec) damp 0.27)))
                (* 0.06 (md-ping-n exc (* pf 7.68) (* (mod dec) damp 0.24)))))
; wash: mostly tanh intermodulation of the dense bank (tonal shimmer — the
; pairs intermodulate into yet more beating partials); only a little
; noise ring-mod on top, or it reads as sand
(def ringm (* pi_body (svf (noise) 6300 2.5 1) 3.0))
(def wash (svf (+ (* 0.30 ringm) (* 0.70 (tanh (* pi_body 5.5)))) 5200 0.7 2))
(def pi_rc (* 0.80 (+ pi_body (* wash (+ 0.5 (* (mod hard) 0.6))))))
; crash: wash-dominated with the body buried, a broadband explosion on the
; attack, and a wide sustained sizzle bed that blooms with the decay env
(def cc_burst (* (noise) (md-env trigger (+ 12 (* (mod hard) 28))) 0.55))
(def cc_sizzle (* (svf (noise) 7400 0.8 1) energy 0.40))
(def pi_cc (* 0.60 (+ (* 0.42 pi_body) (* wash (+ 0.9 (* (mod hard) 0.5))) cc_burst cc_sizzle)))

(def voice (selector eng trx_cy efm_cy pi_rc pi_cc))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
