(defmacro op (input input2) (def phasor2 (phasor 0.3)) (def phasor1 (phasor input)) (def add1 (+ input2 4.0)) (def triangle2 (triangle phasor2)) (def triangle1 (triangle phasor1 triangle2)) (def mul2 (* triangle1 twopi)) (def mul1 (* mul2 add1)) (def cos1 (cos mul1)) cos1)
(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(param myparam @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def modulated1 (mod myparam))
(def add1 (+ modulated1 4.0))
(def op1 (op pitch add1))
(param attack @default 5.0 @min 0.0 @max 1000.0 @unit ms)
(param decay @default 120.0 @min 1.0 @max 2000.0 @unit ms)
(param sustain @default 0.8 @min 0.0 @max 1.0)
(param release @default 180.0 @min 1.0 @max 5000.0 @unit ms)
(param gain @default 0.5 @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def env (adsr gate trigger attack decay sustain release))
(out (* op1 env velocity (mod gain)) 1 @name audio)