;; PM Slenthem / identified bar & tube resonator.
;; Generated by tools/pm-gamelan/build.py; edit engine.lisp.in, then regenerate.
;; Reference coefficients only: no PCM, recorded phase, or spectral frames.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(param hardness @group mallet @default 0.5 @min 0 @max 1 @mod true @mod-mode additive)
(param contact @group mallet @default 1 @min 0.3 @max 3 @mod true @mod-mode additive)
(param spread @group mallet @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dynamics @group mallet @default 1 @min 0 @max 1)
(param decay @group body @default 1 @min 0.15 @max 4 @mod true @mod-mode additive)
(param loss @group body @default 1 @min 0.25 @max 4 @mod true @mod-mode additive)
(param inharmonicity @group body @default 1 @min 0 @max 1.8 @mod true @mod-mode additive)
(param bloom @group body @default 1 @min 0 @max 2 @mod true @mod-mode additive)
(param color @group body @default 0 @min -1 @max 1 @mod true @mod-mode additive)
(param register @group voicing @default 0 @min -24 @max 24 @unit st @mod true @mod-mode additive)
(param amount @group tuning @default 1 @min 0 @max 1 @mod true @mod-mode additive)
(param tune @group tuning @default 0 @min -100 @max 100 @unit cents @mod true @mod-mode additive)
(param touch @group damper @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param release_s @group damper @default 0.4 @min 0.02 @max 12 @unit s @mod true @mod-mode additive)
(param lift @group damper @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param width @group output @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param drive @group output @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param tone_hz @group output @default 20000 @min 1000 @max 20000 @unit Hz @mod true @mod-mode additive)
(param gain @group output @default 1 @min 0 @max 4 @mod true @mod-mode additive)

;; BEGIN GENERATED CALIBRATION
;; Latent Sonorities / memeshift, CC BY-NC 4.0; see ATTRIBUTION.md.
;; Analysis SHA256: 90727845955aae4ff173b9207b2a86f95b1286b39548e9d7bfe229c751033181
(def ratio_table (tensor @shape [7 16] @data [
  1 2.65470932 4.97386475 3.94371241 1.87769372 1.998512 3.00007497 11.8760469 7.64469844 10.0976862 14.0372116 15.3903129 1 1 1 1
  1 2.71609596 11.3549308 5.13241354 2.00062968 2.99888973 4.27446413 13.580739 12.0468183 10.5451277 14.0372116 15.3903129 1 1 1 1
  1 2.67394142 7.95544535 5.00692009 1.48846889 5.77679154 4.11819952 13.580739 11.7342316 10.5451277 12.748752 15.3903129 1 1 1 1
  1 2.12112105 5.11048142 4.33290934 0.976308096 8.55469334 2.75628881 13.580739 7.97611062 10.5451277 12.748752 15.3903129 1 1 1 1
  1 2.00057193 5.20422412 4.50094304 2.42333434 11.3325952 3.0035554 13.580739 8.28014178 10.5451277 12.748752 15.3903129 1 1 1 1
  1 2.00057193 5.19215917 4.44492724 3.87036058 11.7157644 2.70795933 13.580739 8.2996205 10.5451277 12.748752 15.3903129 1 1 1 1
  1 2.00057193 4.64919772 3.00047073 5.31738682 8.3541013 2.80432897 13.580739 9.17552071 10.5451277 12.748752 15.3903129 1 1 1 1
]))
(def rate_table (tensor @shape [7 16] @data [
  0.633854764 1.41400837 1.68332878 0.628021271 1.43815856 0.626602042 0.708571964 1.16137696 0.775082866 1.24598262 3.41769364 1.27908666 1 1 1 1
  0.438420766 0.54783116 0.875193587 0.792324936 0.626199579 0.467181678 0.514605384 0.648615554 0.794212006 0.56444986 3.41769364 1.27908666 1 1 1 1
  1.25231984 0.406102966 1.32159362 0.969504753 1.09662574 0.824781309 0.347046946 0.648615554 1.39135045 0.56444986 1.49972728 1.27908666 1 1 1 1
  1.1417846 0.40779587 1.68396731 0.357578405 1.5670519 1.18238094 0.658402058 0.648615554 3.1263977 0.56444986 1.49972728 1.27908666 1 1 1 1
  0.422341382 0.80225699 6.88581672 0.448029046 4.91282925 1.53998057 0.715384038 0.648615554 2.11600607 0.56444986 1.49972728 1.27908666 1 1 1 1
  0.236715764 0.80225699 1.41156755 0.334074271 8.25860661 0.96280091 0.615012116 0.648615554 0.538517225 0.56444986 1.49972728 1.27908666 1 1 1 1
  0.468048615 0.80225699 0.711547429 1.40354675 11.604384 1.07551536 1.2031745 0.648615554 0.724031206 0.56444986 1.49972728 1.27908666 1 1 1 1
]))
(def rise_table (tensor @shape [7 16] @data [
  0.046656039 0.0865158612 0.00605586332 0.002256377 0.0223236176 0.00101056445 0.166431094 0.00167025459 0.00103070173 0.00189976372 0.013107286 0.00184468164 0.001 0.001 0.001 0.001
  0.0684785434 0.030446892 0.00156813246 0.00117823737 0.001002919 0.00140040231 0.0752898195 0.001008359 0.00101315247 0.00100935902 0.013107286 0.00184468164 0.001 0.001 0.001 0.001
  0.176611262 0.00100004563 0.00121773107 0.00105776732 0.00114523849 0.00183541938 0.038938289 0.001008359 0.00157346155 0.00100935902 0.00138668238 0.00184468164 0.001 0.001 0.001 0.001
  0.0667087789 0.00666033571 0.00197812756 0.120670717 0.00128755798 0.00227043646 0.00148387194 0.001008359 0.0432562742 0.00100935902 0.00138668238 0.00184468164 0.001 0.001 0.001 0.001
  0.0910869739 0.0274419397 0.123683281 0.00168383383 0.267525039 0.00270545354 0.0581064103 0.001008359 0.00100133983 0.00100935902 0.00138668238 0.00184468164 0.001 0.001 0.001 0.001
  0.0673532912 0.0274419397 0.00101806475 0.00100701922 0.533762519 0.00100003165 0.0341155472 0.001008359 0.00100018955 0.00100935902 0.00138668238 0.00184468164 0.001 0.001 0.001 0.001
  0.038465896 0.0274419397 0.00138842705 0.177626777 0.8 0.00128532076 0.00137430751 0.001008359 0.00100000232 0.00100935902 0.00138668238 0.00184468164 0.001 0.001 0.001 0.001
]))
(def direct_table (tensor @shape [7 16] @data [
  0.310890707 0.019045315 0.999894139 0.568062663 0.35149693 0.999974847 0.22086175 0.999767366 0.454689754 0.7517573 7.49675947e-08 0.676344781 1 1 1 1
  0.0466480689 1.08964615e-10 0.943827585 0.715214691 0.999987887 0.858632163 0.649597089 0.999484984 0.999974743 0.998728523 7.49675947e-08 0.676344781 1 1 1 1
  0.319823 0.999989878 2.10114679e-05 2.69017093e-07 0.833457286 0.905752377 1.11022302e-16 0.999484984 0.989268012 0.998728523 0.752994197 0.676344781 1 1 1 1
  2.48750248e-08 0.259262199 0.585667877 1.11022302e-16 0.666926684 0.952872591 0.752202991 0.999484984 1.11022302e-16 0.998728523 0.752994197 0.676344781 1 1 1 1
  0.842306949 6.55154325e-06 0.217476863 0.999999959 0.505898951 0.999992805 3.57047725e-13 0.999484984 0.999354726 0.998728523 0.752994197 0.676344781 1 1 1 1
  0.485438496 6.55154325e-06 0.99996354 0.99540111 0.344871219 0.999975964 6.88338275e-15 0.999484984 0.999955781 0.998728523 0.752994197 0.676344781 1 1 1 1
  0.19575982 6.55154325e-06 0.975289143 1.11022302e-16 0.183843486 0.887974977 0.917586013 0.999484984 0.0206910899 0.998728523 0.752994197 0.676344781 1 1 1 1
]))
(def amplitude_table (tensor @shape [21 16] @data [
  0.0166360052 3.68912018e-05 0.000121395105 0.000199725187 5.94776076e-05 2.74219574e-05 2.00744776e-05 9.97365177e-06 2.97398908e-06 2.54979271e-05 0 0 0 0 0 0
  0.04457908 0.000331518297 0.000362364981 4.09826646e-05 8.38694481e-05 0.000124341475 8.68630892e-05 8.52759301e-05 1.83124284e-05 9.32730503e-05 0 0 0 0 0 0
  0.0967245021 0.00284633746 0.00228343371 0.00131496339 0.000973007868 0.000300688382 0.00025227018 0.000245844305 0.000173219621 9.30157048e-05 0 0 0 0 0 0
  0.0125742613 1.57451745e-05 3.3092809e-06 6.63643192e-06 1.24311638e-05 2.98231305e-06 2.19546476e-05 2.93883691e-06 1.34837945e-06 1.33442705e-06 7.99220779e-06 2.5418358e-06 0 0 0 0
  0.0626362556 0.000195836725 3.66197658e-05 0.000308390132 0.000125985634 5.17092437e-05 0.000409643709 6.36119533e-05 5.76846501e-05 2.26120367e-05 0.000127179301 3.86806958e-05 0 0 0 0
  0.100626676 0.000667911547 0.00021195022 0.000533657387 0.000330397231 0.000168493943 0.000173922138 0.000222895967 0.00016172479 3.36635731e-05 0.000421236204 0.000114421277 0 0 0 0
  0.0347713565 4.01895524e-05 6.52631846e-05 0.000273186859 0 0 2.61711626e-05 0 4.79031596e-06 0 1.1389216e-05 0 0 0 0 0
  0.0951516955 0.000198779817 1.50753409e-05 0.00107292467 0 0 0.00025733533 0 2.79498211e-05 0 8.49376332e-05 0 0 0 0 0
  0.186755632 0.00157320089 0.00182212314 0.00842428199 0 0 0.00157690774 0 0.000260222436 0 0.000222449356 0 0 0 0 0
  0.0440437046 6.32625558e-06 0.000183955369 2.17813662e-05 0.00514527834 0 2.62097978e-05 0 0.000137071483 0 0 0 0 0 0 0
  0.10694524 7.80045393e-05 0.000145402796 0.000110215789 0.0127309988 0 0.000160165998 0 0.000335442684 0 0 0 0 0 0 0
  0.167480909 0.000247682455 0.000727711017 0.000213042839 0.0239510353 0 0.000696702838 0 0.00157598607 0 0 0 0 0 0 0
  0.00607987894 3.19841799e-05 0.000221833302 1.61594709e-06 0 2.90501266e-06 4.67990683e-05 0 2.03622741e-06 0 0 0 0 0 0 0
  0.0246327767 0.000293318885 0.000605098268 4.82247968e-05 0 6.14766343e-05 0.000420273672 0 0.00015112798 0 0 0 0 0 0 0
  0.032899418 0.000730113479 0.00240119308 4.95710922e-05 0 0.000102630695 0.000717356316 0 4.33191956e-05 0 0 0 0 0 0 0
  0.00356628362 0 1.0849378e-05 1.99226234e-06 0 1.91717355e-06 1.12647669e-05 0 2.08128934e-06 0 0 0 0 0 0 0
  0.0314173207 0 2.25813251e-05 6.09050702e-05 0 1.37946789e-05 9.27863266e-05 0 7.06488538e-06 0 0 0 0 0 0 0
  0.0490290674 0 0.000204752816 5.76758475e-05 0 0.00011083604 0.000195485215 0 7.32023267e-06 0 0 0 0 0 0 0
  0.0162239167 0 9.61387721e-05 9.97525581e-05 0.00183831753 2.96080035e-06 2.48297886e-05 0 7.31460021e-06 0 0 0 0 0 0 0
  0.0285550567 0 0.000245909899 0.000508290612 0.00316354051 1.41178717e-05 0.000142558552 0 9.58106802e-06 0 0 0 0 0 0 0
  0.0617558991 0 0.000209018919 0.00253386066 0.0420031403 0.000171752978 0.00245736452 0 4.7798216e-05 0 0 0 0 0 0 0
]))
(def tuning_table (tensor @shape [7] @data [
  16.5621714 -20.1849388 -6.05657155 -36.9710153 10.7119536 24.7551982 8.72830484
]))
(def mode_pan_table (tensor @shape [16] @data [
  0 0.472843206 -0.697319729 0.555520526 -0.121927366 -0.375709636 0.676000552 -0.621213901 0.240127043 0.267089484 -0.63401399 0.667914885 -0.350985309 -0.150303598 0.5726437 -0.694195687
]))
;; END GENERATED CALIBRATION

(defmacro gamelan-smooth (target ms)
  (make-history previous)
  (make-history ready)
  (def pole (exp (/ -1 (* 0.001 ms samplerate))))
  (def value (gswitch (read-history ready) (mix target (read-history previous) pole) target))
  (write-history previous value)
  (write-history ready 1)
  value)

(defmacro gamelan-pole (signal pole)
  (make-history previous)
  (def value (mix signal (read-history previous) pole))
  (write-history previous value)
  value)

;; Coefficients latch on every strike as well as each periodic control tick.
;; A periodic-only hop would miss the beginning of an off-grid force pulse.
;; These are frame-rate latches, so note events can update them immediately.
(def control_tick (eq (accum 1 0 0 16) 0))
(defmacro gamelan-hold (value tick) (latch value tick))

(defmacro gamelan-row (note)
  (+ (clip (/ (- note 50) 2) 0 1) (clip (/ (- note 52) 1) 0 1) (clip (/ (- note 53) 3) 0 1) (clip (/ (- note 56) 1) 0 1) (clip (/ (- note 57) 1) 0 1) (clip (/ (- note 58) 2) 0 1)))

(make-history last_gate)
(def held (gt gate 0.5))
(def onset (max (gt trigger 0.5) (* held (lte (read-history last_gate) 0.5))))
(def update_tick (max control_tick onset))
(write-history last_gate held)
(def hit_velocity (latch (clip velocity 0 1) onset))
(def strength (mix 0.6 hit_velocity (clip dynamics 0 1)))
(def velocity_row (gamelan-hold (+ (clip (/ (- strength 0.6) 0.2) 0 1) (clip (/ (- strength 0.8) 0.2) 0 1)) update_tick))
(def velocity_gain (/ hit_velocity (max 0.6 strength)))
(def key_note (+ 69 (* 12 (/ (log (/ (clip pitch 32.703196 8372.018) 440)) (log 2)))))
(def row (gamelan-hold (gamelan-row (+ key_note (gamelan-smooth (clip (mod register) -24 24) 8))) update_tick))
(def row_low (floor row))
(def row_high (min 6 (+ row_low 1)))
(def row_mix (- row row_low))
(def base_hz (* (clip pitch 32.703196 8372.018)
  (pow 2 (/ (+ (clip (mod tune) -100 100)
    (* (clip (mod amount) 0 1) (peek tuning_table (gamelan-row key_note)))) 1200))))
(def ratio (peek-row ratio_table row))
(def harmonic_ratio (max 1 (floor (+ ratio 0.5))))
(def live_ratio (max 0.1 (mix harmonic_ratio ratio (gamelan-hold (gamelan-smooth (clip (mod inharmonicity) 0 1.8) 8) update_tick))))
(def frequencies (* (gamelan-hold base_hz update_tick) live_ratio))
(def band (clip (/ (- (* samplerate 0.47) frequencies) (* samplerate 0.07)) 0 1))
(def amplitude (mix (peek-row amplitude_table (+ (* row_low 3) velocity_row))
  (peek-row amplitude_table (+ (* row_high 3) velocity_row)) row_mix))

;; A normalized two-pole contact force; measured modal residues are deconvolved
;; by its reference response. Hardness/contact alter the force, not the decay.
(def reference_pole (exp (/ -1 (* 0.0003 samplerate))))
(def contact_tau (* 0.0003 (clip (mod contact) 0.3 3)
  (pow 2 (* 3 (- 0.5 (clip (mod hardness) 0 1))))))
(def contact_pole (exp (/ -1 (* contact_tau samplerate))))
(def force1 (gamelan-pole (* onset velocity_gain) contact_pole))
(def force (gamelan-pole force1 contact_pole))
(def omega (* twopi (/ (min frequencies (* 0.48 samplerate)) samplerate)))
(def inverse_contact (/ (+ (* (- 1 reference_pole) (- 1 reference_pole))
  (* 2 reference_pole (- 1 (cos omega)))) (* (- 1 reference_pole) (- 1 reference_pole))))
;; A finite mallet footprint suppresses shorter spatial wavelengths. Its width
;; is a timbral control: spatial mode shapes cannot be recovered from one mic.
(def footprint (exp (* -0.8 (max 0 (- ratio 1)) (gamelan-hold (clip (mod spread) 0 1) update_tick))))
(def color_weight (pow ratio (gamelan-hold (clip (mod color) -1 1) update_tick)))
;; The force bandwidth and spectral color redistribute a finite excitation
;; budget. Squared acoustic residues are an energy proxy (modal masses are
;; unknown), not a claim to measured impact joules. Soft contacts may dissipate
;; energy; hard contacts cannot manufacture unbounded extra modal energy.
(def live_contact (/ (* (- 1 contact_pole) (- 1 contact_pole))
  (+ (* (- 1 contact_pole) (- 1 contact_pole)) (* 2 contact_pole (- 1 (cos omega))))))
(def reference_residue (* amplitude band))
(def colored_residue (* reference_residue inverse_contact live_contact footprint color_weight))
(def reference_energy (sum (* reference_residue reference_residue)))
(def colored_energy (sum (* colored_residue colored_residue)))
(def energy_scale (min 1 (sqrt (/ reference_energy (max 0.00000000000000000001 colored_energy)))))
(def weight (gamelan-hold (* amplitude inverse_contact band footprint color_weight energy_scale) update_tick))
(def decay_scale (gamelan-hold (gamelan-smooth (clip (mod decay) 0.15 4) 8) update_tick))
(def loss_scale (pow ratio (* 0.5 (- (gamelan-hold (gamelan-smooth (clip (mod loss) 0.25 4) 8) update_tick) 1))))
(def hand_loss (* 100 (pow (gamelan-smooth (clip (mod touch) 0 1) 4) 2)))
(def release_loss (* (- 1 held) (pow (- 1 (clip (mod lift) 0 1)) 2)
  (/ 6.907755 (clip (mod release_s) 0.02 12))))
(def rate (+ (/ (* (peek-row rate_table row) loss_scale) decay_scale)
  (* (gamelan-hold (+ hand_loss release_loss) update_tick) (sqrt ratio))))
(def rise (max 0.00005 (* (peek-row rise_table row)
  (gamelan-hold (gamelan-smooth (clip (mod bloom) 0 2) 8) update_tick))))
(def direct (gamelan-hold (peek-row direct_table row) update_tick))

;; A passive modal reduction followed by a radiation pole at each mode.
;; Its impulse envelope is exp(-rate*t) * (1 - (1-direct)*exp(-t/rise)).
;; This is a causal recurrence, not a recorded or scheduled amplitude envelope.
;; Both complex rotations remain contractive during pitch/damping automation.
(defmacro gamelan-resonator (omega rate rise direct weight force tick)
  (make-tensor-history bar_r @shape [16])
  (make-tensor-history bar_i @shape [16])
  (make-tensor-history radiation_r @shape [16])
  (make-tensor-history radiation_i @shape [16])
  (def x (read-tensor-history bar_r))
  (def y (read-tensor-history bar_i))
  (def xr (read-tensor-history radiation_r))
  (def yr (read-tensor-history radiation_i))
  (def radius (exp (/ (- rate) samplerate)))
  (def c (gamelan-hold (* radius (cos omega)) tick))
  (def s (gamelan-hold (* radius (sin omega)) tick))
  (def coupling (gamelan-hold (exp (/ -1 (* rise samplerate))) tick))
  (def next_r (+ (- (* c x) (* s y)) (* force weight)))
  (def next_i (+ (* s x) (* c y)))
  (def radiated_r (+ (* coupling (- (* c xr) (* s yr))) (* (- 1 coupling) next_r)))
  (def radiated_i (+ (* coupling (+ (* s xr) (* c yr))) (* (- 1 coupling) next_i)))
  (write-tensor-history bar_r next_r)
  (write-tensor-history bar_i next_i)
  (write-tensor-history radiation_r radiated_r)
  (write-tensor-history radiation_i radiated_i)
  (mix radiated_i next_i direct))

(def modes (gamelan-resonator omega rate rise direct weight force update_tick))
(def stereo (gamelan-smooth (clip (mod width) 0 1) 8))
(def left (sum (* modes (sqrt (+ 1 (* mode_pan_table stereo))))))
(def right (sum (* modes (sqrt (- 1 (* mode_pan_table stereo))))))

(def drive_v (gamelan-smooth (clip (mod drive) 0 1) 8))
(def cutoff (min (gamelan-smooth (clip (mod tone_hz) 1000 20000) 8) (* samplerate 0.43)))
(def output_gain (gamelan-smooth (clip (mod gain) 0 4) 8))
(defmacro gamelan-output (signal drive_v cutoff gain_v)
  (def driven (mix signal (/ (tanh (* signal (+ 1 (* drive_v 8)))) (+ 1 (* drive_v 2))) drive_v))
  (def filtered (svf driven cutoff 0.707 0))
  (* filtered gain_v))
(out (gamelan-output left drive_v cutoff output_gain) 1 @name left)
(out (gamelan-output right drive_v cutoff output_gain) 2 @name right)
