(defmacro smoothstep (edge0 edge1 x)
  (def sub (- x edge0))
  (def sub-2 (- edge1 edge0))
  (def div (/ sub sub-2))
  (def clip-2 (clip div 0.0 1.0))
  (def mul (* clip-2 clip-2))
  (def mul-2 (* clip-2 -2.0))
  (def add (+ mul-2 3.0))
  (def mul-3 (* mul add))
  mul-3)
