(defmacro allpass (input delaytime g)
  (make-history history1)
  (def mul2 (* g -1.0))
  (def delay1 (delay (read-history history1) delaytime))
  (def mul1 (* delay1 mul2))
  (def add1 (+ input mul1))
  (def mul3 (* add1 g))
  (def add2 (+ mul3 delay1))
  (write-history history1 mul3)
  add2)
(defmacro damping-delay (input time feedback damping)
  (make-history h)
  (def fb-in (read-history h))
  (def fb-filtered (svf fb-in damping 0.707 0.0))
  (def d-in (+ input (* fb-filtered feedback)))
  (def d-out (delay d-in time))
  (write-history h d-out)
  d-out)
(def value1 0.7)
(use-defmacro schroeder-allpass)
(use-defmacro simp2)
(use-defmacro gain2)
(param dampening @min 50.0 @max 5000.0)
(def input_r (in 2 @name Right))
(def mod1 (in 3 @name mod1 @modulator 1))
(def mod2 (in 4 @name mod2 @modulator 2))
(def mod3 (in 5 @name mod3 @modulator 3))
(def mod4 (in 6 @name mod4 @modulator 4))
(param allpassdelay @min 5.0 @max 900.0 @default 600.0 @mod true @mod-mode additive)
(def input_l (in 1 @name Left))
(param delaytime @min 0.1 @max 4.0 @default 1.0 @mod true @mod-mode additive)
(def modulated1 (mod delaytime))
(param feedback @min 0.0 @max 1.0 @default 0.99 @mod true @mod-mode additive)
(def add4 (+ input_l input_r))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def processed_l input_l)
(def processed_r input_r)
(def mul4 (* modulated1 1234.0))
(def mul3 (* modulated1 1537.0))
(def mul2 (* modulated1 634.0))
(def mul1 (* modulated1 934.0))
(def damping-delay4 (damping-delay add4 mul4 (mod feedback) dampening))
(def damping-delay3 (damping-delay add4 mul3 (mod feedback) dampening))
(def damping-delay2 (damping-delay add4 mul2 (mod feedback) dampening))
(def damping-delay1 (damping-delay input_l mul1 (mod feedback) dampening))
(def add1 (+ damping-delay1 damping-delay2))
(def add2 (+ add1 damping-delay3))
(def add3 (+ add2 damping-delay4))
(def mul5 (* add3 0.25))
(def allpass1 (allpass mul5 (mod allpassdelay) 0.75))
(def allpass2 (allpass allpass1 (mod allpassdelay) 0.78))
(out (mix input_l allpass2 mix-amt) 1 @name Left)
(out (mix input_l allpass2 mix-amt) 2)