(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))

(param amp_attack @default 4 @min 1 @max 2000 @unit ms)
(param amp_decay @default 220 @min 1 @max 4000 @unit ms)
(param amp_sustain @default 0.65 @min 0 @max 1)
(param amp_release @default 180 @min 1 @max 5000 @unit ms)

(param mod_attack @default 2 @min 1 @max 2000 @unit ms)
(param mod_decay @default 380 @min 1 @max 5000 @unit ms)
(param mod_sustain @default 0.18 @min 0 @max 1)
(param mod_release @default 140 @min 1 @max 5000 @unit ms)

(param op1_ratio @default 1 @min 0.25 @max 16)
(param op2_ratio @default 2 @min 0.25 @max 16)
(param op3_ratio @default 3 @min 0.25 @max 16)
(param op1_detune @default 0 @min -1200 @max 1200 @unit cents)
(param op2_detune @default 0 @min -1200 @max 1200 @unit cents)
(param op3_detune @default 7 @min -1200 @max 1200 @unit cents)

(param op1_level @default 0.85 @min 0 @max 1 @mod true @mod-mode additive)
(param op2_level @default 0.04 @min 0 @max 1 @mod true @mod-mode additive)
(param op3_level @default 0.00 @min 0 @max 1 @mod true @mod-mode additive)
(param op2_to_op1 @default 2.1 @min 0 @max 12 @mod true @mod-mode additive)
(param op3_to_op1 @default 0.45 @min 0 @max 12 @mod true @mod-mode additive)
(param op3_to_op2 @default 1.65 @min 0 @max 12 @mod true @mod-mode additive)

(param mod_env_to_op2 @default 1.0 @min -4 @max 8)
(param mod_env_to_op3 @default 0.7 @min -4 @max 8)
(param lfo_rate @default 0.32 @min 0.02 @max 30 @unit Hz @mod true @mod-mode additive)
(param lfo_to_index @default 0.22 @min 0 @max 6)
(param lfo_to_pitch @default 0 @min 0 @max 48 @unit cents)

(param filter_route @default 1 @min 1 @max 5)
(param f1_mode @default 0 @min 0 @max 5)
(param f2_mode @default 0 @min 0 @max 5)
(param f1_cutoff @default 1400 @min 40 @max 16000 @unit Hz @mod true @mod-mode additive)
(param f2_cutoff @default 5200 @min 40 @max 16000 @unit Hz @mod true @mod-mode additive)
(param f1_resonance @default 0.85 @min 0.5 @max 6 @mod true @mod-mode additive)
(param f2_resonance @default 0.75 @min 0.5 @max 6 @mod true @mod-mode additive)
(param f1_drive @default 1.25 @min 0.2 @max 8 @mod true @mod-mode additive)
(param f2_drive @default 1.0 @min 0.2 @max 8 @mod true @mod-mode additive)
(param f1_env_amt @default 1200 @min -8000 @max 8000 @unit Hz)
(param f2_env_amt @default -600 @min -8000 @max 8000 @unit Hz)
(param f1_lfo_amt @default 0 @min -4000 @max 4000 @unit Hz)
(param f2_lfo_amt @default 0 @min -4000 @max 4000 @unit Hz)
(param filter_blend @default 1 @min 0 @max 1 @mod true @mod-mode additive)

(param fold @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)
(param drive @default 1.25 @min 0.2 @max 8 @mod true @mod-mode additive)
(param gain @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)

(def amp_env (adsr gate trigger amp_attack amp_decay amp_sustain amp_release))
(def mod_env (adsr gate trigger mod_attack mod_decay mod_sustain mod_release))

(def lfo_phase (phasor (clip (mod lfo_rate) 0.02 30)))
(def lfo (sin (* lfo_phase twopi)))
(def pitch_lfo_mul (pow 2 (/ (* lfo lfo_to_pitch) 1200)))
(def base_freq (* pitch pitch_lfo_mul))

(def op1_freq (* base_freq op1_ratio (pow 2 (/ op1_detune 1200))))
(def op2_freq (* base_freq op2_ratio (pow 2 (/ op2_detune 1200))))
(def op3_freq (* base_freq op3_ratio (pow 2 (/ op3_detune 1200))))

(def op3_phase (phasor op3_freq))
(def op3 (sin (* op3_phase twopi)))

(def op2_phase (phasor op2_freq))
(def op2_index (+ (clip (mod op3_to_op2) 0 12) (* mod_env mod_env_to_op2) (* lfo lfo_to_index)))
(def op2 (sin (+ (* op2_phase twopi) (* op3 op2_index))))

(def op1_phase (phasor op1_freq))
(def op1_index (+ (clip (mod op2_to_op1) 0 12) (* op3 (clip (mod op3_to_op1) 0 12)) (* mod_env mod_env_to_op3) (* lfo lfo_to_index)))
(def op1 (sin (+ (* op1_phase twopi) (* op2 op1_index))))

(def mix (+ (* op1 (clip (mod op1_level) 0 1)) (* op2 (clip (mod op2_level) 0 1)) (* op3 (clip (mod op3_level) 0 1))))
(def folded (sin (+ (* mix twopi) (* (sin (* mix twopi 2)) (clip (mod fold) 0 1)))))
(def blend (+ (* mix (- 1 (clip (mod fold) 0 1))) (* folded (clip (mod fold) 0 1))))
(def driven (tanh (* blend (clip (mod drive) 0.2 8))))

(def f1_cut (clip (+ (mod f1_cutoff) (* mod_env f1_env_amt) (* lfo f1_lfo_amt)) 40 16000))
(def f2_cut (clip (+ (mod f2_cutoff) (* mod_env f2_env_amt) (* lfo f2_lfo_amt)) 40 16000))
(def f1_in (tanh (* driven (clip (mod f1_drive) 0.2 8))))
(def f2_in (tanh (* driven (clip (mod f2_drive) 0.2 8))))
(def f1 (svf f1_in f1_cut (clip (mod f1_resonance) 0.5 6) f1_mode))
(def f2 (svf f2_in f2_cut (clip (mod f2_resonance) 0.5 6) f2_mode))
(def f12 (svf (tanh (* f1 (clip (mod f2_drive) 0.2 8))) f2_cut (clip (mod f2_resonance) 0.5 6) f2_mode))
(def f21 (svf (tanh (* f2 (clip (mod f1_drive) 0.2 8))) f1_cut (clip (mod f1_resonance) 0.5 6) f1_mode))
(def fpar (* 0.5 (+ f1 f2)))
(def routed (selector filter_route f12 f21 fpar f1 f2))
(def filter_mix (clip (mod filter_blend) 0 1))
(def filtered (+ (* driven (- 1 filter_mix)) (* routed filter_mix)))

(out (* filtered amp_env velocity (clip (mod gain) 0 1)) 1 @name audio)
