; Machinedrum-style hat machines: TRX-HH, EFM-HH, PI-HH.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro md-ping (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def y (- (+ exc (* 2 r (cos (* twopi (/ (clip freq 8 19000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def hz (exp (+ (log 300.0) (* (- 1 (clip amount 0 1)) (- (log 44100.0) (log 300.0))))))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (latch x tick))
(defmacro metal6 (tune spread jit mtal)
  (def t (semi tune))
  (def s (clip spread 0 2))
  (def duty (clip (+ 0.48 (* mtal 0.10)) 0.08 0.92))
  (+ (* 0.18 (polyblep_pulse (phasor (* 205.3 t (+ 1 (* s -0.18)) (+ 1 (* jit 0.015)))) duty (* 205.3 t)))
     (* 0.17 (polyblep_pulse (phasor (* 304.4 t (+ 1 (* s -0.08)))) duty (* 304.4 t)))
     (* 0.16 (polyblep_pulse (phasor (* 369.6 t (+ 1 (* s 0.04)))) duty (* 369.6 t)))
     (* 0.16 (polyblep_pulse (phasor (* 522.7 t (+ 1 (* s 0.16)))) duty (* 522.7 t)))
     (* 0.15 (polyblep_pulse (phasor (* 540.0 t (+ 1 (* s 0.24)))) duty (* 540.0 t)))
     (* 0.13 (polyblep_pulse (phasor (* 800.0 t (+ 1 (* s 0.38)))) duty (* 800.0 t)))))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 19000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 3)
(param tune @default 0 @min -24 @max 24 @mod true @mod-mode additive)
(param gap @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param dec @default 90 @min 20 @max 900 @unit ms @mod true @mod-mode additive)
(param hpf @default 7200 @min 500 @max 16000 @unit Hz @mod true @mod-mode additive)
(param lpf @default 14500 @min 1200 @max 19000 @unit Hz @mod true @mod-mode additive)
(param mtal @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)

(param ptch @default 0 @min -36 @max 48 @mod true @mod-mode additive)
(param trem @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param tfrq @default 120 @min 0.1 @max 300 @unit Hz @mod true @mod-mode additive)
(param mod_amt @default 0.70 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 2900 @min 100 @max 9000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 45 @min 1 @max 500 @unit ms)
(param fb @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)

(param clsn @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param ring @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param ag @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param au @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)
(param br @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)
(param clos @default 127 @min 0 @max 127 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.48 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 70 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 7800 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 6000 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 11000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.70 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.04 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 3))
(def vel (clip velocity 0 1))
(def jit (* (latch-trig (noise) trigger) humanize))
(def metal (metal6 (mod tune) (+ 0.25 (* (mod gap) 1.3)) jit (mod mtal)))
(def mring (* (sin (* (phasor (* 540 (semi (mod tune)))) twopi)) (sin (* (phasor (* 800 (semi (mod tune)))) twopi)) (mod mtal)))

(def trx_env1 (md-env trigger (clip (mod dec) 20 900)))
(def trx_env2 (md-env trigger (clip (* (mod dec) 0.55) 10 500)))
(def trx_b1 (* (svf metal 3440 (+ 1.0 (* (mod gap) 4.0)) 1) trx_env1))
(def trx_b2 (* (svf metal 7100 (+ 1.0 (* (mod gap) 3.0)) 1) trx_env2 (+ 0.4 (* (mod gap) 0.8))))
(def trx_hh (svf (svf (+ trx_b1 trx_b2 (* mring trx_env2 0.45)) (clip (mod hpf) 500 16000) 0.7 2) (clip (mod lpf) 1200 19000) 0.7 0))

(make-history fmfb)
(def fm_env (md-env trigger (clip mdec 1 500)))
(def m (sin (+ (* (retrig-phasor (clip (mod mfrq) 100 9000) trigger) twopi) (* (read-history fmfb) (mod fb) 8.0))))
(write-history fmfb (clip m -1 1))
(def cph (retrig-phasor (clip (* pitch (semi (mod ptch)) 12) 300 15000) trigger))
(def tremolo (+ (- 1 (mod trem)) (* (mod trem) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod tfrq) 0.1 300)) twopi)))))))
(def efm_hh (* (sin (+ (* cph twopi) (* m fm_env (mod mod_amt) 18))) (md-env trigger (clip (mod dec) 20 900)) tremolo))

(def energy (md-env trigger (clip (mod dec) 20 900)))
(def closed (gt (* energy samplerate 0.001) (clip (mod clos) 0 127)))
(def damp_mul (gswitch closed 0.18 1.0))
(def collide (gt (noise) (- 1 (* (mod clsn) energy 0.8))))
(def exc (+ (* (noise) (md-env trigger 2)) (* (noise) (gswitch collide energy 0.0))))
(def pf (clip (* pitch (semi (mod ptch)) 4.0) 260 1800))
(def pi_hh (+ (md-ping exc (* pf 1.00) (* (mod dec) damp_mul (+ 0.20 (* (mod ring) 1.3))))
              (md-ping exc (* pf 1.34) (* (mod dec) damp_mul (+ 0.16 (* (mod ring) 1.1))))
              (md-ping exc (* pf 1.72) (* (mod dec) damp_mul (+ 0.13 (* (mod ring) 0.9))))
              (md-ping exc (* pf 2.18) (* (mod dec) damp_mul (+ 0.11 (* (mod ring) 0.7))))
              (md-ping exc (* pf 2.63) (* (mod dec) damp_mul (+ 0.09 (* (mod ring) 0.6))))
              (md-ping exc (* pf 3.10) (* (mod dec) damp_mul (+ 0.08 (* (mod ring) 0.5))))))
(def pi_tone (+ (* (svf pi_hh 9500 0.7 4) (mod ag)) (* (svf pi_hh 12000 0.7 2) (- 1 (mod au))) (* (svf pi_hh 3000 0.7 1) (mod br))))

(def voice (selector eng trx_hh efm_hh pi_tone))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
