; Internal-master hard sync with fractional event timing. Each discontinuity
; contributes a two-sample polynomial BLEP; the sine's reset slope also gets
; a BLAMP. A one-sample delay provides the sample before each event, avoiding
; the incorrect full-cycle saw correction at a partial-cycle sync reset.
; Frequencies are capped below Nyquist, bounding the event count per sample.
(defmacro heat-sync (frequency ratio wave pulse_width)
  (make-history master_hist)
  (make-history slave_hist)
  (make-history value_hist)
  (make-history correction_hist)
  (def dm (/ (clip frequency 0.01 (* 0.45 samplerate)) samplerate))
  (def ds (/ (clip (* frequency (max 1 ratio)) 0.01 (* 0.45 samplerate)) samplerate))
  (def master (read-history master_hist))
  (def slave (read-history slave_hist))
  (def duty (clip pulse_width 0.01 0.99))
  (def reset (gte (+ master dm) 1))
  (def reset_time (clip (/ (- 1 master) dm) 0 1))
  (def end (gswitch reset reset_time 1))
  (def wrap_time (/ (- 1 slave) ds))
  (def wraps (lte wrap_time end))
  (def fall_time (/ (- (gswitch (lt slave duty) duty (+ duty 1)) slave) ds))
  (def falls (lte fall_time end))
  (def before_reset (wrap (+ slave (* ds end)) 0 1))
  (def after_time (+ reset_time (/ duty ds)))
  (def after_falls (* reset (lte after_time 1)))
  (def phase (gswitch reset (* ds (- 1 reset_time)) before_reset))
  (def sine_mode (eq (round wave) 0))
  (def saw_mode (eq (round wave) 1))
  (def pulse_mode (eq (round wave) 2))
  (def wrap_jump (* wraps (+ (* saw_mode -2) (* pulse_mode 2))))
  (def fall_jump (* falls (* pulse_mode -2)))
  (def after_jump (* after_falls (* pulse_mode -2)))
  (def reset_jump (* reset (+
    (* sine_mode (- 0 (sin (* 6.28318530718 before_reset))))
    (* saw_mode (* -2 before_reset))
    (* pulse_mode (* 2 (gte before_reset duty))))))
  (def reset_slope (* reset (* sine_mode
    (* 6.28318530718 (* ds (- 1 (cos (* 6.28318530718 before_reset))))))))
  (def a (clip wrap_time 0 1))
  (def b (clip fall_time 0 1))
  (def c reset_time)
  (def d (clip after_time 0 1))
  (def pre (+ (* 0.5 (+
    (* wrap_jump (* (- 1 a) (- 1 a)))
    (* fall_jump (* (- 1 b) (- 1 b)))
    (* reset_jump (* (- 1 c) (- 1 c)))
    (* after_jump (* (- 1 d) (- 1 d)))))
    (/ (* reset_slope (* (- 1 c) (* (- 1 c) (- 1 c)))) 6)))
  (def post (+ (* -0.5 (+
    (* wrap_jump (* a a)) (* fall_jump (* b b))
    (* reset_jump (* c c)) (* after_jump (* d d))))
    (/ (* reset_slope (* c (* c c))) 6)))
  (def raw (+ (* sine_mode (sin (* 6.28318530718 phase)))
    (* saw_mode (- (* 2 phase) 1))
    (* pulse_mode (gswitch (lt phase duty) 1 -1))))
  (def result (+ (read-history value_hist) (read-history correction_hist) pre))
  (write-history master_hist (wrap (+ master dm) 0 1))
  (write-history slave_hist phase)
  (write-history value_hist raw)
  (write-history correction_hist post)
  result)
