(defmacro unison-frequencies (base_freq detune_st)
  (def scale_val (* detune_st 0.057762265046662105))
  (def f0 base_freq)
  (def f_1 (* base_freq (exp (* scale_val -0.4))))
  (def f1 (* base_freq (exp (* scale_val 0.4))))
  (def f_2 (* base_freq (exp (* scale_val -0.8))))
  (def f2 (* base_freq (exp (* scale_val 0.8))))
  (def f_3 (* base_freq (exp (* scale_val -1.2))))
  (def f3 (* base_freq (exp (* scale_val 1.2))))
  (tuple f0 f_1 f1 f_2 f2 f_3 f3))
