(defmacro tape-hysteresis (input drive bias hyster damping)
  (make-history h_in)
  (def prev_in (read-history h_in))
  (write-history h_in input)
  (def diff (- input prev_in))
  (def H (+ (* input (+ 1.0 (* drive 4.0))) bias (* hyster diff 5.0)))
  (def M (tanh H))
  (def cutoff (- 20000.0 (* damping 16000.0)))
  (svf M cutoff 0.707 0.0))
(param dampening @min 0.0 @max 1.0)
(param drive @min 0.1 @max 4.0 @default 1.0 @group tape)
(def input_r (in 2 @name Right))
(def mod1 (in 3 @name mod1 @modulator 1))
(def mod2 (in 4 @name mod2 @modulator 2))
(def mod3 (in 5 @name mod3 @modulator 3))
(def mod4 (in 6 @name mod4 @modulator 4))
(def input_l (in 1 @name Left))
(param hyster @min 0.0 @max 1.0 @mod true @mod-mode additive @group tape)
(param bias @min 0.0 @max 1.0 @default 0.0 @mod true @mod-mode additive @group tape)
(def tape-hysteresis2 (tape-hysteresis input_r drive bias (mod hyster) dampening))
(def tape-hysteresis1 (tape-hysteresis input_l drive bias (mod hyster) dampening))
(param mix @min 0.0 @max 1.0 @default 0.5)
(def processed_l input_l)
(def processed_r input_r)
(out (mix input_l tape-hysteresis1 mix) 1 @name Left)
(out (mix input_r tape-hysteresis2 mix) 2 @name Right)