(make-history history1)
(def input_r (in 2 @name Right))
(def mod1 (in 3 @name mod1 @modulator 1))
(def mod2 (in 4 @name mod2 @modulator 2))
(def mod3 (in 5 @name mod3 @modulator 3))
(def mod4 (in 6 @name mod4 @modulator 4))
(def input_l (in 1 @name Left))
(param gater @min 0.0 @max 1.0 @mod true @mod-mode additive)
(def mix1 (mix gater (read-history history1) 0.99))
(def mul2 (* input_r mix1))
(def mul1 (* input_l mix1))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def processed_l input_l)
(def processed_r input_r)
(out (mix input_l mul1 mix-amt) 1 @name Left)
(out (mix input_r mul2 mix-amt) 2 @name Right)
(write-history history1 mix1)