(make-history history1)
(def value2 44100.0)
(def value1 20000.0)
(def add1 (+ (read-history history1) 1.0))
(param sr @min 2000.0 @max 44100.0 @default 20000.0)
(def div1 (/ value2 sr))
(def ceil1 (ceil div1))
(def generated1 (% (read-history history1) ceil1))
(def generated2 (== generated1 0.0))
(def input_l (in 1 @name Left))
(def latch1 (latch input_l generated2))
(def input_r (in 2 @name Right))
(def latch2 (latch input_r generated2))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def processed_l input_l)
(def processed_r input_r)
(out (mix input_l latch1 mix-amt) 1 @name Left)
(out (mix input_r latch2 mix-amt) 2 @name Right)
(write-history history1 add1)