(defmacro mnm_srr (sig amount)
  (def srr_amt (clip amount 0.0 1.0))
  (def hold_hz (* samplerate (pow (/ 300.0 samplerate) srr_amt)))
  (make-history srr_ph_h)
  (make-history srr_val_h)
  (def srr_prev_ph (read-history srr_ph_h))
  (def srr_ph (wrap (+ srr_prev_ph (/ hold_hz samplerate)) 0.0 1.0))
  (def srr_wrapped (lt srr_ph srr_prev_ph))
  (write-history srr_ph_h srr_ph)
  (def srr_held (gswitch (max srr_wrapped (lte srr_amt 0.001)) sig (read-history srr_val_h)))
  (write-history srr_val_h srr_held)
  srr_held)
