(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))

(param model @default 0 @min 0 @max 2)

(param amp_attack @default 1 @min 1 @max 60 @unit ms)
(param amp_decay @default 520 @min 40 @max 3200 @unit ms @mod true @mod-mode additive)
(param amp_sustain @default 0 @min 0 @max 0.25)
(param amp_release @default 55 @min 2 @max 900 @unit ms)

(param tune @default -24 @min -60 @max 24 @mod true @mod-mode additive)
(param fine @default 0 @min -100 @max 100 @unit cents)
(param bend @default 38 @min -24 @max 96 @mod true @mod-mode additive)
(param bend_decay @default 48 @min 3 @max 420 @unit ms)
(param punch @default 8 @min 0 @max 48 @mod true @mod-mode additive)
(param punch_decay @default 8 @min 1 @max 120 @unit ms)

(param body_level @default 0.86 @min 0 @max 1 @mod true @mod-mode additive)
(param sub_level @default 0.58 @min 0 @max 1 @mod true @mod-mode additive)
(param sub_ratio @default 0.50 @min 0.25 @max 1.00 @mod true @mod-mode additive)
(param overtone @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)
(param membrane_decay @default 0.72 @min 0.15 @max 2.00)
(param body_shape @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)

(param click_level @default 0.30 @min 0 @max 1 @mod true @mod-mode additive)
(param click_tone @default 5200 @min 400 @max 16000 @unit Hz @mod true @mod-mode additive)
(param click_decay @default 10 @min 1 @max 120 @unit ms)
(param click_noise_mix @default 0.68 @min 0 @max 1)

(param noise_level @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param noise_tone @default 4400 @min 120 @max 14000 @unit Hz @mod true @mod-mode additive)
(param noise_decay @default 34 @min 2 @max 320 @unit ms)
(param noise_color @default 0.62 @min 0 @max 1)
(param noise_q @default 2.0 @min 0.5 @max 8.0)

(param low_cut @default 28 @min 12 @max 260 @unit Hz @mod true @mod-mode additive)
(param body_tone @default 9000 @min 200 @max 16000 @unit Hz @mod true @mod-mode additive)
(param tone @default 9500 @min 220 @max 16000 @unit Hz @mod true @mod-mode additive)
(param resonance @default 0.72 @min 0.5 @max 3.0 @mod true @mod-mode additive)
(param drive @default 1.8 @min 0.35 @max 12 @mod true @mod-mode additive)
(param dirt @default 0.16 @min 0 @max 1 @mod true @mod-mode additive)
(param gain @default 0.50 @min 0 @max 1 @mod true @mod-mode additive)

(def model_index (+ 1 (floor (clip model 0 2))))
(def model_decay_mul (selector model_index 1.55 0.95 1.10))
(def model_bend_mul (selector model_index 0.78 1.18 0.62))
(def model_sub_gain (selector model_index 1.30 0.72 0.34))
(def model_body_gain (selector model_index 0.95 1.12 1.05))
(def model_mode_gain (selector model_index 0.10 0.36 1.10))
(def model_click_gain (selector model_index 0.72 1.38 0.44))
(def model_noise_gain (selector model_index 0.18 1.18 0.42))
(def model_drive_mul (selector model_index 0.88 1.22 0.96))
(def model_mode_ratio_a (selector model_index 1.48 1.72 1.50))
(def model_mode_ratio_b (selector model_index 2.10 2.65 2.24))

(def tunev (+ (clip (mod tune) -60 24) (/ fine 100)))
(def base_freq (clip (* pitch (pow 2 (/ tunev 12))) 14 520))

(def bend_env (adsr gate trigger 1 bend_decay 0 4))
(def punch_env (adsr gate trigger 1 punch_decay 0 3))
(def bendv (clip (mod bend) -24 96))
(def punchv (clip (mod punch) 0 48))
(def sweep_semi (+ (* bendv bend_env model_bend_mul) (* punchv punch_env)))
(def body_freq (clip (* base_freq (pow 2 (/ sweep_semi 12))) 12 1800))

(def decayv (clip (* (clip (mod amp_decay) 40 3200) model_decay_mul) 30 4200))
(def amp_env (adsr gate trigger amp_attack decayv amp_sustain amp_release))
(def mode_env_a (adsr gate trigger 1 (clip (* decayv membrane_decay 0.62) 18 2600) 0 amp_release))
(def mode_env_b (adsr gate trigger 1 (clip (* decayv membrane_decay 0.38) 12 2100) 0 amp_release))
(def click_env (adsr gate trigger 1 click_decay 0 3))
(def noise_env (adsr gate trigger 1 noise_decay 0 5))

(def body_phase (phasor body_freq))
(def body_angle (* body_phase twopi))
(def body_sine (sin body_angle))
(def body_second (sin (* body_angle 2)))
(def body_third (sin (* body_angle 3)))

(def mode_a_phase (phasor (clip (* body_freq model_mode_ratio_a) 20 7000)))
(def mode_b_phase (phasor (clip (* body_freq model_mode_ratio_b) 20 9000)))
(def mode_a (sin (+ (* mode_a_phase twopi) (* body_sine 0.22))))
(def mode_b (sin (+ (* mode_b_phase twopi) (* mode_a 0.18))))

(def over (clip (mod overtone) 0 1))
(def shapev (clip (mod body_shape) 0 1))
(def body_mix (+ body_sine (* body_second over 0.25) (* body_third over shapev 0.20) (* mode_a mode_env_a over model_mode_gain 0.72) (* mode_b mode_env_b over model_mode_gain 0.48)))
(def body_shaped (+ (* body_mix (- 1 (* shapev 0.35))) (* (tanh (* body_mix (+ 1 (* shapev 11)))) shapev 0.58)))
(def body_pre (* body_shaped amp_env (clip (mod body_level) 0 1) model_body_gain))
(def body (svf body_pre (clip (mod body_tone) 200 16000) 0.7 0))

(def sub_freq (clip (* body_freq (clip (mod sub_ratio) 0.25 1.0)) 8 900))
(def sub_phase (phasor sub_freq))
(def sub_sine (sin (* sub_phase twopi)))
(def sub (* (tanh (* sub_sine (+ 1 (* shapev 2.4)))) amp_env (clip (mod sub_level) 0 1) model_sub_gain))

(def n (noise))
(def click_sweep_freq (clip (* (clip (mod click_tone) 400 16000) (+ 1 (* 6 click_env))) 300 18000))
(def click_osc (sin (* (phasor click_sweep_freq) twopi)))
(def click_bp (svf n (clip (mod click_tone) 400 16000) 3.4 1))
(def click_hp (svf click_bp 1400 0.7 2))
(def cmix (clip click_noise_mix 0 1))
(def click_src (+ (* click_osc (- 1 cmix)) (* click_hp cmix)))
(def click (* click_src click_env (clip (mod click_level) 0 1) model_click_gain 1.25))

(def ntone (clip (mod noise_tone) 120 14000))
(def nq (clip noise_q 0.5 8))
(def snap_lp (svf n ntone nq 0))
(def snap_bp (svf n ntone nq 1))
(def snap_hp (svf n ntone nq 2))
(def ncol (clip noise_color 0 1))
(def snap_blend (+ (* snap_lp (clip (- 0.5 ncol) 0 0.5) 2) (* snap_bp (- 1 (* 2 (abs (- ncol 0.5))))) (* snap_hp (clip (- ncol 0.5) 0 0.5) 2)))
(def snap_tight (svf snap_blend (clip (mod low_cut) 12 260) 0.7 2))
(def snap_edge (svf snap_tight (clip (* ntone 1.8) 500 16000) 0.8 2))
(def snap (* (+ snap_tight (* snap_edge 0.70)) noise_env (clip (mod noise_level) 0 1) model_noise_gain 1.55))

(def raw (+ body sub click snap))
(def lowtight (svf raw (clip (mod low_cut) 12 260) 0.65 2))
(def drivev (* (clip (mod drive) 0.35 12) model_drive_mul))
(def dirtv (clip (mod dirt) 0 1))
(def warm (tanh (* lowtight drivev)))
(def hard (tanh (* (+ lowtight (* lowtight lowtight dirtv)) (+ 1 (* drivev 3.0)))))
(def driven (+ (* warm (- 1 dirtv)) (* hard dirtv)))
(def transient_lift (+ (* click 0.22) (* snap 0.25)))
(def toned (svf (+ driven transient_lift) (clip (mod tone) 220 16000) (clip (mod resonance) 0.5 3.0) 0))

(out (* toned velocity (clip (mod gain) 0 1)) 1 @name audio)
