(defmacro dc-block (input coeff)
  (make-history hx)
  (make-history hy)
  (def x_prev (read-history hx))
  (def y_prev (read-history hy))
  (def y (+ (- input x_prev) (* coeff y_prev)))
  (def wx (write-history hx input))
  (def wy (write-history hy y))
  y)
(def sig (in 1 @name signal))
(def rate (param rate @min 0.01 @max 5.0 @default 0.2))
(def depth (param depth @min 0.0 @max 1.0 @default 0.5))
(def manual (param manual @min 1.0 @max 500.0 @default 120.0))
(def fbk (param feedback @min -0.99 @max 0.99 @default 0.75))
(def color (param color @min 1000.0 @max 16000.0 @default 5000.0))
(def mix-amt (param mix @min 0.0 @max 1.0 @default 0.5))
(def ph1 (phasor rate))
(def ph2 (% (+ ph1 0.25) 1.0))
(def lfo1 (sin (* twopi ph1)))
(def lfo2 (sin (* twopi ph2)))
(def dt1 (+ 1.0 (* manual (+ 1.0 (* lfo1 depth)))))
(def dt2 (+ 1.0 (* manual (+ 1.0 (* lfo2 depth)))))
(make-history h1)
(make-history h2)
(def fbk-in1 (read-history h1))
(def fbk-in2 (read-history h2))
(def fbk-filt1 (biquad fbk-in1 color 0.5 0.0 0.0))
(def fbk-filt2 (biquad fbk-in2 color 0.5 0.0 0.0))
(def d1 (delay (+ sig (* fbk fbk-filt1)) dt1))
(def d2 (delay (+ sig (* fbk fbk-filt2)) dt2))
(write-history h1 d1)
(write-history h2 d2)
(out (mix sig d1 mix-amt) 1 @name Left)
(out (mix sig d2 mix-amt) 2 @name Right)