(defmacro simp11 (input shape depth)
  (def mul5 (* depth 1.0))
  (def add1 (+ shape 1.0))
  (def mul3 (* add1 mul5))
  (def simp21 (simp2 input))
  (def phasor1 (phasor input))
  (def triangle1 (triangle phasor1 shape))
  (def mul1 (* triangle1 twopi))
  (def mul4 (* mul1 mul3))
  (def cos1 (cos mul4))
  (def gain21 (gain2 cos1))
  (def gain22 (gain2 gain21))
  (def mix1 (mix gain22 simp21 shape))
  (def mul2 (* mix1 1.0))
  mul2)
(use-defmacro simp2)
(use-defmacro gain2)