; ULTRASNARE — layered snare designer with Machinedrum DNA.
; BODY engine (TONE/FM/MODAL/CLAP, three contextual character knobs bx/by/bz)
; + always-on TRANSIENT / WIRES / RING layers
; + PUNCH enhancer -> DRIVE -> DIRT -> HP/LP output stage.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))

(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro md-env-hold (trig hold_ms decay_ms)
  (make-history e)
  (make-history age)
  (def prev_age (read-history age))
  (def next_age (gswitch (gt trig 0.5) 0.0 (+ prev_age 1.0)))
  (def held (lt next_age (* hold_ms 0.001 samplerate)))
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (gswitch held 1.0 (* (read-history e) coef))))
  (write-history age next_age)
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)

(defmacro latch-trig (sig trig)
  (make-history h)
  (def old (read-history h))
  (def v (gswitch (gt trig 0.5) sig old))
  (write-history h v)
  v)

(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)

(defmacro md-ping (exc freq t60_ms trig)
  (make-history y1)
  (make-history y2)
  (def y1p (gswitch (gt trig 0.5) 0.0 (read-history y1)))
  (def y2p (gswitch (gt trig 0.5) 0.0 (read-history y2)))
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def c (* 2.0 r (cos (* twopi (/ (clip freq 8 18000) samplerate)))))
  (def y (- (+ exc (* c y1p)) (* r r y2p)))
  (write-history y2 y1p)
  (write-history y1 y)
  y)

(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (def hard (clip (* x (+ 1 (* 16 d))) -1 1))
  (def soft (tanh (* x (+ 1 (* 5 d)))))
  (+ (* soft (- 1 d)) (* hard d)))

(defmacro md-srr (x amount trig)
  (def a (clip amount 0 1))
  (def hold_hz (exp (+ (log 300.0) (* (- 1 a) (- (log 44100.0) (log 300.0))))))
  (def ph (retrig-phasor hold_hz trig))
  (make-history prev)
  (make-history held)
  (def tick (lt ph (read-history prev)))
  (def reset (gt trig 0.5))
  (def should_sample (gt (+ (gswitch reset 1.0 0.0) (gswitch tick 1.0 0.0)) 0.5))
  (def sampled (gswitch should_sample x (read-history held)))
  (write-history prev ph)
  (write-history held sampled)
  (gswitch (lt a 0.0001) x sampled))

(defmacro md-bits (x amount)
  (def bits (+ 2 (* (- 1 (clip amount 0 1)) 10)))
  (def steps (pow 2 bits))
  (/ (floor (* x steps)) steps))

(defmacro md-reset-lp (x cutoff trig)
  (make-history y)
  (def c (exp (/ (* -2.0 pi (clip cutoff 20 18000)) samplerate)))
  (def yp (gswitch (gt trig 0.5) 0.0 (read-history y)))
  (def next (+ (* (- 1.0 c) x) (* c yp)))
  (write-history y next)
  next)

(defmacro md-reset-hp (x cutoff trig)
  (- x (md-reset-lp x cutoff trig)))

(param engine @default 1 @min 1 @max 4)

(param ptch @default -3 @min -24 @max 36 @mod true @mod-mode additive)
(param dec @default 260 @min 20 @max 2000 @unit ms @mod true @mod-mode additive)
(param sweep @default 14 @min 0 @max 48 @mod true @mod-mode additive)
(param swpt @default 28 @min 2 @max 300 @unit ms)

(param bx @default 0.40 @min 0 @max 1 @mod true @mod-mode additive)
(param by @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)
(param bz @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)

(param ttyp @default 0 @min 0 @max 3)
(param tamt @default 0.40 @min 0 @max 1 @mod true @mod-mode additive)
(param ttun @default 3800 @min 200 @max 9000 @unit Hz @mod true @mod-mode additive)
(param tdec @default 5 @min 1 @max 80 @unit ms)

(param wire @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)
(param wtun @default 4200 @min 800 @max 12000 @unit Hz @mod true @mod-mode additive)
(param wdec @default 220 @min 10 @max 1500 @unit ms)

(param ring @default 0.15 @min 0 @max 1 @mod true @mod-mode additive)
(param rtun @default 6.3 @min 2 @max 10)
(param rdec @default 260 @min 10 @max 1500 @unit ms)

(param pnch @default 0.35 @min 0 @max 1 @mod true @mod-mode additive)
(param driv @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)
(param dirt @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param hpf @default 50 @min 20 @max 2000 @unit Hz @mod true @mod-mode additive)
(param lpf @default 16000 @min 200 @max 18000 @unit Hz @mod true @mod-mode additive)
(param humanize @default 0.2 @min 0 @max 1)
(param level @default 0.65 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 4))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def jit2 (* (latch-trig (noise) trigger) humanize))

(def dec_v (* (clip (mod dec) 20 2000) (+ 1 (* jit2 0.12))))
(def swpt_v (clip swpt 2 300))
(def bx_v (clip (mod bx) 0 1))
(def by_v (clip (mod by) 0 1))
(def bz_v (clip (mod bz) 0 1))
(def tamt_v (clip (mod tamt) 0 1))
(def ttun_v (clip (mod ttun) 200 9000))
(def tdec_v (clip tdec 1 80))
(def wire_v (clip (mod wire) 0 1))
(def wtun_v (clip (mod wtun) 800 12000))
(def wdec_v (clip wdec 10 1500))
(def ring_v (clip (mod ring) 0 1))
(def rtun_v (clip rtun 2 10))
(def rdec_v (clip rdec 10 1500))
(def pnch_v (clip (mod pnch) 0 1))
(def driv_v (clip (mod driv) 0 1))
(def dirt_v (clip (mod dirt) 0 1))
(def hpf_v (clip (mod hpf) 20 2000))
(def lpf_v (clip (mod lpf) 200 18000))

(def base (clip (* pitch (semi (+ (mod ptch) (* jit 1.2)))) 60 1500))
(def amp (md-env trigger dec_v))
(def p_env (md-env trigger swpt_v))
(def sweep_semi (* (clip (mod sweep) 0 48) p_env (+ 0.7 (* 0.3 accent))))
(def f0 (clip (* base (semi sweep_semi)) 40 4000))
(def body_gain (+ 0.6 (* 0.4 accent)))

; TONE body (TRX/909-style 2-osc): X=TON2 partial mix, Y=SAT, Z=RTIO partial ratio
(def tn_ratio (+ 1.4 (* bz_v 1.2)))
(def tn_ph1 (retrig-phasor f0 trigger))
(def tn_ph2 (retrig-phasor (clip (* f0 tn_ratio) 40 8000) trigger))
(def tn_mix (+ (* (sin (* tn_ph1 twopi)) (- 1 (* bx_v 0.45))) (* (sin (* tn_ph2 twopi)) bx_v 0.80)))
(def tn_sat (tanh (* tn_mix (+ 1 (* by_v 5)))))
(def tone_b (* (+ (* tn_mix (- 1 by_v)) (* tn_sat by_v)) amp body_gain))

; FM body: X=MOD index, Y=MFRQ 60..3000 Hz exp, Z=MFB feedback (chaos allowed)
(make-history us_fb)
(def fm_idx_env (md-env trigger (clip (* swpt_v 1.3) 4 400)))
(def fm_fb_prev (gswitch (gt trigger 0.5) 0.0 (read-history us_fb)))
(def fm_mfrq (clip (* 60 (pow 50 by_v)) 30 4000))
(def fm_mod_ph (retrig-phasor fm_mfrq trigger))
(def fm_mod (sin (+ (* fm_mod_ph twopi) (* bz_v 8.0 fm_fb_prev))))
(write-history us_fb (clip fm_mod -1 1))
(def fm_car_ph (retrig-phasor f0 trigger))
(def fm_b (* (sin (+ (* fm_car_ph twopi) (* fm_mod fm_idx_env bx_v 13))) amp body_gain))

; MODAL body (drum head modes 1/1.59/2.14/2.65): X=HARD, Y=TENS, Z=DAMP
(def m_energy (md-env trigger (* dec_v 0.5)))
(def m_tens (+ 1 (* by_v 0.45 accent m_energy m_energy)))
; excitation normalized by burst length so ping ring level is independent of samplerate
(def m_norm (/ 1.0 (max 8.0 (* 0.0015 samplerate))))
(def m_mallet (* (svf (noise) (clip (+ 1500 (* bx_v 9000)) 500 12000) 1.0 0) (md-env trigger 1.5) m_norm))
(def m_damp (+ 0.28 (* (- 1 bz_v) 0.85)))
(def m_p1 (md-ping m_mallet (* f0 m_tens) (* dec_v 0.55 m_damp) trigger))
(def m_p2 (md-ping m_mallet (* f0 1.59 m_tens) (* dec_v 0.36 m_damp) trigger))
(def m_p3 (md-ping m_mallet (* f0 2.14 m_tens) (* dec_v 0.26 m_damp) trigger))
(def m_p4 (md-ping m_mallet (* f0 2.65 m_tens) (* dec_v 0.20 m_damp) trigger))
(def modal_b (* (+ (* m_p1 0.58) (* m_p2 0.42) (* m_p3 (+ 0.16 (* bx_v 0.30))) (* m_p4 (+ 0.10 (* bx_v 0.26)))) body_gain 0.60))

; CLAP body (multi-burst noise): X=SPRD burst spacing, Y=ROOM tail, Z=TONE
(def cl_spread (+ 8 (* bx_v 22)))
(def cl_ph (retrig-phasor (/ 1000 cl_spread) trigger))
(def cl_burst (pow (- 1 cl_ph) 2))
(def cl_window (md-env-hold trigger (* cl_spread 2.6) 2))
(def cl_cf (clip (+ 700 (* bz_v 2600)) 300 6000))
(def cl_bp (svf (noise) cl_cf 2.2 1))
(def cl_tail (md-env trigger (+ 60 (* by_v 500))))
(def clap_b (* cl_bp (+ (* cl_burst cl_window 1.7) (* cl_tail (+ 0.22 (* by_v 0.55)))) body_gain 1.1))

(def body (selector eng tone_b fm_b modal_b clap_b))

; TRANSIENT layer: TICK / STICK / CLICK / RIM
(def t_env (md-env trigger tdec_v))
(def tr_tick (* (svf (noise) (clip ttun_v 500 12000) 1.2 2) t_env 2.0))
(def tr_stick (* (svf (noise) (clip ttun_v 200 4000) 3.0 1) t_env 3.2))
(def tr_click_exc (* (noise) (md-env trigger 0.7)))
(def tr_click (md-ping tr_click_exc (clip ttun_v 200 9000) (clip (* tdec_v 2.5) 2 200) trigger))
(def rim_norm (/ 1.0 (max 8.0 (* 0.003 samplerate))))
(def tr_rim_exc (* (md-env trigger 3) (+ 1 (* 0.5 (noise))) rim_norm))
(def tr_rim (* (+ (md-ping tr_rim_exc (clip (* f0 2.65) 100 8000) 80 trigger) (* 0.55 (md-ping tr_rim_exc (clip (* f0 9.5) 200 15000) 55 trigger))) 0.45))
(def ttyp_i (clip (round ttyp) 0 3))
(def trans (* (selector (+ ttyp_i 1) tr_tick tr_stick tr_click tr_rim) tamt_v 1.4 accent))

; WIRES layer: fast snap band + slow buzz band + stochastic rattle pings
(def w_fast (md-env trigger (clip (* wdec_v 0.35) 4 500)))
(def w_slow (md-env trigger wdec_v))
; snap band is a bandpass so WTUN audibly moves the color center
(def w_hp (svf (noise) wtun_v 0.9 1))
(def w_bp (svf (noise) (clip (* wtun_v 0.35) 300 5000) 1.6 1))
(def w_collide (gt (noise) (- 1 (* wire_v w_slow 0.25))))
(def w_hit (* (gswitch w_collide 1.0 0.0) w_slow))
; rattle ping tracks WTUN; excitation kept tiny because the resonator rings ~160x
(def w_rattle_f (clip (* wtun_v 1.15) 1000 14000))
(def w_rattle (md-ping (* w_hit (noise) 0.03) w_rattle_f 25 trigger))
(def wires (* (+ (* w_hp w_fast (+ 0.55 (* 0.45 accent))) (* w_bp w_slow 0.7) (* w_rattle 0.35)) wire_v 1.3))

; RING layer: shell clang, two detuned pings above the fundamental
(def r_exc (* (svf (noise) 4000 1.0 0) (md-env trigger 1.2) m_norm))
(def ring_f (clip (* base rtun_v) 200 12000))
(def ring_sig (* (+ (md-ping r_exc ring_f rdec_v trigger) (md-ping r_exc (clip (* ring_f 1.037) 200 12000) (* rdec_v 0.8) trigger)) ring_v 1.6))

; PUNCH enhancer -> DRIVE -> DIRT
(def punch_env (md-env trigger 25))
(def pre (* (+ body trans wires ring_sig) (+ 1 (* pnch_v 2.0 punch_env))))
(def driven (md-clip pre driv_v))
(def srrd (md-srr driven (* dirt_v 0.75) trigger))
(def dirted (+ (* srrd (- 1 (* dirt_v 0.5))) (* (md-bits srrd (* dirt_v 0.9)) dirt_v 0.5)))

; OUTPUT: 12 dB HP + 12 dB LP, level, velocity
(def hp2 (md-reset-hp (md-reset-hp dirted hpf_v trigger) hpf_v trigger))
(def lp2 (md-reset-lp (md-reset-lp hp2 lpf_v trigger) lpf_v trigger))
(out (* lp2 (clip (mod level) 0 1) vel) 1 @name audio)
