#!/usr/bin/env python3
"""Build an isolated four-operator FM/formant instrument with a native motion asset.

The generated source is standalone and readable. This is an integration
candidate, not factory content: see README.md for unfulfilled release gates.
"""
import argparse
import json
import math
from pathlib import Path

from build_ui import write_ui

OPERATOR_COUNT = 4
MOTION_CHANNELS = 7 * OPERATOR_COUNT + 1

HERE = Path(__file__).resolve().parent
FIELDS = ('voiced_level', 'voiced_center', 'voiced_bandwidth', 'skirt',
          'unvoiced_level', 'unvoiced_center', 'unvoiced_bandwidth')
LIMITS = ((0, 1), (80, 16000), (20, 8000), (0, 1), (0, 1), (80, 16000), (20, 8000))


def validate_motion(value):
    if not isinstance(value, dict) or set(value) != {'version', 'frames'} or type(value['version']) is not int or value['version'] != 2:
        raise ValueError('Motion requires version 2 and frames, with no unknown fields')
    frames = value['frames']
    if not isinstance(frames, list) or not 2 <= len(frames) <= 64:
        raise ValueError('Motion requires 2–64 frames')
    previous = -1
    for frame in frames:
        if not isinstance(frame, dict) or set(frame) != {'position', 'pitch_semitones', 'pairs'}:
            raise ValueError('Frame requires position, pitch_semitones and pairs')
        position = frame['position']
        if type(position) not in (int, float) or not math.isfinite(position) or not 0 <= position <= 1 or not previous < position:
            raise ValueError('Frame positions must be finite, strictly ordered and in [0,1]')
        previous = position
        pitch = frame['pitch_semitones']
        if type(pitch) not in (int, float) or not math.isfinite(pitch) or not -48 <= pitch <= 48:
            raise ValueError('Frame pitch must be in [-48,48] semitones')
        if not isinstance(frame['pairs'], list) or len(frame['pairs']) != OPERATOR_COUNT:
            raise ValueError('Each frame requires exactly four voiced/noise entries')
        for pair in frame['pairs']:
            if not isinstance(pair, dict) or set(pair) != set(FIELDS):
                raise ValueError('Pair fields do not match the version 2 schema')
            for key, (low, high) in zip(FIELDS, LIMITS):
                v = pair[key]
                if type(v) not in (int, float) or not math.isfinite(v) or not low <= v <= high:
                    raise ValueError(f'{key} must be finite and in [{low},{high}]')
    if frames[0]['position'] != 0 or frames[-1]['position'] != 1:
        raise ValueError('Motion endpoints must be 0 and 1')
    return value


def default_motion():
    # Original five-state articulation: broad A / E / I / O / A gesture.
    centers = [(750, 1200, 2500), (500, 1900, 2700), (300, 2300, 3100),
               (450, 850, 2500), (750, 1200, 2500)]
    frames = []
    for index, low in enumerate(centers):
        pairs = []
        for i, fc in enumerate((*low, 4200)):
            pairs.append(dict(zip(FIELDS, (max(.08, .8 * .69**i), fc, 130 + 90*i,
                                           .6, .08 * .8**i, fc, 300 + 170*i))))
        frames.append(dict(position=index/4, pitch_semitones=0, pairs=pairs))
    return dict(version=2, frames=frames)


def build(destination, motion, lazy_gates=True):
    validate_motion(motion)
    first_frame, last_frame = motion['frames'][0], motion['frames'][-1]
    loopable = (first_frame['pairs'] == last_frame['pairs']
                and first_frame['pitch_semitones'] == last_frame['pitch_semitones'])
    destination.mkdir(parents=True, exist_ok=True)
    lines = ['; FM Formant — integration candidate. Generated by build_instrument.py.',
             '; Native program data lives in motion.json; see the adjacent README.',
             HERE.joinpath('kernel.lisp').read_text(), HERE.joinpath('voice.lisp').read_text()]
    params = {}

    def emit(s):
        lines.append(s)

    def param(name, default, low, high, mod=False):
        params[name] = default
        attrs = f' @mod true @mod-mode additive @mod-depth-min {low-high} @mod-depth-max {high-low}' if mod else ''
        emit(f'(param {name} @default {default} @min {low} @max {high}{attrs})')
        return f'(mod {name})' if mod else name

    for i, name in enumerate(('gate', 'pitch', 'velocity', 'trigger', 'pressure', 'pitchbend',
                              'modwheel', 'noteon', 'legato', 'clockinc', 'barclock'), 1):
        emit(f'(def {name} (in {i} @name {name}))')
    for i in range(1, 5):
        emit(f'(def mod{i} (in {11+i} @name mod{i} @modulator {i}))')
    for name, d, low, high in [('motion_position', 0, 0, 1), ('formant_shift', 0, -2, 2),
                              ('width_scale', 1, .25, 4), ('fm_intensity', .4, 0, 2),
                              ('breath', .15, 0, 2), ('skirt_offset', 0, -1, 1),
                              ('attack_scale', 1, .05, 8), ('motion_amount', 1, 0, 1)]:
        value = param(name, d, low, high, True)
        emit(f'(def ctl_{name} (ff-smooth (clip {value} {low} {high}) trigger))')
    for name, d, lo, hi in [('volume_db', -6, -48, 6), ('motion_mode', 2 if loopable else 1, 0, 3 if loopable else 1),
                           ('motion_seconds', 3, .02, 30), ('motion_bars', 1, .0625, 16),
                           ('motion_sync', 0, 0, 1), ('phase_reset', 1, 0, 1),
                           ('legato_retrigger', 0, 0, 1), ('bend_range', 2, 0, 24),
                           ('wheel_motion', .3, 0, 1), ('pressure_fm', .2, 0, 2),
                           ('noise_seed', 1, 1, 1000), ('master_attack', 10, 0, 10000),
                           ('master_decay', 600, 0, 10000), ('master_sustain', .8, 0, 1),
                           ('master_release', 700, 0, 20000), ('pitch_env_depth', 0, -4, 4),
                           ('pitch_attack', 0, 0, 10000), ('pitch_decay', 100, 0, 10000),
                           ('pitch_sustain', 0, 0, 1), ('pitch_release', 200, 0, 20000)]:
        param(name, d, lo, hi)
    emit('(def retrig (* trigger (max (- 1 legato) (gte legato_retrigger 0.5))))')
    emit('(def first (click))')
    emit('(def reset (max first retrig))')
    emit('(def pitch_env (adsr gate retrig pitch_attack pitch_decay pitch_sustain pitch_release))')
    emit('(make-history motion_phase)')
    emit(f'(def motion_mode_value (clip (round motion_mode) 0 {3 if loopable else 1}))')
    emit('(def motion_step (gswitch (gte motion_sync 0.5) (/ clockinc motion_bars) (/ 1 (* samplerate motion_seconds))))')
    emit('(def motion_next (gswitch reset 0 (+ (read-history motion_phase) motion_step)))')
    emit('(def motion_run (gswitch (eq motion_mode_value 1) (min 1 motion_next) (wrap motion_next 0 1)))')
    emit('(write-history motion_phase motion_run)')
    emit('(def motion_pos (clip (+ (selector (+ 1 motion_mode_value) ctl_motion_position motion_run motion_run barclock) (* wheel_motion modwheel)) 0 1))')
    # Irregular keyframe positions are compiled into a continuous, piecewise
    # affine index. No nearest-frame snapping or block-rate motion updates.
    terms = []
    frames = motion['frames']
    for left, right in zip(frames, frames[1:]):
        terms.append(f'(clip (/ (- motion_pos {left["position"]}) {right["position"]-left["position"]}) 0 1)')
    emit(f'(def motion_index (+ {" ".join(terms)}))')
    channels = [[] for _ in range(MOTION_CHANNELS)]
    for frame in frames:
        for i, pair in enumerate(frame['pairs']):
            for j, field in enumerate(FIELDS):
                value = pair[field]
                channels[7*i+j].append(math.log(value) if j in (1, 2, 5, 6) else value)
        channels[MOTION_CHANNELS - 1].append(frame['pitch_semitones'])
    tensor = dict(shape=[len(frames), MOTION_CHANNELS], data=[v for c in channels for v in c])
    (destination / 'motion-tensor.json').write_text(json.dumps(tensor)+'\n')
    (destination / 'motion.json').write_text(json.dumps(motion, indent=2)+'\n')
    emit(f'(def motion_data (tensor @shape [{len(frames)} {MOTION_CHANNELS}] @file "motion-tensor.json"))')
    emit(f'(def note_frequency (* (max pitch 10) (exp (* (log 2) (+ (/ (* pitchbend bend_range) 12) (* pitch_env_depth pitch_env) (/ (* ctl_motion_amount (peek motion_data motion_index {MOTION_CHANNELS - 1})) 12))))))')
    for i in range(1, OPERATOR_COUNT + 1):
        p = f'v{i}'
        fc = motion['frames'][0]['pairs'][i-1]['voiced_center']
        for suffix, d, lo, hi in [('mode', 1, 0, 1), ('ratio', 1, .125, 32),
                                 ('fixed', 0, 0, 1), ('fixed_hz', 220, 10, 20000),
                                 ('cents', 0, -100, 100), ('center', fc, 80, 16000),
                                 ('width', 130+90*(i-1), 20, 8000), ('skirt', .6, 0, 1),
                                 ('tracking', 0, 0, 1), ('level', .8*.69**(i-1), 0, 1),
                                 ('output', 1, 0, 1), ('pan', (i-2.5)/2, -1, 1),
                                 ('attack', 10+3*i, 0, 10000), ('decay', 600, 0, 10000),
                                 ('sustain', .8, 0, 1), ('release', 700, 0, 20000),
                                 ('freq_depth', 0, -4, 4), ('freq_attack', 0, 0, 10000),
                                 ('freq_decay', 300, 0, 10000), ('freq_sustain', 0, 0, 1),
                                 ('freq_release', 400, 0, 20000)]:
            param(f'{p}_{suffix}', d, lo, hi)
        p = f'n{i}'
        for suffix, d, lo, hi in [('center', fc, 80, 16000), ('width', 300+170*(i-1), 20, 8000),
                                 ('level', .08*.8**(i-1), 0, 1), ('pan', (2.5-i)/2, -1, 1),
                                 ('attack', 4, 0, 10000), ('decay', 250, 0, 10000),
                                 ('sustain', .25, 0, 1), ('release', 200, 0, 20000),
                                 ('freq_depth', 0, -4, 4), ('freq_attack', 0, 0, 10000),
                                 ('freq_decay', 300, 0, 10000), ('freq_sustain', 0, 0, 1),
                                 ('freq_release', 200, 0, 20000)]:
            param(f'{p}_{suffix}', d, lo, hi)
    for i in range(1, OPERATOR_COUNT + 1):
        for j in range(1, OPERATOR_COUNT + 1):
            if j < i:
                param(f'pm_{j}_to_{i}', 0, -16, 16)
            param(f'fb_{j}_to_{i}', 0, -16, 16)
        emit(f'(make-history feedback_{i})')
        emit(f'(def delayed_{i} (gswitch reset 0 (read-history feedback_{i})))')
    for i in range(1, OPERATOR_COUNT + 1):
        p = f'v{i}'
        edges = [f'(* (ff-smooth pm_{j}_to_{i} reset) voiced_{j})' for j in range(1, i)]
        edges += [f'(* (ff-smooth fb_{j}_to_{i} reset) delayed_{j})' for j in range(1, OPERATOR_COUNT + 1)]
        emit(f'(def pm_{i} (* (+ ctl_fm_intensity (* pressure pressure_fm)) (+ {" ".join(edges)})))')
        emit(f'(def mode_{i} (latch (clip (round {p}_mode) 0 1) reset))')
        emit(f'(def fe_{i} (adsr gate retrig {p}_freq_attack {p}_freq_decay {p}_freq_sustain {p}_freq_release))')
        emit(f'(def freq_{i} (clip (ff-hz (* (gswitch {p}_fixed {p}_fixed_hz (* note_frequency {p}_ratio)) (exp (* (log 2) (+ (/ {p}_cents 1200) (* (- 1 mode_{i}) {p}_freq_depth fe_{i}))))) reset) 10 (* .49 samplerate)))')
        emit(f'(def phase_{i} (ff-phase freq_{i} (* reset phase_reset)))')
        for j, (suffix, logspace) in enumerate((('level',False), ('center',True), ('width',True), ('skirt',False))):
            base = f'(log {p}_{suffix})' if logspace else f'{p}_{suffix}'
            val = f'(mix {base} (peek motion_data motion_index {7*(i-1)+j}) ctl_motion_amount)'
            if logspace:
                val = f'(exp {val})'
            emit(f'(def mv{i}_{suffix} {val})')
        emit(f'(def center_{i} (clip (ff-hz (* mv{i}_center (exp (* (log 2) (+ ctl_formant_shift (* {p}_freq_depth fe_{i})))) (pow (/ note_frequency 261.625565) {p}_tracking)) reset) 10 (* .49 samplerate)))')
        emit(f'(def width_{i} (ff-hz (* mv{i}_width ctl_width_scale) reset))')
        emit(f'(def ae_{i} (adsr gate retrig (* {p}_attack ctl_attack_scale) {p}_decay {p}_sustain {p}_release))')
        formant = f'(ff-formant phase_{i} freq_{i} center_{i} width_{i} (+ mv{i}_skirt ctl_skirt_offset) pm_{i})'
        sine = f'(sin (+ phase_{i} pm_{i}))'
        if lazy_gates:
            formant = f'(block-gate mode_{i} {formant})'
            sine = f'(block-gate (eq mode_{i} 0) {sine})'
        emit(f'(def voiced_{i} (* ae_{i} (ff-smooth mv{i}_level reset) (gswitch mode_{i} {formant} {sine})))')
        emit(f'(write-history feedback_{i} voiced_{i})')
        p = f'n{i}'
        for j, (suffix, logspace) in enumerate((('level',False),('center',True),('width',True)), 4):
            base = f'(log {p}_{suffix})' if logspace else f'{p}_{suffix}'
            val = f'(mix {base} (peek motion_data motion_index {7*(i-1)+j}) ctl_motion_amount)'
            emit(f'(def mn{i}_{suffix} {f"(exp {val})" if logspace else val})')
        emit(f'(def ne_{i} (adsr gate retrig {p}_freq_attack {p}_freq_decay {p}_freq_sustain {p}_freq_release))')
        emit(f'(def nc_{i} (clip (ff-hz (* mn{i}_center (exp (* (log 2) (+ ctl_formant_shift (* {p}_freq_depth ne_{i}))))) reset) 10 (* .49 samplerate)))')
        emit(f'(def nb_{i} (clip (ff-hz (* mn{i}_width ctl_width_scale) reset) 20 8000))')
        emit(f'(def noise_{i} (ff-noise (+ (* noise_seed 97) {i*271}) first))')
        emit(f'(def unvoiced_{i} (* ctl_breath (ff-smooth mn{i}_level reset) (adsr gate retrig (* {p}_attack ctl_attack_scale) {p}_decay {p}_sustain {p}_release) (ff-noise-band noise_{i} nc_{i} nb_{i})))')
        emit(f'(def (vl_{i} vr_{i}) (ff-pan (* voiced_{i} (ff-smooth v{i}_output reset)) (ff-smooth v{i}_pan reset)))')
        emit(f'(def (nl_{i} nr_{i}) (ff-pan unvoiced_{i} (ff-smooth n{i}_pan reset)))')
    emit('(def master (* .25 (ff-smooth (exp (* .11512925465 volume_db)) reset) (clip velocity 0 1) (adsr gate retrig (* master_attack ctl_attack_scale) master_decay master_sustain master_release)))')
    for channel, side in enumerate(('l','r'),1):
        emit(f'(out (* master (ff-dc (+ {" ".join(f"v{side}_{i} n{side}_{i}" for i in range(1, OPERATOR_COUNT + 1))}))) {channel} @name {side})')
    if len(params) > 512:
        raise ValueError(f'Instrument exceeds host parameter capacity: {len(params)}')
    (destination/'dsp.lisp').write_text('\n'.join(lines)+'\n')
    (destination/'defaults.json').write_text(json.dumps(params, indent=2)+'\n')
    write_ui(destination, params)
    return params


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--motion', type=Path)
    args = p.parse_args()
    motion = json.loads(args.motion.read_text()) if args.motion else default_motion()
    params = build(args.output, motion)
    print(f'Built {args.output}: {len(params)} parameters, {len(motion["frames"])} motion frames')


if __name__ == '__main__':
    main()
