; Compact finite damped-sine formant. No oversampling or partial loop.
; This primitive returns quadratures and an amplitude bound for a finite
; geometric series. The stable factored denominator is critical near phase 0.
(defmacro ff-one-minus-exp (x)
  (def z (min x 0.01))
  (gswitch (lt x 0.01)
    (* z (+ 1 (* z (+ -0.5 (* z (+ 0.166666666667 (* z -0.041666666667)))))))
    (- 1 (exp (* -1 x)))))

(defmacro ff-series (phase decay count)
  (def n (max count 0))
  (def q (exp (* -1 decay)))
  (def qn (exp (* -1 decay n)))
  (def omq (ff-one-minus-exp decay))
  (def omqn (ff-one-minus-exp (* decay n)))
  (def sh (sin (* 0.5 phase)))
  (def snh (sin (* 0.5 phase n)))
  (def c (+ omq (* 2 q sh sh)))
  (def d (* -1 q (sin phase)))
  (def a (+ omqn (* 2 qn snh snh)))
  (def b (* -1 qn (sin (* phase n))))
  (def den (+ (* omq omq) (* 4 q sh sh)))
  (tuple (/ (+ (* a c) (* b d)) den)
         (/ (- (* b c) (* a d)) den)
         (/ omqn omq)))

; Positive harmonic coefficients exp(-2*a*abs(h*f0-center)/bandwidth).
; Nyquist transition uses two cosine-tapered terminal harmonics. The same
; coefficients define the level bound; PM is a quadrature rotation.
(defmacro ff-profile (phase f0 center bandwidth a pm)
  (def top (/ (* 0.5 samplerate) f0))
  (def h (max 0 (- (floor top) 2)))
  (def k (clip (floor (/ center f0)) 0 h))
  (def decay (/ (* 2 a f0) bandwidth))
  (def (lr li lm) (ff-series (* -1 phase) decay k))
  (def (rr ri rm) (ff-series phase decay (- h k)))
  (def lphase (+ (* k phase) pm))
  (def rphase (+ (* (+ k 1) phase) pm))
  (def la (exp (/ (* -2 a (abs (- (* k f0) center))) bandwidth)))
  (def ra (exp (/ (* -2 a (abs (- (* (+ k 1) f0) center))) bandwidth)))
  (def core (+ (* la (- (* lr (cos lphase)) (* li (sin lphase))))
               (* ra (- (* rr (cos rphase)) (* ri (sin rphase))))))
  (def j1 (+ h 1))
  (def j2 (+ h 2))
  (def w1 (* 0.5 (- 1 (cos (* pi (clip (/ (- top j1) 2) 0 1))))))
  (def w2 (* 0.5 (- 1 (cos (* pi (clip (/ (- top j2) 2) 0 1))))))
  (def t1 (* w1 (exp (/ (* -2 a (abs (- (* j1 f0) center))) bandwidth))))
  (def t2 (* w2 (exp (/ (* -2 a (abs (- (* j2 f0) center))) bandwidth))))
  (tuple (+ core (* t1 (cos (+ (* j1 phase) pm))) (* t2 (cos (+ (* j2 phase) pm))))
         (+ (* la lm) (* ra rm) t1 t2)))

; All three profiles are 0.5 at +/-bandwidth/2 and 1 at center.
; Skirt moves from the broader-tailed mixture toward the single exponential.
(defmacro ff-formant (phase frequency center_hz bandwidth_hz skirt pm)
  (def f0 (clip frequency 10 (* 0.49 samplerate)))
  (def center (clip center_hz 10 (* 0.49 samplerate)))
  (def bandwidth (clip bandwidth_hz 20 8000))
  (def s (clip skirt 0 1))
  (def (x0 m0) (ff-profile phase f0 center bandwidth 0.69314718056 pm))
  (def (x1 m1) (ff-profile phase f0 center bandwidth 1.38629436112 pm))
  (def (x2 m2) (ff-profile phase f0 center bandwidth 0.287682072452 pm))
  (def broad (* 0.5 (- 1 s)))
  (/ (+ (* s x0) (* broad (+ x1 x2)))
     (max 1 (+ (* s m0) (* broad (+ m1 m2))))))
