; Membrane Hat — fully synthesized hi-hat, sibling of drums/membrane-snare-rim.
; Two cymbals as 64-mode modal banks (8x8 tensors of 2-pole resonators) that
; COLLIDE at the edge circle. The literature drove every structural choice
; (papers archived in docs/references/):
;   - Sekiguchi & Samejima 2023 tested spring contact vs velocity-exchange
;     contact between the two plates: the projection-style contact with a
;     pseudo-LOSS coefficient was measurably closer to a real hat, and the
;     hat's signature "rattle" is broadband noise BETWEEN the mode lines,
;     generated by the collisions themselves. So: `open` sets the edge gap,
;     contact applies a rectified clipped separating force AND removes energy
;     (per-sample state shrink) while touching — closed hats decay fast
;     because they collide constantly, not because we fake a short envelope.
;   - Skare & Abel (DAFx-19): real cymbal highs EMERGE after the attack (the
;     bloom); a linear modal bank cannot do it. `wash` injects a clipped
;     QUADRATIC of the top-plate edge motion into the top third of the modes
;     (von Kármán caricature) — clip-then-scale, energy-bounded.
; Stability story differs from the membrane family: every mode is a 2-pole
; with |pole| = r < 1, unconditionally stable — no Verlet energy bound to
; respect. The only loops are contact (rectified + clipped + lossy) and bloom
; (clipped before scaling); both are bounded injections into decaying filters.
;
; ARCHITECTURE NOTE: the collision runs on 3 SCALAR edge-proxy modes per
; plate, not on the tensor banks, because a sum() reduce of a tensor-history
; read feeding back into that tensor's write silently kills the feedback
; (measured compiler bug, minimal repro in the git history of this file's
; build session). The banks receive the contact force one-way. Block-size
; equivalence: MF128 vs MF1 differ by ~2.6e-6 (-104dB, float reassociation in
; the fused coefficient tensors) — membrane-snare-rim is bit-exact; benign.
;
; Mode tables are baked literals (log-spaced 1..~34 with near-degenerate
; split pairs + per-plate jitter — free-shell spectra are inharmonic and
; dense; exact Chladni ratios matter less than density and non-overlap
; between the plates). Generated by scratchpad gen_hat_tables.py, seeds 11/47.

; ── Host I/O ────────────────────────────────────────────────────────────────
(def gate (in 1 @name gate))
(def host_pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))
(def vel (clip velocity 0 1))
(def vel-gain (sqrt vel))

; ── Params ─────────────────────────────────────────────────────────────────
; THE param: 0 = pedal tight, 1 = fully open. Modulate/p-lock this per step.
(param open @default 0.25 @min 0 @max 1 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; gate-off pedal choke (909-style OH/CH feel): 0 = ring free, 1 = hard choke
(param choke @default 0.35 @min 0 @max 1 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; T60 of the lowest mode when fully open (contact loss shortens it as the
; pedal closes — decay is EMERGENT below open=1)
(param decay @default 900 @min 60 @max 6000 @unit ms @mod true @mod-mode additive @mod-depth-min -2000 @mod-depth-max 2000 @mod-unit ms)
; freq-dependent decay tilt: T60_n = decay * ratio^-tilt (highs die faster;
; Sekiguchi: frequency-dependent damping is essential)
(param tilt @default 0.55 @min 0 @max 1.5 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; tune offsets host pitch; A4/440 default puts the top-plate fundamental ~415
(param tune @default -1 @min -36 @max 24 @unit st @mod true @mod-mode additive @mod-depth-min -24 @mod-depth-max 24 @mod-unit st)
; bottom plate fundamental vs top (bottom hats are heavier/stiffer)
(param plate_ratio @default 1.32 @min 0.5 @max 3 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; strike position: 0 = bell (dark, pitched), 1 = edge (bright, trashy).
; Sekiguchi measured brightness rising monotonically toward the edge.
(param strike @default 0.7 @min 0 @max 1 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; striker (lumped mass, Hertz contact — verbatim family machinery)
(param stick_hard @default 0.015 @min 0.0005 @max 0.05 @mod true @mod-mode additive @mod-depth-min -0.02 @mod-depth-max 0.02)
(param stick_speed @default 0.03 @min 0.002 @max 0.2 @mod true @mod-mode additive @mod-depth-min -0.05 @mod-depth-max 0.05)
(param scrape @default 0.4 @min 0 @max 1 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; plate-to-plate contact: stiffness of the separating reaction and the
; pseudo-loss (energy removed per sample while touching — Sekiguchi Model 2)
(param rattle @default 1 @min 0 @max 4 @mod true @mod-mode additive @mod-depth-min -2 @mod-depth-max 2)
(param contact_loss @default 0.012 @min 0 @max 0.08 @mod true @mod-mode additive @mod-depth-min -0.04 @mod-depth-max 0.04)
; direct contact mic on the collision force (buzz presence, like snares)
(param sizzle @default 0.8 @min 0 @max 4 @mod true @mod-mode additive @mod-depth-min -2 @mod-depth-max 2)
; nonlinear bloom: quadratic energy transfer into the high modes
(param wash @default 0.5 @min 0 @max 2 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
(param bottom_mix @default 0.7 @min 0 @max 2 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)
; output body resonators (parallel band-pass peaks, hand-rolled) + level
(param body1_freq @default 3800 @min 200 @max 12000 @unit Hz @mod true @mod-mode additive @mod-depth-min -4000 @mod-depth-max 4000 @mod-unit Hz)
(param body1_gain @default 0.8 @min 0 @max 8 @mod true @mod-mode additive @mod-depth-min -4 @mod-depth-max 4)
(param body2_freq @default 8200 @min 400 @max 16000 @unit Hz @mod true @mod-mode additive @mod-depth-min -6000 @mod-depth-max 6000 @mod-unit Hz)
(param body2_gain @default 0.6 @min 0 @max 8 @mod true @mod-mode additive @mod-depth-min -4 @mod-depth-max 4)
(param level @default 0.5 @min 0 @max 2 @mod true @mod-mode additive @mod-depth-min -1 @mod-depth-max 1)

; Clipped modulation targets — active modulation can never exceed the bounds
; the loss/contact math was tuned for.
(def open-v (clip (mod open) 0 1))
(def choke-v (clip (mod choke) 0 1))
(def decay-v (clip (mod decay) 60 6000))
(def tilt-v (clip (mod tilt) 0 1.5))
(def tune-v (clip (mod tune) -36 24))
(def plate-ratio-v (clip (mod plate_ratio) 0.5 3))
(def strike-v (clip (mod strike) 0 1))
(def stick-hard-v (clip (mod stick_hard) 0.0005 0.05))
(def stick-speed-v (clip (mod stick_speed) 0.002 0.2))
(def scrape-v (clip (mod scrape) 0 1))
(def rattle-v (clip (mod rattle) 0 4))
(def contact-loss-v (clip (mod contact_loss) 0 0.08))
(def sizzle-v (clip (mod sizzle) 0 4))
(def wash-v (clip (mod wash) 0 2))
(def bottom-mix-v (clip (mod bottom_mix) 0 2))
(def body1-freq-v (clip (mod body1_freq) 200 12000))
(def body1-gain-v (clip (mod body1_gain) 0 8))
(def body2-freq-v (clip (mod body2_freq) 400 16000))
(def body2-gain-v (clip (mod body2_gain) 0 8))
(def level-v (clip (mod level) 0 2))

; ── Mode tables (baked; see header) ─────────────────────────────────────────
(def top-ratios (tensor @shape [8 8] @data [
  1.000 1.019 1.115 1.133 1.309 1.327 1.408 1.431
  1.526 1.550 1.789 1.826 1.899 1.920 2.127 2.172
  2.532 2.547 2.918 2.989 3.167 3.222 3.375 3.393
  3.927 3.951 4.252 4.294 4.685 4.752 5.476 5.595
  6.184 6.294 6.916 7.042 7.716 7.797 9.115 9.342
  10.060 10.252 10.699 10.802 11.956 12.033 14.050 14.233
  15.866 16.068 17.969 18.290 18.363 18.458 22.456 22.779
  25.331 25.659 25.925 26.381 31.189 31.514 32.596 32.976]))
(def bot-ratios (tensor @shape [8 8] @data [
  1.000 1.020 1.104 1.119 1.250 1.264 1.408 1.427
  1.504 1.524 1.682 1.694 1.932 1.979 2.213 2.248
  2.588 2.648 2.803 2.829 3.126 3.164 3.655 3.676
  3.867 3.939 4.432 4.504 5.045 5.094 5.696 5.829
  5.885 5.954 6.821 6.907 7.780 7.858 8.812 9.011
  10.144 10.366 10.594 10.805 12.547 12.762 13.925 14.074
  15.753 15.907 17.277 17.453 19.314 19.427 21.166 21.602
  23.590 24.053 27.893 28.371 30.731 31.012 33.950 34.774]))
; strike-position excitation masks over sorted-mode index (L1-normalized to
; each other so the strike morph holds loudness)
(def bell-mask (tensor @shape [8 8] @data [
  1.110 0.874 0.779 0.741 0.913 0.608 0.601 0.650
  0.542 0.605 0.431 0.374 0.379 0.267 0.361 0.243
  0.222 0.239 0.154 0.193 0.193 0.130 0.166 0.120
  0.125 0.095 0.082 0.068 0.050 0.053 0.076 0.054
  0.047 0.054 0.042 0.046 0.029 0.024 0.033 0.019
  0.025 0.021 0.023 0.020 0.016 0.009 0.008 0.011
  0.012 0.007 0.008 0.005 0.006 0.004 0.005 0.005
  0.004 0.005 0.003 0.003 0.002 0.002 0.003 0.002]))
(def edge-strike-mask (tensor @shape [8 8] @data [
  0.069 0.107 0.074 0.125 0.115 0.131 0.127 0.117
  0.097 0.104 0.109 0.113 0.113 0.121 0.155 0.177
  0.183 0.191 0.124 0.196 0.135 0.126 0.150 0.183
  0.129 0.148 0.170 0.219 0.175 0.178 0.175 0.145
  0.239 0.246 0.225 0.188 0.196 0.181 0.225 0.227
  0.186 0.259 0.242 0.179 0.257 0.242 0.188 0.195
  0.258 0.169 0.219 0.293 0.197 0.233 0.291 0.288
  0.278 0.243 0.302 0.206 0.299 0.231 0.270 0.264]))
; signed edge readouts (mode shape at the rim contact circle) — the same mask
; maps modes -> edge displacement and contact force -> mode injection, which
; is what makes the contact reaction reduce the overlap by construction
(def edge-read-top (tensor @shape [8 8] @data [
  -0.727 -0.736 0.409 -0.811 -0.469 0.571 0.554 0.382
  0.692 0.613 0.307 0.509 -0.273 0.430 0.562 0.558
  -0.497 -0.524 0.241 -0.269 0.324 0.274 0.288 -0.330
  0.400 0.392 0.393 0.190 0.360 0.263 0.180 0.246
  -0.140 0.306 -0.261 -0.141 -0.238 0.114 0.110 0.149
  0.237 0.231 -0.100 0.090 -0.134 0.099 -0.178 -0.182
  0.113 -0.124 0.127 0.125 0.110 -0.125 -0.084 0.100
  0.055 -0.098 -0.097 0.053 0.080 0.069 0.092 -0.046]))
(def edge-read-bot (tensor @shape [8 8] @data [
  0.845 0.932 0.888 -0.610 0.684 0.391 -0.442 0.580
  -0.398 -0.689 0.347 0.326 0.310 -0.580 -0.321 0.540
  -0.552 0.440 -0.507 0.497 0.284 -0.236 -0.200 -0.335
  -0.342 -0.240 0.272 -0.263 0.160 0.147 0.311 -0.288
  -0.238 -0.132 -0.289 -0.245 0.267 -0.163 0.223 -0.211
  0.219 -0.224 -0.135 0.205 -0.198 0.118 -0.098 -0.091
  0.180 -0.075 0.121 -0.088 0.140 -0.098 -0.138 -0.098
  0.065 0.127 0.110 -0.080 -0.106 -0.076 0.100 0.071]))
; output "mic" masks: random signs so the attack isn't an all-positive spike
(def mic-top (tensor @shape [8 8] @data [
  -0.814 0.687 -0.876 0.707 0.542 -0.623 0.442 0.539
  -0.425 0.843 0.770 -0.597 -0.469 0.621 -0.891 -0.957
  -0.731 -0.691 -0.422 0.541 0.525 0.936 0.858 0.838
  -0.686 0.521 0.933 -0.619 -0.631 0.632 -0.456 0.996
  -0.695 0.849 -0.765 0.774 -0.502 -0.956 -0.758 -0.462
  -0.888 0.625 0.806 0.975 -0.993 0.754 0.695 -0.548
  0.497 -0.883 0.690 0.431 -0.574 -0.502 -0.603 0.990
  0.687 -0.975 0.837 -0.527 0.877 0.761 -0.749 0.585]))
(def mic-bot (tensor @shape [8 8] @data [
  0.484 -0.999 -0.472 0.607 0.539 0.592 0.959 0.954
  0.429 0.754 -0.514 0.750 0.864 0.740 0.767 -0.974
  -0.869 0.791 -0.895 0.511 -0.719 -0.955 0.710 -0.797
  0.584 -0.750 -0.757 0.660 0.717 -0.998 -0.659 -0.958
  0.707 -0.458 0.503 0.609 -0.614 -0.422 0.878 0.521
  0.431 -0.897 0.676 0.699 0.751 0.846 -0.836 0.612
  0.892 0.966 -0.700 0.604 -0.815 -0.561 -0.980 -0.471
  -0.553 0.508 -0.458 -0.525 -0.841 0.900 -0.627 0.420]))
; bloom target: only the top third of the modes receive the quadratic drive
(def bloom-mask (tensor @shape [8 8] @data [
  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  0.000 0.000 0.000 0.000 0.003 0.010 0.026 0.030
  0.055 0.067 0.071 0.113 0.104 0.154 0.144 0.167
  0.228 0.309 0.239 0.280 0.379 0.476 0.438 0.432
  0.608 0.407 0.665 0.538 0.526 0.549 0.649 0.879]))

; ── Feedback state ─────────────────────────────────────────────────────────
(make-tensor-history ty1 @shape [8 8])   ; top plate modal outputs (t)
(make-tensor-history ty2 @shape [8 8])   ; top plate modal outputs (t-1)
(make-tensor-history by1 @shape [8 8])   ; bottom plate (t)
(make-tensor-history by2 @shape [8 8])   ; bottom plate (t-1)
(make-history stickx)                    ; striker position
(make-history stickv)                    ; striker velocity
; output-filter states (hand-rolled biquads, family convention)
(make-history dcx1)
(make-history dcy1)
(make-history b1x1) (make-history b1x2) (make-history b1y1) (make-history b1y2)
(make-history b2x1) (make-history b2x2) (make-history b2y1) (make-history b2y2)

; ── Mode frequencies / per-mode decay ───────────────────────────────────────
(def f0-top (clip (* host_pitch (exp (/ (* (log 2) tune-v) 12))) 20 2000))
(def f0-bot (clip (* f0-top plate-ratio-v) 20 2000))
; per-mode clamp happens in the w domain against float bounds: clip is
; signal-only and min(signalTensor, signal) is unsupported, but
; min(signalTensor, float) exists. 2.83 rad ~= 0.45 * 2pi (just under
; Nyquist); above-Nyquist modes would only arise at extreme tune settings.
(def f-top (max (* top-ratios f0-top) 30))
(def f-bot (max (* bot-ratios f0-bot) 30))
(def w-top (min (* twopi (/ f-top samplerate)) 2.83))
(def w-bot (min (* twopi (/ f-bot samplerate)) 2.83))
; T60 per mode: high-frequency tilt (ratio^-tilt) TIMES a mount shape
; r/(r+3) — the clutch clamps the plate at the center, so the low rocking
; modes are heavily damped and the LONGEST-ringing modes are the mids (the
; "ping"). Without this the low modes ring ~1s and the open hat reads as a
; 900Hz clank instead of metal (measured). Floor keeps r finite.
(def mount-top (/ top-ratios (+ top-ratios 3)))
(def mount-bot (/ bot-ratios (+ bot-ratios 3)))
(def t60-top (max (* decay-v 0.0022 mount-top (pow top-ratios (* tilt-v -1))) 0.002))
(def t60-bot (max (* decay-v 0.0018 mount-bot (pow bot-ratios (* tilt-v -1))) 0.002))
(def r-top (exp (/ -6.9077553 (* samplerate t60-top))))
(def r-bot (exp (/ -6.9077553 (* samplerate t60-bot))))

; ── Read state (each history read EXACTLY once) ─────────────────────────────
(def ty1v (read-tensor-history ty1))
(def ty2v (read-tensor-history ty2))
(def by1v (read-tensor-history by1))
(def by2v (read-tensor-history by2))

; ── Striker: lumped mass in Hertz contact (family machinery, stiffer tip) ───
(def stick-x (gswitch trigger 0.0001 (read-history stickx)))
(def stick-v (gswitch trigger (* -1 (* stick-speed-v vel-gain))
                      (read-history stickv)))
(def stick-pen (max (* stick-x -1) 0))
(def stick-f (min (* stick-hard-v stick-pen (sqrt stick-pen)) 0.01))
(def stick-v-next (+ stick-v stick-f))
(def stick-x-next (+ stick-x stick-v-next))
(write-history stickx stick-x-next)
(write-history stickv stick-v-next)
(def strike-force (* stick-f -1 (+ 1 (* scrape-v (noise))) 3))
(def strike-mask-m (+ (* bell-mask (- 1 strike-v)) (* edge-strike-mask strike-v)))

; ── Plate-to-plate contact at the edge circle ───────────────────────────────
; COMPILER CONSTRAINT (measured, scratchpad thist-test): a sum() reduce of a
; tensor-history read feeding back into that same tensor's write silently
; KILLS the feedback — the banks go dead. Same family as membrane-snare's
; "no tensor reduce feeds dynamics" rule. So the collision runs on SCALAR
; edge proxies: 3 low modes per plate (the rocking modes that dominate real
; plate contact) as scalar 2-poles. The proxies collide; the big tensor banks
; only RECEIVE the contact force one-way (scalar -> tensor is fine) and
; radiate the rattle spectrum.
(defmacro edgemode (x f t60s dmv y1h y2h)
  (def w0 (min (* twopi (/ (max f 20) samplerate)) 2.83))
  (def rr (exp (/ -6.9077553 (* samplerate (max t60s 0.002)))))
  (def y1v (* (read-history y1h) dmv))
  (def y2v (* (read-history y2h) dmv))
  (def y (+ (* 2 rr (cos w0) y1v) (* -1 rr rr y2v) x))
  (write-history y2h y1v)
  (write-history y1h y)
  y)
(make-history ep1a) (make-history ep1b)   ; top plate edge proxies
(make-history ep2a) (make-history ep2b)
(make-history ep3a) (make-history ep3b)
(make-history eq1a) (make-history eq1b)   ; bottom plate edge proxies
(make-history eq2a) (make-history eq2b)
(make-history eq3a) (make-history eq3b)
; contact force from LAST sample (scalar history breaks the algebraic loop).
; The impulse does NOT feed back into the proxies: an injected (non-
; conservative) kick can phase-lock and PUMP the proxies into a rattle that
; never dies (measured: sustained ~1kHz tail at open=1). The proxies are
; purely decaying linear systems + contact LOSS — the overlap pattern then
; dies with the plate motion by construction.
(make-history cfh)
(def contact-prev (read-history cfh))
(def t60-p (max (* decay-v 0.001) 0.002))
(def px-in (* strike-force 1.5))
(def qx-in (* strike-force 0.15))
; proxy damping uses last-sample contact (same scalar-history seam): the
; press/choke terms are current, only the contact indicator is one sample old
(def ind-prev (min (* contact-prev 2500) 1))
(def loss-prev (clip (+ (* ind-prev contact-loss-v)
                        (* (- 1 open-v) (- 1 open-v) 0.002)
                        (* (- 1 gate) choke-v 0.03))
                     0 0.25))
(def dm-p (- 1 loss-prev))
(def zp1 (edgemode px-in f0-top t60-p dm-p ep1a ep1b))
(def zp2 (edgemode px-in (* f0-top 2.53) (* t60-p 0.6) dm-p ep2a ep2b))
(def zp3 (edgemode px-in (* f0-top 6.18) (* t60-p 0.35) dm-p ep3a ep3b))
(def zq1 (edgemode qx-in f0-bot t60-p dm-p eq1a eq1b))
(def zq2 (edgemode qx-in (* f0-bot 2.65) (* t60-p 0.6) dm-p eq2a eq2b))
(def zq3 (edgemode qx-in (* f0-bot 5.9) (* t60-p 0.35) dm-p eq3a eq3b))
(def z-top (+ zp1 (* zp2 0.5) (* zp3 0.3)))
(def z-bot (+ zq1 (* zq2 0.5) (* zq3 0.3)))
; pedal gap: tight when closed, plates never meet when fully open. The floor
; keeps a loose metal-on-metal rattle even at open=0 (a real closed hat still
; sizzles). Scale tuned against measured proxy edge amplitudes.
(def pedal-gap (+ 0.02 (* open-v open-v 2.5)))
; overlap -> IMPULSIVE separating force: proportional to the overlap
; INCREASE (approach velocity), not the overlap itself. A sustained penalty
; force follows the low proxy cycle and drives the banks' low modes
; resonantly (measured: 900Hz centroid, clanky); impulses at each new
; penetration are broadband bounces — the Sekiguchi Model 2 insight in force
; form. Clipped BEFORE scaling.
(make-history ovh)
(def overlap (max (- (- z-top z-bot) pedal-gap) 0))
(def overlap-prev (read-history ovh))
(write-history ovh overlap)
(def approach (max (- overlap overlap-prev) 0))
(def contact-f (* (min approach 0.02) rattle-v))
(write-history cfh contact-f)
; high-pass the force before it reaches the banks: a one-sided impulse train
; carries strong LOW harmonics of the bounce rate, and the ~28 bloom-band
; 2-poles pass those as forced response with summed gain ~1 (measured:
; 415Hz-comb tail). THIRD-order HP (~2.2kHz): first-order was measurably not
; enough — the leak sat only ~8dB under the resonant ring.
(defmacro hp1 (x hist)
  (def lpv (read-history hist))
  (def lpn (+ lpv (* 0.25 (- x lpv))))
  (write-history hist lpn)
  (- x lpn))
(make-history cfl1) (make-history cfl2) (make-history cfl3)
(def contact-hp (hp1 (hp1 (hp1 contact-f cfl1) cfl2) cfl3))
; the LOSS indicator fires on bounce EVENTS (approach), not sustained
; overlap: Sekiguchi's pseudo-loss acts at collision instants. Sustained
; overlap-driven loss wiped the whole open-hat tail (measured: -80dB at
; 300ms), because a slow proxy swell held the indicator on for entire half
; cycles. Closed hats still decay fast emergently — constant re-collision =
; a dense stream of loss events.
(def contact-ind (min (* approach 250) 1))

; ── Pseudo-loss (Sekiguchi Model 2) + pedal press + choke ───────────────────
; all "extra damping" folds into one per-sample state shrink — multiplying
; the stored states is dissipative BY CONSTRUCTION, it cannot add energy
(def loss-total (clip (+ (* contact-ind contact-loss-v)
                         (* (- 1 open-v) (- 1 open-v) 0.002)
                         (* (- 1 gate) choke-v 0.03))
                      0 0.25))

; ── Nonlinear bloom (wash): clipped quadratic of top-plate edge motion ──────
(def bloom-x (clip (* z-top 4) -1 1))
(def bloom-inj (* bloom-x bloom-x wash-v 0.003))

; ── Modal bank updates (2-pole per mode: y = 2r cos(w) y1 - r² y2 + x) ──────
; contact injection drives ONLY the high modes (bloom-mask band): the bounce
; train is quasi-periodic at the proxy fundamental, and any energy it puts
; into low bank modes rings as a ~1kHz clank (measured, twice). The plate's
; low modes ARE the proxies here — they carry the collision, they don't
; radiate. The bounce periodicity survives as amplitude modulation of the
; high-frequency wash, which is exactly what a real hat's sizzle is.
(def x-top (+ (* strike-force strike-mask-m)
              (* contact-hp -1 bloom-mask)
              (* bloom-inj bloom-mask)))
(def x-bot (+ (* contact-hp 1 bloom-mask)
              ; bottom plate hears a little of the strike through the stand
              (* strike-force bell-mask 0.1)))
; loss is frequency-TILTED: Sekiguchi measured contact attenuation largest
; at low frequencies (big slow overlaps swallow the rocking modes first)
(def loss-tilt-top (pow top-ratios -0.4))
(def loss-tilt-bot (pow bot-ratios -0.4))
(def dm-top (max (- 1 (* loss-total loss-tilt-top)) 0.75))
(def dm-bot (max (- 1 (* loss-total loss-tilt-bot)) 0.75))
(def ty1d (* ty1v dm-top))
(def ty2d (* ty2v dm-top))
(def by1d (* by1v dm-bot))
(def by2d (* by2v dm-bot))
(def ty-next (+ (* 2 r-top (cos w-top) ty1d) (* -1 r-top r-top ty2d) x-top))
(def by-next (+ (* 2 r-bot (cos w-bot) by1d) (* -1 r-bot r-bot by2d) x-bot))
; NaN-safety clamps only; modal amplitudes live well under these
(def ty-nextc (max (min ty-next 3) -3))
(def by-nextc (max (min by-next 3) -3))

; ── Output taps (computed before the history writes) ────────────────────────
; radiation tilt: a small plate radiates low modes poorly (rises ~f below
; coincidence), and this is where a hat's 5-20kHz identity comes from. The
; tilt is OUTPUT-only voicing — the low modes still ring internally and keep
; driving the contact dynamics. Normalized so the top mode weight is ~1.
(def rad-top (* (pow top-ratios 0.7) 0.085))
(def rad-bot (* (pow bot-ratios 0.7) 0.083))
(def mic-t (sum (* ty-nextc mic-top rad-top)))
(def mic-b (sum (* by-nextc mic-bot rad-bot)))
(def mic-sizzle (* contact-hp 10))
(def mixdown (+ mic-t (* mic-b bottom-mix-v) (* mic-sizzle sizzle-v)))

; ── Write feedback ──────────────────────────────────────────────────────────
(write-tensor-history ty2 ty1d)
(write-tensor-history ty1 ty-nextc)
(write-tensor-history by2 by1d)
(write-tensor-history by1 by-nextc)

; ── Body EQ + DC block (hand-rolled scalar-history filters) ─────────────────
(defmacro bpf (x f q x1h x2h y1h y2h)
  (def w0 (* twopi (/ (clip f 20 20000) samplerate)))
  (def alpha (/ (sin w0) (* 2 q)))
  (def a0 (+ 1 alpha))
  (def x1v (read-history x1h))
  (def x2v (read-history x2h))
  (def y1v (read-history y1h))
  (def y2v (read-history y2h))
  (def y (/ (+ (* alpha x) (* -1 alpha x2v)
               (* 2 (cos w0) y1v) (* -1 (- 1 alpha) y2v))
            a0))
  (write-history x2h x1v)
  (write-history x1h x)
  (write-history y2h y1v)
  (write-history y1h y)
  y)

(def bq1 (bpf mixdown body1-freq-v 2 b1x1 b1x2 b1y1 b1y2))
(def bq2 (bpf mixdown body2-freq-v 1.5 b2x1 b2x2 b2y1 b2y2))
(def bodied (+ mixdown (* bq1 body1-gain-v) (* bq2 body2-gain-v)))
; one-pole-zero DC blocker
(def dcin bodied)
(def dcy (+ (- dcin (read-history dcx1)) (* 0.998 (read-history dcy1))))
(write-history dcx1 dcin)
(write-history dcy1 dcy)
(out (* dcy level-v vel-gain 3) 1 @name audio)
