(defmacro simp11 (input)
  (def value1 1.0)
  (def mix2 (mix __patcher_missing_input__ __patcher_missing_input__ __patcher_missing_input__))
  (def simp21 (simp2 input))
  (def phasor1 (phasor input))
  (def triangle1 (triangle phasor1))
  (def mul1 (* triangle1 twopi))
  (def cos1 (cos mul1))
  (def gain21 (gain2 cos1))
  (def gain22 (gain2 gain21))
  (def mix1 (mix gain22 simp21 0.5))
  mix1)
(use-defmacro simp2)
(use-defmacro gain2)