;; Dispatcher from built-in audio effect name to custom panel body.
(def builtin-audio-fx-ui (fx)
  (if (= (get fx :name) "Filter")
    (builtin-fx-filter-ui fx)
    (if (= (get fx :name) "EQ8")
      (builtin-fx-eq8-ui fx)
      (if (= (get fx :name) "Str8 Delay")
        (builtin-fx-str8-delay-ui fx)
        (if (= (get fx :name) "Space Echo")
          (builtin-fx-space-echo-ui fx)
        (if (= (get fx :name) "Dimension")
          (builtin-fx-dimension-ui fx)
        (if (= (get fx :name) "DJ Mixer")
          (builtin-fx-dj-mixer-ui fx)
          (if (or (= (get fx :name) "444 Compressor")
                  (= (get fx :name) "Glue Compressor"))
            (builtin-fx-dynamics-ui fx)
            (if (= (get fx :name) "Compressor")
              (builtin-fx-compressor-ui fx)
              (if (= (get fx :name) "Limiter")
                (builtin-fx-limiter-ui fx)
                (if (= (get fx :name) "Tape")
                  (builtin-fx-tape-ui fx)
                  (if (= (get fx :name) "Convolution Reverb")
                    (builtin-fx-convolution-reverb-ui fx)
                    false))))))))))))
