(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def mod1 (in 5 @name mod1 @modulator 1))
(def mod2 (in 6 @name mod2 @modulator 2))
(def mod3 (in 7 @name mod3 @modulator 3))
(def mod4 (in 8 @name mod4 @modulator 4))
(def mod5 (in 9 @name mod5 @modulator 5))
(def mod6 (in 10 @name mod6 @modulator 6))
(def ext1 (in 11 @name ext1 @modulator 7))
(def ext2 (in 12 @name ext2 @modulator 8))
(def ext3 (in 13 @name ext3 @modulator 9))
(def ext4 (in 14 @name ext4 @modulator 10))

(param amp_attack @default 1 @min 1 @max 40 @unit ms)
(param amp_decay @default 380 @min 30 @max 2400 @unit ms @mod true @mod-mode additive)
(param amp_sustain @default 0 @min 0 @max 0.35)
(param amp_release @default 55 @min 2 @max 900 @unit ms)

(param tune @default -24 @min -60 @max 12 @mod true @mod-mode additive)
(param bend @default 42 @min -24 @max 96 @mod true @mod-mode additive)
(param bend_decay @default 34 @min 3 @max 320 @unit ms)
(param punch @default 11 @min 0 @max 48 @mod true @mod-mode additive)
(param punch_decay @default 7 @min 1 @max 100 @unit ms)
(param drift @default 0.00 @min 0 @max 0.05)

(param body_level @default 0.82 @min 0 @max 1 @mod true @mod-mode additive)
(param body_decay @default 1.00 @min 0.25 @max 2.25)
(param sub_level @default 0.44 @min 0 @max 1 @mod true @mod-mode additive)
(param sub_ratio @default 0.50 @min 0.25 @max 1.00 @mod true @mod-mode additive)
(param sub_decay @default 1.22 @min 0.30 @max 3.00)
(param harmonic @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)
(param phase_bite @default 0.20 @min 0 @max 1 @mod true @mod-mode additive)
(param body_shape @default 0.42 @min 0 @max 1 @mod true @mod-mode additive)

(param fm_level @default 0.28 @min 0 @max 1 @mod true @mod-mode additive)
(param fm_ratio @default 4.50 @min 0.50 @max 16.00)
(param fm_decay @default 30 @min 1 @max 180 @unit ms)
(param fm_feedback @default 0.32 @min 0 @max 1 @mod true @mod-mode additive)

(param click_level @default 0.36 @min 0 @max 1 @mod true @mod-mode additive)
(param click_tone @default 5200 @min 400 @max 16000 @unit Hz @mod true @mod-mode additive)
(param click_decay @default 9 @min 1 @max 90 @unit ms)
(param click_noise_mix @default 0.72 @min 0 @max 1)
(param click_sweep @default 0.30 @min 0 @max 1)

(param noise_level @default 0.34 @min 0 @max 1 @mod true @mod-mode additive)
(param noise_tone @default 5200 @min 120 @max 14000 @unit Hz @mod true @mod-mode additive)
(param noise_decay @default 38 @min 2 @max 240 @unit ms)
(param noise_q @default 2.20 @min 0.5 @max 8)
(param noise_color @default 0.70 @min 0 @max 1)
(param air_level @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)

(param low_cut @default 30 @min 12 @max 260 @unit Hz @mod true @mod-mode additive)
(param body_tone @default 8500 @min 200 @max 16000 @unit Hz @mod true @mod-mode additive)
(param tone @default 9200 @min 220 @max 16000 @unit Hz @mod true @mod-mode additive)
(param resonance @default 0.72 @min 0.5 @max 3.0 @mod true @mod-mode additive)
(param drive @default 2.2 @min 0.4 @max 16 @mod true @mod-mode additive)
(param dirt @default 0.24 @min 0 @max 1 @mod true @mod-mode additive)
(param squash @default 0.14 @min 0 @max 1 @mod true @mod-mode additive)
(param gain @default 0.50 @min 0 @max 1 @mod true @mod-mode additive)

(def tunev (clip (mod tune) -60 12))
(def base_freq_clean (clip (* pitch (pow 2 (/ tunev 12))) 14 240))
(def randbend (* (noise) drift base_freq_clean))
(def base_freq (clip (+ base_freq_clean randbend) 14 260))

(def bend_env (adsr gate trigger 1 bend_decay 0 4))
(def punch_env (adsr gate trigger 1 punch_decay 0 3))
(def fm_env (adsr gate trigger 1 fm_decay 0 5))
(def bendv (clip (mod bend) -24 96))
(def punchv (clip (mod punch) 0 48))
(def sweep_semi (+ (* bendv bend_env) (* punchv punch_env)))
(def body_freq (clip (* base_freq (pow 2 (/ sweep_semi 12))) 12 1400))

(def decayv (clip (mod amp_decay) 30 2400))
(def amp_env (adsr gate trigger amp_attack decayv amp_sustain amp_release))
(def body_env (adsr gate trigger amp_attack (clip (* decayv body_decay) 20 3200) amp_sustain amp_release))
(def sub_env (adsr gate trigger amp_attack (clip (* decayv sub_decay) 30 4200) amp_sustain amp_release))
(def click_env (adsr gate trigger 1 click_decay 0 3))
(def noise_env (adsr gate trigger 1 noise_decay 0 5))
(def air_env (adsr gate trigger 1 (clip (* noise_decay 0.60) 1 180) 0 3))

(def fbv (clip (mod fm_feedback) 0 1))
(def fml (clip (mod fm_level) 0 1))
(def fm_phase (phasor (clip (* body_freq fm_ratio) 20 16000)))
(def fm_base_angle (* fm_phase twopi))
(def fm_wave (sin (+ fm_base_angle (* fbv 2.6 (sin (* fm_base_angle 2))) (* fbv 0.9 (sin (* fm_base_angle 3))))))
(def fmv (* fm_wave fm_env fml))
(def fm_knock_raw (* (tanh (* fm_wave (+ 1 (* fbv 7)))) fm_env fml 0.95))
(def fm_knock_bp (svf fm_knock_raw (clip (* body_freq fm_ratio 1.2) 90 5200) 1.8 1))
(def fm_knock (svf fm_knock_bp 80 0.7 2))

(def body_phase (phasor body_freq))
(def sub_phase (phasor (clip (* body_freq (clip (mod sub_ratio) 0.25 1.0)) 8 700)))
(def body_angle (+ (* body_phase twopi) (* fmv 9.5)))
(def body_sine (sin body_angle))
(def body_second (sin (* body_angle 2)))
(def body_third (sin (* body_angle 3)))
(def sub_sine (sin (* sub_phase twopi)))

(def shapev (clip (mod body_shape) 0 1))
(def bite (clip (mod phase_bite) 0 1))
(def harm (clip (mod harmonic) 0 1))
(def asymmetric (+ body_sine (* bite body_second) (* harm 0.28 body_third)))
(def folded (tanh (* asymmetric (+ 1 (* shapev 12)))))
(def shaped_body (+ (* body_sine (- 1 (* shapev 0.42))) (* body_second harm 0.32) (* body_third harm shapev 0.18) (* folded shapev 0.42)))
(def body_pre (* shaped_body body_env (clip (mod body_level) 0 1)))
(def body (svf body_pre (clip (mod body_tone) 200 16000) 0.7 0))
(def sub (* (tanh (* sub_sine (+ 1 (* shapev 2.2)))) sub_env (clip (mod sub_level) 0 1)))

(def n (noise))
(def n2 (noise))
(def click_sweep_freq (clip (* (clip (mod click_tone) 400 16000) (+ 1 (* click_sweep 6 click_env))) 300 18000))
(def click_osc (sin (* (phasor click_sweep_freq) twopi)))
(def click_bp (svf n (clip (mod click_tone) 400 16000) 3.0 1))
(def click_hp (svf click_bp 1400 0.7 2))
(def cmix (clip click_noise_mix 0 1))
(def click_src (+ (* click_osc (- 1 cmix)) (* click_hp cmix)))
(def click (* click_src click_env (clip (mod click_level) 0 1) 1.25))

(def ntone (clip (mod noise_tone) 120 14000))
(def nq (clip noise_q 0.5 8))
(def snap_lp (svf n ntone nq 0))
(def snap_bp (svf n ntone nq 1))
(def snap_hp (svf n ntone nq 2))
(def ncol (clip noise_color 0 1))
(def snap_blend (+ (* snap_lp (clip (- 0.5 ncol) 0 0.5) 2) (* snap_bp (- 1 (* 2 (abs (- ncol 0.5))))) (* snap_hp (clip (- ncol 0.5) 0 0.5) 2)))
(def snap_tight (svf snap_blend (clip (mod low_cut) 12 260) 0.7 2))
(def snap_edge (svf snap_tight (clip (* ntone 1.8) 500 16000) 0.8 2))
(def snap (* (+ snap_tight (* snap_edge 0.85)) noise_env (clip (mod noise_level) 0 1) 1.70))
(def air_hp1 (svf n2 6200 0.65 2))
(def air_hp2 (svf air_hp1 9000 0.65 2))
(def air_sizzle (tanh (* air_hp2 3.5)))
(def air (* air_sizzle air_env (clip (mod air_level) 0 1) 2.10))

(def raw (+ body sub (* fm_knock 1.35) click snap air))
(def lowtight (svf raw (clip (mod low_cut) 12 260) 0.65 2))
(def drivev (clip (mod drive) 0.4 16))
(def dirtv (clip (mod dirt) 0 1))
(def warm (tanh (* lowtight drivev)))
(def clipped (tanh (* lowtight (+ 2 (* drivev 2.4)))))
(def crushed (tanh (* (+ lowtight (* lowtight lowtight dirtv)) (+ 1 (* drivev 3.0)))))
(def driven (+ (* warm (- 1 dirtv)) (* clipped dirtv 0.65) (* crushed dirtv 0.35)))
(def squashv (clip (mod squash) 0 1))
(def squashed (tanh (* driven (+ 1 (* squashv 8)))))
(def comped (+ (* driven (- 1 squashv)) (* squashed squashv)))
(def transient_lift (+ (* click 0.20) (* snap 0.28) (* air 0.34) (* fm_knock 0.22)))
(def toned (svf (+ comped transient_lift) (clip (mod tone) 220 16000) (clip (mod resonance) 0.5 3.0) 0))

(out (* toned amp_env velocity (clip (mod gain) 0 1)) 1 @name audio)
