#!/usr/bin/env python3
"""Generate the FM routing/spectral arithmetic from auditable musical data.

Only this file owns algorithm connectivity and harmonic anchors. Authored UI
and state-machine macros remain separate. Generated Lisp and spectra.json are
checked in; neither generation nor NumPy is required at runtime.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'content/instruments/Synths/Digi FM'
OPS = ('c', 'a', 'b1', 'b2')
ALGORITHMS = [
    dict(edges=[('b2','b1'),('b1','c'),('a','c')], feedback='a', x=[('c',False)], y=[('b1',False)]),
    dict(edges=[('a','c'),('b2','b1')], feedback='b2', x=[('c',False)], y=[('b1',False)]),
    dict(edges=[('a','c'),('a','b1'),('a','b2')], feedback='a', x=[('c',False),('b2',False)], y=[('b1',False)]),
    dict(edges=[('b2','b1'),('b1','a'),('a','c')], feedback='b2', x=[('c',False)], y=[('b1',False)]),
    dict(edges=[('b2','b1'),('b2','a'),('b1','a'),('a','c')], feedback='b1', x=[('c',False)], y=[('a',False)]),
    dict(edges=[('a','c'),('a','b1'),('b2','c'),('b2','b1')], feedback='a', x=[('c',False)], y=[('b1',False)]),
    dict(edges=[('a','c'),('b2','b1')], feedback='a', x=[('c',False),('a',True)], y=[('b1',True),('b2',True)]),
    dict(edges=[('a','c')], feedback='b1', x=[('c',False),('b2',True)], y=[('b1',True)]),
]
PARTIALS = 16
TABLE_SAMPLES = 8192
ANCHOR_COUNT = 7

def anchors(h):
    """Fundamental stays one. Bell is a harmonic color, not inharmonic tuning."""
    if h == 1:
        return [1.] * 7
    saw = 1 / h
    square = saw if h % 2 else 0.
    return [0., saw, saw * math.exp(-.28*(h-1)),
            saw * (1 if h % 2 else .3), square,
            square * math.exp(-.32*(h-1)),
            {2:.12,3:.5,5:.3,8:.18,13:.08}.get(h,0.)]

def choice(values):
    return '(selector alg ' + ' '.join(str(v) for v in values) + ')'

def build_spectra():
    """Cumulative spectra: seven morph anchors for each partial limit.

    Interpolating adjacent limits retains the additive renderer's fractional
    final-partial fade. Phase is periodic; do not duplicate its end sample.
    Accumulate in float64, then round each completed waveform to float32, as
    in the auditioned Fast Test bank.
    """
    import numpy as np

    phase = np.arange(TABLE_SAMPLES) / TABLE_SAMPLES
    waves = np.zeros((ANCHOR_COUNT, TABLE_SAMPLES))
    bank = []
    for partial in range(1, PARTIALS + 1):
        waves += np.array(anchors(partial))[:, None] * np.sin(2 * np.pi * partial * phase)
        bank.extend(waves.astype(np.float32).ravel().tolist())
    (DEST / 'spectra.json').write_text(json.dumps(
        {'shape': [TABLE_SAMPLES, ANCHOR_COUNT * PARTIALS], 'data': bank},
        separators=(',', ':')))

def build():
    DEST.mkdir(parents=True, exist_ok=True)
    lines = ['; Generated by tools/digi-fm/build.py. Edit the generator for routing/anchors.',
             '(use-defmacro drift-filter-core)', '(use-defmacro digi-fm-envelope)']
    emit = lines.append
    params = {}
    def param(name, default, lo, hi, unit=None, mod=True):
        params[name] = default
        attrs = f' @unit {unit}' if unit else ''
        if mod:
            attrs += f' @mod true @mod-mode additive @mod-depth-min {lo-hi} @mod-depth-max {hi-lo}'
        emit(f'(param {name} @default {default} @min {lo} @max {hi}{attrs})')
        return f'(clip (mod {name}) {lo} {hi})' if mod else name
    for i,name in enumerate(('gate','pitch','velocity','trigger'),1):
        emit(f'(def {name} (in {i} @name {name}))')
    for i in range(1,5):
        emit(f'(def mod{i} (in {4+i} @name mod{i} @modulator {i}))')
    param('algorithm',2,1,8,mod=False)
    param('phase_reset',1,0,4,mod=False)
    for op in OPS:
        param(op+'_ratio',2 if op=='b2' else 1,.25,16)
        param(op+'_fine',0,-1,1)
        param(op+'_level_db',dict(c=0,a=-9,b1=-6,b2=-12)[op],-60,6,'dB')
        if op!='c': param(op+'_keyscale',0,0,1)
    for group in ('a','b'):
        for name,d,lo,hi in [('delay',0,0,5000),('attack',4,0,5000),('decay',400,0,12000)]:
            param(group+'_'+name+'_ms',d,lo,hi,'ms')
        param(group+'_end',.35,0,1)
        param(group+'_depth',3,0,8)
        for name,d in [('gated',0),('reset',1),('hold',1)]:param(group+'_'+name,d,0,1,mod=False)
    for name,d,lo,hi,unit in [('harmonics',0,-6,6,None),('feedback',.15,0,2,None),('mix_xy',.3,0,1,None),
          ('source_db',-6,-36,12,'dB'),('cutoff',5000,20,16000,'Hz'),('resonance',.2,0,1,None),
          ('highpass',20,20,12000,'Hz'),('keytrack',.3,0,1,None),('filter_depth',0,-8,8,'oct'),
          ('volume_db',-12,-48,6,'dB'),('pan',0,-1,1,None),('velocity_amount',.35,0,1,None)]:
        param(name,d,lo,hi,unit)
    param('filter_type',0,0,1,mod=False)
    for prefix in ('amp','filter'):
        for n,d,lo,hi in [('attack_ms',4,0,5000),('decay_ms',400,0,12000),('sustain',.7 if prefix=='amp' else 0,0,1),('release_ms',1600 if prefix=='amp' else 400,0,12000)]:
            param(prefix+'_'+n,d,lo,hi,'ms' if n.endswith('_ms') else None)
    emit('''
(defmacro df-smooth (target reset)
  (make-history h)
  (def value (gswitch reset target (+ (read-history h) (* (- 1 (exp (/ -1 (* .002 samplerate)))) (- target (read-history h))))))
  (write-history h value)
  value)
(defmacro df-db (db) (exp (* .11512925465 db)))
; Cumulative harmonic tables evaluated at the phase INCLUDING incoming PM.
; sample wraps phase and interpolates phase and morph; limit interpolation
; preserves the frequency-dependent partial fade at the 4x internal rate.
''')
    emit(f'(def spectrum_bank (tensor @shape [{TABLE_SAMPLES} {ANCHOR_COUNT * PARTIALS}] @file "spectra.json"))')
    emit(f'''
(defmacro df-wave (phase frequency morph)
  (def p phase)
  (def pos (clip morph 0 {ANCHOR_COUNT - 1}))
  (def limit (clip (/ (* samplerate 1.8) (max frequency 1)) 1 {PARTIALS}))
  (def lower (floor limit))
  (def upper (min {PARTIALS} (+ lower 1)))
  (def lower_wave (+ (* {ANCHOR_COUNT} (- lower 1)) pos))
  (def upper_wave (+ (* {ANCHOR_COUNT} (- upper 1)) pos))
  (mix (sample spectrum_bank p lower_wave)
       (sample spectrum_bank p upper_wave) (- limit lower)))
; B2 is structurally sine-only in every algorithm.
(defmacro df-sine (phase frequency morph) (sin (* twopi phase)))
''')
    # One state-free internal step. A without incoming PM is used by algorithms
    # where A precedes B; algorithms where B precedes A use the later A node.
    args='alg pc pa p1 p2 fc fa f1 f2 gc ga g1 g2 ea eb da db harm fb olda old1 old2'
    emit(f'(defmacro df-step ({args})')
    for op in ('a','b1','b2'):
        emit(f'  (def fb_{op} (* fb {choice([int(a["feedback"]==op) for a in ALGORITHMS])}))')
    emit('  (def aclean (df-wave (+ pa (* fb_a olda)) fa (max harm 0)))')
    emit('  (def b2 (df-sine (+ p2 (* fb_b2 old2) (* aclean ga ea da '+choice([int(('a','b2') in a['edges']) for a in ALGORITHMS])+')) f2 0))')
    emit('  (def b1 (df-wave (+ p1 (* fb_b1 old1) (* b2 g2 eb db '+choice([int(('b2','b1') in a['edges']) for a in ALGORITHMS])+') (* aclean ga ea da '+choice([int(('a','b1') in a['edges']) for a in ALGORITHMS])+')) f1 (max harm 0)))')
    emit('  (def a (df-wave (+ pa (* fb_a olda) (* b1 g1 eb db '+choice([int(('b1','a') in a['edges']) for a in ALGORITHMS])+') (* b2 g2 eb db '+choice([int(('b2','a') in a['edges']) for a in ALGORITHMS])+')) fa (max harm 0)))')
    emit('  (def c (df-wave (+ pc (* a ga ea da) (* b1 g1 eb db '+choice([int(('b1','c') in a['edges']) for a in ALGORITHMS])+') (* b2 g2 eb db '+choice([int(('b2','c') in a['edges']) for a in ALGORITHMS])+')) fc (max (- 0 harm) 0)))')
    gains=dict(c='gc',a='ga',b1='g1',b2='g2')
    for bus in ('x','y'):
        vals=[]
        for algo in ALGORITHMS:
            terms=[f'(* {op} {gains[op]}'+((' ea)' if op=='a' else ' eb)') if env else ')') for op,env in algo[bus]]
            vals.append(terms[0] if len(terms)==1 else '(+ '+' '.join(terms)+')')
        emit(f'  (def {bus} {choice(vals)})')
    emit('  (tuple x y a b1 b2))')
    # A literal algorithm at each call lets the compiler eliminate unused
    # edges/operators. The four substeps stay together inside one gate. All
    # persistent phase, feedback and decimator state lives outside the gates.
    core_args = [f'p_{op}_{step}' for step in range(1, 5) for op in OPS]
    core_args += [f'f_{op}' for op in OPS] + [f'g_{op}' for op in OPS]
    core_args += ['env_a', 'env_b', 'ctl_a_depth', 'ctl_b_depth', 'ctl_harmonics',
                  'ctl_feedback', 'raw_a_0', 'raw_b1_0', 'raw_b2_0', 'ctl_mix_xy']
    core_outputs = [f'mixed_{step}' for step in range(1, 5)]
    core_outputs += ['raw_a_4', 'raw_b1_4', 'raw_b2_4']
    emit('\n; State-free four-substep core, specialized by the literal algorithm.')
    emit(f'(defmacro df-core (alg {" ".join(core_args)})')
    for step in range(1, 5):
        call = ' '.join(f'p_{op}_{step}' for op in OPS) + ' '
        call += ' '.join(f'f_{op}' for op in OPS) + ' ' + ' '.join(f'g_{op}' for op in OPS)
        emit(f'  (def (x_{step} y_{step} raw_a_{step} raw_b1_{step} raw_b2_{step}) (df-step alg {call} env_a env_b ctl_a_depth ctl_b_depth ctl_harmonics ctl_feedback raw_a_{step-1} raw_b1_{step-1} raw_b2_{step-1}))')
        emit(f'  (def mixed_{step} (mix x_{step} y_{step} ctl_mix_xy))')
    emit(f'  (tuple {" ".join(core_outputs)}))')
    emit('''
; Explicit 4x FM integration. Four substeps share phase and feedback state.
; Eighth-order Butterworth reconstruction filter: cutoff .10 of internal rate.
; States are passed through each substep, never duplicated as macro histories.
(defmacro df-biquad-step (x q s1 s2)
  (def g 0.3249196962)
  (def norm (/ 1 (+ 1 (/ g q) (* g g))))
  (def b0 (* g g norm))
  (def a1 (* 2 (- (* g g) 1) norm))
  (def a2 (* (+ 1 (- 0 (/ g q)) (* g g)) norm))
  (def y (+ (* b0 x) s1))
  (tuple y (+ (* 2 b0 x) (- s2 (* a1 y))) (- (* b0 x) (* a2 y))))
''')
    emit("""
; Discrete routing changes fade to zero for 2 ms, switch the complete graph,
; then fade in for 2 ms. No fractional edges or mixed feedback topology.
(def reset (gt trigger .5))
(make-history algorithm-h)
(make-history routing-gain-h)
(def requested-algorithm (clip (round algorithm) 1 8))
(def old-algorithm (max 1 (read-history algorithm-h)))
(def old-routing-gain (read-history routing-gain-h))
(def switch-routing (gt (+ reset (* (- 1 (eq requested-algorithm old-algorithm)) (lte old-routing-gain 0))) 0))
(def alg (gswitch switch-routing requested-algorithm old-algorithm))
(def routing-gain (gswitch reset 1
  (clip (+ old-routing-gain (* (/ 1 (* .002 samplerate))
    (gswitch (eq requested-algorithm alg) 1 -1))) 0 1)))
""")
    for algorithm in range(1, len(ALGORITHMS) + 1):
        emit(f'(def active_{algorithm} (eq alg {algorithm}))')
    emit("""
(write-history algorithm-h alg)
(write-history routing-gain-h routing-gain)
""")
    for prefix in ('a','b'):
        emit(f'(def env_{prefix} (digi-fm-envelope gate trigger (mod {prefix}_delay_ms) (mod {prefix}_attack_ms) (mod {prefix}_decay_ms) (clip (mod {prefix}_end) 0 1) {prefix}_gated {prefix}_reset {prefix}_hold))')
    for prefix in ('amp','filter'):
        emit(f'(def env_{prefix} (adsr gate trigger (max 0 (mod {prefix}_attack_ms)) (max 0 (mod {prefix}_decay_ms)) (clip (mod {prefix}_sustain) 0 1) (max 0 (mod {prefix}_release_ms))))')
    for op in OPS:
        emit(f'(def f_{op} (df-smooth (clip (* pitch (+ (mod {op}_ratio) (mod {op}_fine))) .1 (* samplerate 1.8)) reset))')
        key='1' if op=='c' else f'(pow (min 1 (/ 261.6256 (max pitch 1))) (clip (mod {op}_keyscale) 0 1))'
        emit(f'(def g_{op} (* (df-db (df-smooth (clip (mod {op}_level_db) -60 6) reset)) {key}))')
        emit(f'(make-history phase_{op})')
        rst='(gt phase_reset .5)' if op=='a' or op=='b2' else ('(+ (eq phase_reset 1) (eq phase_reset 3))' if op=='b1' else '(+ (eq phase_reset 1) (eq phase_reset 2))')
        if op=='a' or op=='b2':rst='(+ (eq phase_reset 1) (eq phase_reset 3) (eq phase_reset 4))'
        emit(f'(def p_{op}_0 (gswitch (* reset {rst}) (- 0 (/ f_{op} (* 4 samplerate))) (read-history phase_{op})))')
    for op in ('a','b1','b2'):
        emit(f'(make-history feedback_{op})')
        emit(f'(def raw_{op}_0 (gswitch switch-routing 0 (read-history feedback_{op})))')
    for n in range(8):
        emit(f'(make-history decim_{n})')
        emit(f'(def z{n}_0 (gswitch switch-routing 0 (read-history decim_{n})))')
    for name,lo,hi in [('harmonics',-6,6),('feedback',0,2),('a_depth',0,8),('b_depth',0,8),('mix_xy',0,1)]:
        emit(f'(def ctl_{name} (df-smooth (clip (mod {name}) {lo} {hi}) reset))')
    for step in range(1,5):
        for op in OPS:emit(f'(def p_{op}_{step} (wrap (+ p_{op}_{step-1} (/ f_{op} (* 4 samplerate))) 0 1))')
    for algorithm in range(1, len(ALGORITHMS) + 1):
        outputs = ' '.join(f'a{algorithm}_{name}' for name in core_outputs)
        emit(f'(def ({outputs}) (block-gate active_{algorithm} (df-core {algorithm} {" ".join(core_args)})))')
    for name in core_outputs:
        outputs = ' '.join(f'a{algorithm}_{name}' for algorithm in range(1, len(ALGORITHMS) + 1))
        emit(f'(def {name} (+ {outputs}))')
    for step in range(1,5):
        sig=f'mixed_{step}'
        for section,q in enumerate((.5097955791,.6013448869,.8999762231,2.5629154477)):
            a=section*2;b=a+1
            emit(f'(def (lp{section}_{step} z{a}_{step} z{b}_{step}) (df-biquad-step {sig} {q} z{a}_{step-1} z{b}_{step-1}))')
            sig=f'lp{section}_{step}'
    for op in OPS:emit(f'(write-history phase_{op} p_{op}_4)')
    for op in ('a','b1','b2'):emit(f'(write-history feedback_{op} raw_{op}_4)')
    for n in range(8):emit(f'(write-history decim_{n} z{n}_4)')
    emit('''
(def source (* .4 routing-gain lp3_4 (df-db (df-smooth (clip (mod source_db) -36 12) reset))))
(def cutoff_hz (clip (* (df-smooth (clip (mod cutoff) 20 16000) reset)
  (pow (/ (max pitch 1) 261.6256) (clip (mod keytrack) 0 1))
  (pow 2 (* env_filter (clip (mod filter_depth) -8 8)))) 20 (min 16000 (* samplerate .36))))
(def filtered (drift-filter-morph-gated source cutoff_hz
  (df-smooth (clip (mod resonance) 0 1) reset)
  (df-smooth (clip (mod highpass) 20 (min 12000 (* samplerate .36))) reset) (df-smooth (clip filter_type 0 1) reset)))
(def vel (+ 1 (* (- velocity 1) (clip (mod velocity_amount) 0 1))))
(def signal (* (clip filtered -.875 .875) env_amp vel (df-db (df-smooth (clip (mod volume_db) -48 6) reset))))
(def pan_value (df-smooth (clip (mod pan) -1 1) reset))
(out (* signal (sqrt (* .5 (- 1 pan_value)))) 1 @name left)
(out (* signal (sqrt (* .5 (+ 1 pan_value)))) 2 @name right)
''')
    (DEST/'dsp.lisp').write_text('\n'.join(lines).rstrip()+'\n')
    (Path(__file__).parent/'parameters.json').write_text(json.dumps(params,indent=2)+'\n')
    build_spectra()
    return params

if __name__=='__main__':build()
