; Machinedrum-style snare machines: TRX-SD, EFM-SD, PI-SD, TRX-RS, EFM-RS, PI-RS.

(def gate (in 1 @name gate))
(def pitch (in 2 @name pitch))
(def velocity (in 3 @name velocity))
(def trigger (in 4 @name trigger))
(def clock (in 5 @name clock))
(def mod1 (in 6 @name mod1 @modulator 1))
(def mod2 (in 7 @name mod2 @modulator 2))
(def mod3 (in 8 @name mod3 @modulator 3))
(def mod4 (in 9 @name mod4 @modulator 4))

(defmacro semi (s) (pow 2 (/ s 12)))
(defmacro md-env (trig decay_ms)
  (make-history e)
  (def coef (exp (/ -6.907755 (max 1.0 (* decay_ms 0.001 samplerate)))))
  (def next (gswitch (gt trig 0.5) 1.0 (* (read-history e) coef)))
  (write-history e (gswitch (lt (abs next) 0.00000000000000000001) 0.0 next))
  next)
(defmacro retrig-phasor (freq trig)
  (make-history p)
  (def next (wrap (+ (read-history p) (/ freq samplerate)) 0 1))
  (def ph (gswitch (gt trig 0.5) 0.0 next))
  (write-history p ph)
  ph)
(defmacro latch-trig (sig trig)
  (make-history h)
  (def v (gswitch (gt trig 0.5) sig (read-history h)))
  (write-history h v)
  v)
(defmacro md-ping (exc freq t60_ms)
  (make-history y1)
  (make-history y2)
  (def r (exp (/ -6.907755 (max 1.0 (* t60_ms 0.001 samplerate)))))
  (def y (- (+ exc (* 2 r (cos (* twopi (/ (clip freq 8 18000) samplerate))) (read-history y1))) (* r r (read-history y2))))
  (write-history y2 (read-history y1))
  (write-history y1 y)
  y)
(defmacro md-clip (x drive)
  (def d (clip drive 0 1))
  (+ (* (tanh (* x (+ 1 (* 5 d)))) (- 1 d)) (* (clip (* x (+ 1 (* 15 d))) -1 1) d)))
(defmacro md-srr (x amount)
  (def a (clip amount 0 1))
  (def hz (exp (+ (log 300.0) (* (- 1 a) (- (log 44100.0) (log 300.0))))))
  (def ph (phasor hz))
  (make-history prev)
  (def tick (lt ph (read-history prev)))
  (write-history prev ph)
  (latch x tick))
(defmacro md-out (x)
  (def am (* x (+ (- 1 (clip (mod amd) 0 1)) (* (clip (mod amd) 0 1) (+ 0.5 (* 0.5 (sin (* (phasor (clip (mod amf) 0.1 2000)) twopi))))))))
  (def eqp (svf am (clip (mod eqf) 40 12000) 1.2 4))
  (def eqd (+ am (* eqp (/ (clip (mod eqg) -15 15) 15))))
  (def hp (svf (svf eqd (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2) (clip (mod fltf) 20 14000) (clip (mod fltq) 0.5 8) 2))
  (def lp (clip (+ (mod fltf) (mod fltw)) 40 18000))
  (def flt (svf (svf hp lp (clip (mod fltq) 0.5 8) 0) lp (clip (mod fltq) 0.5 8) 0))
  (md-clip (md-srr flt (mod srr)) (mod dist)))

(param engine @default 1 @min 1 @max 6)
(param ptch @default 0 @min -48 @max 48 @mod true @mod-mode additive)
(param dec @default 310 @min 20 @max 2500 @unit ms @mod true @mod-mode additive)
(param bump @default 16 @min -24 @max 72 @mod true @mod-mode additive)
(param benv @default 28 @min 2 @max 320 @unit ms)
(param snap @default 0.72 @min 0 @max 1 @mod true @mod-mode additive)
(param tone @default 0.56 @min 0 @max 1 @mod true @mod-mode additive)
(param tune @default 0.18 @min -1 @max 1 @mod true @mod-mode additive)
(param clip @default 0.18 @min 0 @max 1 @mod true @mod-mode additive)

(param noise @default 0.64 @min 0 @max 1 @mod true @mod-mode additive)
(param ndec @default 190 @min 8 @max 1800 @unit ms)
(param mod_amt @default 0.45 @min 0 @max 1 @mod true @mod-mode additive)
(param mfrq @default 310 @min 10 @max 3000 @unit Hz @mod true @mod-mode additive)
(param mdec @default 55 @min 1 @max 800 @unit ms)
(param hpf @default 1600 @min 60 @max 9000 @unit Hz @mod true @mod-mode additive)

(param hard @default 0.48 @min 0 @max 1 @mod true @mod-mode additive)
(param tens @default 0.25 @min 0 @max 1 @mod true @mod-mode additive)
(param rvol @default 0.50 @min 0 @max 1 @mod true @mod-mode additive)
(param rdec @default 260 @min 10 @max 1800 @unit ms)
(param ring @default 0.22 @min 0 @max 1 @mod true @mod-mode additive)
(param humanize @default 0.25 @min 0 @max 1)

(param level @default 0.58 @min 0 @max 1 @mod true @mod-mode additive)
(param amd @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param amf @default 42 @min 0.1 @max 2000 @unit Hz @mod true @mod-mode additive)
(param eqf @default 2400 @min 40 @max 12000 @unit Hz @mod true @mod-mode additive)
(param eqg @default 0 @min -15 @max 15 @unit dB @mod true @mod-mode additive)
(param fltf @default 80 @min 20 @max 12000 @unit Hz @mod true @mod-mode additive)
(param fltw @default 17000 @min 20 @max 18000 @unit Hz @mod true @mod-mode additive)
(param fltq @default 0.75 @min 0.5 @max 8 @mod true @mod-mode additive)
(param srr @default 0 @min 0 @max 1 @mod true @mod-mode additive)
(param dist @default 0.10 @min 0 @max 1 @mod true @mod-mode additive)

(def eng (clip (round engine) 1 6))
(def vel (clip velocity 0 1))
(def accent (pow vel 1.5))
(def jit (* (latch-trig (noise) trigger) humanize))
(def base (clip (* pitch (semi (+ (mod ptch) (* jit 2)))) 35 1400))
(def amp (md-env trigger (clip (mod dec) 20 2500)))
(def bump_env (md-env trigger (clip benv 2 320)))
(def nraw (noise))
(def nfast (md-env trigger (clip (* ndec 0.38) 4 600)))
(def nslow (md-env trigger (clip ndec 8 1800)))
(def hp_noise (svf nraw (clip (mod hpf) 60 9000) 1.0 2))
(def bp_noise (svf nraw (+ 850 (* (mod tone) 5200)) (+ 0.7 (* (mod tone) 3.0)) 1))
(def snap_layer (+ (* hp_noise nfast) (* bp_noise nslow)))

; TRX-SD
(def sd_f1 (clip (* 180 (semi (mod ptch)) (+ 1 (* 0.10 (mod tune))) (semi (* (mod bump) bump_env))) 55 2600))
(def sd_f2 (clip (* 330 (semi (mod ptch)) (+ 1 (* 0.35 (mod tune))) (semi (* (mod bump) bump_env 0.55))) 90 4200))
(def sd_body_env (md-env trigger (clip (* (mod dec) 0.42) 15 1000)))
(def sd_body (* sd_body_env (+ (* 0.62 (sin (* (retrig-phasor sd_f1 trigger) twopi))) (* 0.38 (sin (* (retrig-phasor sd_f2 trigger) twopi))))))
(def trx_sd (md-clip (+ sd_body (* snap_layer (mod snap) 1.25)) (mod clip)))

; EFM-SD
(make-history fmfb)
(def fm_menv (md-env trigger (clip mdec 1 800)))
(def fm_m (sin (+ (* (retrig-phasor (clip (mod mfrq) 10 3000) trigger) twopi) (* (read-history fmfb) 5.8 (mod mod_amt)))))
(write-history fmfb (clip fm_m -1 1))
(def efm_body (* (sin (+ (* (retrig-phasor base trigger) twopi) (* fm_m fm_menv (mod mod_amt) 14))) amp))
(def efm_sd (+ efm_body (* hp_noise (md-env trigger (clip ndec 8 1800)) (mod noise))))

; PI-SD
(def energy (md-env trigger (clip (mod dec) 20 2500)))
(def tens_mul (+ 1 (* (mod tens) 0.35 accent energy energy)))
(def exc (* (svf nraw (+ 1800 (* (mod hard) 9000)) 0.8 0) (md-env trigger (+ 2 (* (- 1 (mod hard)) 8)))))
(def pi_m1 (md-ping exc (* base 1.00 tens_mul) (* (mod dec) 0.52)))
(def pi_m2 (md-ping exc (* base 1.59 tens_mul) (* (mod dec) 0.34)))
(def pi_m3 (md-ping exc (* base 2.14 tens_mul) (* (mod dec) 0.25)))
(def pi_m4 (md-ping exc (* base 2.65 tens_mul) (* (mod dec) 0.19)))
(def collide (gt (noise) (- 1 (* (mod rvol) energy 0.9))))
(def wire_hit (* (gswitch collide 1.0 0.0) energy (mod rvol)))
(def wire (md-ping (svf (* wire_hit (noise)) 3500 1.8 1) 5000 (clip rdec 10 1800)))
(def shell_ring (+ (md-ping exc (* base 6.27) (* (mod dec) 0.36)) (md-ping exc (* base 6.50) (* (mod dec) 0.34))))
(def pi_sd (md-clip (+ (* pi_m1 0.60) (* pi_m2 0.40) (* pi_m3 0.28) (* pi_m4 0.18) wire (* shell_ring (mod ring) 0.24)) (mod clip)))

; Rim machines
(def rim_exc (* (md-env trigger 3) (+ 1 (* 0.5 nraw))))
(def trx_rs (md-clip (+ (md-ping rim_exc (* base 2.65) 80) (* 0.55 (md-ping rim_exc (* base 9.5) 55))) (+ 0.25 (mod clip))))
(def efm_rs (* (sin (+ (* (retrig-phasor (* base 3.2) trigger) twopi) (* fm_m 7.0 fm_menv))) (md-env trigger (clip (* (mod dec) 0.18) 8 300))))
(def pi_rs (md-clip (+ (* 0.8 trx_rs) (* 0.45 wire) (* 0.30 shell_ring (mod ring))) (mod clip)))

(def voice (selector eng trx_sd efm_sd pi_sd trx_rs efm_rs pi_rs))
(out (* (md-out voice) vel (clip (mod level) 0 1)) 1 @name audio)
